kubevirt-ui/kubevirt-plugin

- src/utils/hooks/useKubevirtDataPod/useKubevirtDataPodFilters.ts
Fix query so request will be consist 
> Update fetch query filters

- src/utils/components/BootOrderModal/BootOrderModalBody.tsx
- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/vm/utils/source.ts
https://issues.redhat.com/browse/CNV-23926
Fixing 2 problems for 4.11:
1. After we created a new boot source whose type is CD-ROM it doesn't recognize that it is a boot source.
2. After creating the VM we see the pending changes warning for Boot disk, and it's incorrect.
Before: 
After:
> CNV-23926: Fixing warnings and behavior when managing bootable disk and CD-ROM (4.11)

- src/views/catalog/wizard/tabs/scripts/components/DynamicSSHKeyInjectionWizard.tsx
Fixing the check if the label exists and also if it is 'true'.
Before: 
After:
> CNV-31533: Fixing the dynamic ssh key injection on wizard

- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthProjects.ts
Adding sorting to project list at manage ssh key
Before:
After:
> CNV-31975: Adding sorting to manage ssh project list

- src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
Not loading icon if vm isnt available yet 
Before:
After:
> CNV-31974: Removing vm status if no vm loaded yet

- src/views/virtualmachines/list/VirtualMachinesList.tsx
VM list crash because of missing default values to printStatus
> CNV-32023: Fix printstatus default value

- src/utils/components/EnableFeatureCheckbox/EnableFeatureCheckbox.tsx
Externalink was missing a check to see if has a value in the prop in order the link to work
> CNV-32016: Fix loadbalancer link

- src/utils/resources/bootableresources/hooks/useCanCreateBootableVolume.ts
- src/views/bootablevolumes/list/BootableVolumesList.tsx
Removing the add volume button in case this is a non admin user (non admin user cannot right now list or use instancetypes)
> CNV-32103: Add permission check for non admin user - add volume button

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
In a situation the same drive is mounted in several places like here:
We have counted this twice.
Before:
After:
> CNV-26810: Fix multi count of same drive in storage donuts

- src/views/catalog/templatescatalog/TemplatesCatalog.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
Fixing key added automatically after settings changed by clearing the session storage and applying an empty value to the auth key in the context
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/16ee0edc-7599-444a-919d-6b2accc649e6
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/512ac534-6ab3-49bb-9a52-5dfd61169b43
> CNV-30896: Authorized SSH key is added to VM automatically even no key is set in settings

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthKeys.ts
When adding a secret to the user settings and then the secret is deleted there's no indication of that in the UI. 
When creating a VM with the template's catalog, it will still try to apply the key from the settings even if the secret is missing.
Now when trying to apply a non existing secret from the settings, we will check if the secret exist and if not it will be removed from the settings when trying to apply it or in the manage SSH keys section
Before:
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/defeffa3-e296-4d33-8b49-8de31df69967
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/433c12a9-6bc4-437b-a351-d70bcb355502
> CNV-31906: Deleted secret is showing in overview settings

- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthKeys.ts
> CNV-30896: Manage SSH settings keeps loading

- src/utils/components/Charts/utils/queries.ts
> Fix memory query

- src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
- src/utils/hooks/useKubevirtDataPod/utils/utils.ts
Missing websocket update for DELETED messages. 
> CNV-32024: Update vm list objects when vm is deleted

- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthKeys.ts
Follow up fix for https://github.com/kubevirt-ui/kubevirt-plugin/pull/1482#discussion_r1299816767
> Follow-up to comment on #1482

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/utils/utils.ts
Remove message in nic modal if VM is not running
After:
Before:
> CNV-32389: Remove delete msg from nic modal if vm is running

- src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
> CNV-32024: reverse check

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/templatescatalog/utils/os-icons.tsx
Preference is null for non-admin users , so using volume name its mimic the action of getting icon.
Before:
After:
> CNV-32486: Fix instancetype icons for non admin users

- src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
- src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
- src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx
> [release-4.13] Boot from CD with CD source "PVC (clone PVC)" not working

- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.scss
> CNV-32524: Align lines instancetypes form

- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
For nonadmin users, sometimes VM list crashes as an error response return value.
> CNV-32520: Sometimes vm list crash for non admin user

- src/views/templates/list/VirtualMachineTemplatesList.tsx
Missing default value for params, and ns
Before:
After:
> CNV-32523: Fix template list default value

- .eslintrc.json
- cypress/plugin.js
- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
- src/utils/components/Consoles/components/DesktopViewer/utils/utils.ts
- src/utils/components/Consoles/components/SerialConsole/SerialConsoleConnector.tsx
- src/utils/components/DiskModal/DiskModal.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/components/SidebarEditor/utils.ts
- src/utils/components/TabModal/TabModal.tsx
- src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
- src/utils/resources/shared.ts
- src/utils/resources/vm/utils/disk/drivers.ts
- src/utils/resources/vmi/utils/cloud-init.ts
- src/utils/utils/utils.ts
- src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
- src/views/catalog/customize/components/FormActionGroup.tsx
- src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
- src/views/clusteroverview/OverviewTab/status-card/utils/URLHealthItemPopup.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/TemplatesProjectSection/TemplatesProjectSection.tsx
- src/views/datasources/dataimportcron/hooks/useDataImportCronActions.tsx
- src/views/datasources/hooks/useDataSourceActions.tsx
- src/views/templates/actions/editBootSource.ts
- src/views/virtualmachines/actions/actions.ts
- src/views/virtualmachines/actions/tests/actions.test.ts
Activating the no-console log to prevent commits from containing consloe.log/error/warn from the dev step. If you want to add logs to the application, you can use kubevirtConsole. The linter won't alert it.
> CNV-32543: Adding no-console linter rule

- src/utils/resources/shared.ts
- src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
- src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Manual backport for #1420 and #1433 
> [release-4.13] CNV-31188: Fix VM clone

- src/views/clusteroverview/OverviewTab/vms-per-resource-card/RunningVMsChartLegendLabel.tsx
fix import of useActiveNaemsapce
> CNV-32447: update useActiveNamespace import

- .eslintrc.json
- src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.tsx
- src/utils/components/CloudinitModal/CloudInitNetworkForm.tsx
- src/utils/components/CloudinitModal/CloudinitForm.tsx
- src/utils/components/CloudinitModal/CloudinitModal.tsx
- src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
- src/utils/components/CloudinitModal/utils/useCloudInit.ts
Replace cloud-init mechanism - fixes the bug and some other things such as deleting all data or adding different data.
After:
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/14824964/ab6f5988-6522-4e81-a19e-9299a648f229
> CNV-29095: Fix cloud init parsing

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
VM wont start when adding a second nic.
Bridge was with capital B and BE ignored it.
NAD name is ns/name , but vm needs only the name without the ns.
> CNV-32666: Fix adding second nic

- src/utils/hooks/useAlerts/useAlerts.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
Description 
Added React Hooks the missing dependency.
> CNV-32597: Handling yarn lint warnings

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/HardwareDevices/HardwareDevicesPage.tsx
- src/utils/components/HardwareDevices/HardwareDevicesPageRow.tsx
- src/utils/components/HardwareDevices/HardwareDevicesPageTable.tsx
- src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
- src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesPageColumns .tsx
- src/utils/components/HardwareDevices/modal/HardwareDevicesModal.tsx
- src/utils/components/HardwareDevices/utils/constants.ts
The Hardware Devices table in Compute -> Hardware Devices shows nothing.
Before the current change, the table was the same as the table that was in the vm overview. 
I changed the table and added the correct values ​​that should be there.
Before:
After:
> CNV-32568: Fixing Hardware Devices table in Compute -> Hardware devices

- src/utils/components/HardwareDevices/form/NameFormField.tsx
- src/utils/components/HardwareDevices/modal/HardwareDevicesModal.tsx
- src/utils/components/HardwareDevices/utils/helpers.ts
Removing required from name field and adding auto-populated pretty name
After:
> CNV-32869: Devices modal - name auto-populated and not required

- src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
Production get a white screen while try to clone
> [release-4.12] CNV-32633: Fix clone vm crash

- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/utils/utils.ts
VNC console can't paste long strings in the current implementation.
VNC console is 3rd party component we are consuming and apparently, it can handle fast key sending which causes the paste to break for long strings(probably a buffer issue). I've added a sleep function before each key is sent in order to slow down the rate and make it work.
Before:
After:
> CNV-32824: Paste long string into vnc console

- console-extensions.json
> [release-4.14] CNV-32927: Fix console extension entries

- src/utils/resources/shared.ts
- src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
- src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
> [release-4.12] CNV-33504: Clone VM should clone from pvc and not from pvc source

- src/utils/components/DiskModal/state/initialState.ts
- src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
- src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
- src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
- src/views/catalog/customize/components/CustomizeSource/utils.ts
- src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx
- src/views/templates/actions/components/SelectSource.tsx
- src/views/templates/actions/components/utils.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-33739
Reduce the disk size of CDROM when customizing VM.
**Before:**
**After:**
> CNV-33739: Reduce the default disk size of CDROM to 10GiB

- start-console-auth-mode.sh
- start-console.sh
Recent changes in ocp image create in quay, create only linux image, adding this platform arg will make those scripts workable also on macos
> Adding platform arg to docker and pod man

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
- src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Update links in Overview -> Getting started resources card
> CNV-35198: Update links in getting started resources

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
- src/utils/components/ActionDropdownItem/action-dropdown-item.scss
- src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
- src/utils/components/WithPermissionTooltip/WithPermissionTooltip.tsx
- src/utils/hooks/usePermissions/usePermissions.ts
- src/views/clusteroverview/SettingsTab/UserTab/components/TaskPermissionsSection/TaskPermissionsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/AddNetworkInterfaceButton.tsx
- src/views/virtualmachines/details/tabs/configuration/network/network-interface-list-page.scss
Removing from setting page some permission, and when user don't have permission, disable the component and adding a msg about it
according to:
https://docs.google.com/document/d/1N8hVqDRBcFhVo1HBPCze7433ZiQ2AQK568nVUz5kK3Q/edit#heading=h.jrwrppw7qg4f
https://issues.redhat.com/browse/CNV-29749
less permissions in setting page:
clone disabled:
add network disabled:
> CNV-29749: Adding user permission to disable component

- src/utils/components/DiskModal/DiskFormFields/NameFormField.tsx
- src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
- src/utils/components/HardwareDevices/modal/HardwareDevicesModal.tsx
- src/utils/components/HardwareDevices/utils/helpers.ts
- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/resources/template/utils/helpers.ts
- src/utils/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/checkups/network/components/form/CheckupsNetworkForm.tsx
- src/views/checkups/network/utils/utils.ts
- src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx
- src/views/datasources/list/CreateDataSourceModal/utils.ts
- src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
- src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotModal.tsx
- src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
Combining all pretty name resource creation into 1 function and removing rest.
> CNV-34259: Aggragate pretty name creation

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
Add autoUpdate feature on rhel vms
> CNV-26796: auto-update rhel on customize

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
Fix the behavior of the switch button of disable log in setting tab
> CNV-35500: Fix switch of disable log setting tab

- src/views/checkups/network/hooks/useCheckupsNetworkData.ts
- src/views/checkups/storage/components/hooks/useCheckupsStorageData.ts
> Change checkups data  hook source

- src/utils/components/DescriptionItem/DescriptionItem.scss
- src/utils/components/DescriptionItem/DescriptionItem.tsx
- src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
- src/utils/components/DiskListTitle/DiskListTitle.tsx
- src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
- src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
- src/utils/components/SearchItem/SearchItem.tsx
- src/utils/components/SearchItem/search-item.scss
- src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DynamicSSHKeyInjectionIntanceType.tsx
- src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyDescriptionItem.tsx
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionHardware.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/InitialRunTab.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabCloudinit.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
- src/views/virtualmachines/details/tabs/configuration/metadata/MetadataTab.tsx
- src/views/virtualmachines/details/tabs/configuration/network/NetworkTab.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionLeftGrid.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
- src/views/virtualmachines/details/tabs/configuration/search/VirtualMachineConfigurationTabSearch.tsx
- src/views/virtualmachines/details/tabs/configuration/search/virtual-machine-configuration-tab-search.scss
- src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabSSHAccess.tsx
- src/views/virtualmachines/details/tabs/configuration/utils/search.ts
- src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
This 1/2 pr's
This pr contains all logic and HOC in the needed places.
Next pr will be tweaking CSS and creating the initial DB for search.
[CNV-36116](https://issues.redhat.com/browse/CNV-36116)
> CNV-36116: Adding search for configuration tab

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/BridgedNICHotPlugModalAlert/NICHotPlugModalAlert.tsx
- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/components/PendingChanges/utils/helpers.ts
This feature adds SR-IOV NIC hot-plug.
Epic: https://issues.redhat.com/browse/CNV-30169
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/b90c6bfa-16ad-47f1-8ab2-34873eb9bd4c
> CNV-30169: Add SR-IOV NIC hot-plug

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.scss
Adding (enabling) 2 more instance types O and N
> CNV-31864: Adding 2 new instancetypes O and N

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
Fix catalog drawer width
** Before **
** After **
> Catalog drawer width

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
After changes in configuration tab linking need to be updated
> CNV-36133: Fix linking of details and disks in vm overview page

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
This time is real. Fixed. Console use patternfly 5 + v4
> CNV-36135: Fix catalog drawer

- src/views/checkups/Checkups.tsx
- src/views/checkups/storage/utils/utils.ts
Fix in the case subjects don't exist on clusterrolebinding object
> CNV-36344: fix install checkups storage

- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIViewerModal/utils/utils.ts
> CNV-36325: fix backslash is missing cli command

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
Changed title form disks to storage
> CNV-36251: Change disks to storage

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
Narrow favorites column
Before:
After:
> CNV-36405: Narrow favorites column

- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
> CNV-35808: fix ksm request

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
> CNV-36407: Fix switch ssh load balancer

- src/utils/components/CPUMemory/CPUMemory.tsx
Change CPU and memory component to first try to present values form VM instead of vmi
> CNV-34073: Change cpu and memory to show from vm first

- src/views/catalog/Catalog.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/constants.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
useParams hook do not grab the URL namespace correctly. 
Show template fetch error if there is any
> Fix namespace undefined in the drawer

- src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
- src/utils/hooks/usePermissions/usePermissions.ts
Fix what are we checking for no prev user permissions
> CNV-36090: fix permissions

- src/utils/components/SelectSnapshot/types.ts
- src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
- src/utils/resources/bootableresources/selectors.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
> CNV-36439: Supporting volumesnapshoot as source in IT list

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
Changing something in the drawer, clear the VM name input
**Before**
**After**
> CNV-35476: Fix clearing vm name on change

- src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
- src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
- src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
- src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
- src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
- src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
- src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
Fixing frame of page the changed in recent console update and expanding yaml editor to full height
After:
Before:
> CNV-36154: fix css template wizard

- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
Moving boot and hardware to right side of tab
After:
Before:
> CNV-36435: Moving boot and hardware to right side of tab

- src/utils/components/CloudinitModal/CloudinitModal.tsx
- src/utils/components/SSHSecretSection/utils/utils.ts
Fix when the cloud-init modal is updating after dynamic injection has been turned on; the user name, if changed in the cloud-init modal, is not reflected on users of dynamic injection.
> CNV-36225: fix-dynamic-injection-user

- src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
> CNV-36752: Update doc links for non-admin user

- src/views/templates/details/TemplateNavPage.tsx
- src/views/templates/list/VirtualMachineTemplatesList.tsx
Fix namespace is undefined after new console changes
> CNV-36767: Fix template list and details with new console changes

- src/utils/components/DiskListTitle/DiskListTitle.tsx
Align title and icon.
After:
Before:
> CNV-36883: Align disk title

- src/views/clusteroverview/OverviewTab/getting-started-card/GettingStartedCard.tsx
Change the quick start item
After:
Before:
> CNV-35199: Change Virtualization -> overview -> quick start item

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewStatus/VirtualMachineOverviewStatus.tsx
Fix view diagnostic link for 4.14
> CNV-36227: Fix diagnostic link

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
> CNV-36881: Fix borken link VMCP

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/network/NetworkTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
Adjusting names of title for tabs uner configurations.
Whats in red is added
> CNV-36459: Adjust tabs names

- src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
Fixing name loading params for catalog drawer.
After:
Before:
> CNV-36753: Fix params loading and name value return

- src/utils/components/WindowsDrivers/WindowsDrivers.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/DriversCheckbox.tsx
Auto-add windows driver disk if its Windows template
After:
Before:
> CNV-36191: Auto add windows driver disk for windows templates

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
> CNV-35455: Adding namespace to NAD name

- src/utils/resources/vmi/utils/ips.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/hooks/useVirtualMachinesOverviewTabInterfacesData.ts
Removing ipv6 form ips list
After:
Before:
> CNV-34072: Removing ipv6 form ip's list

- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
- src/utils/resources/vmi/utils/selectors.ts
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
Pending changes expect to compare VM vs VMI for some fields , depend on the check.
When VM created from instance type the yaml is different, in the case of bios for some instance types bios is added to vmi but not shown in VM yaml, added the expand-spec call, to get the expand yaml of VM to compare to vmi for boot loader.
After:
Before:
> CNV-36795: Fix pending changes bios instance type

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
Fix vm tabs -> configuration -> network crash
> CNV-36880: Fix vm tabs -> configuration -> network crash

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/search/VirtualMachineConfigurationTabSearch.tsx
- src/views/virtualmachines/details/tabs/configuration/search/virtual-machine-configuration-tab-search.scss
Adding a configuration not found for search in configuration tab
and also fixing small issue regarding item name don't stay in search input once item from auto complete is clicked
> CNV-36933: Adding no results found search configuration

- src/templates/vm-template-yaml.ts
- src/templates/vm-yaml.ts
Updating fedora version from 36 to latest
> CNV-36794: Update vm example template

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
When creating a template from example yaml we are crashing. this will fix it.
> CNV-37005: Fix user template example crash

- webpack.config.ts
This PR fixes a bug wherein reloading of the dev server would cause loading of the page to fail.
> Fix dev server reload issue

- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/details-right-grid.scss
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Adding an option to change storage class for IT
After:
Before:
> CNV-32502: add option to change SC - create IT

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/SectionWithSwitch/SectionWithSwitch.tsx
- src/utils/components/SectionWithSwitch/section-with-switch.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
Adjusting node port setting appearance
After:
Before:
> CNV-37025: Adjusting adjusting node port setting apperance

- src/views/virtualmachines/list/VirtualMachinesList.tsx
Fix IP filtering while running kubevirt proxy
> CNV-36059: Fix filtering ip address kubevirt proxy

- test-prow-e2e.sh
This is considered a potential vulnerability
> Do not dump secrets on ci test failures

- src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
> CNV-29307: Fix copy and paste to serial console firefox

- src/utils/resources/vmi/utils/ips.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/hooks/useVirtualMachinesOverviewTabInterfacesData.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/utils/types.ts
- src/views/virtualmachines/list/components/FirstItemListPopover/FirstItemListPopover.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachinesinstance/details/tabs/details/components/Details/IP/IP.tsx
Restoring back the ipv6 and adding the ethX name next each ip
After:
Before:
> CNV-34072: Adding interface name to ip

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/UsersInstanceTypeList/UsersInstanceTypeList.scss
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/UsersInstanceTypeList/UsersInstanceTypeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/hooks/useInstanceTypeCardMenuSection.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/state/hooks/useUserInstanceTypes.ts
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Making the user instancetype working
> CNV-37414: Fix jumping bug and make user provided instancetype working

- src/utils/components/SSHSecretSection/SSHSecretModal.tsx
- src/utils/components/SSHSecretSection/SSHSecretSection.tsx
- src/utils/components/SSHSecretSection/components/SSHOptionUseExisting/SSHOptionUseExisting.tsx
Fix loading of ssh modal
Now each project change is loading, instead of loading all secrets
> CNV-37024: Fix loading of ssh modal

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/SettingsTab/SettingsTab.tsx
- src/views/clusteroverview/SettingsTab/settings-tab.scss
Removing the alert
After:
Before:
> CNV-37667: Removing all setting are effective across.. alert

- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIViewerModal/utils/utils.ts
Removed the key form cli command in instance type catalog
After:
Before:
> CNV-36325: remove ssh key from command structure

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
> CNV-37725: update doc link to 4.15

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/HorizontalNavbar/horizontal-nav-bar.scss
- src/utils/components/HorizontalNavbar/utils/utils.ts
- src/views/bootablevolumes/list/BootableVolumesList.tsx
- src/views/catalog/wizard/Wizard.tsx
- src/views/catalog/wizard/tabs.tsx
- src/views/templates/details/TemplateNavPage.tsx
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/configuration/disk/DiskListPage.tsx
- src/views/virtualmachines/details/tabs/configuration/environment/VirtualMachineEnvironmentPage.tsx
- src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/VirtualMachineSchedulingPage.tsx
- src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
- src/views/virtualmachines/details/tabs/configuration/utils/types.ts
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
- src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
- src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
- src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
- src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx
- src/views/virtualmachines/details/tabs/yaml/virtual-machine-yaml-page.scss
- src/views/virtualmachines/details/virtual-machine-page.scss
When using ocp 4.15 and cnv 4.14 , there is a routing problem because of the console change to react-router v6
This is a manual backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1661
> [release-4.14] CNV-37739: fix routhing

- src/utils/components/DiskModal/DiskFormFields/AccessMode.tsx
- src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUploadPVCProgress.tsx
- src/utils/components/DiskModal/DiskFormFields/VolumeMode.tsx
- src/utils/components/DiskModal/DiskFormFields/utils/modesMapping.ts
- src/utils/hooks/useCDIUpload/utils.ts
- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/utils/disk/rowData.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/CustomizeSource.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/SelectSourceUploadPVCProgress.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/utils.ts
- src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormAccessMode.tsx
- src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormVolumeMode.tsx
- src/views/clusteroverview/OverviewTab/status-card/utils/storage-health-item/StorageHealthItem.tsx
- src/views/clusteroverview/OverviewTab/status-card/utils/utils.tsx
- src/views/clusteroverview/TopConsumersTab/TopConsumersTab.tsx
- src/views/clusteroverview/TopConsumersTab/utils/utils.ts
- src/views/templates/actions/editBootSource.ts
- src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotFormFields/SnapshotDeadlineFormField.tsx
- src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
Substitute all `t` functions passed as parameters with the global `t` function. 
Some functions had just `t` as parameter to i created objects instead.
> CNV-37820: remove t function usage

- src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.scss
- src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.scss
Fix popover css
After:
Before:
> CNV-37951: Fix popover css

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ListPageFilter/ListPageFilter.tsx
- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
- src/views/bootablevolumes/list/BootableVolumesList.tsx
- src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
- src/views/checkups/network/hooks/useCheckupsNetworkListColumns.ts
- src/views/checkups/network/list/CheckupsNetworkList.tsx
- src/views/checkups/storage/components/hooks/useCheckupsStorageListColumns.ts
- src/views/checkups/storage/list/CheckupsStorageList.tsx
- src/views/instancetypes/list/ClusterInstancetypeList.tsx
- src/views/instancetypes/list/UserInstancetypeList.tsx
- src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
- src/views/instancetypes/list/hooks/useUserInstancetypeListColumns.ts
- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesCreateButton/MigrationPoliciesCreateButton.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
- src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
- src/views/preferences/list/ClusterPreferenceList.tsx
- src/views/preferences/list/UserPreferenceList.tsx
- src/views/preferences/list/hooks/useClusterPreferenceListColumns.ts
- src/views/preferences/list/hooks/useUserPreferenceListColumns.ts
- src/views/templates/list/VirtualMachineTemplatesList.tsx
- src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
- src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticConditionsTableColumns.ts
- src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabConditions.tsx
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Fix column management for all tables across the plugin
The same goes for all tables.
Note:
1. left props as comments on Listpagefilter - this component needs to be amended to support those props like the SDK component. @upalatucci, please open a bug for it.
2. The most significant benefit of this change compared to the previous change or using useACtiveColumns directly is the consistency between browsers; feel free to test with another logged-in browser and see that the changes reflect between browsers.
> CNV-37821: Fix column management for all tables across the plugin

- package.json
- src/views/cdi-upload-provider/hooks/useCDIUpload.tsx
- yarn.lock
Upgrading axios version according to jira ticket
> CNV-38813: Upgrade axois version

- src/utils/components/FormPFSelect/FormPFSelect.tsx
- src/views/checkups/network/components/form/CheckupsNetworkFormNADS.tsx
> Fix NAD dropdown in Checkups->Network->Run checkup

- package.json
- src/views/cdi-upload-provider/hooks/useCDIUpload.tsx
- yarn.lock
Updating axios according to the ticket.
> [release-4.15] CNV-36844: Update axios

- src/views/checkups/network/details/CheckupsNetworkDetailsPage.tsx
- src/views/checkups/storage/details/CheckupsStorageDetailsPage.tsx
Fix no params found in 4.15 due to router changes to v6.
now checkups details page network/storage will be loaded.
After:
Before:
> [release-4.15] CNV-39048: Fix 4.15 broken link of checkups details

- src/utils/components/SSHSecretSection/components/SecretDropdown/SecretDropdown.tsx
based on https://github.com/kubevirt-ui/kubevirt-plugin/pull/1751
> CNV-39108: Configure public SSH key from existing key not work

- console-extensions.json
- src/utils/components/Consoles/ConsoleStandAlone.tsx
Fix the standalone route for the console
After:
Before:
blank screen
> CNV-39025: fix standalone console 4.15

- package.json
- yarn.lock
Updating axios again because of https://issues.redhat.com/browse/CNV-39458 , internal package of follow-redirect
> CNV-39458: Updaing axios again for security

- .vscode/settings.json
- plugin-metadata.ts
- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/HorizontalNavbar/utils/utils.ts
There is an issue if a VM name contains a tab name; the navigation is messing around, and this will fix it.
After:
Before:
> CNV-39722: Fix tab navigaiton

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabGeneral/VirtualMachinesOverviewTabGeneral.tsx
Pod lin in VM overview page was missing a ns
> CNV-40136: Fix link to pod adding ns

- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Enable force stop for a situation a VM is stuck in terminating status.
> CNV-40099: Enable force stop for terminating state

- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
Fix link for pending changes of disk
Before:
After:
> CNV-40334: Fix route pending changes storage

- src/views/checkups/Checkups.tsx
Now the default tab when going on checkups is network an not storage
> CNV-40161: Change default tab checkup

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ErrorAlert/ErrorAlert.tsx
- src/views/catalog/Catalog.tsx
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/CustomizeInstanceTypeVirtualMachine.tsx
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/components/CustomizeITVMFooter.scss
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/components/CustomizeITVMFooter.tsx
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/components/CustomizeITVMHeader.tsx
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/tabs/configuration/ConfigurationTab.scss
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/tabs/configuration/ConfigurationTab.tsx
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/tabs/configuration/utils/constants.ts
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/tabs/yaml/YamlTab.scss
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/tabs/yaml/YamlTab.tsx
- src/views/catalog/CustomizeInstanceTypeVirtualMachine/utils/constants.ts
Adding layouts to for the Customize VM from IT flow
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/76d5eebd-0a39-4334-b654-a2b6e713a3fc
> CNV-32699: Customize IT layouts

- src/utils/hooks/useMetalLBOperatorInstalled/useMetalLBOperatorInstalled.ts
Fix crash in sh tab when metal lb installed
Before:
> CNV-39995: Fix metal lb ssh crash

- src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceUrlInput/URLSourceHelperText.tsx
Missing default value caused a crash.
Before: white crashin screen.
After:
> CNV-40914: Fixed default value for url text helper

- package.json
- src/views/cdi-upload-provider/hooks/useCDIUpload.tsx
- yarn.lock
Updating axios according to cve.
> [release-4.14] CNV-41221: Update axios

- package.json
- src/views/cdi-upload-provider/hooks/useCDIUpload.tsx
- yarn.lock
> [release-4.13] CNV-41220: Update axios

- src/utils/components/SSHAccess/components/SSHCommand.tsx
- src/utils/components/SSHAccess/components/SSHServiceState.tsx
- src/utils/components/SSHAccess/useSSHCommand.ts
If there is no IP, it's because the load balancer is going to be bonded but it's not ready yet. 
Waiting for UX/UI approve 
**New**
**Old**
> CNV-39941: Load balancer bonding alert

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/CapacityInput/CapacityInput.tsx
- src/utils/components/DiskModal/DiskModal.tsx
- src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/DiskSourceSelect.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceSelectOptions/DiskSourceSelectOptionGroups.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceSelectOptions/DiskSourceSelectOptions.tsx
- src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassAndPreallocation.tsx
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/components/DiskModal/utils/types.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/utils/getEditDiskStates.ts
Allow the user to edit anything other than the source in the disk modal.
> CNV-41495: Edit minimal disk info after creation

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
manually backport : https://github.com/kubevirt-ui/kubevirt-plugin/pull/1927
> [release-4.14] CNV-41494: Fix preferred disk 4.14

- src/utils/components/CPUMemoryModal/components/CPUInput/CPUHelperText.tsx
- src/utils/components/CPUMemoryModal/components/CPUInput/CPUMemoryModalHeader.tsx
This PR addresses comments on https://github.com/kubevirt-ui/kubevirt-plugin/pull/1905.
> Address comments on CPU/memory hot-plug feature

- src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
This PR fixes an issue where old PVC versions were displayed in the bootable volumes list.
Jira: https://issues.redhat.com/browse/CNV-41224
> CNV-41224: Remove old PVC versions from bootable volume list

- src/utils/resources/vm/utils/selectors.ts
- src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
Add smm feature on `k8sPatch`. On other places smm feature was already added
> CNV-39685: Fix uefi secure smm

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumesPipelinesHint/BootableVolumesPipelinesHint.tsx
> CNV-41640: Add space for windows hint

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
We were checking the permissions for the wrong processed template. Adding apiGroup will fetch the right permissions
> CNV-40419: fix processed template access review with apiGroup

- src/views/checkups/network/details/CheckupsNetworkDetailsPage.tsx
- src/views/checkups/network/details/checkups-network-details-page.scss
- src/views/checkups/storage/details/CheckupsStorageDetailsPage.tsx
- src/views/checkups/storage/details/checkups-storage-details-page.scss
Fix height of yaml tabs in checkups details page 
After:
Before:
> CNV-40162: Fix css checkups yaml's

- src/views/welcome/components/WelcomeButtons.tsx
Fix namespace for welcome modal
> [release-4.15] CNV-39682: Fix namespace for welcome modal

- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
Adjusting the check of the permissions for regular users to be able to create VM from a snapshot they just created
> CNV-41286: Fix permission for create vm from snapshot

- src/views/catalog/CustomizeInstanceType/tabs/configuration/CustomizeInstanceTypeConfigurationTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/yaml/CustomizeInstanceTypeYamlTab.tsx
Yaml tab was looking for data from the VM store instead of signal. Changed to the right location.
> CNV-41846: Fix customize IT yaml

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
Change display name of ITand preference link in VM overview
After:
Before:
> CNV-41804: Fix vm overview link display name for IT and preference

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootableVolumeOSes.ts
This PR addresses comments on https://github.com/kubevirt-ui/kubevirt-plugin/pull/1911.
> Address PR comments for guide users to pipelines feature

- src/views/catalog/CreateFromInstanceTypes/state/hooks/useVirtualMachineInstanceTypes.ts
- src/views/instancetypes/list/UserInstancetypeList.tsx
Instancetype hook didn't fetch for all namespaces, added arg to hook to bypass if needed.
After:
Before:
> CNV-41689: Fix fetching for all namespaces on user instance types

- src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
In some cases the template drawer was crashing on non permission users
> CNV-40419: fix template undefined on permissions error

- src/utils/hooks/useMigrationPolicies.ts
- src/utils/utils/types.ts
- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
Make sure to use search page on migration policy list
> CNV-42023: use searchpage props on migrationpolicylist

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/CustomizeSource.tsx
Fix crush when disk root is missing.
No crash screen
> CNV-41959: Fix crash no rootDisk

- src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
- src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
- src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
- src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
- src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
- src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
- src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
This is a manual backport for #1671 
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/bea85941-11ef-4eb2-bca5-8a4c9a6ac50f
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/52cd5120-68d2-47c7-8eb6-5fa76464a854
> [release-4.14] CNV-40434: The YAML editor is too small on customize wizard and grey page sections instead of white

- src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
> CNV-41205: fix sameVolume func

- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
Fix customize IT flow of boot mode
> CNV-41686: Fix boot mode customize IT

- src/utils/components/DiskModal/components/StorageProfileSettings/AccessMode.tsx
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/61e6e9a2-7f95-4b95-ae84-22b459f25c67
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/f258a0b6-ef7e-42cb-9bbb-075413bf4a4e
> CNV-40242: UI goes blank when changing the storage class field when adding a disk

- src/utils/components/SSHAccess/SSHAccess.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeSSHTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabSSHAccess.tsx
Adjusting customize IT flow to not include sshe service creation , same as instance type quick flow and template flows. 
After:
Before:
> CNV-41526: Remove ssh servie creation from customize IT

- src/utils/components/OwnerReferences/OwnerReferences.tsx
Fix owner resource link
Before:
After:
> CNV-42470: Fix link of owner

- src/utils/resources/vm/utils/source.ts
- src/views/virtualmachines/details/tabs/configuration/ssh/components/DynamicSSHKeyInjectionDescription.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
> CNV-41587: Fix Dynamic SSH key message

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
Fix sorting for bootable volume list in catalog instance type and modal.
Before:
After:
> CNV-42853: Fix sorting for bootable volume list in catalog and modal

- src/views/virtualmachines/details/tabs/configuration/initialrun/utils/utils.ts
missing ns in configmap creation
> CNV-41586: Missing ns create configmap

- src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
Remove B suffix when adding it to the YAML
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/43c97da8-19ae-4b4a-b18f-ca800baaa6fa
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/96f031ca-e224-4b16-9fe8-3d40a588e21d
> [release-4.15] CNV-42881: Remove B suffix when submitting YAML

- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
- src/utils/hooks/useKubevirtUserSettings/utils/const.ts
> CNV-38284: Change UI settings namespace

- src/utils/components/AddBootableVolumeModal/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
Move DV creation to be after DS creation is successful
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/0764f2dd-3b42-40fa-accb-0b5e08701fc9
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/8be52672-baeb-47e3-b6d0-69863a0dc1ec
> CNV-42080: Add bootable volume from PVC is adding DV on error

- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
Pages are stuck at loading state.
> CNV-43101: Fix loading pages

- console-extensions.json
- src/utils/resources/template/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/preferences/list/PreferencePage.tsx
- src/views/preferences/list/UserPreferenceList.tsx
1. Fix all projects selected in VMP
2. Fix name of cloufinit user, now default is cloud-user and will check also for os label to match name 
> CNV-42852: Cloudint user by new label and fix allprojects for VMP

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
adding a scroll bar to network modal, NAD section
> [release-4.15] CNV-42480: Adding scroll bar to network modal

- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/utils/selectors.ts
vms created with instancetype do not have the rootdisk in the yaml but it actually exists.
So in that case just return the usual rootdisk object.
> CNV-43114: fix getBootDisk for instanceType vms

- src/utils/components/DurationOption/DurationDropdown.tsx
Change the order of charts time dropdown to make better sense
After:
Before:
> CNV-42317: Change order of time dropdown - charts

- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
Clipboardtext is undefined sometimes 
> CNV-43667: Clipboardtext is undefined

- locales/en/plugin__kubevirt-plugin.json
- src/views/bootablevolumes/list/components/BootableVolumesEmptyState.tsx
Change button text from Add bootable volume to Add volume to be the same across the app.
> CNV-43591: Change button label

- src/views/clusteroverview/OverviewTab/alerts-card/hooks/useSimplifiedAlerts.ts
- src/views/virtualmachines/details/tabs/overview/utils/hook/useVMAlerts.tsx
Change alerts order appearance
After:
Before:
> CNV-41922: Change alerts order

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/1820
> [release-4.15] CNV-43996: Backport to 4.15

- locales/en/plugin__kubevirt-plugin.json
- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.scss
- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/Conditions/ConditionIcon.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/Conditions/Conditions.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/Conditions/constants.ts
Conditions 
Go to HCO resource page on clicking the condition
> CNV-40088: add conditions to dashboard alert popup

- src/utils/components/CapacityInput/CapacityInput.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Add disk size on instancetype page
TODO: in a different pr I have to add the disk size editing in the customize storage tab
> CNV-43096: edit disk size on instancetype

- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
- loading and empty state were showing together for some seconds (when loaded is false)
- do not show Critical and warning if there are 0 critical or 0 warning alerts
**Before**
**After**
> CNV-40088: fix dashboard alert popup

- src/views/checkups/storage/list/CheckupsStorageListEmptyState.tsx
- src/views/checkups/storage/utils/utils.ts
Moved the permissions loading, to disabled and loading, as currently its only used once and will be ignored later 
> CNV-36085: Moving loading permissions

- .github/workflows/ci_checks.yml
- Dockerfile
- package.json
- yarn.lock
upgrade eslint-plugin-jsdoc to support node >= 18
Enforce node >= 18.x
> CNV-43951: Upgrade Node version

- src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
- src/views/clusteroverview/OverviewTab/inventory-card/utils/constants.ts
- src/views/clusteroverview/OverviewTab/inventory-card/utils/flattenTemplates.ts
Remove template default label when cloning a default template
> CNV-45383: Clone a default template is making the cloned template default too

- package.json
- yarn.lock
Updating fast XML parser package according to CVE
> CNV-45400: Update fast xml parser package

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
Fix wizard template to show start VM checked, ignoring the running: false, but still looking at runStrategy
> CNV-45002: Fix auto start vm in template wizard

- src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
Default bus is 'virtio' but windows do not support it if the VM has no drivers installed so switch to sata.
> CNV-42505: set bus depends on window

- package.json
> CNV-45462: Change npx to cypress binary

- package.json
- yarn.lock
Update kubevirt-api version to 1.3.1
> Bump APIs 1.3.1

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/HorizontalNavbar/utils/useDynamicPages.ts
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
- src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
- src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
- src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
- src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx
- src/views/virtualmachines/details/utils/types.ts
backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/2092
> [release-4.16] CNV-44838: Use VirtualMachine dynamic extension pages

- console-extensions.json
> CNV-44855: Change v1alpha1 to v1beta1

- package.json
- yarn.lock
VMIT and VMP models changed version to v1beta1
No visual change
> Bump API v1.3.2

- .vscode/settings.json
- src/utils/resources/template/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Manual backport of os label fix to 4.15
If no os detected, don't use fedora as user name for clud init, use user name "cloud-user" 
> [release-4.15] CNV-42852: manual backporting os label fix to 4.15

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabGeneral/VirtualMachinesOverviewTabGeneral.tsx
Fix VMI link, was referring always to all namespace
> CNV-46318: Fix link namespace VMI

- console-extensions.json
- plugin-metadata.ts
- src/utils/extensions/telemetry/telemetry.ts
- src/utils/extensions/telemetry/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/hooks/useInstanceTypeCardMenuSection.ts
- src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
- src/views/catalog/templatescatalog/TemplatesCatalog.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/utils/useWizardVmCreate.ts
- src/views/catalog/wizard/components/WizardFooter.tsx
This PR adds monitoring for events in the InstanceType and Template VM creation flows.
Jira: https://issues.redhat.com/browse/CNV-38571
> CNV-38571: Monitor user interaction in InstanceTypes and Templates flow

- package.json
- webpack.config.ts
- yarn.lock
> CNV-46444: CVE axios updaing package

- package.json
- webpack.config.ts
- yarn.lock
> [release-4.15] CNV-46436: update axios

- package.json
- webpack.config.ts
- yarn.lock
> [release-4.13] CNV-46443: update axios

- package.json
- webpack.config.ts
- yarn.lock
> [release-4.14] CNV-46439: Update axios

- plugin-extensions.ts
- src/perspective/extensions.ts
- src/utils/extension.ts
- src/views/cdi-upload-provider/extensions.ts
- src/views/checkups/extensions.ts
- src/views/dashboard-extensions/extensions.ts
- src/views/virtualmachines/extensions.ts
- yarn.lock
The console changed the flag from KUBEVIRT to KUBEVIRT_DYNAMIC, which caused many things to not load/see/work.
This will fix it to work the same and load all our extensions as it should 
> CNV-44306: Kubevirt to KUBEVIRT_DYNAMIC

- src/utils/resources/vm/utils/disk/rowData.ts
> CNV-46752: Restore pvc link

- console-extensions.json
manual backport for https://github.com/kubevirt-ui/kubevirt-plugin/pull/2134
> CNV-47157: Replace 'KUBEVIRT' flag with 'KUBEVIRT_DYNAMIC'

- src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormSize.tsx
Fix upload PVC size unit select input
Before:
https://github.com/user-attachments/assets/4088dc3a-1d07-4cb5-92d8-1072ca0fafbf
After:
https://github.com/user-attachments/assets/827c50cb-5cce-46e0-802f-b305a17a521a
> CNV-47158: Fix upload PVC form unit selection

- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.scss
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
Minor css nitpicks
Before:
After:
> CNV-40580: InstanceType form UI updates

- src/utils/utils/headless-service.ts
Missing async await to catch the error and not present it in dev mode
> CNV-47576: Headless service already exisit error message

- src/views/checkups/storage/utils/utils.ts
Missing try catch for storage checkups - appear only in dev mode
> CNV-47244: Missing try catch for storage checkups

- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
initilize type based on VM's interface if exists, if it doesn't exist it will fallback to bridge interface as default.
Before:
https://github.com/user-attachments/assets/8ffeec74-3ea9-43ba-a7c1-947d68c5ff52
After:
https://github.com/user-attachments/assets/d46392bc-71e3-447b-a739-75b2593f4832
> CNV-47511: Editing NIC in UI uses wrong binding and does not allow changing MAC

- src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
> CNV-47104: Fix typo restore

- src/views/clusteroverview/OverviewTab/metric-charts-card/utils/constants.ts
Metrics changed by eslint and prettier
> CNV-46396: fix metrics order

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
Add namespace column in bootable volume list and handle selection correctly
> CNV-48154: Namespace in bootable volume list

- src/utils/resources/shared.ts
- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
- src/views/virtualmachines/utils/virtualMachineStatuses.ts
Disable start/pause/stop vm while snapshotting or restoring
> CNV-47176: Disable start/pause/stop vm while snapshotting or restoring

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Remove default SATA from rootDisk - iso flow
> CNV-48521: Remove default SATA from rootDisk - iso flow

- src/utils/components/DiskModal/OtherDiskModal.tsx
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/resources/vm/utils/disk/rowData.ts
Add storage settings on otherdisk modal when the edited disk has datavolume template
**Before**
**After**
Change storage class
> CNV-44913 missing storage settings on other disk modal

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
Change boot disk size to disk size
> CNV-46584: Change boot disk size to disk size

- src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
- src/utils/components/toggles/SelectToggle.tsx
Adding data test ids to disk modal options
> CNV-47153: Add data test ids

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Disk size didn't worked for long time, since DV name isn't ROODISK in default, that will fix it.
> CNV-48785: Fix disk size

- src/perspective/extensions.ts
Correct links in the virt perspective
**Before**
default console list page
**After**
kubevirt custom perspective / isntancetype list page
> CNV-48839: fix virt perspective links

- src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationChartLegend.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/constants.ts
Adding a color array to match chart data and chart legend
> CNV-45253: No color in the virtual machine migration graph legend

- src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
- src/utils/components/DynamicSSHKeyInjection/DynamicSSHKeyInjection.tsx
- src/utils/components/DynamicSSHKeyInjection/utils.ts
- src/utils/components/SSHSecretModal/utils/constants.ts
- src/utils/components/SSHSecretModal/utils/utils.ts
- src/views/catalog/wizard/tabs/scripts/components/DynamicSSHKeyInjectionWizard.tsx
If other `runcmd`s are defined, just add the ssh injection command to the script.
If the VM already has labels and `runcmd` for injection, check the switch
https://github.com/user-attachments/assets/5b867c06-3242-4281-8a17-4e17ac263f24
> CNV-42401: add runcmd if other commands defined

- src/utils/components/GuidedTour/components/EndTourContent/EndTourContent.tsx
> CNV-48224: OpenShift Virt doc link needs to be changed in the new Guided Tour

- src/utils/components/Charts/utils/utils.ts
As you can see from the chart, the y scale is wrong as the max y calculated is not right.
**Before**
**After**
> CNV-45733: fix metrics yaml

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
Added a check for undefined value and exact value, before it was only exact value.
> CNV-49040: Improve check for undefined value

- src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
Fix link for learn more about operators
> CNV-48195: Fix link operators

- src/utils/components/ListPageFilter/SearchFilter.tsx
add a guard for removeEventisnter 
> CNV-49306: removeEventLisnter is undefined

- .github/workflows/deploy.yml
> OCPONZ-4464: docker image support for s390x

- package.json
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumesPipelinesHint/QuickStartLauncherLink/QuickStartLauncherLink.tsx
- src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/QuickStartsSection.tsx
- yarn.lock
`Create a Window boot source` link not working
**Before**
nothing happens on click (on console exception)
**After**
> CNV-43785: fix quickstart links using new sdk

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
fixing efi and bios conflict on windows VM creation with instance type
> CNV-49374: Fix bootloader efi and bios

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
backporting manually https://github.com/kubevirt-ui/kubevirt-plugin/pull/2211
> [release-4.17] CNV-49374: Fix bootloader efi and bios

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/2162
Jira: https://issues.redhat.com/browse/CNV-46751
> [release-4.15] CNV-46751: Prevent deletion of pod network on Instancetype VM

- package.json
- yarn.lock
Upgade the Snapshot and Restore version using the newest API npm package
> CNV-49347: snapshot upgrade to v1beta1

- src/utils/components/Consoles/ConsoleStandAlone.tsx
- src/utils/components/Consoles/Consoles.tsx
- src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
- src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
- src/utils/components/Consoles/components/DesktopViewer/utils/types.ts
- src/utils/components/Consoles/components/utils/ConsoleConsts.ts
- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
- src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
- src/utils/components/Consoles/components/vnc-console/vnc-console.scss
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Part 1: 
* refactoring console components
* CSS
* enlarging standalone mode
Standalone now strached:
> CNV-48466: Changing apperance of console - part 1

- .github/workflows/deploy.yml
> Build plugin on arm64

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/hooks/useVolumeOwnedResource.tsx
Before:
https://github.com/user-attachments/assets/475ea7de-0c06-4256-8ad2-b6597efe60ff
After:
https://github.com/user-attachments/assets/ab1b567b-3ef1-4918-adac-bf79ac5d2ab4
> CNV-49382: page goes blank while detaching cloudinit disk (RHEL VM) or driver disk from Windows VM

- package.json
- yarn.lock
Upgrade quickstart pkg because of CVE - dompurify pkg
No visual changes
> CNV-49872: Upgrade quickstart pkg

- src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
- src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
WE hide the namespace column in all console lists when the user selected a specific namespace. SO do the same with the bootable volume list. This will make space more comfortable for other infos
> CNV-50471: show/hide namespace bootablevolume column

- package.json
- yarn.lock
Update webpack packages and dynamic plugin packages
> CNV-47149: Update webpack and dynamic plugin packages

- src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
use `VirtualMachineActionFactory` for the action and for the disabled field so actions in dropdown and icons will always be in sync
> CNV-50293: fix icon button actions disabled when should not

- src/utils/components/DiskModal/utils/submit.ts
We can't hotplug a containerdisk, so if we are in this case, just submit the disk. The page will ask for a restart in order to see the disk change and that's a good thing
> CNV-50567: fix diskmodal hotplugging a containerdisk

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/AddBootableVolumeModal/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/utils/utils.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/CreateBootableVolumeModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Bootable volume using the AddBootableVolumes components.
The default bootable volume name is VM_NAME + DISK_NAME. 
https://github.com/user-attachments/assets/b47c7865-cf86-4dc4-9dc6-636965bd79e7
**Edit modal title and action label for design change**
> CNV-48279: Create bootable volume from disk

- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
We decided not to allow the user to upload a disk to the registry. We'll wait to see if people need that.
> CNV-46447: We don't want to upload the disk to registry anymore

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
We don't want to enable delete action on running vms
> CNV-51418: disable delete on running vm

- src/views/virtualmachines/actions/hooks/constants.ts
- src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.ts
Hide stop when the user select all stopped vms, same thing for running and pause
> CNV-50655: hide nonsense actions

- deploy-kubevirt-gating.sh
This PR deploy kubevirt with KVM_EMULATION enabled, to allow testing on EC2
> Use KVM_EMULATION

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
When clicking on Make persistent we have also to add the dataVolumeTemplate in the array so will be really persistent.  
This will also fix https://issues.redhat.com/browse/CNV-52393
It was taking a while to restart so I attach also a photo of the result after restart
https://github.com/user-attachments/assets/c0afc975-dfea-4024-ac7a-f39581a8ebd4
> CNV-52060: fix persistent hotplug after restart

- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
The cancel button in the migration storage class modal was not working at all
> CNV-52386: Fix Cancel button not working

- cypress/tests/e2e/check-tab-yaml.cy.ts
- cypress/tests/e2e/overview.cy.ts
> enable skipped test

- cypress/tests/e2e/check-tab-yaml.cy.ts
- cypress/views/tab.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/CustomizeInstanceTypeConfigurationTab.tsx
1. add data-test-id to customize IT subTabs
2. update tests to use data-test-id when visit various tabs
3. add tests to check VMI tabs
> update selectors for e2e tests

- src/utils/components/ExportModal/constants.ts
Ben notified me about a new container version that can handle better the instance type and other labels
The new container needs more permissions
> CNV-46447: upgrade the disk uploader container

- src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
we add the `-mig-${RANDOM_CHARS}` including alphabetic characters so in order to eliminate those, I wrote the regex wrong in the beginning
> CNV-51680:  fix regex including alphabetic characters

- src/perspective/extensions.ts
> CNV-53286: add udn navbar item in network virt-perspective

- deploy-kubevirt-gating.sh
Upgrade deploy-kubevirt-gating make it work better with our CI
> CNV-53397: Update deploy-kubevirt-gating 

- src/templates/vm-template-yaml.ts
- src/templates/vm-yaml.ts
those fields are incompatible with s390x and receive default values depending on the cluster architecture
> CNV-53430: make examples compatible with s390x arch clusters

- src/utils/components/MoveVMToFolderModal/MoveVMToFolderModal.tsx
> CNV-54188: change "Move to folder" to "Save"

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
> CNV-54331: do not show fqdn on udn managed namespace

- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
if children is a react component, don't convert to string as it will give this error here in the select typehead 
**FIX**
> CNV-54110: Fix object select

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
This PR fixes an issue where the template name was used as the prefix to create the name for the registry credentials Secret instead of the VM name.
Jira: https://issues.redhat.com/browse/CNV-53247
> CNV-53247: Bug registry credentials secret uses template name

- src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
cause:
DS go into this state and the DS list page do not recognize it as a CloneInProgress
fix:
recognize this state just like CloneInProgress
> CNV-52237: CSICloneInProgress status for DataSource

- src/utils/flags/useEnableKubevirtMenuFlags.ts
If the test user has permission to list only on cluster preference and instance type, show the navbar items anyway
> CNV-52452: Preference instancetype navbar disappear

- yarn.lock
backporting: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2355
> [release-4.17] CNV-52558: CVE path to regex backport 

- yarn.lock
Solving differently https://github.com/kubevirt-ui/kubevirt-plugin/pull/2360 as patternfly/quickstarts has a different version in 4.15 than 4.16
> [release-4.15] CNV-49814: CNV-50620: solve dompurify cve

- src/utils/hooks/useFeatures/constants.ts
Disable treeview as its a FeaturePreview so needs to be disabled by default
> CNV-53453: disable treeview by default

- cypress/support/nav.ts
- cypress/support/resource.ts
- cypress/support/selectors.ts
- cypress/tests/e2e/create-vm-it.cy.ts
- cypress/types/vm.ts
- cypress/utils/const/index.ts
- cypress/utils/const/testVM.ts
- cypress/views/perspective.ts
- cypress/views/vm.ts
> This PR adds 4 ui tests to upstream:
1. Quick create VM from IT
2. Customize create VM from IT
3. Verify customized VM
4. Select all VMs and stop them together
> US Tests - Creation of VM from InstanceType tests

- src/utils/resources/vm/utils/network/constants.ts
- src/utils/resources/vm/utils/network/selectors.ts
Add a special label for l2bridge networks (created by default when udn is in the namespace)
> CNV-55089: l2bridge binding label

- yarn.lock
backport: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2363
> [release-4.14] CNV-50616: CNV-49873: solve dompurify cve

- package.json
- yarn.lock
backport: 
https://github.com/kubevirt-ui/kubevirt-plugin/pull/2275
https://github.com/kubevirt-ui/kubevirt-plugin/pull/2364
> [release-4.17] CNV-50981: CNV-51359: CNV-52643: fix postcss, cross-spawn nanoid cves 

- src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Remove fixed `accessMode` and `volumeMode`. It will be applied the default storage profile
> CNV-55109: storagemigration with no fixed accessMode and volumeMode

- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/utils/quick-create-vm.ts
- src/views/catalog/utils/useWizardVmCreate.ts
- src/views/catalog/wizard/components/WizardFooter.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabService/VirtualMachinesOverviewTabService.tsx
When primary UDN is in a namespace, do not create headless service, and do not add the label to the VM in order to not attach the VM to the service
> CNV-51526: do not use headless service on udn

- src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
- src/utils/resources/vm/utils/network/constants.ts
filtering the primary binding . The name is fixed
**Before**
**After**
> CNV-55094: filter udn primary binding on nads

- locales/en/plugin__kubevirt-plugin.json
- src/utils/constants/documentation.ts
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
> update doc link to 4.18

- src/utils/components/ExportModal/constants.ts
as requested by dominik: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2318#discussion_r1891529966
and here https://issues.redhat.com/browse/CNV-55082
> CNV-55082: use new 4.18 image for export bootable volumes

- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
> CNV-50559: Wrap Snapshot tab title and action in a ListPageHeader

- cypress/views/selector-common.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/virtual-machines-overview-tab-interfaces.scss
Fix layout issues by migrating to standard DescriptionList layout.
> Use DescriptionList layout for displaying network details

- src/utils/components/DiskModal/ContainerDiskModal.tsx
- src/utils/components/DiskModal/DiskModal.tsx
- src/utils/components/DiskModal/RegistryDiskModal.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceContainer/DiskSourceContainer.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/utils/constants.ts
- src/utils/components/DiskModal/components/utils/constants.ts
- src/utils/components/DiskModal/utils/form.ts
- src/utils/components/DiskModal/utils/submit.ts
- src/utils/components/DiskModal/utils/types.ts
- src/utils/resources/secret/utils.ts
- src/utils/resources/template/utils/helpers.ts
- src/utils/resources/vm/utils/selectors.ts
- src/utils/resources/vm/utils/source.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/ContainerSource.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
- src/views/catalog/utils/useRegistryCredentials/useRegistryCredentials.ts
- src/views/catalog/utils/useRegistryCredentials/utils/types.ts
- src/views/catalog/utils/useRegistryCredentials/utils/utils.ts
- src/views/catalog/utils/useWizardVmCreate.ts
- src/views/catalog/wizard/components/WizardFooter.tsx
- src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
- src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
- src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
This PR fixes an issue where the registry credentials entered in the quick create template flow don't persist in the customize template flow. It also triggers deletion of the created Secret when the VM is deleted.
Jira: https://issues.redhat.com/browse/CNV-53248
[registry-credentials-persist-to-customize-flow--AFTER--2025-01-06 08-50.webm](https://github.com/user-attachments/assets/4c668f29-0949-4c34-ace2-a33b0484e699)
> CNV-53248: Add registry credentials to the template wizard flow

- src/utils/components/ExportModal/constants.ts
4.18 image not working. Tested 4.17 and it's working
> CNV-55361: fix downstream upload image url

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Pod networking is masquerade not bridge binding
**Before**
**After**
> CNV-52101: fix pod networking from bridge to masquerade

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
WE should not allow user to select two times the nad as this action is not supported
**VM with one nad**
**Before**
**After**
> CNV-53056: do not let user select same nad two times

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/GuidedTour/components/EndTourContent/EndTourContent.tsx
> CNV-55041: fix Openshift in OpenShift

- src/views/catalog/CustomizeInstanceType/tabs/configuration/CustomizeInstanceTypeConfigurationTab.scss
- src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
Add some padding. Use `--body` class to add some specificity for CSS style priority
**Before**
**After**
> CNV-54789: add padding for configuration tabs

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/AlertsCard/AlertStatusItem.tsx
Instead of showing always 'View alert', change that to 'View info' or 'View warning' in case of 'info' and 'warning'
> CNV-54705: fix link text on overview alert

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachinesinstance/details/tabs/network/VirtualMachineInstancePageNetworkTabRow.tsx
Use the same function that VM network list use in the VMI network list to show the network type
**Before**
**After**
> CNV-54432: Fix vmi network type

- src/utils/resources/vm/utils/constants.ts
- src/utils/resources/vm/utils/selectors.ts
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
Use the backend text instead of the generic text in the pending changes alert
**Before**
Generic message
**Backend text in pending changes**
Some examples
> CNV-52708: use RestartCondition on pending changes alert

- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
The page lets you edit the CPU | memory even tho all the resources were not fetched
**Before**
**After**
It works
> CNV-55697: Fix cpu and memory edit crash

- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
Before:
https://github.com/user-attachments/assets/bc969dcb-a611-429a-bbbe-46a3b6c0fdfb
After:
https://github.com/user-attachments/assets/0a73ea40-2275-4f59-9daf-ca50c19e862f
> CNV-55845: Tree view flickering when it should be off

- src/perspective/extensions.ts
If UDN is not enabled, don't show the networking element 
**Before**
**After**
> OCPBUGS-44823: hide udn in virt networking

- src/utils/components/ExportModal/constants.ts
Use image from unreleased registry that
will contain disk-uploader binary.
> fix: use v4.18.0-27 uploader image

- locales/en/plugin__kubevirt-plugin.json
- src/views/checkups/components/DeleteCheckupModal.tsx
- src/views/checkups/network/components/CheckupsNetworkActions.tsx
- src/views/checkups/storage/components/CheckupsStorageActions.tsx
adding delete confirmation dialog
https://github.com/user-attachments/assets/861c064a-c5ae-44c4-a14f-7f33c31af270
> CNV-38560: [RFE] delete confirmation dialog checkups

- src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
- src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
Before:
https://github.com/user-attachments/assets/70f9e0b6-5cad-48f9-a1c8-c74c8c48dc06
After:
https://github.com/user-attachments/assets/ca3dec8f-8068-476a-8e3d-267dcd514721
> CNV-55900: add/edit disk in customize VM crashes

- src/utils/components/InstanceTypeModal/utils/types.ts
- src/utils/components/InstanceTypeModal/utils/util.ts
Order instancetypes by size
**Before**
**After**
> CNV-49588: order instancetype by size (cpu and memory)

- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Cancel and stop button were a little bit confusion
**Before**
**After**
> CNV-55840: migrate storage remove cancel button

- src/views/checkups/network/details/CheckupsNetworkDetailsPageSection.tsx
- src/views/checkups/network/hooks/useCheckupsNetworkListColumns.ts
- src/views/checkups/network/list/CheckupsNetworkListRow.tsx
- src/views/checkups/network/utils/utils.ts
Fix according suggestion from latest comment here: https://issues.redhat.com/browse/CNV-43411
> CNV-43411: Target node changed after the network checkup finished

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
- src/views/virtualmachines/list/hooks/sortColumns.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/list/metrics.ts
- src/views/virtualmachines/utils/mappers.ts
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Sort VM list by node, CPU, memory and network
**Before**
no sorting
**After**
https://github.com/user-attachments/assets/63ff05eb-52ac-4cf2-9e38-09bd86c977ae
> CNV-49912: sort vm list by nodes, cpu, memory and network

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
When removing all nic's form VM and trying to add a new one, opening the modal crash the app.
> CNV-56004: Fixing no nic in vm - adding new nic crash

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/views/catalog/CustomizeInstanceType/CustomizeInstanceTypeVirtualMachine.tsx
- src/views/catalog/wizard/Wizard.tsx
in customize and wizard there is an infinite loading as statehanlder was waiting for loaded to be true and was not passed
> CNV-55086: fix state handler loading infinite

- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Hide stop button after migration completed
> CNV-56376: Migration hide stop

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/shared/GeneralSettingsProject.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/shared/GeneralSettingsProjectSelector.tsx
Remove the create project button in the settings  as we already have other ways to create projects 
Discussed with guohua and yifat
> CNV-55105: remove create project within the project dropdown

- src/utils/components/DiskModal/utils/form.ts
Creating the dv we use `dv-VM_NAME-3_RANDOM_WORDS-RANDOM_CHARS`
> CNV-56496: use a shorter name for dv

- src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
Add PF select `selectedLabel` prop
**Before**
**After**
> CNV-56499: fix bootmode select in template

- package.json
- src/utils/components/Consoles/Consoles.tsx
- src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
- yarn.lock
Version 1.5 released in Jun 2024 contains multiple improvements over version 1.3 (Oct 2021).
> Update novnc from 1.3.0 to 1.5.0

- src/utils/components/ExportModal/constants.ts
Use image from released registry
that will contain disk-uploader binary.
> fix: use v4.18.0-985 uploader image

- deploy-kubevirt-gating.sh
Also, add some improvements in the CNV deploy script to save unnecessary wait times.
Fixes #2330
> [CI] Use HPP-CSI instead of the legacy one

- OWNERS
Adding @adamviktora @rszwajko @lkladnit @gouyang to owners file
> CNV-57039: Adjusting owners file

- cypress/tests/e2e/a-setup.cy.ts
- cypress/tests/e2e/b-overview.cy.ts
This sums up to **40** tests, **2** of which are currently disabled
Closes https://issues.redhat.com/browse/CNV-57083
> SSH key/secret related tests added

- cypress/support/nav.ts
- cypress/tests/all.cy.ts
- cypress/tests/e2e/d-networking.cy.ts
- cypress/views/nad.ts
Closes https://issues.redhat.com/browse/CNV-57112
> NAD related tests added

- cypress/tests/e2e/a-setup.cy.ts
- cypress/tests/e2e/check-tab-yaml.cy.ts
- cypress/tests/overview.cy.ts
- cypress/tests/overview/overview-tab.cy.ts
Test virtualization overview tab
> CNV-57150: add test for virtualization overview tab

- locales/en/plugin__kubevirt-plugin.json
- src/utils/hooks/useFeatures/constants.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
- src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
- src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
- src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
- src/views/virtualmachines/tree/hooks/useHideNamespaceBar.ts
This PR moves the tree view feature from tech preview to GA.
Note: The tree view folder feature is still in tech preview.
Jira: https://issues.redhat.com/browse/CNV-55956
> CNV-55956: Move the tree view feature from TP to GA

- cypress/cypress.config.js
- cypress/tests/e2e/a-setup.cy.ts
- cypress/tests/overview.cy.ts
- cypress/tests/overview/overview-tab.cy.ts
- cypress/tests/overview/top-consumers-tab.cy.ts
- cypress/views/overview.ts
- cypress/views/perspective.ts
> CNV-57354: add test for top consumers tab

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumesPipelinesHint/BootableVolumesPipelinesHint.tsx
> CNV-57871: Change "boot source" to "bootable volume"

- src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/CPUComponentInput.tsx
- src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.scss
- src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.tsx
- src/utils/components/CPUMemoryModal/components/CPUInput/components/vCPUInput/VCPUInput.tsx
- src/utils/components/CPUMemoryModal/components/MemoryInput/MemoryInput.tsx
- src/utils/components/CPUMemoryModal/cpu-memory-modal.scss
- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
- src/utils/components/Consoles/components/vnc-console/VncConnect.tsx
- src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/DiskSourceSelect.tsx
- src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
- src/views/checkups/network/components/form/CheckupsNetworkFormLatency.tsx
- src/views/checkups/network/components/form/CheckupsNetworkFormNodes.tsx
- src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/MigrationPolicyCreateFormHeader/MigrationPolicyCreateFormHeader.tsx
- src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
- src/views/virtualmachines/actions/components/VMActionsIconBar/VMActionsIconBar.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/AddNetworkInterfaceButton.tsx
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
- src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
- src/views/virtualmachines/details/tabs/metrics/virtual-machine-metrics-tab.scss
- src/views/virtualmachines/list/components/VirtualMachineSelection/virtual-machine-selection.scss
Visual improvements after updating to PF6
- Console is not hidden
- alignment fixes
- color fixes
> Visual improvements after updating to PF6

- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/DefaultRightClickActionMenu.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/TreeViewRightClickActionMenu.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/VMRightClickActionMenu.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/utils.ts
- src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
Add folders and projects right-click actions in the Treeview
https://github.com/user-attachments/assets/f40110c1-79da-45db-9b0a-1df1f8f4593e
> CNV-55202: TreeView folders/projects right click actions

- src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
VM Right click operation overlap with the folder and project one. The project even wins on everything else
**Before**
https://github.com/user-attachments/assets/fdb451fa-1ffe-4900-a0cb-44a121cfe1c9
**After**
https://github.com/user-attachments/assets/1d4182b5-48c5-4e4b-84ea-60a8a120dcdf
> CNV-55202: stop right click treeview propagation

- src/utils/components/DiskModal/components/StorageClassAndPreallocation/StorageClassSelect.tsx
- src/utils/components/DiskModal/components/utils/constants.ts
Read disk source type from the form data to differentiate between blank-disk scenario and other scenarios.
> CNV-58305: Ignore storage class different than boot PVC for blank disks

- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
The form is considered valid if all required fields were provided and no validation errors were found.
https://github.com/user-attachments/assets/75cb03d3-6c5a-4591-9865-d3f291f97191
https://github.com/user-attachments/assets/07207975-5fac-4465-b602-1a68aa3210f0
> CNV-56945: Validate NetworkInterfaceModal based on values in the state

- src/utils/components/NetworkIcons/LinkStateIcon.scss
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceLinkState/NetworkInterfaceLinkState.scss
- src/views/virtualmachines/list/VirtualMachinesList.scss
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/tree/icons/CollapseAllIcon.tsx
- src/views/virtualmachines/tree/icons/ExpandAllIcon.tsx
Fixes alignment issue in table (+ some other class name updates that were still on PF5)
Before:
After:
> CNV-58912: fix aligning VM list table

- cypress/tests/all.cy.ts
- cypress/tests/e2e/a-setup.cy.ts
- cypress/tests/e2e/catalog-filter.cy.ts
- cypress/tests/e2e/create-vm.cy.ts
- cypress/views/actions.ts
- cypress/views/selector-catalog.ts
Closes https://issues.redhat.com/browse/CNV-58596
> CNV-58596: Catalog filtering tests added

- src/views/virtualmachines/tree/hooks/dragndrop.ts
- src/views/virtualmachines/tree/hooks/utils.ts
Error on dropping VM with no labels.
Store the dragging VM instead of only namespace to make use to patch it accordingly.
Adding the /metadata/labels to a VM that already have it, it will means to wipe it every other labels else out
> CNV-54573: fix drop vm with no label error

- src/utils/resources/vm/utils/dataVolumeTemplate/selectors.ts
- src/utils/resources/vm/utils/selectors.ts
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/hooks/sortColumns.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Storageclass name column. If VM has multiple storageclass  names, we'll list them all
> CNV-58541: add storageclassname column

- cypress/tests/e2e/create-vm.cy.ts
Fix for a broken navigation in the test
> Fix flaky navigation

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineStatusWithPopover/VirtualMachineOverviewStatus.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineStatusWithPopover/VirtualMachineProvisioningStatus.tsx
**Before**
https://github.com/user-attachments/assets/54464365-826a-4bac-9559-e8b2e7974a63
**After**
https://github.com/user-attachments/assets/4b76d048-2d4f-4c2a-ae50-022bb0bb3b41
> CNV-59150: Fix diagnostic link

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/ComposableDrilldownSelect/ComposableDrilldownSelect.tsx
Bug fixed [here in the patternfly example code ](https://github.com/patternfly/patternfly-react/pull/11271/files).
Some thing here and its working
> CNV-59275: fix drilldown select crash

- cypress/tests/all.cy.ts
- cypress/tests/e2e/template-list.cy.ts
Closes https://issues.redhat.com/browse/CNV-59175
> CNV-59175: Templates filtering tests

- cypress/support/login.ts
> CNV-59587: skip tour after login the console

- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/resources/vm/utils/network/constants.ts
- src/utils/resources/vm/utils/network/selectors.ts
- src/views/catalog/wizard/tabs/network/hooks/useNetworkRowFilters.ts
- src/views/templates/details/tabs/network/hooks/useNetworkRowFilters.ts
- src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkRowFilters.ts
- src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
Simple refactor PR to rename two variables that touch multiple files.
> Rename interfacesTypes and interfaceLabels

- src/views/virtualmachines/tree/VirtualMachineTreeView.scss
- src/views/virtualmachines/tree/components/PanelToggleButton.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
Changes VM tree view close button styles. Request number 7 in [this doc](https://docs.google.com/document/d/1ZSfyxDfPxRuRNWggAKJ504wLe_t45MAd85jtsdZ34xw/edit?tab=t.0#heading=h.d7oxg5i37fkv)
Before:
https://github.com/user-attachments/assets/edf57fbf-db62-41f5-b332-eeb709abf77a
After:
https://github.com/user-attachments/assets/9b8b8008-643b-4a64-bf84-a2b3c811933f
> CNV-56949: tree view close button styling changes

- src/views/checkups/network/utils/utils.ts
> CNV-57315: Remove unknown params from network checkup job

- cypress/tests/all.cy.ts
- cypress/views/instance-flow.ts
- cypress/views/modals.ts
- test-cypress.sh
Fix leftovers from previous PR
> Remove 1h debug sleep

- src/utils/components/AffinityModal/utils/helpers.ts
Preserve existing content when adding new rules.
https://github.com/user-attachments/assets/87b180af-6f3e-4480-891a-45e81577b3c7
https://github.com/user-attachments/assets/c118e45a-f321-43aa-a1db-05a4a1418c86
> CNV-57651: Allow multiple affinity rules of the same type

- src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
- src/utils/resources/udn/constants.ts
- src/utils/resources/vm/utils/network/constants.ts
Filter out NADs created from udn resources
**Before**
**After**
> CNV-60049: fix interface modal with udn

- src/views/virtualmachines/list/VirtualMachinesList.tsx
Small fix to have pagination with pod proxy alive
In localhost we can't reproduce the issue as we don't use the proxy there.
> CNV-58522: fix vm list paginations for pod proxy

- src/utils/components/PendingChanges/utils/helpers.ts
Verify that the user do not change the nad network name.
https://github.com/user-attachments/assets/ef40f9a9-dffa-4d62-b93c-351dbf3d9030
> CNV-59599: Pending changes detect nad interface

- package.json
- yarn.lock
Updates `@patternfly/react-catalog-view-extension` version to fix styling
Before:
After:
> CNV-60420: update @patternfly/react-catalog-view-extension

- src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/PreviewFeaturesTab.tsx
Use `canEdit` feature attribute to disable the switch that the regular user cannot change
> CNV-56565: Fix previewfeature canedit

- src/utils/resources/vm/utils/selectors.ts
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachines/list/hooks/sortColumns.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/utils/mappers.ts
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Storageclasse in the VM list was detected from the VM spec. But when VM use the default storage class do not have this info.
Fetch it from the pvcs
IN order to access it faster, create a PVC mapper
**Before**
**After**
https://github.com/user-attachments/assets/9b6c25c3-a704-4438-8f75-e84e609615cd
> CNV-60576: show pvc storageclass

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDetails.tsx
When there is no migratable PVC we let the user continue in the migration modal
> CNV-60551: show no migratable pvcs in the migration list

- package.json
- yarn.lock
upgrade cypress version to 14.3.x
> CNV-60359: upgrade cypress version to 14.3.x

- src/views/storagemigrations/extensions.ts
> CNV-60343: fix storagemigration link

- src/utils/resources/instancetype/selectors.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
https://github.com/user-attachments/assets/9cd5bf5e-9e60-4741-ac7b-5170f51b0ecc
> CNV-46341: Use controllerRevisionRef.name for preference and instance type

- src/utils/components/ExportModal/constants.ts
Bump uploader images to use binary from latest released registries.
> chore: bump uploader images

- src/perspective/extensions.ts
I'll add them in nmstate plugin
> CNV-61011: Remove nncs and nncp virt links and move them in nmstate plugin

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
cherry picking [CNV-60605](https://issues.redhat.com//browse/CNV-60605): Fix rerendering all over vm details #2612
> [release-4.18] CNV-60605: Fix rerendering all over vm details 

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
backporting : https://github.com/kubevirt-ui/kubevirt-plugin/pull/2621
> [release-4.17] CNV-60605: Fix rerendering all over vm details 

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
fixing a navlink crash . 
Just cherry-picking did not work. 
the 4.17 backport do not have this issue: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2630
> [release-4.18] CNV-60605: Fix rerendering all over vm details

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
Fix the error in a `find`
**Error**
> `find undefined` Make persistent fix

- cypress/support/nav.ts
- cypress/tests/all.cy.ts
- cypress/tests/e2e/set-default-sc.cy.ts
- cypress/views/actions.ts
test for set default storageclass
> CNV-59099: test for set default storageclass

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
- src/views/virtualmachines/list/hooks/constants.ts
- src/views/virtualmachines/list/utils/totalsQueries.ts
Hide metrics on non-running vm
(The metrics are shown as there is a delay in Prometheus  )
https://github.com/user-attachments/assets/20053c47-4cc3-4bdb-91de-42ad5ceae1f5
> CNV-59371: Show metrics on running vm

- cypress/cypress.config.js
- cypress/tests/downstream/a-setup.cy.ts
- cypress/tests/downstream/b-setup.cy.ts
- cypress/tests/downstream/vm-action.cy.ts
- cypress/tests/downstream/vm-actions/bulk-operation.cy.ts
- cypress/tests/overview/overview-tab.cy.ts
- cypress/tests/vm-action/vm-actions-confirm.cy.ts
- cypress/views/migrate-modal.ts
> CNV-58544: test for bulk storageclass migration

- src/utils/components/LabelsModal/LabelsModal.tsx
- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/utils.ts
- editing is enabled even if no label is shared
- editing doesn't overwrite non-shared labels
Before:
https://github.com/user-attachments/assets/2a223dc7-bc62-4bc2-ab79-ff4d28de9900
After:
https://github.com/user-attachments/assets/66b9d1de-030d-4b2b-ba90-6682402c614c
> CNV-60146: edit labels on multiple VMs bug fixes

- src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
- src/utils/components/ColumnManagementModal/column-management-modal.scss
- src/utils/components/TabModal/TabModal.tsx
- src/views/checkups/components/DeleteCheckupModal.tsx
- src/views/virtualmachines/actions/components/ConfirmMultipleVMActionsModal/ConfirmMultipleVMActionsModal.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
- align positioning of Modal footer buttons with PatternFly
- use danger button and warning icon for Delete modals
> CNV-61535: modal buttons fix alignment

- locales/en/plugin__kubevirt-plugin.json
- src/utils/constants/documentation.ts
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
> CNV-61810: update doc link to 4.19

- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
Jira: https://issues.redhat.com/browse/CNV-61969
> CNV-61969: Fix resource link for VM root disk in VM disks list

- src/utils/components/DurationOption/DurationDropdown.tsx
- src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Adds `isScrollable` to Select components that have a variable length of options, or too many options.
> CNV-62082: make Selects scrollable

- OWNERS
adding myself to owners 
before:
after:
> adding batya to owners

- package.json
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIEditor/YamlAndCLIEditor.tsx
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/components/YamlAndCLIViewerModal/YamlAndCLIViewerModal.tsx
- yarn.lock
Make sure we use the latest Console 4.19 plugin SDK packages.
> Use latest Console 4.19 plugin SDK packages

- cypress/views/selector-common.ts
- cypress/views/selector.ts
- plugin-extensions.ts
- src/perspective/extensions.ts
- src/utils/components/AffinityModal/components/AffinityList/components/AffinityRow.tsx
- src/utils/components/HardwareDevices/list/HardwareDeviceRow.tsx
- src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
- src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
- src/views/checkups/network/list/CheckupsNetworkListRow.tsx
- src/views/checkups/storage/list/CheckupsStorageListRow.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
- src/views/datasources/list/DataSourcesListRow.tsx
- src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
- src/views/instancetypes/list/components/UserInstancetypeRow.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
- src/views/preferences/list/components/ClusterPreferenceRow.tsx
- src/views/preferences/list/components/UserPreferenceRow.tsx
- src/views/storagemigrations/list/components/StorageMigrationRow.tsx
- src/views/storagemigrations/list/hooks/useStorageMigrationColumns.ts
- src/views/templates/details/tabs/disks/components/DiskRow.tsx
- src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
- src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
> CNV-62226: Add missing attributes to tables and navigation.

- src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
- src/views/virtualmachines/details/tabs/yaml/virtual-machine-yaml-page.scss
Unnecessary scroll bar, and unused space for tabs - yam; and configuration under VM details page.
Before:
After:
> CNV-62175: Remove scroll bar from VM yaml & configuration tab

- src/utils/components/ListPageFilter/components/TextFiltersToolbarItem.tsx
- src/utils/components/ListPageFilter/hooks/useListPageFiltersMethods.ts
- fixes search by Label which didn't work if multiple labels were used
- fixes "filter is undefined" issue on clicking "Clear all" button
Before:
https://github.com/user-attachments/assets/801d0431-77d8-478e-91f9-d4ac926b2854
After:
https://github.com/user-attachments/assets/209036ef-4de9-4bb1-b0d7-93616fcc5c83
> CNV-62313: CNV-62292: fix search by multiple labels

- package.json
- src/utils/components/GuidedTour/GuidedTour.tsx
- yarn.lock
in the user guided tour on step 6 the bottom page view was missing where the target for the popover appears. the problem occurs through the joyride package- the page has difficulty scrolling down to the target and has known issues with scrolling. i forced a scroll to the target when it appears by id in the tourGuide file in the joyride callback and updated the joyride package. 
before:
after:
> CNV-62203: fixing bottom page display on guided tour step 6

- package.json
- src/utils/components/CloneVMModal/CloneVMModal.tsx
- src/utils/components/CloneVMModal/components/CloningStatus.tsx
- src/utils/components/CloneVMModal/hooks/useCloneVMModal.ts
- src/utils/components/CloneVMModal/utils/helpers.tsx
- src/utils/resources/shared.ts
- src/views/cdi-upload-provider/utils/selectors.ts
- yarn.lock
Update the kubevirt-api version to v1.3.8.
> Update kubevirt-api package version to v1.3.8

- src/utils/components/DiskModal/utils/form.ts
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/components/DiskModal/utils/submit.ts
Make DataVolume and PVC name be based on the disk name
After:
https://github.com/user-attachments/assets/8901a349-c1eb-4e2e-9c37-ba29dc78c5db
> CNV-62815: DataVolume name is derived from disk name

- src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
- src/utils/components/Charts/ChartLabels/SubTitleChartLabel.tsx
- src/utils/components/Charts/ChartLabels/TitleChartLabel.tsx
- src/utils/components/Charts/ChartLabels/styleOverrides.ts
- src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
- src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
- src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
- src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsTimeAxis.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
- src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.tsx
- src/views/clusteroverview/OverviewTab/vms-per-resource-card/VMsPerResourceChart.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
Applying changes from this PR https://github.com/kubevirt-ui/kubevirt-plugin/pull/2427 by @rszwajko to `release-4.18` branch
> CNV-62937: Use custom chart styles based on PatternFly CSS variables

- src/utils/components/DiskModal/utils/form.ts
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/components/DiskModal/utils/submit.ts
Backporting changes from https://github.com/kubevirt-ui/kubevirt-plugin/pull/2714 to 4.18 as requested on Jira by the issue author.
> [release-4.18] CNV-62815: DataVolume name is derived from disk name

- src/utils/hooks/useCDIUpload/utils.ts
Backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/2726 to 4.18
> [release-4.18] CNV-62819: increase timeout for DataVolume to be ready to upload

- src/utils/components/TabModal/TabModal.tsx
Show proper error message when bootable volume upload fails.
Before:
After:
> CNV-62923: show proper error message when volume upload fails

- src/utils/utils/utils.ts
- src/views/topology/components/ODCBaseNode.tsx
- src/views/topology/extensions.ts
- src/views/topology/hooks/useModifyApplicationActionProvider.ts
- src/views/topology/hooks/usePodsAdapterForVM.ts
- src/views/topology/hooks/usePodsForVM.ts
- src/views/topology/hooks/useVMSidePanelDetailsTabSection.tsx
- src/views/topology/topology.ts
- src/views/topology/utils/constants.ts
- src/views/topology/utils/is-kubevirt-resource.ts
- src/views/topology/utils/kubevirt-component-factory.ts
- src/views/topology/utils/kubevirt-data-transformer.ts
- src/views/topology/utils/resource-utils.ts
- src/views/topology/utils/topology-utils.ts
- src/views/topology/utils/utils.ts
- src/views/topology/utils/vm-tab-sections.tsx
- yarn.lock
This PR adds the remaining topology extensions.
Jira: https://issues.redhat.com/browse/CNV-56431
> CNV-56431: Add remaining virtualization topology extensions

- src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/resources/udn/hooks/useNamespaceUDN.ts
- src/utils/resources/udn/types.ts
Support user-defined network (UDN) as secondary network
https://github.com/user-attachments/assets/8498cc99-d708-4514-abcd-f69b95c900d6
> CNV-61063: Support user-defined network (UDN) as secondary network

- cypress/support/selectors.ts
- cypress/tests/upstream/vm-adv-search.cy.ts
- cypress/tests/us.cy.ts
- test-setup.sh
- test VM search bar
- test VM search in other project
- test VM search by description
- test VM search by labels
- test VM search by vCPU
- test VM search by memory
- test VM search by IP
- test VM search by name
- clear search
- test saving search
- test reusing saved search
- test removing saved search
- exit search
> CNV-63362: Test advanced VM search

- src/utils/resources/vm/utils/index.ts
- src/utils/resources/vm/utils/utils.ts
- src/utils/utils/utils.ts
- src/views/clusteroverview/OverviewTab/inventory-card/utils/vm-status-section/VMStatusInventoryItem.tsx
- src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
- src/views/clusteroverview/OverviewTab/vms-per-resource-card/RunningVMsChartLegendLabel.tsx
- src/views/clusteroverview/OverviewTab/vms-per-resource-card/utils/utils.ts
This PR adds a link to the legend item for uncategorized VMs in the VMs per Resource chart on the Virtualization Overview page.
Jira: https://issues.redhat.com/browse/CNV-63016
> CNV-63016: Add link for uncategorized VMs in VMs per Resource chart

- LICENSE
According to https://www.mozilla.org/en-US/MPL/2.0/FAQ/ 
> Q8: I want to distribute (outside my organization) executable programs or libraries that I have compiled from someone else's unchanged MPL-licensed source code, either standalone or part of a larger work. What do I have to do?
>
>You must inform the recipients where they can get the source for the MPLed code in the executable program or library you are distributing (i.e., you must comply with Section 3.2). You may distribute any executables you create under a license of your choosing, as long as that license does not interfere with the recipients' rights to the source under the terms of the MPL.
>
> Add notice about noVNC licence

- src/utils/constants/documentation.ts
[CNV-62147 doc](https://docs.google.com/document/d/1iGkHb1eTbD5lWN9uY05NAzckozMUufWMiSCwUSJZVaQ/edit?tab=t.0#heading=h.f0gwk9besg6x) updates
> CNV-64453: Fix and optimize documentation URLs

- src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
https://github.com/user-attachments/assets/ccb04573-fd2b-486d-b05e-fb954102c510
> CNV-59354: Use VirtualMachine route to standalone console

- src/templates/vm-yaml.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
when creating a vm from yaml changing the vm example to a rhel9 one instead of fedora
before:
after:
> CNV-61454: when creating a vm in yaml changing example to rhel9 instead of fedora

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
added ssh key creation in customizing a vm created from template. 
Before:
https://github.com/user-attachments/assets/5c5122ec-3281-461c-8def-ba4efa44bd23
After:
https://github.com/user-attachments/assets/c4da4ba9-6157-4948-a2c3-db3aec17539f
> CNV-61359: fixing SSH key creation when creating vm from template

- src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
- src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
- src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
- src/utils/hooks/useVMQueries.ts
- src/utils/resources/vm/hooks/useMigrationPercentage.tsx
- src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
Refactor of vm metrics with the discussed
> ACM-20341: refactor vm metrics with acm logic

- src/utils/components/SSHAccess/components/SSHCommand.tsx
added selector labels to vmi to be able to display the right status in the ui
before:
after:
> CNV-64734: added service labels to vmi so the updated status would display in the ui

- cypress/support/selectors.ts
- cypress/tests/gating/vm-adv-search.cy.ts
- cypress/tests/setup/setup.cy.ts
- src/utils/components/EnvironmentEditor/components/EnvironmentFormActions.tsx
- src/views/clusteroverview/SettingsTab/SettingsTab.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/components/SSHAuthKeyRow/SSHAuthKeyRow.tsx
- src/views/search/components/AdvancedSearchModal/AdvancedSearchModal.tsx
- src/views/search/components/SaveSearchModal.tsx
- src/views/search/components/SavedSearchesDropdown.tsx
- src/views/search/components/SearchSuggestBox/SearchSuggestBox.tsx
- src/views/templates/details/tabs/details/components/CPUMemoryModal/CPUMemoryModal.tsx
- src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
This optimizes the tests to use non-class selectors
> CNV-64532: Reduce classname usage in tests

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
> ACM-20341: add cluster column in vm row

- src/multicluster/hooks/useClusterParam.ts
- src/multicluster/hooks/useIsAllClustersPage.ts
- src/multicluster/hooks/useVMListQueries.ts
- src/utils/hooks/useNamespaceParam.ts
- src/views/virtualmachines/list/hooks/useVMMetrics.ts
- src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
- src/views/virtualmachines/list/utils/totalsQueries.ts
- tsconfig.json
Summary metrics do not show all clusters metrics. With this pr we'll do it correctly
> ACM-20341: Fix VM list summary metrics on multicluster view

- __mocks__/multicluster-sdk.ts
- src/multicluster/components/ACMExtentionsTableData.tsx
- src/multicluster/hooks/useACMExtensionActions/constants.ts
- src/multicluster/hooks/useACMExtensionActions/useACMExtensionActions.ts
- src/multicluster/hooks/useACMExtensionActions/utils.tsx
- src/multicluster/hooks/useACMExtensionColumns/useACMExtensionColumns.tsx
- src/multicluster/hooks/useACMExtensionColumns/utils.ts
- src/multicluster/hooks/useACMExtensionsHeaders.ts
- src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
- src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
DEMO
(The error occuring in the modal is because i've not properly setup the odf operator btu the modal is called correcly)
https://github.com/user-attachments/assets/7244e023-3cf1-46ad-b459-f51e496bdfef
> ACM-20341: Multicluster sdk odf integration

- cypress/tests/gating/vm-adv-search.cy.ts
- deploy-kubevirt-gating.sh
we have to fix this part when adam will be back.
remove the 2hr sleep
> skipping CPU and memory adv search test

- @types/console/index.d.ts
- console-telemetry.md
- cypress/support/index.ts
- cypress/support/login.ts
- src/utils/extensions/telemetry/telemetry.ts
- src/utils/utils/utils.ts
- tsconfig.json
Backport of #2808 for `release-4.19` code branch.
> CNV-65960: Adapt Segment analytics code based on Console telemetry plugin

- package.json
- src/multicluster/hooks/useACMExtensionActions/useACMExtensionActions.ts
- src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
fixing break after press action btn which happen because infinite render.the infinite render was becuse acmActions dependency its arry so i wrap it with useMemo
Before:
/home/aavissar/Pictures/Screenshots/Screenshot From 2025-07-15 14-37-02.png
After:
/home/aavissar/Pictures/Screenshots/Screenshot From 2025-07-15 14-29-50.png
> CNV-64218: Project workloads view breaks on VMs

- src/views/virtualmachines/tree/utils/utils.tsx
The clusters order is random
When the user land into the vm page, the treeview needs to open the vm cluster and vm namespace
> ACM-20341: Order clusters and open them by default if selected

- package.json
- src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
- src/utils/hooks/useKubevirtWatchResource/useRedirectWatchHooks.ts
- src/views/virtualmachines/search/hooks/useVMSearchQueries.ts
- yarn.lock
Modify the search hook parameter in order to have two times the same key in the query and an AND condition
Usign the new multisearch version that accept an array of objects instead of a single object. (This is mandatory to have an AND condition in the search api)
> ACM-20341: add created parameter to the search api

- src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
- src/utils/components/ActionsDropdown/constants.ts
- src/utils/resources/shared.ts
- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/components/VMActionsIconBar/components/ActionIconButton.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/InitialRunTab.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewTabDetailsConsoleWrapper.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabGeneral/VirtualMachinesOverviewTabGeneral.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Use fleet component to check access reviews in other clusters
> ACM-20341: fleet access review for vm pages

- src/multicluster/hooks/useGuestAgentURL.ts
- src/multicluster/hooks/useInstanceTypeSpecURL.ts
- src/multicluster/hooks/useK8sBaseAPIPath.ts
- src/utils/components/Consoles/ConsoleStandAlone.tsx
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/hooks/useVirtualMachineLogData.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
- src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
Do not use directly the `useFleetK8sAPIPath` hook but use a cnv hook that use it so we de-couple it from the sdk
> ACM-20341: make cnv hook for k8s api path

- cypress/tests/gating.cy.ts
- cypress/tests/gating/check-tab-yaml.cy.ts
- plugin-extensions.ts
- src/perspective/extensions.ts
Removing Prefrences from virtualization navigation menu
Before:
After:
> CNV-66351: Removing Prefrences from virtualization navigation menu

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/multicluster/components/CrossClusterMigration/CrossClusterMigration.tsx
- src/utils/components/ActionDropdownItem/ActionDropdownItem.scss
- src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
Add a migrate submenu to display all the migration option (storage and cross cluster)
Make sure to add the cross clsuter migration only if the mtv is installed, if the selected vms are in the same cluster and same namespace (after that we'll evaluate if same namespace is too strict or we can do migrations from different namespaces)
> CNV-65202: Cross cluster migration bulk action

- package.json
- src/utils/components/HardwareDevices/utils/constants.ts
- yarn.lock
This PR updates the kubevirt-api package to v1.4.0
> Update kubevirt-api to v1.4.0

- i18n-scripts/export-pos.sh
- i18n-scripts/memsource-upload.sh
Uploaded PO files are invalid for memsource. The issue is a `;` at the end of the plural definition. Just fix that with a script
> fix po files for memsource

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
> CNV-66455: fix typo of "Edit InstanceType"

- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/RegistrySource.tsx
- src/utils/components/AddBootableVolumeModal/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/utils/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/ContainerSource.tsx
Added username and password fields to the registry source option in the bootable volume modal
Before:
After:
> CNV-65108: Adding credentials to the add volume modal for registry source type

- cypress/tests/gating.cy.ts
- cypress/tests/tier1/vm-tab.cy.ts
- cypress/tests/tier1/vm-tabs/vm-adv-search.cy.ts
1. the advance search test is flaky, move it out of gating
> CNV-66511: move advance search out of gating

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/hooks/useFeatures/constants.ts
- src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
- src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
- src/views/virtualmachines/search/VirtualMachineSearchResults.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
- src/views/virtualmachines/tree/hooks/useFilteredTreeView.ts
- make advanced search feature generally available - remove from "preview features"
- removes search above tree view completely (was hidden before when advanced search was active)
> CNV-61755: make advanced search feature GA (general availability)

- package.json
- yarn.lock
- backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/2880 to 4.19
> [release-4.19] CNV-66337: update axios and form-data dependency

- package.json
- yarn.lock
- backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/2880 to 4.18
> [release-4.18] CNV-66338: update axios and form-data dependency

- src/views/checkups/network/components/CheckupsNetworkActions.tsx
- add missing "Actions" text to menu toggle
Before:
After:
> CNV-66909: add missing "Actions" text to menu toggle

- src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Fixing name definition for storage migration 
Before:
After:
> CNV-67145: Fix migration storage long vm name

- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/VirtualMachineLogViewer.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/constants.ts
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/hooks/useVirtualMachineLogData.ts
- `guest-console-log` container has changed it's location in YAML on backend
- this PR updates path from `pod.spec.containers` to `pod.spec.initContainers` so the logs are visible in UI
Before:
https://github.com/user-attachments/assets/cafa486c-8305-4b0d-b34d-598507a243d5
After:
https://github.com/user-attachments/assets/a8671b15-186d-42db-a66b-4c8642f3fd70
> CNV-66657: fix unavailable Guest system log

- src/multicluster/urls.ts
- src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
- fixes a bug, where "all-namespaces" project was being set when clicking on InstanceTypes / Template catalog tabs
Before:
https://github.com/user-attachments/assets/b0120f59-8541-4b6a-9af4-f04c73ba48e9
After:
https://github.com/user-attachments/assets/18820efa-dcea-4456-af30-2d0306ecd857
> CNV-67463: fix "all-namespaces" project showing up in Catalog

- src/utils/components/VMSSHSecretModal/VMSSHSecretModal.tsx
- src/utils/resources/secret/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/AuthorizedSSHKey.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
- src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
when creating a vm from user template with ssh key an error would occur not allowing for vm creation. 
template ssh secrets were incorrectly treated as new secrets instead of existing secrets, causing duplicate creation.
Before:
After:
https://github.com/user-attachments/assets/a8d8c553-4932-4783-82aa-9fe56d69855f
> CNV-66273: create vm from template with ssh

- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DeletionProtection/DeletionProtectionModal.tsx
User is now able to add a delete protection to a VM when creating it.
> CNV-61108: Add delete protection to vm creation

- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
- sort VirtualMachines alphabetically in tree view 
Before:
After:
> CNV-67816: sort VirtualMachines alphabetically in tree view

- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
- use natural sort instead of alphabetical (followup to https://github.com/kubevirt-ui/kubevirt-plugin/pull/2924)
> CNV-67816: use natural sort instead of alphabetical

- src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
Do not let the user enable this feature if the acm backend is not even there
> Disable multicluster feature flag if no fleet available

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/components/VirtualMachinesOverviewTabNetworkFQDN.tsx
- src/views/virtualmachines/details/tabs/overview/utils/utils.tsx
Using the hostname when it's present to generate the FQDN URL. 
https://github.com/user-attachments/assets/f94e1ad9-412b-4dfd-8c8e-ddba1f946fdb
> CNV-66617: Refactor FQDN generation

- src/utils/utils/units.ts
quantity is optional as for HTTP and Container disks we don't need that. 
This is crashing template catalog
> CNV-68469: make sure quantityString is optional

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
Depends on: #2933 
Follow-up to: #2919
https://github.com/user-attachments/assets/e25e323b-a8e7-4c39-b2d7-22407d265eba
https://github.com/user-attachments/assets/3d7f9d8b-2051-4bad-ae98-0c9b1022c288
> CNV-68347: Force re-creating NetworkSelect on network pre-selection

- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
- src/utils/resources/vm/utils/constants.ts
Depends on: #2933 
Use POD_NETWORK constant to detect Pod Network
https://github.com/user-attachments/assets/844dcafe-f865-482a-af81-8730510b4ed4
https://github.com/user-attachments/assets/c2696832-45f5-44ab-8ede-b80421958794
> CNV-61453:  Use POD_NETWORK constant to detect Pod Network

- src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
- fixes tree view reloading bug
BEFORE:
https://github.com/user-attachments/assets/a2ae8c03-5776-4c8e-ab05-8f8b6788ccf4
AFTER:
https://github.com/user-attachments/assets/4dae03f1-b6af-4e7b-b11c-c47194abd002
> CNV-68724: fix tree view reloading

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
- src/utils/components/NetworkInterfaceModal/components/hooks/types.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/useFetchNADs.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
- src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts
**EXTERNAL CLUSTER VM SHOWS EXTERNAL CLUSTER NAD**
> CNV-68780: fetch NADs from vm cluster

- src/multicluster/components/CrossClusterMigration/components/ReadinessStep.tsx
Indexes vms do not have uid field, so we have to use the namespace and name fields.
> CNV-68829: use namespace and name instead of uid 

- OWNERS
> Makes gal approver

- src/multicluster/urls.ts
- src/utils/resources/vm/utils/utils.ts
- src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
Make sure that clicking on vm list summary numbers will led to the same view and not switch from the multicluster to singlecluster view
> CNV-69007: fix summary links for all cluster vm list

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/VirtualizationFeaturesWizard.tsx
- changes Wizard "Next" button text to "Finish" in last step (in Settings -> Virtualization features -> Configure features)
- adds translations for "Cancel" and "Back" button too
> CNV-68855: fix wizard next button text

- package.json
- yarn.lock
The new version use the new indexed values for vms (architecture, sockets and threads)
> bump multicluster sdk version

- src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/VirtualizationFeaturesContext/utils/hooks/useVirtualizationFeatures/useVirtualizationFeatures.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/utils/VirtualizationFeaturesContext/utils/utils.ts
changing the routing in virtualization feature links and overview related operators from operatorhub to catalog after console change to display the operator items in the catalog instead of 404 error page.
Before:
https://github.com/user-attachments/assets/9909ee51-b5da-444d-8a33-23dcaa60ae05
After:
https://github.com/user-attachments/assets/df1bcda4-f5ee-4512-91d6-8976f75fbcd7
> CNV-69444: Fixing routing to correctly display operators in the software catalog

- src/multicluster/components/CrossClusterMigration/hooks/useCrossClusterMigrationSubmit.ts
- src/multicluster/components/CrossClusterMigration/hooks/useStorageReadiness.ts
- src/multicluster/components/CrossClusterMigration/hooks/utils.ts
- src/multicluster/components/CrossClusterMigration/types.ts
- src/multicluster/components/CrossClusterMigration/utils.ts
make sure `.spec.type` is `live` 
`spec.map.source.id` is not necessary
Make sure to run the migration plan with a creation of migration !
> CNV-69750: Fix cross cluster migration live

- src/views/virtualmachines/tree/hooks/dragndrop.ts
- src/views/virtualmachines/tree/hooks/useSelectNamespaceBasedOnPrivileges.ts
- src/views/virtualmachines/tree/hooks/utils.ts
Make sure drag n drop now works with the cluster parameter in the element ID (in folders and vm elements)
> CNV-69747: fix multicluster treeview draganddrop

- src/utils/components/DiskModal/AddCDROMModal.tsx
- src/utils/components/DiskModal/utils/constants.ts
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
- src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/index.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MountCDROMModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
[CNV-69308](https://issues.redhat.com/browse/CNV-69308): 
When DeclarativeHotplugVolumes is enabled and HotplugVolumes is removed from `featureGates` - `hotpluggable=true` should be added to the cd-rom volume. 
https://github.com/user-attachments/assets/c46577ff-ceac-4a27-b954-7536d8e841d7
https://github.com/user-attachments/assets/058b9af5-7892-4a94-88fb-7db7866b04e1
> CNV-69308: Adding a CD-ROM drive: hotpluggable should be set to true when DeclarativeHotplugVolumes is enabled

- src/utils/components/DiskModal/AddCDROMModal.tsx
- src/utils/components/DiskModal/components/DiskNameInput/DiskNameInput.tsx
- src/utils/components/DiskModal/components/DiskSourceSelect/components/DiskSourceUploadPVC/DiskSourceUploadPVC.tsx
- src/utils/hooks/useCDIUpload/utils.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MountCDROMModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
[CNV-69306](https://issues.redhat.com/browse/CNV-69306): User should not be able to change the CD-ROM name / file when the ISO is being uploaded. 
Before:
https://github.com/user-attachments/assets/4c87639e-071a-40ea-b7ee-897283a57276
After: 
https://github.com/user-attachments/assets/0dbfe8de-82b7-4577-b841-29dd524a2efc
> CNV-69306: Disable relevant buttons when uploading a a file in mount / add cd-rom modal

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/VirtualizationFeaturesSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/LoadBalanceSection/LoadBalanceSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/SummaryStatusIcon/SummaryStatusIcon.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/utils/utils.ts
This PR adds a text label to the installing icon in the virtualization features wizard summary step.
Jira: https://issues.redhat.com/browse/CNV-68860
> CNV-68860: Add Installing label to virt features wizard summary page

- package.json
- yarn.lock
upgrade axios  to at least 1.12.0
> CNV-69617: fix axios cve

- src/utils/constants/documentation.ts
> CNV-69930: update dock link for 4.19

- package.json
- yarn.lock
Updates to @stolostron/multicluster-sdk@0.7.5
We now have some metrics when running in-cluster for VMs on managed clusters
> CNV-69917 Update to @stolostron/multicluster-sdk@0.7.5

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- plugin-metadata.ts
- src/utils/constants/documentation.ts
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
Jira Ticket: [CNV-69851](https://issues.redhat.com/browse/CNV-69851)
Automatically get current version from plugin-metadata
> CNV-69851: Automatically get current version from plugin-metadata

- src/views/search/components/SearchBar.tsx
- src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
[CNV-70149](https://issues.redhat.com/browse/CNV-70149): Fixing an issue where due to an infinite render loop page crashes when rendering search results. 
Before:
https://github.com/user-attachments/assets/343f4688-e001-4638-a4b2-f1b363208097
After:
https://github.com/user-attachments/assets/33caf821-f5c1-43f0-862c-54e13859e86e
> CNV-70149: Page crash when searching for a vm

- src/utils/components/TemplateValue/TemplateValue.tsx
- fix alignment of Boot order
Before:
After:
> CNV-70169: fix alignment of Boot order

- src/multicluster/extensions.ts
- src/multicluster/urls.ts
When clicking VMI links on ACM, the page go into the VM page. This is confusing.
> CNV-69969: remove extension for vmi link

- src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
- src/views/instancetypes/list/components/UserInstancetypeRow.tsx
The link in case of multicluster will navigate the user to the acm search page.
> CNV-69204: fix instancetype link when multicluster page
