kubevirt-ui/kubevirt-plugin

- src/utils/components/PendingChanges/utils/helpers.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/LiveMigratePendingChanges.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
- src/views/virtualmachines/details/utils/utils.ts
This PR fixes a bug wherein the restart section of the pending changes alert is shown after adding a hot-plug NIC when there are no pending changes for that section.
jira issue: https://issues.redhat.com/browse/CNV-32912
> CNV-32912: Fix duplicate pending changes messages

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
Backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1535
jira issue: https://issues.redhat.com/browse/CNV-33137
> CNV-33137: Fix hot plug NIC not added to VMI after live migration

- src/utils/components/CloneTemplateModal/utils.ts
- src/utils/constants/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/templatescatalog/tests/mocks.ts
- src/views/templates/actions/editBootSource.ts
Align the name of the bootable volume to `rootdisk`
Before:
After:
> CNV-32995: Align volume name 'rootdisk' convention

- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
When clicking paste in the console screen the button stays in focus and when clicking enter it pastes again.
the fix is those 2 lines of code:
e.currentTarget.blur();
e.preventDefault();
the rest is to remove React.* 
> CNV-32923: Fix clicking enter after copy console

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
Sorting IT according to their CPUs and Memory
Before:
After:
> CNV-33013: Sort the instanceType list by the size of CPU and memory

- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
- src/views/virtualmachines/list/VirtualMachinesList.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-33133
Make empty state related buttons for _VirtualMachines_ list and _MigrationPolicies_ list pages not blink, when entering those pages for the first time.
Note that the problem this PR is fixing, is not so easy to reproduce and not always reproducible, you must try couple of times to see the issue there.
**Before**:
_VirtualMachines_ list page (see how the buttons blink once or twice when entering the page):
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/4d96880e-117b-46d3-a5ed-aa6705c69085
_MigrationPolicies_ list page (see how the buttons blink once or twice when entering the page):
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/f4d9efa9-5d77-43fc-a5d4-3ae112635470
**After:**
_VirtualMachines_ list page …
> CNV-33133: Make buttons in VMs and MigrationPolicies pages not blink

- src/utils/components/SSHSecretSection/utils/utils.ts
- src/utils/resources/vm/utils/selectors.ts
- src/utils/resources/vm/utils/source.ts
- src/views/catalog/wizard/tabs/scripts/components/DynamicSSHKeyInjectionWizard.tsx
- src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
- src/views/virtualmachines/details/tabs/configuration/scripts/hooks/useDynamicSSHInjection.ts
These changes involve adding the missing line - 'runcmd - [ setsebool, -P, virt_qemu_ga_manage_ssh, on ]` to the YAML in instanceTypes.
Also, I fixed the problem that after creating a VM, and the dynamic SSH key injection switch was turned on, we could not edit the ssh key. Now, we should be able to edit or remove the SSH key.
If the dynamic SSH key injection switch has not been activated, it will not be possible to edit the ssh key after creation and the option to edit will be disabled.
Template-
InstanceType -
> CNV-32684: Fixing the dynamic ssh key injection

- src/templates/bootablevolume-yaml.ts
add immediate bind annotation to allow image import
YAML edited:
PVC bound:
> CNV-32266: The example of bootable volumes does not show in the list

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachineOverviewStatus/VirtualMachineOverviewStatus.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-33531
Make _View diagnostic_ broken link, displayed in VM _Overview_ _Details_ card _Status_ popover, lead to _Diagnostics_ tab successfully, in case of some VM status error. Make the link work by using `createUrl` util to generate the url for the page correctly.
Note that when finding and then investigating this bug, I've found that all other links present in the VM _Overview_ tab were created by use of `createUrl`. It seems it was just forgotten to use it also for that broken link hidden in the popover of one field in that page.
Also note that you must click on _Overview_ tab to be able to always reproduce the bug. When accessing _Overview_ tab from VM list page and not clicking on the tab name explicitly, you won't be able to reproduce …
> CNV-33531: Fix broken Diagnostics link in VM Overview Details card

- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
- src/views/virtualmachines/list/VirtualMachinesList.tsx
In the VM and MP list pages we get a couple of flickering situations:
1. When we switch from any route to the VMs list page we load then we get an empty state then load again then the real list. (Same thing for MP list)
2. When we switch NS inside the VM list page, the empty state remains on the screen even though the data is currently loading. 
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/45f01fde-80b6-456c-8745-bb36dc49b9cc
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/f575229a-bf7f-4250-a51e-c73fe6941391
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/4c78c629-97cc-403d-8f8f-0d6d175f5f26
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/f42ce2d8-3616-4fed-a03a-cf1d5fe04dd7 …
> Empty state flickering in VM list

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
More info on the BE jira: https://issues.redhat.com/browse/CNV-32985
Before:
After:
> Remove Overcommited IT series from create VM flow

- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/vmi/utils/selectors.ts
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
- src/views/virtualmachines/details/tabs/configuration/network/utils/constants.ts
- src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
This PR fixes an issue where the pending changes alert and pending label appear briefly, then disappear when a hot-plug NIC is added to a VM.
jira issue: https://issues.redhat.com/browse/CNV-33499
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/ca42b3fd-ded7-4b5a-a82e-f997ffc7dfb8
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/f7c5d261-4417-4b6b-89c3-89456eb75a09
> CNV-33499: Fix hot-plug NIC pending changes behavior

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/views/virtualmachines/actions/actions.ts
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
This PR fixes a bug where hot-plug NICs are not added upon completion of the Add network interface modal. This was caused by a change in the implementation of NIC hot-plug in the backend. The subresource API endpoints for `addInterface` and `removeInterface` were removed in favor of patching the YAML.
jira issue: https://issues.redhat.com/browse/CNV-33502
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/75fa0a89-5691-4954-8dd5-c3cb5e512732
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/2d907a49-20ac-4668-9d9c-935e671b7c27
> CNV-33502: Fix add/remove hot-plug NIC behavior

- src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
When adding a new SSH key we get an error (BE bug), but even though we get an error and close the modal dialog, the state is saved to the form
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/e585aa34-7ca5-4e5e-a89b-e24235fd6bd2
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/d9ee4ccf-0684-4e22-84d0-8cc6cdef0e45
> SSH modal saves state even if error encountered

- src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.tsx
- src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
- src/utils/components/CloudinitModal/utils/useCloudInit.ts
- src/utils/components/SSHSecretSection/utils/utils.ts
- src/utils/resources/vmi/utils/cloud-init.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/wizard/tabs/scripts/components/DynamicSSHKeyInjectionWizard.tsx
Moving from cloudDrive to noCloud will solve these issues:
https://issues.redhat.com/browse/CNV-28438
https://issues.redhat.com/browse/CNV-29802
https://issues.redhat.com/browse/CNV-28700
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/65eb2aa4-d9a2-4cf7-849a-ad4e39d686fc
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/52d94117-55b7-494c-8445-29246759cbf7
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/84245162-fa98-4478-8847-aaace5b653f3
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/d2c6896e-01c7-40f3-aae4-0c980511370e
> CNV-28438: cloudInitConfigDrive yaml contains cloudInitNoCloud content

- src/utils/components/ListPageFilter/AutocompleteInput.tsx
- src/utils/components/ListPageFilter/SearchFilter.tsx
Add focus action on `/` key press. Like in the SDK version.
Hide and show the label suggestions on blur and focus
https://github.com/kubevirt-ui/kubevirt-plugin/assets/29160323/8adba369-9052-4b1b-a177-eecd542e09d0
> CNV-32097: Add focus/blur action to the listpagefilter search input

- src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.scss
- src/utils/components/ExpandSectionWithSwitch/ExpandSectionWithSwitch.tsx
- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.scss
- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.tsx
This PR:
- Adds the ExpandSectionWithSwitch component, which will be used by the kernel same-page merging and auto-compute CPU limits features on the Settings page
- Adds the `isIndented` and `isDisabled` options to the `ExpandSection` component
- Adds the `isIndented` prop to all expandable sections on the Settings page
> Add ExpandSectionWithSwitch component

- src/utils/hooks/useFeatures/useFeatures.ts
When there is an error getting UI feature configmap, useFeature returns loading true while it should return loading false
> CNV-34341: fix usefeature loading

- src/utils/components/SSHSecretSection/SSHSecretSection.tsx
- src/utils/hooks/useActiveNamespace.ts
- src/utils/hooks/useKubevirtAlerts.ts
- src/utils/hooks/useLastNamespacePath.ts
- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/useMigrationChartsData.ts
- src/views/clusteroverview/MigrationsTab/hooks/useMigrationCardData.ts
- src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useMetricChartData.ts
- src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
- src/views/clusteroverview/OverviewTab/resources-inventory-card/hooks/useResourcesQuantities.ts
- src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
- src/views/clusteroverview/OverviewTab/vms-per-template-card/hooks/useVMsPerTemplateResources.ts
`useActiveNamespace` was moved from internal-sdk to the SDK. 
This produce a crash when our 4.13 plugin gets installed on 4.14 and above clusters
> Copy useActiveNamespace

- src/views/virtualmachines/actions/components/VMActionsIconBar/components/ActionIconButton.tsx
This PR adds the `data-test-id` attribute to the VM action icons for testing purposes.
Jira issue: https://issues.redhat.com/browse/CNV-34765
> CNV-34765: Add data-test-ids to VM action icons

- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
We had a bug with username containing @ or other special chars that cannot used as keys in obj.
Now we will try to use uuid if user has one, all should have one except kube:admin, and rest we will replace special chars with dashes.
> CNV-35122: Adjust user name in configmap to uuid

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
With authorized keys we have a bug on customize.
In additionalObjects we are adding the actual VM.
On create action, the wizard try to create the additionalObjects first (and here we have the vm), after try to create the vm and it gets the error. After that remove the additionalObjects and for this reason we don't create the vm.
> Fix additionalObjects with authorized ssh key

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
Fix the issue where quick create button was not showing up.
The issue: the variable `canQuickCreate` does not disable the button but it hide it. So i moved the `allRequiredParametersAreFulfilled` function in the hook to disabled the button if the template required parameters are not satisfied.
The every function was failing with templates that have at least one optional parameter so i splitted the every function with filter and every
> CNV-35416: fix disappearing quick-create button

- src/views/virtualmachines/list/components/VirtualMachineRow/virtual-machine-row-layout.scss
The table class changed from `pf-c-table`  to `pf-v5-c-table`  so we have to change also the scss here
**Before**
**After**
> Fix condition column width

- src/utils/components/ListPageFilter/ListPageFilter.tsx
- src/utils/components/ListPageFilter/hooks/useListPageFiltersMethods.ts
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
Clicking on `clear all filters` do not clear IP address filter 
Instead of use `startsWith` to filter IP addresses, use `includes` so `129.2` will get the ip `10.129.2.1` for example.
All vms will probably get the same prefix being in the same network
> Fix IP Address

- src/utils/hooks/useHyperConvergeConfiguration.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
It seems like there is an error in the docs that declares there is a configuration field under spec, but in the hco instance, there isn't.
also added an effect to the state, because if data is still loading state get wrong data
> CNV-35808: fix ksm config

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/hooks/useVolumeOwnedResource.tsx
Opening the detach modal for an ephemeral disk (`containerDisk`) triggers a loading error as the `groupVersionKind` in `useVolumeOwnedResource` is `undefined`.
Fix: Do not load anything if the `groupVersionKind` is `undefined`. There is no resource to show in the modal and delete after submit if the volume is emphemeral 
**Before**
**After**
> Fix detach emphemeral disk

- src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
The background color of the vertical subtab of the Configuration tab on the VM page stays white in dark mode.
Jira issue: https://issues.redhat.com/browse/CNV-36232
> CNV-36232: Vertical submenu of the VM Configuration tab is white in dark mode

- src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
- src/utils/components/PendingChanges/utils/helpers.ts
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/actions/actions.ts
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
This PR fixes a bug wherein a bridged hot-plug NIC is not added after the VM has been migrated.
The root cause of this bug is that I changed the API for adding/removing hot-plug NICs too early. This PR reverts back to the correct hot-plug API for 4.14.
This PR can't be applied to main first and then backported because the hot-plug API for 4.15 is different.
Jira ticket: https://issues.redhat.com/browse/CNV-35415
> CNV-35415: Fix hot plug NIC add/remove behavior

- src/utils/components/CloneVMModal/components/InstanceTypeConfiguration.tsx
- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/components/PendingChanges/utils/types.ts
- src/utils/resources/instancetype/helper.ts
- src/utils/resources/vm/hooks/useInstanceType.ts
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/LiveMigratePendingChanges.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/RestartPendingChanges.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
- src/views/virtualmachines/details/utils/utils.ts
Fixing 2 bugs with that:
1. vms created through IT do not show pending changes
2. adding hotplug network triggers also the pending changes on the 'default' network. If vms do not have networks, vmi will have one default network. But no pending change should be triggered in this case.  
**Before**
No pending changes
**After**
> Refactor pending changes with live mgiration

- src/utils/components/ListPageFilter/AutocompleteInput.tsx
- src/utils/components/ListPageFilter/constants.ts
- src/utils/components/ListPageFilter/hooks/useDocumentListener.ts
Label suggestions were not working so with this pr I fix this issue.
When the user clicks on one suggestion, the onBlur method is called and before firing the suggestion onClick, the suggestion element is removed from the dom.
Fixing it by copying the useDocumentListener method from the console
**Before**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/29160323/9565acfd-7ece-45e9-b9b1-7102820d92e5
**After**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/29160323/949b9158-947e-4cfe-b0ad-1728c5d29cf9
> CNV-35753: fix suggestion focus/blur logic

- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
Adding default value to favorites array, this help in case the configmap of user setting is old and missing this array for initial run.
> CNV-36436: Fiox favorites default value

- src/utils/components/DiskModal/DiskFormFields/AccessMode.tsx
- src/utils/components/DiskModal/DiskFormFields/EnablePreallocationCheckbox.tsx
- src/utils/components/DiskModal/DiskFormFields/StorageClassAndPreallocation.tsx
- src/utils/components/DiskModal/DiskFormFields/VolumeMode.tsx
- src/utils/components/DiskModal/DiskFormFields/storage-class-and-preallocation.scss
Disable volume and access mode if the apply storage profile is checked, as they don't have any meaning. If u check apply, change the volume and access according to the claim. change appearance by new design
Before:
After:
> CNV-36799: Disable volume and access mode when apply storage profile is checked

- src/views/catalog/utils/quantity.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-35271
Prevent changing disk size unit to "B" after selecting a PVC when using an existing volume in _Add volume_ modal (_InstanceTypes_ tab in _Catalog_).
**Before:**
Disk size unit suddenly changed to "B" when selecting PVC from the _PVC name_ dropdown:
**After:**
Correct disk size:
> CNV-35271: Prevent changing disk size unit to B after PVC selection

- src/utils/resources/vmi/hooks/useVirtualMachineInstanceMigration.ts
- src/utils/resources/vmim/constants.ts
Filter vmi migrations using the proper label
This pr fix also this bug here: https://issues.redhat.com/browse/CNV-34889
> CNV-36625: filter vmims by vmi name label

- src/utils/components/CPUMemory/CPUMemory.tsx
- src/utils/components/CloneVMModal/components/ConfigurationSummary.tsx
- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/HorizontalNavbar/utils/utils.ts
- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
- src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
- src/utils/resources/vm/utils/instanceTypes.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateInfoSection.tsx
- src/views/catalog/wizard/Wizard.tsx
- src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/utils/types.ts
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
- src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
- src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
- src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
- src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx
- src/views/virtualmachines/details/utils/types.ts
Fix instance type bios, presenting the correct value.
Instance type can have some fields with values that affect bios type when VM is created.
We cannot check all the fields and make assumptions. We need to use the expand-spec of instance type VM in order to compare to vmi and get right values of bios or anything else. This fix will send instanceTypeExpandedSpec to all tabs and can be used instead of VM when needed.
Also, I changed a bit of the CPU memory component while exploring the code; this component made a lot of network calls to instance type to get CPU and memory; now, it's not needed as instanceTypeExpandedType can deliver the same data.
After:
Before:
> CNV-35635: Fix instance type different bios

- src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
- src/views/templates/details/tabs/scripts/components/SysPrepItem/sysprep-utils.ts
- src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/utils/utils.ts
It seems like an old bug before the day that you could create a VM that won't start at the beginning.
The sysprep on the init run tab was missing the modal when clicking edit, and edit was hard coded disabled.
> CNV-35730: Fix windows sysprep on vm init run tab

- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/utils/disk/constants.ts
- src/utils/resources/vm/utils/disk/rowData.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/utils/helpers.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-34692
Prevent VM getting stuck in "Starting" status in case of detaching a disk that is in error (if PVC is not in "Bound" state, for example if you added wrong url when creating that disk) by disabling _Detach_ button for that specific disk in the VM's _Disks_ list.
**Before:**
Possible to detach the problematic disk leading to VM stuck in starting status:
**After:**
_Detach_ button disabled if the disk is problematic/if PVC is not in Bound state:
> CNV-34692: Prevent VM stuck in starting status after detaching disk

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/InstanceTypeDrilldownSelect.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/UsersInstanceTypeList/UsersInstanceTypeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/state/hooks/useClusterInstanceTypes.ts
- src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypesAndPreferences.ts
- src/views/catalog/CreateFromInstanceTypes/state/hooks/useUserInstanceTypes.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/instancetypes/list/ClusterInstancetypeList.tsx
This PR fixes a bug that prevents user-created Instancetypes from being displayed in the User Provided tab on the Instancetypes page.
Jira ticket: https://issues.redhat.com/browse/CNV-32929
> CNV-32929: Display user-created Instancetypes in the User Provided tab

- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
If a NIC is deleted when the VM is stopped it will not be removed until the VM is started. This PR disables the NIC to avoid confusing the user.
To Do: Determine if there are any other items that don't change until the VM is started.
Jira issue: https://issues.redhat.com/browse/CNV-35782
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/1344aa39-b2ba-480f-891e-faaa60b43e72
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/f9f6a886-1d66-47c8-8ff4-07b8d423fd9e
> CNV-35782: Disable deleted NIC when VM is stopped

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/utils.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-36169
Display correct disk size when creating a new VM from template and choosing "PVC (clone PVC)" as a disk source in the drawer.
**Before**:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/509b9e87-03ab-42eb-8b0b-b96f64af962a
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/d867ce12-8dac-48ef-9205-b14a804ad463
> CNV-36169: Display correct disk size in Catalog drawer for cloning PVC

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
`hasVMValidDVSources` returns `undefined` when the VM does not have `dataVolumeTemplates` array. Instead, should return true if there should be no dataVolumeTemplates
> CNV-37075: Fix "Quick create VirtualMachine" is disabled 

- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/ProjectSelectorModal.tsx
This PR fixes a bug wherein the CPU limits project selector modal indicates that all projects are selected if no labels have been entered.
It also adds space between the edit icon and "Project selector" label in the "Auto-compute CPU limits" setting in the Resource management section.
Jira: https://issues.redhat.com/browse/CNV-37265
> CNV-37265: Fix default matching state for autocompute CPU limits

- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/ProjectSelectorModal.tsx
This PR fixes a bug wherein the Auto-compute CPU labels project selector modal can't be saved if no labels are entered.
Jira: https://issues.redhat.com/browse/CNV-37266
> CNV-37266: Allow saving Autocompute CPU limits modal with no labels

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/DiskListTitle/DiskListTitle.tsx
Removing disk title help icon
After:
Before:
> CNV-36883: removing disk help icon

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
This PR fixes a bug wherein the pod network is deleted from an Instancetype VM when another network is added.
Jira: https://issues.redhat.com/browse/CNV-36438
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/c6fb9c74-ecf9-4ca6-8548-aef07658fd71
> CNV-36438: Prevent deletion of pod network on Instancetype VM

- src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
- src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-37111
Adjust _Bootable volumes_ list columns sizes to look better, more balanced, prevent _Name_ column to take too much space, display _Namespace_ column as expected (available only for _All Projects_ project/namespace).
_Note:_
This PR/commit is just a partial fix for the provided jira bug. We still need to figure out how to make saving the settings from Manage columns for the specific user work as expected.
**Before:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/9227b7e1-816d-46c8-91e9-b8d8a4f5f953
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/9da39a6a-b381-4365-9767-fcd5ebc99895
> CNV-37111: Adjust Bootable volumes list columns

- locales/en/plugin__kubevirt-plugin.json
- src/utils/hooks/useRHELAutomaticSubscription/useRHELAutomaticSubscription.ts
- src/utils/hooks/useRHELAutomaticSubscription/utils/types.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionForm/AutomaticSubscriptionForm.tsx
On a fresh cluster, the switch to allow RHEL auto updates was on by default, even if the key and id are missing, that caused the mechanism to not get the default unless you toggle it off and back on.
Allowing to set the switch on just if both id and key values are not empty after applying them is solving the issue
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/47c00d8a-201a-4959-bc8d-f92bd2d76fc7
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/380be26d-48ae-4b9e-9b24-cfbf6f875bfb
> CNV-37480: "auto updates for RHEL VirtualMachines" is enabled by default but does not work

- src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
blank page on DeleteModalLoading. Not happen every time.
> Crash on delete moal loading

- src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
- src/utils/components/SSHAccess/constants.ts
- src/utils/hooks/useMetalLBOperatorInstalled/constants.ts
- src/utils/hooks/useMetalLBOperatorInstalled/useMetalLBOperatorInstalled.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
This bug is introducing a few problematic behaviors:
1. Under Overview > Settings > Cluster > General settings > SSH configurations we have a switch to toggle the option of SSH over LB inside the VM's Configuration > SSH tab. If the metalLB operator is installed, the option inside the VM is always selectable no matter what state the switch has.
2. If the metalLB operator was installed in the cluster, then uninstalled, we still show as the operator is installed (the ssh over LB inside the VM is still selectable
The solution includes a tighter check if metalLB is installed, and if so we disable the switch as on.
###Before:
MetalLB is installed:
MetalLB is NOT installed:
switch is on:
switch is off:
> CNV-37382: Inconsistency between the cluster settings and VM settings for SSH over LoadBalancer

- src/utils/components/ListPageFilter/ListPageFilter.tsx
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
When `filter.items` is empty for some filters like 'Node' as maybe all vms are stopped, the filters appears in the dropdown.
**Before**
**After**
> Fix search filters appearing in the dropdown

- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-37383
Move "Not available" text (or the name of the existing SSH key if present) above the message "Dynamic SSH key injection is not enabled in this virtual machine. Learn more" in the VM's Configuration SSH tab to make the information more clear to the user. Make this change according to the UX decisions.
**Before:**
**After:**
> CNV-37383: Move "Not available" above "Dynamic SSH key injection .." msg

- src/utils/components/SSHSecretSection/components/SecretDropdown/SecretDropdown.tsx
When configuring an existing SSH secret for the namespace in which that secret resides in the "Manage SSH keys" section the UI displays the secret name with a randomly generated suffix. In actuality, that secret wasn't created and doesn't exist. This can be demonstrated by navigating away from that screen and returning to it. Upon doing so "Not configured" will be displayed for that namespace instead of the generated secret name.
This PR makes it so that the existing secret is used instead of generating a new name.
Jira: https://issues.redhat.com/browse/CNV-37629
> CNV-37629: Keep name when configuring existing SSH key in same namespace

- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDataVolumeConvertedVolumeNames.ts
- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
We should not count volumes that use PVC attached with `persistentVolumeClaim`  in the DeleteVM modal.
Those volumes are attached to the VM as `existing PVCs` so they do not have the same VM lifecycle. 
Maybe in the next version we can consider a checkbox list to let the user decide which disks wants to delete. 
VM with one volume that use `persistVolumeClaim`
**Before**
**After**
> CNV-23927: Do not count persistentVolumeClaim volumes in DeleteVMModal

- src/utils/components/SSHAccess/components/ConsoleOverVirtctl.scss
- src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
- src/utils/components/SSHAccess/components/VirtctlSSHCommandClipboardCopy.tsx
- src/utils/components/SSHAccess/constants.ts
This PR adds the example command to the info icon popover and beneath the "SSH secret not configured" text. It removes the example command when the SSH secret is configured. 
Jira: https://issues.redhat.com/browse/CNV-37501
> CNV-37501: Move SSH using virtctl helper text to info popover

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
The VM row would show IP and node only if the VM is in "Running" status, we should also show ip and node name even if VM is migrating (still running) or if the VM is paused.
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/3c0ab398-2f5b-4970-bec3-75a5929b0b06
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/b76eab52-31d6-41ca-97f0-f76ad2d8d9bd
> CNV-37373: VM IP address disappears from UI when migrating VM

- src/utils/flags/useEnableKubevirtMenuFlags.ts
- src/views/instancetypes/list/InstanceTypePage.tsx
- src/views/preferences/list/PreferencePage.tsx
Bring back preferences and instance type menu items for regular users
After:
> CNV-37412: Bring back preferences and instance type menu items for regular users

- src/utils/resources/instancetype/helper.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
Fixing instancetype link in VM details tab
there are 2 kinds of instance type , cluster and user.
user type need to add a namespace to it.
> CNV-37788: Fix instancetype link on vm details tab

- package.json
- yarn.lock
Upgrade Kubernetes API from 1.27 to 1.29
Upgrade KubeVirt API from 1.0 to 1.1
Set CDI API as v1.57.0 instead of main
> Kubevirt api upgrade to 1.2.2

- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
The crash happens when the user create a VM using a template.
The `instanceTypeVM` is `undefined` is this case and we need to use `vm`
> CNV-37915: fix crash on bootmode modal

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesEditNetworkInterfaceModal.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx
Changing from using k8sUpdate to K8sPatch as it can cause the promise to fail if the VM has changed
> CNV-35729: Improve modal save while there are changes occurred in the back-end - part 2 network

- src/views/datasources/dataimportcron/details/DataImportCronDetailsPage.tsx
- src/views/datasources/details/DataSourceDetailsPage.tsx
- src/views/migrationpolicies/details/tabs/details/MigrationPolicyDetailsPage.tsx
- src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
- src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
- src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
- src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-37818
Set the background for Patternfly `PageSection` component we use back to white due to the change of the default setting of the component from white to grey. Adjust the component by adding `variant={PageSectionVariants.light}` to achieve the expected look in the following pages:
- Template _Details_ tab
- Template _Scheduling_ tab
- Template _Scripts_ tab
- Template _Parameters_ tab
- _DataSource details_ (from _Bootable volumes_ list), incl. _Conditions_ part
- _DataImportCron details_ (from _DataSource details_ page)
- _MigrationPolicy details_
**Before:**
**After:**
> CNV-37818: Set white background for PageSection component where needed

- package.json
**Fixes:**
https://issues.redhat.com/browse/CNV-37819
~~The aim of this PR is to test if changes to new i18n json file after running yarn i18n will be added to the commit so the commit or PR could pass once on GitHub, and one won't need to add the json file to the commit manually.~~
Adjust _package.json_  file by adding `git add locales/en/plugin__kubevirt-plugin.json` for `lint-staged` to achieve including the related i18n json file with its changes in the commit so the related tests pass here on GH successfully.
_Q & A:_
What if no any i18n changes present after `yarn i18n` when creating commit? -> Nothing happens, including _locales/en/plugin__kubevirt-plugin.json_ file changes in the commit is ignored.
More on `lint-staged`:
https://www.npmjs.com/package/lint-staged
> CNV-37819: Adjust package.json's lint-staged to include i18n json file in commit

- src/views/templates/details/tabs/disks/TemplateDisksPage.scss
Fix broken/not applied css `margin` prop for Template _Disks_ page title so the title looks the same as in the other Template tabs. This got probably broken during some refactoring or other related changes of the page/`DiskListTitle` component.
**Before:**
Title of the page too close to the upper border of the page:
**After:**
More space around the title, same as in other VM Template's tabs/pages:
> Fix Template's Disks title margin prop

- src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
The issue is related to the `onEditChange={setDisableVmCreate}` 
This callback should disable the `Create` button in the wizard but this the trigger a re-loading.
I would remove that behaviour at this point as we do not do that in other tabs.
the sidebar editor triggers a VM update at the beginning and everytime we change something in the editor. 
Instead of using `onChange` we should use `onResourceUpdate`. It will show the Save button on the bottom like in all the other tabs. Clicking on the save button will trigger the reloading of the EnvironmentForm.
> Add save button to the environment sidebar editor

- src/views/checkups/network/details/CheckupsNetworkDetailsPage.tsx
- src/views/checkups/storage/details/CheckupsStorageDetailsPage.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsTab.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/InitialRunTab.tsx
- src/views/virtualmachines/details/tabs/configuration/metadata/MetadataTab.tsx
- src/views/virtualmachines/details/tabs/configuration/network/NetworkTab.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/SchedulingTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/StorageTab.tsx
- src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx
- src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx
- src/views/virtualmachinesinstance/details/tabs/scheduling/VirtualMachinesInstancePageSchedulingTab.tsx
Fixes https://issues.redhat.com/browse/CNV-37818
This is a followup PR of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1777
Set the background for Patternfly `PageSection` component (all occurrences) we use back to white due to the change of the default setting of the component from white to grey. Adjust the component by adding `variant={PageSectionVariants.light}` to achieve the expected look in the various pages.
**Before:**
Example: VMI Details tab and the grey background of the page:
**After:**
Example: VMI Details tab and the expected white background of the page:
> CNV-37818: Set white background to all PageSection component occurrences

- src/utils/components/ListPageFilter/SearchFilter.tsx
When the user press `/` we make focus on the search input. Like in other pages.
Bug: when the input is already in focus and the user type `/`, the handler prevent the typing.
Fix: do not preventDefault when the input is in focus
**Demo**
> CNV-38404: search with / does not work

- .husky/pre-commit
- package.json
**Fixes:**
https://issues.redhat.com/browse/CNV-37819
This is a followup PR of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1787
Adjust _package.json_ and Husky _pre-commit_ files to achieve properly including _locales/en/plugin__kubevirt-plugin.json_ file in the commit, and hence prevent failing i18n tests for an opened PR on GitHub.
Add `git add locales/en/plugin__kubevirt-plugin.json` to _pre-commit_, after yarn i18n is ran.
_Q & A:_
What if no any i18n changes present after yarn i18n when creating commit? -> Nothing happens, including locales/en/plugin__kubevirt-plugin.json file changes in the commit is ignored.
_More on lint-staged and Husky:_
https://www.npmjs.com/package/lint-staged
https://typicode.github.io/husky/how-to.html
> CNV-37819: Adjust package.json, pre-commit to prevent i18n tests failing

- src/utils/components/HardwareDevices/HardwareDevicesPage.tsx
- src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
- src/utils/constants/constants.ts
- src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/constants.ts
- src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/index.ts
Regular users cannot access Hyperconverge configuration. 
in order to fix this bug we have to fetch the new Kubevirt Hyperconverge configuration made exactly for that
> CNV-34180: fetch user accessible hyperconverge config resource

- src/utils/resources/vmi/utils/cloud-init.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-38450
Prevent the VM Console tab crashing if cloudInitNoCloud user's password is a number.
**Before:**
**After:**
> CNV-38450: Display VM Console tab as expected

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/AuthorizedSSHKey.tsx
when `sshDetails` is `null`, the catalog drawer crash.
**Before**
**After**
> Fix crash when sshDetails is null

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
This PR fixes the alert message shown when a NIC is deleted as well as the logic dictating when the alert is shown. The alert is to be shown only when a hot-plug NIC is being deleted while the VM is running.
Jira: https://issues.redhat.com/browse/CNV-38360
ault NIC
t-plug NIC
> CNV-38360: Fix NIC hot-unplug alert message

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/InstanceTypeDrilldownSelect.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/UserInstanceTypeMenu/UserInstanceTypeMenu.tsx
A side effect from https://github.com/kubevirt-ui/kubevirt-plugin/pull/1803 caused user-created VM InstanceTypes to be displayed in the Add boot volume modal, but the resource badge used is for `VirtualMachineClusterInstanceTypes`. This PR corrects that behavior and directly fixes the issue created by the side effect to ensure a regression doesn't happen in the future.
Jira: https://issues.redhat.com/browse/CNV-32929
> CNV-32929: Correct resource badge for user-created VM InstanceTypes in Add boot volume modal

- i18n-scripts/set-english-defaults.js
Remove double {{count}} in translations
Create singular and plural depends on `_one` and `_other` translations. Those translations can be edited anyways by us. 
> remove double {{count}}

- src/utils/components/Charts/utils/queries.ts
- src/views/clusteroverview/TopConsumersTab/utils/queries.ts
The `kubevirt_vmi_cpu_usage_seconds` metric was updated to `kubevirt_vmi_cpu_usage_seconds_total` in 4.14. This PR updates the UI to match.
jira: https://issues.redhat.com//browse/CNV-38819
> CNV-38819: Update CPU usage metric name

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/CustomizeSource/Sources/UploadSource.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
File was needed to be set in `onFileInputChange` property and when uploading a file from create VM flow, we upload the disk before the proccessed template's VM is getting populated with a namespace.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/07acf543-ea54-4422-a01d-58a7d0576d5e
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/2266f98c-c24c-4de5-b328-289ded248050
> CNV-38842: Create VM from upload file does not work

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/utils/constants.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-38883
Fix the broken _Read more_ link to the documentation about activation key for automatic subscription of RHEL VirtualMachines. Use the newer working link:
https://access.redhat.com/documentation/en-us/red_hat_insights/1-latest/html/remote_host_configuration_and_management/activation-keys_intro-rhc
Clicking on Read more:
**Before:**
**After:**
> CNV-38883: Update the link to Activation key doc

- src/utils/resources/vmi/utils/pod.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineLogViewer/VirtualMachineLogViewer.tsx
The initial setting of the serial console wasn't loaded into the features config map.
More checks were added to tell if the VM needs to restart after enabling the setting in cluster scope.
Before:
as can be seen in the photos in the bug report https://issues.redhat.com/browse/CNV-38577
After:
> CNV-38577: Fix initial load of serial console

- src/utils/components/FilterSelect/InlineFilterSelect.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/components/SSHAuthKeyRow/SSHAuthKeyRow.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthProjects.ts
Once a project is selected, it couldn't be selected again as each project can have only one secret.
We should check if a project has a secret name attached to it, before eliminating him from the select list.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/6cc41971-22a8-4194-8a3d-a5f907c6e0c9
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/74919f1e-dd87-45a0-98ec-5bddc3e72fcd
> Show selected project in Manage SSH keys section

- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
When creating a VM we point to the original resource and not the cloned one in the ControllerRevision.
There's also a mix in Timezone and Hostname.
After:
> CNV-39030: point to controller revision IT and pref

- src/utils/components/PendingChanges/utils/helpers.ts
VirtualMachine API doesn't require disks to be populated and can automatically populate based on the volumes provided.
Hence when removing the disks section, it wouldn't change the boot order and we can remove the pending changes alert.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/caa4cb28-8b38-49a6-9c1f-6bd454fa49c0
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/99dfb76b-5da2-4773-b07a-11a9bc92ce61
> CNV-33541: Removing spec.template.spec.domain.devices.disks from VM definition leads to "Pending Changes" message

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Removing `spec.template.spec.domain.devices`, `spec.dataVolumeTemplates.spec.storage.resources` , and `spec.template.spec.networks` sections as they are auto populated by the BE.
After: (fedora YAML)
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
name: fedora-ivory-donkey-88
namespace: default
spec:
dataVolumeTemplates:
- metadata:
name: fedora-ivory-donkey-88-volume
spec:
sourceRef:
kind: DataSource
name: fedora
namespace: openshift-virtualization-os-images
storage:
resources: {}
storageClassName: hostpath-csi-basic
instancetype:
kind: VirtualMachineClusterInstancetype
name: u1.medium
preference:
name: fedora
running: true
template:
metadata:
labels:
app.kubernetes.io/name: headless
spec:
domain:
devices: {}
subdomain: headless
volumes:
- dataVolume:
name: …
```
> CNV-27329: Cover more flows of disk based VM creation

- src/utils/components/SSHAccess/components/ConsoleOverVirtctl.scss
- src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
To apply specific min-width in a popover we need to enforce `!important` due to this change: https://github.com/openshift/console/blob/00e15520c97e200b53cd1850b5f534063292b7dc/frontend/public/style/_overrides.scss#L404 
Before:
After:
> CNV-38295: fix PF5 regression

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Remove un-needed kind when selecting cluster instance type
Before:
After:
> CNV-39028: UI generated VirtualMachine provides an instance type kind when one isn't required

- src/utils/components/FormPFSelect/FormPFSelect.tsx
- src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
- src/utils/components/ListPageFilter/ListPageFilter.tsx
- src/utils/components/ListPageFilter/RowFilters.tsx
Fixing some minor glitches from PF5 upgrade
Before:
After:
> Fix PF5 glitches - part 2

- locales/en/plugin__kubevirt-plugin.json
- src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-39418
Change _VirtualMachine labels_ to _VirtualMachineInstance labels_ in _MigrationPolicies details_ page to reflect exactly which labels are shown in the page.
**Before:**
_VirtualMachine labels_  are shown in the page, which can be confusing to the user:
**After:**
_VirtualMachineInstance labels_ are shown:
> CNV-39418: Use "VirtualMachineInstance labels" for MigrationPolicies

- console-extensions.json
- locales/en/plugin__kubevirt-plugin.json
- plugin-metadata.ts
- src/utils/hooks/useMigrationPolicies.ts
- src/views/clusteroverview/MigrationsTab/hooks/useMigrationCardData.ts
- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesCreateButton/MigrationPoliciesCreateButton.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.scss
- src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-38902
Display the page also for the users without privileges to get a bit more familiar with the page, add popover for disabled _Create MigrationPolicy_ button to inform the user what to do to be able to see and create MigrationPolicies.
**Before:**
No MigrationPolicies menu item, nor the paqe displayed at all:
**After?:**
>  CNV-38902: Display MigrationPolicies page for nonprivileged user

- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Allowing VirtualMachinePreference (namespace scoped) in the preference select dropdown in Add volume modal.
Before: 
After:
> CNV-39425: Not able to select user prefereces in add volume modal

- locales/en/plugin__kubevirt-plugin.json
- src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
- src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-39418
Change _VirtualMachine labels_ to _VirtualMachineInstance labels_ in _MigrationPolicies_ list page to reflect exactly which labels are shown in the page. Same for _Create MigrationPolicy_ form.
**Before:**
_Create MigrationPolicy_ form and incorrect _VirtualMachine labels_ used:
_MigrationPolicies_ list page and incorrect _VirtualMachine labels_ used:
**After:**
_Create MigrationPolicy_ form and _VirtualMachineInstance labels_ used:
_MigrationPolicies_ list page and _VirtualMachineInstance labels_ used:
> CNV-39418: Use VirtualMachineInstance labels at MigrationPolicies pages

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/SettingsTab/PreviewFeaturesTab/hooks/usePreviewFeaturesData.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-39659
Change "limit" to use plural in _Enable CPU limit_ string in the _Overview_ > _Settings_ page - _Preview features_ section to reflect the related documentation: https://kubevirt.io/user-guide/virtual_machines/resources_requests_and_limits/
**Before:**
_Enable CPU limit_ used in the page:
**After:**
_Enable CPU limits_ used in the page:
> CNV-39659: Change "Enable CPU limit" to "limits" in Overview settings

- src/views/bootablevolumes/list/BootableVolumesList.tsx
ns param returns undefined at all time which causes a cluster-scope request and not a namespace-scope request
Before: (volumes from all namespaces)
After: (volumes only from active namespace)
> [release-4.15] CNV-39686: Users cannot use their own images from the UI

- src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabConditions.tsx
- src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabDataVolumeStatus.tsx
- src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
- src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabFilesystem/VirtualMachinesOverviewTabFilesystemTitle.tsx
- src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableTitle.tsx
Fixes:
https://issues.redhat.com/browse/CNV-40247
Make the icons smaller to look better, also delete non-existent `title-help-text-icon` class from `HelpTextIcon` components in more places of the codebase.
**Before:**
"?" icons too big in VM _Diagnostics_ tab:
**After:**
"?" icons smaller, nicer:
> CNV-40247: Make VM Diagnostics tab's help icons smaller

- src/views/cdi-upload-provider/upload-pvc-form/UploadPVC.tsx
- src/views/cdi-upload-provider/upload-pvc-form/UploadPVCForm.tsx
Fixing use of FileUpload props to allow to click on `Browse` button
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/9c4c1082-bf75-4efb-b873-202fe7b0159e
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/b3411160-a71b-4d10-a8fb-9f7b103c815c
> CNV-37607: "Upload data" dialog does not work in PVC -> "With Data upload form"

- src/utils/components/DiskModal/DiskFormFields/AccessMode.tsx
- src/utils/components/DiskModal/DiskFormFields/StorageClassAndPreallocation.tsx
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/521883a4-0e2d-4216-850c-2a37ef079137
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/76ec063b-e677-446a-9a43-b7548c008bcc
> CNV-40242: UI goes blank when changing the storage class field on add disk

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/resources/vm/utils/network/constants.ts
- src/utils/resources/vm/utils/network/selectors.ts
we try to bind sr-iov to the VM interface when added but should be sriov, which causing to not add the sriov interface properly
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/e68be0b1-a08d-4365-9aae-472f2cca8831
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/41920848-833b-4924-86fb-5dbf2b136558
> CNV-38061: Missing SR-IOV binding to VM spec

- src/utils/components/CloneVMModal/CloneVMModal.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-40200
Display _Clone_ submit button text in _Clone VirtualMachine_ modal window instead of _Create_.
Keep displaying _Create_ submit button text for cloning VM snapshots.
**Before:**
_Create_ button text in the modal:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/e1a88120-22d0-42da-9b18-b07ffef36f23
**After:**
_Clone_ button text:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/3ed07577-f2d2-4047-8ac6-7b52c5657889
> CNV-40200: Use "Clone" submit button for VM cloning instead of "Create"

- src/views/clusteroverview/OverviewTab/getting-started-card/utils/getting-started-grid/GettingStartedGrid.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-39531
Display _Getting started resources_ expandable section in the _Virtualization Overview_ **expanded by default** - same as in the console.
**Before:**
Getting started card not expanded when entering _Virtualization Overview_ for the 1st time:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/c3f88608-a495-46e2-bc10-8340ba8a5f47
**After:**
Getting started card expanded by default:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/87e3ab92-e29b-4ce7-a3cd-13fbcf0447ac
> CNV-39531: Make Getting started card expandable

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/CloneVMModal/CloneVMModal.tsx
- src/utils/components/CloneVMModal/components/StartClonedVMCheckbox/StartClonedVMCheckbox.scss
- src/utils/components/CloneVMModal/components/StartClonedVMCheckbox/StartClonedVMCheckbox.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-40341
Make small improvements in the modal according to the design doc:
- remove unnecessary field name for checkbox - _Start cloned VM_
- remove "clone" substring from the new generated VM name.
**Before:**
**After:**
> CNV-40341: Improve "Create VirtualMachine from snapshot" modal

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/utils.ts
The common instance types are missing since deployment has changed, changing to a common label both deployments ways have.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/c97c1e09-b125-4109-b724-df6f65470eb8
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/1e5cb10a-f69d-40f0-a17f-4d60e65b7c15
> CNV-40457: Instancetype list is empty on catalog -> instanceTypes page

- src/utils/components/FilterSelect/InlineFilterSelect.tsx
When the InlineFilter component starts with an empty option list and then it populates based on other value, the list fails to initialize properly. 
Also when searching in the search input and selecting an option, re-opening the same dropdown is still fixed to the search options even when the search input is cleared.
Before:
After:
> CNV-40196: PVC is not found in "Bootable volumes" -> Add volume modal

- src/views/migrationpolicies/list/MigrationPoliciesList.tsx
- src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
**This is another PR belonging to the epic:**
https://issues.redhat.com/browse/CNV-40059
Display _MigrationPolicies_ list correctly after getting zero results from the list filtering. Do not display empty state page in this scenario.
**Before:**
Empty state displayed even when there are some MigrationPolicies, but just zero results after filtering:
**After:**
> CNV-40059: Update MigrationPolicies list for 0 results after filtering

- src/views/checkups/network/list/CheckupsNetworkList.tsx
- src/views/checkups/storage/list/CheckupsStorageList.tsx
**This is another PR belonging to the epic:**
https://issues.redhat.com/browse/CNV-40059
Display Network latency and storage checkups lists correctly after getting zero results from the list filtering. Update the message that is displayed in this scenario by adding the resource name to it. ~~Also display missing pagination.~~
**Before:**
Network latency checkups list:
Storage checkups list:
**After:**
Network latency checkups list:
Storage checkups list:
> CNV-40059: Update Checkups lists for 0 results after filtering

- locales/en/plugin__kubevirt-plugin.json
- src/utils/resources/instancetype/helper.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/InstanceTypeDescription.tsx
Preference link leads to 404 page for a second (missing namespace)
Instance type is not loading on create VM from snapshot.
Adding explanatory text for why linking ControllerReviosion clones to IT and Pref
After:
> CNV-39030: preference link leads 404 blink page

- src/utils/components/SSHAccess/components/VirtctlSSHCommandClipboardCopy.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-41210
Remove unnecessary example text for _SSH access_ section, already displayed in the tooltip next to _SSH using virtctl_.
**Before**:
Example command displayed twice:
**After:**
Example displayed only once, as part of the tooltip:
> CNV-41210: Display 'virtctl ssh' example only once in VM SSH settings

- src/utils/components/DynamicSSHKeyInjection/constants/constants.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-41139
Change Public SSH key's _Learn more_ link in the VM _Configuration_ page to point ad the correct downstream doc instead of upstream one:
https://docs.openshift.com/container-platform/4.15/virt/virtual_machines/virt-accessing-vm-ssh.html
Clicking on _Learn more_ link leading to...
**Before:**
... upstream doc:
**After:**
... downstream doc:
> CNV-41139: Change SSH key doc link to point at downstream doc

- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
On DataSource with volume snapshot as source, just like PVC, save the volume snapshot in the store to show the size in the details.
> CNV-41386: fix volume snapshot storage size

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
- src/utils/components/SysprepModal/SelectSysprep.tsx
- src/utils/components/SysprepModal/Sysprep.tsx
- src/utils/components/SysprepModal/SysprepInfo.tsx
- src/utils/components/SysprepModal/hooks/useConfigMaps.ts
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SimplifiedSysprepDescription.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SysprepDescriptionItem.tsx
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
**Epic:**
https://issues.redhat.com/browse/CNV-35740
_Design doc:_
https://docs.google.com/document/d/1xwev8T5mR0lCp0oqMefa-etfgKayKrb7j2fEOxWYcNE/edit
_Useful resources:_
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#sysprep-examples
Adjust the third section of the form when creating VMs from InstanceTypes depending on the OS type that is being created: Linux or Windows (according to the InstanceType preference selection). Add _Sysprep_ option for Windows VMs instead of SSH data to the section.
**Before:**
When choosing bootable volume with Windows OS, SSH data section still present:
**After:**
Adding new sysprep configuration:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/cd329db4-2b89-4a38-99df-489bfe09c53c
Attaching the existing sysprep: …
> CNV-35740: Add Sysprep option for Windows VMs when creating from InstanceTypes

- src/utils/components/SysprepModal/hooks/useConfigMaps.ts
- src/utils/components/SysprepModal/sysprep-utils.ts
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
- src/views/templates/details/tabs/scripts/components/SysPrepItem/sysprep-utils.ts
- src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
**Epic:**
https://issues.redhat.com/browse/CNV-35740
_Related PR:_
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1899
Add some small code adjustments for the freshly added feature - adding sysprep option for Windows VMs when creating from InstanceTypes.
> CNV-35740: Add Sysprep option for Windows VMs adjustments

- src/utils/components/DynamicSSHKeyInjection/DynamicSSHKeyInjection.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DynamicSSHKeyInjectionInstanceType.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-41206
Make the _Dynamic SSH key injection_ field not checked when creating VMs from InstanceTypes and changing volume to boot from to other than RHEL 9 one. Hence create the VM without dynamic SSH key injection as expected.
**Before:**
_Dynamic SSH key injection_ disabled after choosing RHEL 8 volume, but still checked:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/bfc471ae-35f7-4731-ada8-a46ae516a6cd
**After:**
_Dynamic SSH key injection_ disabled after choosing RHEL 8 volume, and also not checked - as expected:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/e73c1ebb-4963-446f-9d83-5ca3079d0349
> CNV-41206: Uncheck Dynamic SSH key injection if not supported

- src/utils/components/CloneVMModal/components/InstanceTypeConfiguration.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-41199
Remove the unnecessary resource link from InstanceType's name displayed in _Create VirtualMachine from snapshot_ modal.
**Before:**
Possible to click on the resource's name and redirect to its details page:
**After:**
> CNV-41199: Remove InstanceType link from Create VM from snapshot modal

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/utils/getEditDiskStates.ts
backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1914
on file `src/utils/components/DiskModal/utils/editDiskModalHelpers.ts` 
there was a bug after editing disk. To don't allow disk source editing (as probably PVC already created) the disk source in the edit modal is `Other` but on the way of creating the new volume with new data user input, the function create a volume with not source.
on `src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/utils/getEditDiskStates.ts`
in case of containerDisk type of volume, the modal was not showing the container disk image URL.
> [release-4.15] CNV-41495: Edit disk minimal info

- src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
In the instancetype there is no `disks` property so it was creating an empty volume array before adding the new volume.
> CNV-41402: Edit environment instancetype

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
On instancetype VM there is no need to specify the disks, networks and interfaces arrays  . See on [main](https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/src/views/catalog/CreateFromInstanceTypes/utils/utils.ts)
> [release-4.15] CNV-41494: Fix fixed virtio bus on instancetype

- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-40445
Display OpenshiftVirtualization Degraded Alerting page correctly, when clicking on _Warning_ in _Overview > Status_ card's related modal.
**Before:**
Clicking on _Warning_ leads to an empty page:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/2f9d0a45-9916-4d37-ad66-062e4802c2a7
**After:**
The related page displays correctly with all the relevant alerts:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/4c575079-86b7-484a-99d8-b919a7418e6b
> CNV-40445: Display OpenshiftVirtualization Degraded warning alerts

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
When selecting a bootable volume in instancetype VM creation, the list pagination gets on the first page.
This because we are using the unsorted list to calculate in which page we should be.
Why we do that? Because user can select the bootablevolume from a modal clicking on 'Show all' bootable volume. And clicking on 'select' should change the list page into the current selection page.
So we need a sorted array for identify the right page in which the selection is and a sortedPaginated array to show just the paginated volumes that we want in the list
Another fix:
TabModal expect a submit method that return a promise. So just return a promise.resolve instead of changing the type.
Just changing the type result into an infinite button loading in the modal .
> CNV-39727: fix pagination on bootablevolume selection

- src/utils/components/BootOrderModal/BootOrderModal.tsx
- src/utils/store/customizeInstanceType.ts
- src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeInitialRunTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeMetadataTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeNetworkTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeSSHTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeSchedulingTab.tsx
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeStorageTab.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskList.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Fix the flow of customize IT
Edit disk
Edit nic
Cancel redirect
Adding SSH
Boot managment
> CNV-41522: Fix customize IT

- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/utils/utils.ts
This PR fixes a bug where the labels selected in the Auto-compute CPU Limits modal aren't deleted when the feature is disabled.
Jira: https://issues.redhat.com/browse/CNV-41385
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/341c3aa5-3f40-4c8c-8a43-575f2db48094
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/23b2083f-f09e-46f8-a9ef-09bcff30a55a
> CNV-41385: Remove labels when auto-compute CPU limits is disabled

- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/utils/utils.ts
**Fixes:**
https://issues.redhat.com/browse/CNV-40445
Prevent unnecessary reloading whole page (incl. the whole left menu) when displaying _Openshift Virtualization Degraded_ warning alerts page, displayed after clicking on _Warning_ in the _Overview > Status_ card's related modal. Fix the not quite correct url of the page by adding missing "/" to the beginning of the url.
**Before:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/2a1acb21-403e-4eb7-b9e1-0ceba9de49bb
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/03acd4f6-eac0-412c-9d89-7bc4db2d3b45
> CNV-40445: Prevent reloading page when clicking on Degraded alerts

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/SSHAccess/components/SSHServiceSelect.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-39558
Add tooltip to provide more info to the user in case when "SSH over NodePort" service is disabled, in VM's SSH settings.
The final text: _NodePort service is disabled. Ask your cluster admin to enable it in cluster settings._
**Before:**
**After:**
> CNV-39558: Add tooltip for disabled SSH over NodePort option

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/StorageSection/cd.ts
If the cdrom is edited, it's already in the disks array so in that case its bootOder gets modified. 
Check the disk name to determine which bootOrder to give.
> CNV-41604: fix cdrom bootOrder

- src/utils/utils/utils.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
disks in that array have names under `diskName` property, not `name`
> CNV-41600: Storage utilization fix

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
If there is no permission for the user to create a VM, the button is currently disabled. Add a tooltip to the button.
> CNV-39682: Add tooltip cant create vm

- src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
The UI assumes that the subscription that holds the version metadata has a unique name.
Since the name of the subscription CR is arbitrary, we now check if the subscription is from the package of `kubevirt-hyperconverged` or in some community upstream cases the package named `community-kubevirt-hyperconverged`.
Before:
After:
> CNV-39940: UI does not show installed version

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/GracePeriodInput/GracePeriodInput.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteOwnedResourcesMessage.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteVolumeCheckbox.tsx
- src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts
Show a checkbox list for each volume that we can delete.
This modal removes the VM owner reference to all volumes and removes the dataVolumes from the dataVolumeTemplates array from the VM. 
Nit: fix the grace period question mark space
> CNV-41205: Add checkboxes for each disk to delete

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
tabsData will always be undefined as it gets defined only on customize VM flow.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/8657a2f0-a7c3-43e4-a50f-979344a18be1
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/22c744e5-2ef5-4e3c-b606-beaacf7302fc
> CNV-42015: SSH key is cleared when creating VM from template

- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListNamespaceSelect/BootableVolumeListNamespaceSelect.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListPagination/BootableVolumeListPagination.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
Allow changing the namespace in the volumes list under Catalog > Instance type so a user can select a volume from a different namespace than the openshift-virtualization-os-images / kubevirt-os-images.
After:
> CNV-39946: Regular user cannot create vm with their own volumes from UI

- src/utils/components/SysprepModal/sysprep-utils.ts
Since a VM in IT flow is created without disks, this error occurs
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/1520222a-c7f3-485b-9559-543d640921ae
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/68ad3919-81af-4dab-b11e-f5601a75dac7
> CNV-41589: Error "Cannot read properties of undefined (reading "push")" on creation of a VM with Sysprep

- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.scss
- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.tsx
**Fixes:**
https://issues.redhat.com/browse/CNV-40344
Our console folks broke our css by using `!important`, which is not a good practice, exactly here:
https://github.com/hstastna/console/blob/master/frontend/packages/console-shared/src/components/getting-started/GettingStartedExpandableGrid.scss#L58
Hence, to fix broken expandable sections in our UI, we must use `!important`, too. 
**Before:**
Sections in Overview settings not indented at all:
**After:**
> CNV-40344: Make expanded sections indented as expected

- src/utils/utils/headless-service.ts
Changing the headless service selector to network.kubevirt.io/headlessService so it could be more unique
After:
> CNV-41591: unexpected "headless" on creating a VM with sysprep

- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DynamicSSHKeyInjectionInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
This PR fixes a bug where dynamic SSH key injection is disabled when the RHEL 9 DataSource is backed by a VolumeSnapshot instead of a PVC.
Jira: https://issues.redhat.com/browse/CNV-40903
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/b844a326-addc-4314-9554-edadf15db7af
https://github.com/kubevirt-ui/kubevirt-plugin/assets/8544299/223f9e82-9277-4c4b-83fd-34d3266d2dc3
> CNV-40903: Fix SSH key injection when DataSource is a VolumeSnapshot

- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/resources/template/utils/helpers.ts
- use VM parameter to create dataVolumes and PVC names. For each vms we'll have different datavolumes
> CNV-42157: Fix disk modal template

- src/utils/components/SSHAccess/SSHAccess.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabAuthorizedSSHKey.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabSSHAccess.tsx
Changing SSH sub tab:
1. removing expand sections so info will always appear, this also fixes the wrong indentation bug [here](https://issues.redhat.com/browse/CNV-41211)
2. Changing SSH access items order for better UX.
3. Removing Linux label from both sub titles and adding one occurrence to main title
Before:
After:
> CNV-40894: SSH page adjustments

- src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
- src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
Some VM charts are missing Y axis to it
Before:
After:
> CNV-42316: VM Metrics page is lacking Y axis

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/hooks/constants.ts
- src/views/virtualmachines/list/hooks/useSelectedFilters.ts
When cluster has proxy pod enabled, the `unfilteredData` is empty as the proxy pod return empty array from the fetch even if the user just filtered data. 
In that case, just watch the selected filters. If we are using the pod for fetching data and the user has selected a filter, don't show the empty state. 
Show the empty state if :
unfiltered data is empty if the cluster is not using the pod
if we are using the pod and unfiltered data is empty, check if the user has selected some filters from the query params (no other way to do it )
> CNV-41633: Fix VM list EmptyState on filtering with pod proxy

- src/utils/store/customizeInstanceType.ts
- src/utils/store/customizeInstanceType/utils/utils.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeInitialRunTab.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/components/InitialRunTabSysprep.tsx
- src/views/virtualmachines/details/tabs/configuration/initialrun/utils/utils.ts
Fix customize IT flow sysprep - missing functions
> CNV-41586: Missing functions for sysprep customizr IT flow

- src/utils/hooks/useToggle.ts
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionHardware.tsx
Every VM update the component gets re-rendered, when the default value is folded expandable section it will close on every VM change. Using localStorage to save the folded value with useToggle new hook
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/bda87e18-1a3c-488e-9f89-5b714eb1b2cc
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/099a66f1-eb7a-43a5-adc6-fde11251f692
> CNV-38101: "Boot management" became folded after editing something on the page

- src/utils/resources/vm/utils/disk/rowData.ts
When we attach a pvc to a VM and the PVC size is ending with 000 or 000000 and so on, k8s shortens the actual number to have either k/m/g suffix and so on. this is getting the wrong size in the disk list
Before:
After:
> CNV-41776: Console is showing incorrect value's for disks attached to VMs

- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
missing namespace in CM create callback
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/26c93805-684f-41be-a191-4590841ae89e
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/aad4e0f2-6b11-4e24-b82a-f9bf42e20c43
> CNV-42786: Windows VM with sysprep cannot be started due to configMap of sysprep not found

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
> update highlight to 4.16

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
Favorite column header is overlapping with the name column header on firefox, adjusting padding values.
Before:
After:
> CNV-40907: Table column alignment issue with "volume to boot from" table

- src/utils/components/ListPageFilter/SearchFilter.tsx
document.addEventListener is adding an event listener for the entire document, instead of just adding to the listener to the proper element in the DOM.
After:
> CNV-41592: unexpected behavior on '/' on creating a VM with sysprep

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/DiskModal/components/DiskTypeSelect/DiskTypeSelect.tsx
- src/utils/resources/vm/utils/disk/constants.ts
Enable disk type on hotplug disk, also removing `floppy` disk type as it's only purpose is to be filtered out at all times.
Before:
After:
> CNV-43078: LUN type is greyed out from UI

- src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
- src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeLink/AddBootableVolumeLink.tsx
Allow a regular user to create volume to his namespace
Before:
After:
> CNV-43068: Catalog -> "Add volume" should be enabled for regular user

- src/utils/hooks/useFeatures/constants.ts
- src/utils/hooks/useFeatures/useFeaturesConfigMap.ts
Moving the `kubevirt-ui-settings` config map to `openshift-cnv` namespace
> CNV-38284: move features ConfigMap to openshift-cnv namespace

- src/utils/components/SSHSecretModal/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SysprepDescriptionItem.tsx
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
We can only have sysprep or ssh credentials. Not both. If the user change bootable volume, he can select both of them in the zustand state and produce some issues
> CNV-43120: sysprep or sshcredentials in zustand

- src/utils/components/AffinityModal/AffinityModal.tsx
- src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionLeftGrid.tsx
I am removing the restart required message from the affinity and node selector models as they are now live update, and no restart is needed if they are live migratable. 
After:
Before:
> CNV-43091: Remove restart required msg from affinity and node selector

- src/views/checkups/storage/components/hooks/useCheckupsStoragePermissions.ts
- src/views/checkups/storage/utils/utils.ts
Fix permission for storage checkups, 
1. non-previlige user cant check clusterbindingroles
2. fix order of promises so role will be deleted/added before role binding.
> CNV-43172: Fix checkups storage permissions

- locales/en/plugin__kubevirt-plugin.json
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
- src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
- src/views/catalog/utils/quick-create-vm.ts
- src/views/catalog/utils/useWizardVmCreate.ts
- src/views/catalog/wizard/components/WizardFooter.tsx
Documentation: https://docs.openshift.com/container-platform/4.11/virt/virtual_machines/virt-create-vms.html#virt-about-runstrategies-vms_virt-create-vms
`spec.running` and `spec.runStrategy` are mutually exclusive. `spec.runStrategy` specified by user and we add `spec.running`
Solution: do not set `spec.running` if `spec.runStrategy` is already defined by the template. Show in the 'start vm' checkbox label the runStrategy if defined. runStrategy `always` or `runonfailure` are special cases of running: true so the checkbox will be checked. 
If the user changes the checkbox status, remove `spec.runStrategy` and use `spec.running`. 
Note: I removed the `startVM` from all the contexts as this is something that is defined in the VM itself. So instead of having another state in the context, I …
> CNV-43245: use runStrategy if defined

- src/views/checkups/network/components/CheckupsNetworkActions.tsx
- src/views/checkups/network/details/CheckupsNetworkDetailsPage.tsx
- src/views/checkups/network/details/CheckupsNetworkDetailsPageHeader.tsx
- src/views/checkups/network/list/CheckupsNetworkListRow.tsx
- src/views/checkups/network/utils/utils.ts
Now, when deleting network latency checkups, it will also delete the jobs and cascade the deletion of the jobs pods.
> CNV-38598: Cascade delete for jobs and pods when checkups deleted

- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/vm/utils/constants.ts
- src/utils/resources/vm/utils/network/rowData.ts
- src/utils/resources/vm/utils/network/utils.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
- src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
- set `autoattachPodInterface` to false for instanceType vms and explicitly defined the default network interface. Explicitly defining the interface, instead of relying on the default autoAttach, let the user delete all the network interfaces from the VM on customize or after creation.
- When the user deletes the last interface from existing vms, set the flag to false, so that the user will delete all the interfaces. Currently, If the user deletes all interfaces, the VM will always keep the default one. 
- In the network list, show the label 'pending' when the user try to remove one network from a running VM. Currently we show the pending label only when the user add the network and when it remove it, we just show the pending alert in top . 
- The first interface is marked as the default …
> CNV-38351: set autoattachPodInterface to false by default

- package.json
- yarn.lock
This PR bumps Console plugin SDK dependencies to latest for OCP 4.16 - see Console PR [#14012](https://github.com/openshift/console/pull/14012) for details.
> Bump Console plugin SDK dependencies to latest for OCP 4.16

- README.md
When running Console Bridge locally,
```
-plugins kubevirt-plugin=http://localhost:9001/
```
(note the trailing slash) should be paired with
```
-i18n-namespaces=plugin__kubevirt-plugin
```
to ensure that the proper i18n namespace is registered for the plugin at Console runtime.
:information_source: Note that `.devcontainer/Dockerfile.console` already contains
```
-i18n-namespaces $OC_PLUGIN_I18N_NAMESPACES
```
which could also be updated to
```
-i18n-namespaces plugin__$OC_PLUGIN_NAME
```
(and thus removing the need for `OC_PLUGIN_I18N_NAMESPACES` env variable) but I leave that up to you :smiley:
> Improve docs regarding running Console Bridge locally

- src/utils/components/DiskModal/utils/helpers.ts
This PR fixes a bug where modifications to the size of a disk in the Edit disk modal on the Templates details page don't persist.
jira: https://issues.redhat.com/browse/CNV-42619
> CNV-42619: Modifications to disk size on Templates details page don't persist

- README.md
The issues feature in GitHub has been turned off to maintain a single source of truth for issues, which is Jira.
This PR adds instructions on how to open an issue to the README.
> Add instructions for opening issues to README

- src/utils/components/DiskModal/DiskModal.tsx
- src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/components/DiskModal/utils/types.ts
- src/utils/components/TabModal/TabModal.tsx
- src/utils/resources/vm/hooks/disk/useDisksSources.ts
- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/hooks/disk/utils.ts
- src/utils/resources/vm/utils/disk/rowData.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeStorageTab.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/DetachModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskList.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/utils/getEditDiskStates.ts
Change disk size in diskmodal option.
Only on customize flag true as it cannot be done on VMs already created
**Before**
**After**
https://github.com/user-attachments/assets/aebd86ed-2fa2-41b7-8222-94828dae2c21
> CNV-43096: Customize disk size instancetype

- src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
- src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/DeleteDiskModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/hooks/useVolumeOwnedResource.tsx
**fix detach crash**
`useVolumeOwnedResource` was using `volumeResourceModel.verbs;` with no assignment. Strange.
`volumeResourceModel`can be undefined. 
it is crashing not only on cloudinit but also on containerDisk source disk.
**Fix detach message**
detach message has namespace. Do not make sense to have namespace in it. 
It was already fixed in VM but not in template and wizard
**Before**
**After**
> CNV-44420: Fix detach disk crash

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/HorizontalNavbar/utils/useDynamicPages.ts
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTab.tsx
- src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
- src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
- src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
- src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx
- src/views/virtualmachines/details/utils/types.ts
Add obj as prop to be compliant with the SDK horizontal navbar that call extension components giving the obj prop
**Adding test tab**
Here as you can see Overview and Test tabs are 'active' 
I solved this issue
> CNV-44838: Use VirtualMachine dynamic extension pages

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/types.ts
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.scss
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
Adding correct annotation to get descriptive title, also asjusting tile size to be shorter.
Before:
After:
> CNV-44514: Missing descriptive names inside the InstanceTypes tiles

- src/utils/components/FilterSelect/InlineFilterSelect.tsx
SelectOption onClick event is not fired for some reasons. But the onSelect is fired always so we'll better to use that.
> CNV-45428: Fix inlinefilterselect onselect

- src/utils/components/DiskModal/utils/helpers.ts
- src/utils/resources/vm/utils/disk/rowData.ts
BUgs when DataSources are connected to VolumeSnapshots instead of PVCs. We can't grab the PVC size because the chain is too long DS -> VS -> PVC . So just don't show the size. 
When hotplugging something, the dataVolume needs to be created from dataVolumeTemplates. We cannot create it directly from the dataVolumeTemplates (doesn't have kind , apiVersion and namespace )
**Before**
> CNV-44890: fix diskmodal issues

- src/utils/components/SnapshotModal/SnapshotModal.tsx
- src/utils/components/SnapshotModal/utils/utils.ts
Previously, auto-generated snapshot names provided no useful information outside of the VM name. This PR modifies the name format to add creation date and time information to make the auto-generated names more meaningful.
Jira: https://issues.redhat.com/browse/CNV-46589
> CNV-46589: Auto-generate meaningful snapshot names

- src/perspective/extensions.ts
- src/perspective/perspective.scss
- src/perspective/perspective.ts
- src/utils/i18n.ts
Adding the cluster -> overview in the virtualization perspective as a doc change
- adding some data attributes to make the CSS works. (No className property)
Reduce padding for all the items and remove the border between them.
The last item Chekup does have borders so use a different class for that.
Add horizontal padding for the separator
https://docs.google.com/document/d/1_mv7aEDC2KiXv423CGPPnydu-WnF4zUP9xRbGjlcIIw/edit
> CNV-44365: add cluster -> overview to virtualization perspective

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/DeleteDiskModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
Enable detach disks from running vm
> CNV-46660: enable disk delete on running vm

- src/templates/vm-template-yaml.ts
- src/templates/vm-yaml.ts
The `running` field in the VirtualMachine's spec is being deprecated in kubevirt in favor of the `runStrategy` field, therefore all examples show be using the `runStrategy` for specifying the requested running state of the VMI.
Reference: https://github.com/kubevirt/kubevirt/issues/11993
> CNV-45441: New VM template: Use `runStrategy` field instead of deprecated `running`

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/utils/utils.ts
- src/utils/components/FilterSelect/InlineFilterSelect.tsx
- src/utils/components/FilterSelect/components/InlineFilterSelectOption.tsx
- src/utils/components/FilterSelect/components/InlineFilterSelectOptionContent.tsx
- src/utils/components/FilterSelect/components/InlineFilterSelectOptions.tsx
- src/utils/components/FilterSelect/utils/types.ts
- src/utils/components/FilterSelect/utils/utils.ts
Allow grouping in InlineFilterSelect component
Before:
After:
> CNV-43592: Preference dropdown in 'Add volume' has no grouping for user/RH preferences

- plugin-metadata.ts
Bumping version for the plugin's metadata 
Before:
After:
> Bump plugin metadata version to 4.17

- locales/en/plugin__kubevirt-plugin.json
- src/utils/hooks/useRHELAutomaticSubscription/utils/types.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionForm/AutomaticSubscriptionForm.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionType/AutomaticSubscriptionType.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionType/utils/utils.ts
Fix rhel regiretion appearance
* no more apply button
* first select b value from dropdown then enter key and orgid 
* no more text regarding cluster admin permission
After:
Before:
> CNV-47590: Fix rhel registration apperance

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
Backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1728
Jira: https://issues.redhat.com/browse/CNV-46751
> CNV-46751: Prevent deletion of pod network on Instancetype VM

- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
Moving the registry config to be under source details sub title and below the registry URL input instead of under the destination sub-title below the namespace input.
Before:
After:
> CNV-47229: Move the config of registry together in the add volume modal

- src/utils/resources/bootableresources/helpers.ts
- src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
- src/utils/resources/shared.ts
- src/views/bootablevolumes/list/BootableVolumesList.tsx
- src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
DataSource CloneInProgress is a state that now depends on a condition in the DataImportCron.
Now there is no condition in the DataSource that indicates whether it's cloning or not
It can take a couple of seconds to show up but it's okay I think
Bootable Volumes list
Create instance type bootable volume list (last item)
> CNV-43594: Fix bootable incloning

- src/utils/components/DiskModal/DiskFormFields/StorageClass/StorageClassSelect.tsx
- src/utils/hooks/useDefaultStorage/useDefaultStorageClass.ts
When the storage class is empty initially, the dropdown is selecting the cluster's default SC instead of virt default SC.
Before:
https://github.com/user-attachments/assets/9cd8b875-4801-47bd-b2b2-4055ccbf518f
After:
https://github.com/user-attachments/assets/ee33b0ad-71ba-414e-8617-eab7a77b72dc
> CNV-42324: SC select is showing cluster default instead of virt default

- src/utils/resources/vm/hooks/disk/useDisksSources.ts
- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/hooks/disk/utils.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
**Before**
VM disk list show the original PVC where data source clone the data for the disk
VM -> DataSource -> PVC (source cloned)
The PVC that you see here is not the PVC that the VM will use but what the datavolume will clone. This will probably create confusion to the user.
**After**
Vm disk list show the actual PVC used by the VM 
VM -> DataVolume -> Actual PVC used (The one that we have to resize, not the source cloned)
**Why we did that?**
Because in the instancetype we want to show in the disk list the source size that will be cloned. In order to do that, we have to set the `storage.resources.requests.storage` property
> CNV-46660: show disk pvc not the original source

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
When createing a VM with ssh key on Catalog > Templates > Quick create flow, the secret is not created because of a missing request to create such secret. The missing secret causes the VM's pod to fail running, and the VM is not operable.
> CNV-47291: public ssh key credential does not get created

- cypress/tests/catalog/filter.spec.ts
- cypress/views/catalog.ts
- src/utils/resources/bootableresources/constants.ts
- src/utils/resources/bootableresources/hooks/useHideDeprecatedBootableVolumes.ts
- src/utils/resources/template/utils/constants.ts
- src/views/bootablevolumes/list/BootableVolumesList.tsx
- src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts
- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
- src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
- src/views/catalog/templatescatalog/TemplatesCatalog.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
- src/views/catalog/templatescatalog/hooks/useHideDeprecatedTemplateTiles.ts
- src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
- src/views/templates/list/VirtualMachineTemplatesList.tsx
- src/views/templates/list/hooks/useHideDeprecatedTemplates.ts
- src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
This PR causes the 'Hide deprecated bootable volume' filter to be selected by default on the Bootable volume list page and the InstanceTypes VM creation page.
Jira: https://issues.redhat.com/browse/CNV-45860
[hide-deprecated-by-default--2024-09-13 21-29.webm](https://github.com/user-attachments/assets/a89d4d6f-2b23-42ec-b365-e3387e602504)
> CNV-45860: Select 'Hide deprecated bootable volume' filter by default

- src/utils/components/SysprepModal/hooks/useConfigMaps.ts
Once migrating VMs with MTV, a config map is created with a property of binaryData and is missing the data prop.
This causes the sysprep modal to crash as it's missing the prop and trying to reach it.
https://github.com/user-attachments/assets/3fdb4218-7f42-4fc4-8558-f960802510d6
https://github.com/user-attachments/assets/89f37c12-df05-4ad4-91d4-2badf972547b
> CNV-48451: Windows autoattend.xml can not be created as a regular user

- src/utils/components/ProjectDropdown/ProjectDropdown.tsx
This is a fix for moving between projects on the bootable volume list in IT flow; when returning to ALL projects, the namespace column is missing.
* Checked in both places where this component is consumed and doesn't seem to break anything.
> CNV-45249: Fix selecting all projects on bootable volume list IT flow

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
Non-privileged users getting "All projects" option selected, but they don't have privileges to see all projects, so the list is empty. Selecting the `openshift-virtualization-os-images` project as default for non-admin users.
https://github.com/user-attachments/assets/4d9fe0c0-e701-4fc1-b89e-9e8b2c9342cf
https://github.com/user-attachments/assets/d869c5db-b7db-4d69-a5e5-3f8066fa6f63
> CNV-45815: No volumes found for nonpriv user in All projects

- src/utils/components/DiskModal/utils/form.ts
At beginning, set the storage profile as optimized. 
With anything specified in volume and access modes, we'll use the optimized way
**After**
> CNV-48314: apply opt storage at beginning

- src/views/checkups/storage/components/hooks/useCheckupsStoragePermissions.ts
- src/views/checkups/storage/list/CheckupsStorageList.tsx
- src/views/checkups/storage/list/CheckupsStorageListEmptyState.tsx
Disable the install button for checkups storage for non cluster reader users, and adding a link to docs
according to - https://docs.openshift.com/container-platform/4.16/virt/monitoring/virt-running-cluster-checkups.html#virt-checking-storage-configuration_virt-running-cluster-checkups
> CNV-41290: Disable checkups storage install button for non cluster reader

- src/views/virtualmachines/actions/components/VMActionsIconBar/components/ActionIconButton.tsx
- src/views/virtualmachines/actions/components/VMActionsIconBar/utils/types.ts
- src/views/virtualmachines/actions/components/VMActionsIconBar/utils/utils.ts
Show the icon actions and disable instead of hiding
> CNV-43588: Start/Restart/Stop icon controls disappear during shutdown

- src/utils/components/DiskModal/utils/helpers.ts
Clicking on the disk action edit is triggering a function also to update the correlated volume. 
This bug affects only 4.16.z. can't reproduce in main/4.17/4.15.z
https://github.com/user-attachments/assets/b9a42839-5105-480c-ab7f-57960e2e0e95
https://github.com/user-attachments/assets/cfbbc3cc-3046-4412-830d-4706ef0d3e7d
> CNV-48180: edit rootdisk causes VM create to fail

- src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
- src/utils/components/TolerationsModal/TolerationsModal.tsx
Wrong path verified caused the toast alert to pop.
https://github.com/user-attachments/assets/a810f70f-b692-4618-b9d8-b6d81b9c46fe
https://github.com/user-attachments/assets/05c911b8-cb11-4fe9-8ea1-a308a5de2153
> CNV-49577: nodeSelector and tolerations edit shows alert

- src/views/instancetypes/list/InstanceTypePage.tsx
- src/views/preferences/list/PreferencePage.tsx
Remove the `useEffect` that was causing a bug switching projects. Now the activeKey is not a state but we get it directly from the pathname. 
`useVirtualMachineInstanceTypes` hook now has a third parameter that we need to use.
**Before**
https://github.com/user-attachments/assets/35d5985b-d2b9-4e88-8d92-89a7c4032a94
**After**
https://github.com/user-attachments/assets/2869fc22-d564-4b50-871a-7a0b3793352e
> CNV-47477: fix switching project from all-namespaces

- src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
- src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
- src/utils/components/EnvironmentEditor/components/EnvironmentSelectResource.tsx
- src/utils/resources/vm/hooks/disk/useDisksSources.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskList.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
disk list loading is just for fetching PVC so we don't have to show the list loading
for environment list the loading is just for selecting new items, so we can show the loading only on the select if visible. 
(We can't show loading inside the select dropdown for a patternfly bug)
**Before**
https://issues.redhat.com/secure/attachment/13183584/storage_reload_times.mp4
**After**
https://github.com/user-attachments/assets/bd364d89-4b04-4ce1-8b41-14f89f59bcc4
> CNV-41403: localize loading

- default.conf
fix nginx config according to https://github.com/kubevirt-ui/kubevirt-plugin/issues/2072
We don't have issues with the installation through the openshift operator tho.
The operator uses a ConfigMap to override the nginx config. But for external people that come in this repo and use only the quay dockerfile, this config is wrong
> Fix nginx config for okd installation

- src/utils/hooks/useFeatures/constants.ts
- src/utils/hooks/useFeatures/useFeatures.ts
- src/utils/hooks/useFeatures/useFeaturesConfigMap.ts
- src/utils/hooks/useKubevirtHyperconvergeConfiguration.ts/index.ts
- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
- src/utils/hooks/useKubevirtUserSettings/utils/const.ts
- src/utils/utils/utils.ts
- src/views/clusteroverview/utils/constants.ts
- src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts
Using a kinD cluster i was able to install kubevirt, okd console, and make things work.
use `HYPERCONVERGED_NAMESPACE` to retrieve the right hyperconverged namespace. `kubevirt-hyperconverged` or `openshift-cnv` depending on okd or openshift. 
Also one other thing to fix for infinite loading:
in case of auth disabled mode (only development) we get an error on fetching the user (there is no user)
so if there is an error with the user in `useKubevirtUserSettings`, just stop loading. 
We'll have this error only in development but because we are just fetching the user settings, it's better to not have infinite loading.
solving the #2072  issue . Because kubevirt support plain k8s, it would be a nice thing to have also the UI plugin support this
**Before**
**After**
> Make kubevirt works with okd

- src/utils/components/CloneVMModal/utils/helpers.tsx
- src/utils/components/EnvironmentEditor/tests/mocks.ts
- src/utils/components/GuidedTour/utils/constants.tsx
- src/utils/constants/constants.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useDrawerContext.tsx
- src/views/catalog/wizard/components/WizardFooter.tsx
- src/views/virtualmachines/actions/tests/mocks.ts
As a part of the deprecation of the VM's .spec.running field, we need the UI plugin to stop using it, and use the runStrategy API everywhere by default.
> CNV-45435: Migrate all `.spec.running` usages to `.spec.runStrategy`

- Dockerfile
[here](https://github.com/kubevirt-ui/kubevirt-plugin/pull/2208) we added docker support for s390x archs.
Github on creating images cross-arch is giving network errors.
This is because the network is very slow on those cross-arch docker builds. So just make sure to have github be patient :) 
> CNV-49906: fix docker image builder

- src/utils/components/CloneVMModal/CloneVMModal.tsx
- src/utils/components/CloneVMModal/utils/helpers.tsx
`spec.running` and `spec.runStrategy` are mutual exclusive. YAML example now use `spec.runStrategy` so patching the VM with `spec.running: true` does not work. So if the VM use `spec.running` patch that spec attribute otherwise use `spec.runStrategy`
> CNV-49299: use runStrategy on cloning

- src/utils/components/ActionDropdownItem/ActionDropdownItem.tsx
Migration action disabled when no accessReview specified.
Seems like `useAccessReview` now returns false when no accessReview specified. 
**Bug**
> CNV-50786: fix accessReview on migration action

- locales/en/plugin__kubevirt-plugin.json
- package.json
- src/utils/components/ActionsDropdown/ActionsDropdown.tsx
- src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.ts
- src/views/virtualmachines/list/VirtualMachinesList.scss
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineActionButton.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/selectedVMs.ts
- src/views/virtualmachines/utils/virtualMachineRowFilter.ts
- yarn.lock
Let the user select multiple vms to run actions in parallel
1. Should we have a loading state somewhere?
2. Currently we cannot have the selection for all vms for SDK VirtualizedList limitations. Are we sure to let the user select ALL vms in the namespace or cluster? Can this have issues with running the action for 100 or 1000 vms? 
https://github.com/user-attachments/assets/195a4d32-921b-40f4-a272-3eef5ad6617e
> CNV-43052: Select multiple vms at a time

- src/utils/hooks/useKubevirtUserSettings/utils/utils.ts
The patch was not working as we were trying to add `/data/username` but there was no `/data` key in the root of the configmap
> CNV-51085: add data key to user settings configmap if no data

- deploy-kubevirt-gating.sh
This should avoid the error we see in the logs, where the task abort if `type virtctl` exit code is not 0.
> refactor download virtctl tool if needed

- test-prow-e2e.sh
Unset KUBERNETES_* vars which conflict with OpenShift-CI
```
{`cy.exec('oc patch virtualmachine example --type merge -p '{"spec":{"runStrategy": "Always"}}'')` failed because the command exited with a non-zero code.
Pass `{failOnNonZeroExit: false}` to ignore exit code failures.
Information about the failure:
Code: 1
Stderr:
Error from server (NotFound): namespaces "ci-op-fl2b7jdp" not found
```
> Unset KUBERNETES_* vars

- src/views/virtualmachines/list/VirtualMachinesList.tsx
Sometimes the header checkbox is wrongly checked. 
I added `useComputed` wrongly thinking was something like `useMemo` for signals. 
We don't need to use `useComputed` or `useMemo` as the value is boolean and do not trigger a re-rendering if the value does not change
**Before**
**After**
> CNV-50655: fix useComputed is not updated properly

- src/utils/components/ExportModal/utils.ts
BE says that we should not create pods with security context as it can leads to some issues in particular cases. 
There are namespaces with `restricted` policies  in our developer clusters that will not allow creating pods like that but the BE ensured me that in production people will not configure namespaces like that
> CNV-46447: do not add securty context

- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
If the user has no permission to access the PVC size, use the default value of `30Gi`
> CNV-49651: put a default disk size if user have no access to the pvcs

- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
A `for` with `in` iterate on the indexes. The first index `0` satisfy the condition `osLabel?.includes(name)` for `rhel10` as the `10` have the `0`.  This is why the bug was found only now. The default username for cloud-init was always `cloud-user` 
Using `of` in the `for`, we iterate over the values of the array so `rhel`, `fedora`, `windows` etc etc. Now the default username for cloud-init depends on the os so for windows is `windows`, for rhel is `rhel` and so on.
With this fix
> CNV-51122: fix cloud init default name

- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
The component used to select a network in the "Add network interface" modal was recently changed to a typeahead component exhibiting the standard selection behavior found in the Patternfly typeahead component [1]. This change introduced a change in behavior where selecting the currently selected option deselects that option and reverts to a placeholder value.
This PR modifies the behavior such that selecting the currently selected option does nothing.
Jira: https://issues.redhat.com/browse/CNV-51588
[1] https://v5-archive.patternfly.org/components/menus/select/react-templates/#typeahead
[select-nad-behavior-change--BEFORE--2024-11-21 16-44.webm](https://github.com/user-attachments/assets/d30808ba-4097-4d76-97dd-4920e2a7a0eb)
[select-nad-behavior-change--AFTER--2024-11-21 …
> CNV-51588: Fix network selection behavior change in Add network interface modal

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
We don't have to remove the hotpluggable flag to make the disk persistent. 
You have to add the volume in the VM if it's not there. 
https://github.com/user-attachments/assets/3ed44cfa-5f6d-4045-8dcf-47bea24c0dab
> CNV-50957: make disk persistent after hotplug

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
Because all columns have fixed sizes ( in percentage to the window size) the select column does not respect it's size and gets bigger when some column is hided. 
Having a couple of columns with a flexible width make sure that the row is much more readable.
For example, when all columns are on, the node name and the created timestamp can easily break the wording
With flexible width, when the user hides some columns, the node and created timestamp column take more space when needed. 
Note: the name column is the most important and can't be hided
**Before**
https://github.com/user-attachments/assets/1c193601-32c0-43d3-82a1-dd7a59a6cbb7
**After**
https://github.com/user-attachments/assets/bd6e2fc7-e5f5-473f-b081-56d4bce8a9fb
> CNV-50655: fix VirtualMachineList columns width with checkbox

- src/utils/components/WindowsDrivers/WindowsDrivers.tsx
- src/utils/components/WindowsDrivers/drivers.ts
- src/utils/components/WindowsDrivers/utils.ts
- src/utils/store/drivers.ts
WIndowsDrivers component is showing loading state intermittently as it get mounted and unmounted firing effects
We have this issue during VM starting or stopping
**Before**
https://github.com/user-attachments/assets/3eb40c6c-1c16-4f17-bbb1-2e38def4171a
**After**
https://github.com/user-attachments/assets/ef979efa-b0ea-4406-a37f-49a02fbda3d5
> CNV-41403: resolve disk list flickering loading

- locales/en/plugin__kubevirt-plugin.json
- src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
- src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
- src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
- src/views/virtualmachines/list/VirtualMachinesList.scss
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.scss
- src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
- tsconfig.json
Adding status summary to VM list view
Note: This PR is built on top of https://github.com/kubevirt-ui/kubevirt-plugin/pull/2248
> CNV-45822: Vm tree view 2

- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
The next button `isDisabled` condition was inverted. 
This button should be disabled if the user didn't selected any disk
**Before**
.
**After**
https://github.com/user-attachments/assets/d2fee6f5-f364-484f-aef2-056ecbf013d9
> CNV-52283: inverted condition in next button disabled

- cypress/tests/e2e/check-tab-yaml.cy.ts
- cypress/views/selector.ts
check the VM can be started in CI.
> start example vm

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
- src/views/virtualmachines/list/hooks/constants.ts
- src/views/virtualmachines/list/hooks/useVMMetrics.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/list/hooks/utils.ts
- src/views/virtualmachines/list/metrics.ts
Adding Network, Memory and CPU Usage in VM list
Note: 
- right now the columns are not sortable but we can add that later
-  For network we use the total usage (received + transferred)
> CNV-49533: Add Memory, CPU and Network usage on vm list

- src/utils/components/SearchItem/search-item.scss
> This fixes [CNV-52406: Search results highlight is too bright](https://issues.redhat.com/browse/CNV-52406)
**Before**
**After**
>  CNV-52406: Search result highlight transparency added

- src/perspective/virtualization-icon.tsx
This fixes [CNV-52273: Virtualization icon is bigger than others in perspective switcher](https://issues.redhat.com/browse/CNV-52273) bug.
**Before**
**After**
> CNV-52273: Virtualization icon is bigger than others in perspective switcher

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/hooks/constants.ts
- src/views/virtualmachines/list/hooks/useVMMetrics.ts
- src/views/virtualmachines/list/metrics.ts
Align the utilization percentage between VM list and VM details page
VM details page for memory utilization is using the vmi memory amount and does not fetch it from the prometheus query.
This seems a smart thing to do so I do the same thing in the VM list 
So now we do 4 queries in VM list and not 5. (Good for performance)
Note: use `toFixed` instead of `round` to show percentage with fixed number of digits (also with 0 ending numbers)
**VM Details page**
**VM List page**
> CNV-49533: Fix memory utilization percentage in vmlist

- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
- src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
- src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
- Do not let the user run multiple storage migrations in the same VM multiple times. If the user launches a storage migration let it cancel it. 
- Fix `migration` to `Migration` in the `updateVolumesStrategy` field. 
- the DV destination name in multiple sequential migrations tends to become larger and larger. So I fixed that by following what the MTV team did: add to the original name `mig-xxxx` . In a future migration we'll re-create the suffix removing `-mig-xxx` and adding again `-mig-yyyy`  
**Before**
**After**
> CNV-51680: migrate or cancel migration and fix storage migration

- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/GettingStartedSection/GettingStartedSection.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/ManageSSHKeySection.tsx
- src/views/clusteroverview/SettingsTab/UserTab/components/TaskPermissionsSection/TaskPermissionsSection.tsx
- src/views/clusteroverview/SettingsTab/UserTab/user-tab.scss
1. fix the alignment issue
2. add data-test-id for elements under Settings - User
Before:
After:
> CNV-53287: fix the alignment issue on Settings -> User

- plugin-metadata.ts
> CNV-53388: Bump plugin version to 4.18

- cypress/tests/e2e/check-tab-yaml.cy.ts
Try to enable tests for the snapshot tab for debugging.
> check the snapshot tab of the VM can be loaded

- locales/en/plugin__kubevirt-plugin.json
- package.json
- src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
- src/utils/constants/documentation.ts
- src/utils/resources/udn/hooks/useNamespaceUDN.ts
- src/utils/resources/udn/types.ts
- src/utils/utils/matchSelector.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
- yarn.lock
Hide the virtctl command for VMs on udn managed namespaces
Hide the `Internal FQDN` interfaces
**Before**
**After**
> CNV-51530: hide virtctl on managed udn namespaces

- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/MakePersistentModal.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/modal/utils.ts
Make sure that the dataVolumeTemplate that we add, it also has info about storage size ( I don't know why, but in my cluster was not an issue)
> CNV-52060: add storage info to datavolumeTemplate in make persistent

- src/utils/components/ActionsDropdown/ActionsDropdown.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/components/ComposableDrilldownSelect/ComposableDrilldownSelect.tsx
- src/utils/hooks/useClickOutside/useClickOutside.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/hooks/useInstanceTypeCardMenuSection.ts
This regression was introduced when we changed the actions dropdown to a Popper component that needs to add an effect to make this behavior happen (which comes out of the box when using Select component with onOpenChange prop).
Enhancing the useClickOutside hook that we already have for this cases to get more than one ref (the menu and the toggle components refs) to solve this issue.
Before:
https://github.com/user-attachments/assets/6c44b35f-0351-4e42-991b-cc86e14ba2a4
After:
https://github.com/user-attachments/assets/cfb3bc18-0853-4ccc-afa4-79cfedc185a1
> CNV-54208: The dropdown menu of "Actions" is not closed by clicking somewhere else

- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
- src/views/virtualmachines/tree/utils/utils.tsx
Tree view crashed to non priv users when they have no projects, fixing this and disabling the switch on the toolbar when no projects (system projects can be found but they are filtered by default as they shouldn't appear at all).
before:
https://github.com/user-attachments/assets/2b24e0ed-40d0-4e26-b550-c04be58b143a
after:
https://github.com/user-attachments/assets/2b6af05e-9f1d-4dc1-ac6a-fa606f496912
> CNV-53452: VirtualMachines page crashes for nonpriv user when user hasn't created a project

- src/views/virtualmachines/tree/hooks/useTreeViewSelect.ts
When clicking a project/all projects tree view item we need to apply the last namespace we visited so the breadcrumbs would behave properly
Before:
https://github.com/user-attachments/assets/93e648d7-e1f0-4cfc-8986-b4c899edcff2
After:
https://github.com/user-attachments/assets/7f81ef40-9a55-4939-9f9f-bdabae007683
> CNV-54221: Apply last namespace to project items in tree-view

- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceRow.tsx
If we first create a VM from IT flow, than customize a VM in template flow, the VM from IT flow is selected just from the network section. Drilling the actual VM as a prop instead of relaying on global signal VM being populated or not
Before:
https://github.com/user-attachments/assets/a51fae9d-5e2c-46fe-8921-8d2c8519f2d7
After:
https://github.com/user-attachments/assets/62f3f423-2ee3-4bfb-8c0c-35f4e5c6ab39
> CNV-50766: Cannot delete NIC from VM

- src/perspective/extensions.ts
Monitoring team is merging this https://github.com/openshift/monitoring-plugin/pull/318 on 4.18. 
When they'll merge it, we would see Observe section two times and they will define it in their console-extension file.
So we have to remove our own definition
> CNV-51386: Observe section handled by monitoring-plugin

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
This PR fixes the sorting of bootable volumes table columns on the create VM from InstanceTypes page. The sorting algorithm wasn't accounting for the namespace column which is present when All Projects is selected, which threw off which column was being sorted by one index.
Jira: https://issues.redhat.com/browse/CNV-51653
[bootable-volumes-sort--BEFORE--2025-01-13 06-55.webm](https://github.com/user-attachments/assets/e0d43311-59d6-4822-ad18-2ea7a463a0f8)
[bootable-volumes-sort--AFTER--2025-01-13 06-52.webm](https://github.com/user-attachments/assets/8ea78e70-51a5-49b0-83b6-d7f5505d287c)
> CNV-51653: Fix bootable volume column sorting on create VM from IT page

- yarn.lock
upgrade `webpack-dev-server` to use `path-to-regex` `0.1.12`
> CNV-52557: CVE path-to-regex fixed

- package.json
- yarn.lock
upgrade `mocha` (a tool used for unit tests) as `9.2` uses a fixed version of nanoid that has the vulnerability . `10` version does not even use nanoid.
> CNV-52642: fix nanoid cve

- src/utils/resources/vm/hooks/disk/utils.ts
This PR fixes a bug that caused the storageclass for disks added after VM creation from being displayed in the Disk list in the VM Details page.
Jira: https://issues.redhat.com/browse/CNV-52393
> CNV-52393: Fix missing storageclass in VM Details disk list

- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/hooks/useSSHAuthKeys.ts
This PR fixes a bug that caused the list in the "Manage SSH keys" section of the User settings page to not display existing keys.
Jira: https://issues.redhat.com/browse/CNV-55048
> CNV-55048: Fix display of default SSH settings list

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/VMNameValidationHelperText/VMNameValidationHelperText.tsx
- src/utils/components/VMNameValidationHelperText/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/wizard/tabs/overview/components/VMNameModal/VMNameModal.tsx
This PR adds limits the length of VM names to the maximum k8s label length of 63 characters. Names larger than this cause errors when migrating VMs.
Jira: https://issues.redhat.com/browse/CNV-55112
> CNV-55112: Limit VM name length to max k8s label length (63 characters)

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
Extend existing type by adding `2xmedium` option.
> CNV-49438: Add 2xmedium to InstanceTypeSize

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
Feature flag is retrieved from/saved to the server which introduces delay. Before this fix nothing was rendered when waiting for the flag. After this fix the UI will be rendered with following safety measures:
1. callback to toggle the feature will be disabled
2. on initial load (no data) the switch will be disabled
https://github.com/user-attachments/assets/6aafe06b-7277-4dc2-a4ad-5d1bfc39b61b
https://github.com/user-attachments/assets/c9ce4d8c-cc2a-43cf-979e-4f47850e5fb1
> CNV-47203: Display Automatic subscription section with incomplete data

- src/views/virtualmachines/details/tabs/diagnostic/VirtualMachineDiagnosticTabRow.tsx
- src/views/virtualmachines/details/tabs/diagnostic/hooks/constants.ts
- src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticDataVolumeStatusTableColumns.ts
- src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabDataVolumeStatus.tsx
Add diagnosis datavolume table list a link to datavolume so if there is a problem we can go directly into the datavolume page.
The UI clicks to go there without it are numerous  
**Before**
**After**
> CNV-54834: add datavolume link on diagnosis table

- src/utils/components/HardwareDevices/modal/HardwareDevicesModal.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
- src/utils/resources/vm/utils/constants.ts
- src/utils/resources/vm/utils/network/constants.ts
- src/views/catalog/wizard/tabs/overview/components/WizardOverviewNetworksTable/WizardOverviewNetworksTable.tsx
`deviceIndex` property most likely leaked from [HardwareDeviceModalRow](https://github.com/kubevirt-ui/kubevirt-plugin/blob/4b8c4a624581fdaa7a2e5d5d96a27093b416df15/src/utils/components/HardwareDevices/utils/constants.ts#L7)  type. 
`l2bridge` prop leaked from [network interface to label mapping](https://github.com/kubevirt-ui/kubevirt-plugin/blob/4b8c4a624581fdaa7a2e5d5d96a27093b416df15/src/utils/resources/vm/utils/network/constants.ts#L21) which treats the same keys of [V1Interface](https://kubevirt.io/api-reference/v0.38.1/definitions.html#_v1_interface) and synthetic type `l2bridge`. 
Both cases fixed by explicit filtering and better typing (to prevent similar cases in the future).
> CNV-54166: Admission webhook warning about non existing properties l2bridge and deviceIndex

- package.json
- src/utils/components/DiskModal/components/StorageProfileSettings/ApplyStorageProfileSettings.tsx
- src/utils/components/DiskModal/components/StorageProfileSettings/VolumeMode.tsx
- src/utils/components/DiskModal/components/utils/modesMapping.ts
- src/utils/components/FirmwareBootloaderModal/utils/utils.ts
- src/utils/resources/preference/helper.ts
- src/utils/types/storage.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/hooks/usePreference.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/utils/tabs/CustomizeInstanceTypeDetailsTab.tsx
- src/views/cdi-upload-provider/upload-pvc-form/UploadPVCFormVolumeMode.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- yarn.lock
The default mode for us if we don't have anything specified is bios but preference overrides this if firmware fields are specified. 
On customized we cant fetch the extended VM with preference and instacetype info like we do in the VM details page. So we have to fetch the preference and see what we got
**Before**
**After**
> CNV-55111: get preference bootmode

- src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
- src/utils/components/Charts/utils/utils.ts
The network chart is on bps. This means that when the VM does a network traffic in the order of kbs or mbs, our code creates hundreds and millions of ticks in the Y axis.
Ticks are the Y axis points that we see. 
As you can see from the *before* charts, they are darker in the background. This is because millions of ticks have been created. 1 kps? 1000 bps -> 1000 ticks. 1mps ? 1_000_000 bps -> 1_000_000 ticks.
the `getNetworkTickValues` function was responsible to create the ticks in the chart and `formatNetworkYTick` is responsible to give at each tick a label. As you can see we give labels only to the first and last tick
We defined a label for the first one (min in the chart) and the maximum in the chart, but our code creates the ticks in between anyway without labels.
I removed this …
> CNV-55454: Fix metrics freezing

- src/utils/utils/utils.ts
- src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
- src/views/instancetypes/list/hooks/useUserInstancetypeListColumns.ts
- src/views/instancetypes/list/hooks/utils.ts
sorting was not working as memory was not converted in bytes but compared as string. 
So 4Gi was smaller than 512Mi
Create a generic function that can sort any columns, make the existing function use the generic function adding the compared function. Use the generic function to sort memory with a custom compared function
> CNV-55042: instancetype list sort memory fixed

- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/components/vnc-console/vnc-console.scss
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Key points:
1. enable scaleViewport flag by default
2. move 'Open web console' link above the console - with insufficient
width the link is pushed too far to the bottom. The console
calculates the dimensions dynamically so it's not possible to assign
the correct height in a static way.
3. remove unnecessary CSS
Based on works previously done for oVirt project - https://github.com/oVirt/ovirt-web-ui/pull/1585
https://github.com/user-attachments/assets/f38b2599-4cdb-4355-b7a0-ffe286b252f5
https://github.com/user-attachments/assets/dc6bb3d2-c704-4b4f-acaa-cc308990837e
https://github.com/user-attachments/assets/947c6926-cfba-4e84-9621-19c5e9590970
https://github.com/user-attachments/assets/314c7a05-5f2e-47c4-b2e0-a9233a1769e6
> CNV-55088: Scale VNC console

- locales/en/plugin__kubevirt-plugin.json
- src/views/virtualmachines/details/tabs/configuration/scheduling/SchedulingTab.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
Propagate `instanceTypeVM` to Scheduling section and use as source of `dedicatedCpuPlacement` property.
`dedicatedCpuPlacement`  seems the only type of dedicated resource that is currently handled.
> CNV-55050: Read dedicatedCpuPlacement status from InstanceType

- src/utils/components/Consoles/components/vnc-console/vnc-console.scss
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/virtual-machines-overview-tab-details.scss
Toggle `viewOnly` flag and adjust cursor styling.
> CNV-54192: Make VNC Console in the Overview page read only

- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
All three components rely on re-render to fetch new values via getVMMetrics() call. They are simple leaf nodes so there should be no measurable performance impact.
> CNV-54463: Remove memoization from CPU/Memory/Network usage columns

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/StateHandler/StateHandler.tsx
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
On VM change, we wait only for the VM to be fetched. We should also wait for the instancetype spec expansion request
Changing VMs without waiting will make the screen flickering between the previous instance and the other 
**Before**
https://github.com/user-attachments/assets/fa80e07b-923b-4708-b33c-994a44d58886
**After**
https://github.com/user-attachments/assets/a752b893-9d51-4a88-ba03-31f26f4e2b31
> CNV-55107: loading on vm change

- src/utils/components/DiskModal/OtherDiskModal.tsx
- src/utils/components/DiskModal/utils/submit.ts
Editing a disk was triggering hotplug instead of just editing the VM
The 'Other' disk modal was fetching again the PVC but we already have a prop for that. We fetch it on DiskModal component
> CNV-55749: fix editing disk error

- src/utils/components/AlertsCard/utils/utils.tsx
arrange order for just virtualization scope alerts
Before:
After:
> CNV-41922: Alerts are displayed in the wrong order in the Virtualization Overview page

- src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
- src/utils/components/Charts/ChartLabels/SubTitleChartLabel.tsx
- src/utils/components/Charts/ChartLabels/TitleChartLabel.tsx
- src/utils/components/Charts/ChartLabels/styleOverrides.ts
- src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
- src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
- src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
- src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
- src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsTimeAxis.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsChartDonut/MigrationsChartDonut.tsx
- src/views/clusteroverview/OverviewTab/metric-charts-card/components/MetricChart.tsx
- src/views/clusteroverview/OverviewTab/vms-per-resource-card/VMsPerResourceChart.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/components/HealthPopupChart.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx
Chart styles are not overwritten in dark theme. As a workaround use
the same approach as OpenShift Console: configure custom style based
on standard PatternFly CSS variables that are correctly overwritten in
dark theme.
Reference-Url: https://github.com/openshift/console/blob/0ec4d06857e6021c92edab3435794c5869194c82/frontend/public/components/graphs/themes.ts#L7
Reference-Url: https://github.com/openshift/console/blob/0ec4d06857e6021c92edab3435794c5869194c82/frontend/packages/pipelines-plugin/src/components/pipelines/pipeline-metrics/charts/successRatioDonut.tsx#L34
> CNV-55087: Use custom chart styles based on PatternFly CSS variables

- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
Adding paused to list of statuses start should be disabled in.
Before:
After:
> CNV-51525: Remove "Start" button from ICON action list when VM in pause

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
- src/views/virtualmachines/tree/utils/utils.tsx
When switching between vms, persist the tab
During the switch make sure to visualize all the tabs and have the loading inside them.
Previously there were two StateHandler for the loading. As you can see from the demo, there was a loading before displaying the tabs and another loading for the tab content. Now we display the tabs and the loading inside so the switch between vms does not have so much shifts
**Before**
https://github.com/user-attachments/assets/61ff03c4-5974-41af-a05b-6b369de4c674
**After**
https://github.com/user-attachments/assets/afe75262-3184-4fc3-b6db-85ea16e81767
> CNV-55086: persist vm tab on treeview vm switch

- src/views/bootablevolumes/list/components/BootableVolumeAddButton.tsx
This PR fixes a bug where the incorrect YAML template is shown when the user selects Add volume -> From YAML on the Bootable volumes page.
Jira: https://issues.redhat.com/browse/CNV-51198
> CNV-51198: Fix YAML template displayed when clicking "Add volume" -> "By YAML" on the Bootable volumes page

- src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/MigrationsLimitionsPopover.tsx
- src/views/clusteroverview/MigrationsTab/components/MigrationsLimitionsPopover/hooks/useHyperConvergedMigrations.ts
- src/views/clusteroverview/MigrationsTab/hooks/useMigrationCardData.ts
The values shown in the Limitations popover on the Migrations card on the Virtualization Overview page aren't displayed to non-admin users because the values are pulled from a HyperConverged resource to which non-admin users do not have access. This PR hides the link from non-admin users since the popover isn't useful without the values.
Jira: https://issues.redhat.com/browse/CNV-51468
> CNV-51468: Hide migration Limitations link for non-admin users

- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
replacing the condition to create the tree to have loaded data rather than if data is not empty for non admin users
Before:
After:
> CNV-56030: Projects not displayed in tree view for non-admin users

- src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotData.ts
We have this bug as we bumped the kubevirt-api version for this https://issues.redhat.com/browse/CNV-51123
So I just fixed the snapshot and restore version is they are the only one installed in the cluster at this point.
> [release-4.16] CNV-56325: Fix snapshot model version

- cypress/tests/e2e/check-tab-yaml.cy.ts
e2e tests are failing on this part of check tabs  
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/kubevirt-ui_kubevirt-plugin/2443/pull-ci-kubevirt-ui-kubevirt-plugin-main-kubevirt-e2e-aws/1888942441495531520/artifacts/kubevirt-e2e-aws/tests/artifacts/gui-test-screenshots/screenshots/all.cy.ts/2_Check%20all%20virtualization%20pages%20can%20be%20loaded%20--%20Check%20VM%20tabs%20--%20vm%20tabs%20are%20loaded%20(failed).png
> fix check tab e2e tests

- src/utils/components/FirmwareBootloaderModal/utils/utils.ts
- src/views/catalog/CustomizeInstanceType/tabs/configuration/hooks/usePreference.ts
- when `vmPreference` has no `kind` means its a cluster preference so we should not fetch it using the namespace field.
- before the fix here we're returning `bios` boot mode after verifying `uefi` and `uefi secure` . Not that this function have a default boot mode, we have to verify that the VM has bios enabled before returning the default mode 
**Before**
https://github.com/user-attachments/assets/7d9c6fd6-3798-4a44-b9a9-1cc67db5604c
**After**
https://github.com/user-attachments/assets/98a9da32-fdf5-4dd7-af2c-6d38a824f4ae
> CNV-55111: fix get bootmode bios when seelcted

- src/utils/constants/documentation.ts
- src/views/clusteroverview/TopConsumersTab/utils/NoDataAvailableMessage.tsx
- src/views/clusteroverview/TopConsumersTab/utils/constants.ts
- src/views/templates/list/components/VirtualMachineTemplateSupport/VirtualMachineTemplateSupport.tsx
- src/views/templates/utils/constants.ts
1. migrate all links from docs.openshift.com to docs.redhat.com
2. update all RH docs to latest (tested with 4.17)
3. remove language part from the links(switch to default language)
4. fix broken documentation links
5. consolidate documentation links in one file
> CNV-56364: Update documentation links to 4.17

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx
Reverts kubevirt-ui/kubevirt-plugin#2466 as per introduces a new bug: https://issues.redhat.com/browse/CNV-54461
> Revert "[release-4.18] CNV-54461: [RFE] Add link to VM status on VM list page"

- src/utils/components/GuidedTour/utils/constants.tsx
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
The state handling on top of the VM Configuration Tab component was in a infinite loading
AND 
the gouded tour was using the all-namespaces URL 
I changed the VM URL link removing /all-namespaces/ and use /ns/default (the tour VM has default namespace)
**Before**
https://github.com/user-attachments/assets/5647669b-0d5b-4efa-95fc-516fbb743774
**Fix**
https://github.com/user-attachments/assets/762f4f3f-9bf2-40d5-9b2f-908a051870a1
> CNV-56219: fix guided tour

- src/utils/components/SSHAccess/SSHAccess.tsx
- src/utils/components/SSHAccess/components/SSHCommand.tsx
- src/utils/components/SSHAccess/constants.ts
- src/utils/components/SSHAccess/utils.ts
- src/views/virtualmachines/details/tabs/configuration/ssh/SSHTab.tsx
- src/views/virtualmachines/details/tabs/configuration/ssh/components/SSHTabSSHAccess.tsx
- src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
Replacing load balancer service selector according to: https://issues.redhat.com/browse/CNV-55889 
Before:
After:
> CNV-55889: SSH over LoadBalancer creates Service with incorrect selector

- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/components/utils.ts
- src/views/virtualmachines/actions/components/VirtualMachineMigration/utils.ts
Do not let the user migrate non-migratable volumes.
Migratable volume: Not shared disk and PVC with RWX accessMode
In the demo below, the disk `disk-teal-stingray-79` is connected to a PVC that do not have accessMode RWX but only RWO
**Before**
**After**
> CNV-56226: migrate only migratable disks

- src/views/virtualmachines/actions/components/ConfirmVMActionModal/ConfirmVMActionModal.tsx
This PR fixes a bug where the VM action confirmation modal would remain open after clicking the confirmation button.
Jira: https://issues.redhat.com/browse/CNV-57476
[fix-confirm-vm-actions--2025-03-05 20-55.webm](https://github.com/user-attachments/assets/294df094-ce70-4b84-b483-8f8d9868ef3e)
> CNV-57476: Fix VM action confirmation modal not closing on confirmation

- package.json
- yarn.lock
Library dompurify is an indirect dependency of @patternfly/quickstarts. The updated version matches the requested pattern ^2.2.6. Accidental downgrade is prevented by enforcing the minimum version with the 'resolutions` section.
none
> [release-4.12] CNV-50618: Update dompurify from 2.3.10 to 2.5.8

- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
- src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
- src/utils/components/Consoles/components/vnc-console/utils/util.ts
1. iterate on code points to avoid splitting surrogate pairs
2. handle new line, tab and Latin-1 set
a) detect new line as LF/NL char and map to XK_KP_Enter keysym
b) map tab char to XK_Tab
c) map Latin-1 directly to keysym
3. fix handling capital letters (limited to ASCII) 
4. replace new line marker used for login and password from CR(code 13)
to LF/NL(code 10)
Reference-Url: https://github.com/novnc/noVNC/blob/b45f35c6d7b06c1d8641ceb8e7f5ee00c23484eb/core/input/keysym.js#L221
Reference-Url: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt#looping_with_codepointat
Reference-Url: https://en.wikipedia.org/wiki/ISO/IEC_8859-1
https://github.com/user-attachments/assets/5369b6cd-08ff-4f17-ac14-3d319d897bd4 …
> CNV-52511: Keep formatting in VNC paste action

- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
PR ensures that pressing `Enter` key in the VM creation form correctly triggers the Quick Create VirtualMachine action (which is expected by users) instead of causing an unintended full-page reload (default browser behavior). 
- Added a form submit handler (onSubmitForm) to prevent default submission behavior and trigger `onQuickCreate`.
- Removed `onClick={onQuickCreate}` from the Quick Create VirtualMachine button since form submission now handles it, and `button[type=submit]` automatically submits the form when clicked (so no need for an onClick handler).
- Remove `e: MouseEvent` from onQuickCreate parameters, as default browser behavior is already prevented on the form submission (`e.preventDefault()`)
Current behavior upon pressing `Enter` key. …
> Fix Form Submission Behavior for Virtual Machine Creation

- README.md
- package.json
- plugin-metadata.ts
- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
- tsconfig.json
- bump output JS build target to ES 2021
- simplify TS config `lib` compiler option to include all ES 2021 APIs and all DOM APIs
- modify plugin metadata `version` to `4.19.0`
- modify `@console/pluginAPI` (lowest compatible Console version) to `~4.19.0` meaning `>=4.19.0 <4.20.0`
- modify `version` in `package.json` to `0.0.0` since this package is marked as private
- refer to `OC_PLUGIN_I18N_NAMESPACES` in README for consistency
- fix `@patternfly/react-icons` import to avoid webpack build warning
```
<w> Non-index and non-dynamic module import @patternfly/react-icons/dist/esm/icons/times-icon
```
Console 4.19 supported browsers should all work with ES 2021 (see [Sam's comment](https://github.com/openshift/console/pull/14620#discussion_r1884067061)).
> CNV-57788: Update @console/pluginAPI dependency and other small improvements

- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
Fix of a bug where selected VMs state was not updated if a selected VM was deleted.
Before:
https://github.com/user-attachments/assets/beb6b053-16a3-4ada-9ffc-22c855988d42
After:
https://github.com/user-attachments/assets/4c5e289a-f9af-48b1-83aa-57ea6927dc12
> CNV-57968: fix selected VMs state after delete

- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu.tsx
- src/views/virtualmachines/tree/hooks/useTreeViewItemRightClick.ts
- src/views/virtualmachines/tree/utils/utils.tsx
On hiding and expanding elements, the elements are destroyed and re-created by react so we have to add listeners to the re-created elements on `onExpand` event
Additionally do some logic to add and remove listeners on multiple `useLayoutEffect` runs over time 
**Before**
https://github.com/user-attachments/assets/aa76133d-bd3f-43af-860e-24d691335c3a
**After**
https://github.com/user-attachments/assets/0b9c0678-16f3-453b-bb20-bba890ed0d07
> CNV-55963: Fix right click on expanded elements

- src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
- src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityConditionSelect.tsx
- src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityTypeSelect.tsx
- src/utils/components/AffinityModal/components/AffinityList/components/AffinityRowActionsDropdown.tsx
- src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
- src/utils/components/DurationOption/DurationDropdown.tsx
- src/utils/components/FilterSelect/InlineFilterSelect.tsx
- src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
- src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/checkups/network/components/CheckupsNetworkActions.tsx
- src/views/checkups/storage/components/CheckupsStorageActions.tsx
- src/views/datasources/actions/DataSourceActions.tsx
- src/views/migrationpolicies/components/MigrationPolicyConfigurations/compnents/MigrationPolicyConfigurationDropdown/MigrationPolicyConfigurationDropdown.tsx
- src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
- src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRowActions.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshotsRow.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
Fixes a bug when DurationDropdown couldn't be closed on clicking outside the menu or pressing escape.
Also refactors `(open: boolean) => setIsOpen(open)` to `setIsOpen` in other Dropdowns and Selects
After fix:
https://github.com/user-attachments/assets/3b0dd5cc-55dd-432d-9b3c-25edcccc05f7
> CNV-57425: DurationDropdown closes on clicking outside or pressing Escape

- plugin-metadata.ts
This is a follow-up to #2504 
Kubevirt plugin version N supports Console versions from N-2 to N+2.
This PR updates `@console/pluginAPI` dependency to semver range `>=4.17.0-0` which means 4.17.0 and up, including any pre-release versions.
Quote from the Console [dynamic plugins README](https://github.com/openshift/console/blob/main/frontend/packages/console-dynamic-plugin-sdk/README.md):
> The `@console/pluginAPI` dependency is optional and refers to Console versions this dynamic plugin is compatible with. The `dependencies` object may also refer to other dynamic plugins that are required for this plugin to work correctly. For dependencies where the version string may include a [semver pre-release](https://semver.org/#spec-item-9) identifier, adapt your semver range constraint (dependency …
> CNV-57788: Update @console/pluginAPI dependency for Console 4.17.0+

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/CloneVMModal/CloneVMModal.tsx
- src/utils/components/CloneVMModal/utils/helpers.tsx
- src/utils/components/Consoles/Consoles.tsx
- src/utils/components/Consoles/utils/utils.ts
- src/utils/components/DiskModal/utils/form.ts
- src/utils/components/HardwareDevices/HardwareDevicesHeadlessMode.tsx
- src/utils/components/HardwareDevices/modal/HardwareDevicesHeadlessModeModal.tsx
- src/utils/components/HeadlessMode/HeadlessMode.tsx
- src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
- src/utils/components/InstanceTypeModal/StandaloneInstanceTypeModal.tsx
- src/utils/components/InstanceTypeModal/utils/types.ts
- src/utils/components/InstanceTypeModal/utils/util.ts
- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/instancetype/constants.ts
- src/utils/resources/instancetype/helper.ts
- src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
- src/utils/resources/vm/utils/instanceTypes.ts
- src/utils/resources/vm/utils/selectors.ts
- src/utils/utils/typeGuards.ts
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
- src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
- src/views/virtualmachines/details/tabs/configuration/details/utils/utils.ts
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
Before the fix, VirtualMachineNavPageTitle used the result of
expand-spec instead of a raw VM object. The approach failed
in scenarios where:
1. isInstanceTypeVM() was used as this information is by design
erased by the backend.
2. the VM was sent to the backend - as expanded VM is considered a new
VM (with references to old VM removed)
The main section distinguished both objects and passed them separately
as 'instanceTypeExpandedSpec' and 'vm' (both of type V1VirtualMachine).
After the fix the raw VM object will be used by default in
VirtualMachineNavPageTitle and the expanded VM will be passed as
'instanceTypeExpandedSpec'.
Key points:
1. hasOwnProperty() checks used for 'autoattachGraphicsDevice' were
refactored to use isHeadlessMode() helper
3. created an independent version of …
> CNV-49608:  Default to raw VM in VirtualMachineNavPageTitle

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ExportModal/ExportModal.tsx
- src/utils/components/SSHSecretModal/SSHSecretModal.tsx
- src/utils/components/SSHSecretModal/components/SSHKeyUpload/SSHKeyUpload.tsx
- src/utils/components/SSHSecretModal/utils/utils.ts
- src/utils/components/VMSSHSecretModal/VMSSHSecretModal.tsx
- src/utils/resources/secret/utils.ts
- src/utils/resources/secret/utils/selectors.ts
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/AuthorizedSSHKey.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/useTemplateSecrets.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/utils/types.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useTemplateSecrets/utils/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
- src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
- src/views/catalog/utils/useWizardVMCreate.ts
- src/views/catalog/wizard/components/WizardFooter.tsx
- src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
- src/views/catalog/wizard/tabs/scripts/hooks/useTemplateWizardSecrets.ts
- src/views/clusteroverview/SettingsTab/UserTab/components/ManageSSHKeySection/SSHAuthKeysList/components/SSHAuthKeyRow/SSHAuthKeyRow.tsx
- src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
- src/views/templates/details/tabs/scripts/components/SSHKey/sshkey-utils.ts
This PR fixes a bug that occurs when a default SSH Secret is configured for a namespace and a separate SSH Secret is configured on a template within that namespace.
Reproduction steps:
1. Configure a Secret named "auto-test-secret" as the default Secret for the namespace in the User settings section
2. Clone a Template and add a Secret named "auto-test-secret1" to the Template
3. Create a VM from this Template
4. Create a VM from this Template again
Jira: https://issues.redhat.com/browse/CNV-50292
[fix-template-ssh-secret-conflict--2025-03-24 10-59.webm](https://github.com/user-attachments/assets/27e25061-c91c-49fd-a3e3-e810acf1cf23)
> CNV-50292: Fix conflict caused by separate namespace and template SSH secrets

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionCustomUrl/AutomaticSubscriptionCustomUrl.tsx
Before, typing custom URL resulted in update operation for each typed character. Subsequent updates must include the whole resource. Each update changes the resource revision. If user types too quickly the updates were fired with previous revision and rejected by the server optimistic locking check.
After this PR:
1. the update method was changed to k8sPatch which allows overwriting the current resource (without providing revision)
2. debounce period was extended from 500ms to 1 second
3. server state is used for initialization only
4. error handling was added using inline error alert with the last error
> CNV-58163: Update custom URL with k9sPatch

- src/utils/hooks/useFeatures/useFeatures.ts
The Console uses resource object in k8sPatch for:
1. early return in case when no patches were provided - it's border condition not very useful in our scenarios (response ignored anyway). It's also questionable if the provided resource should be returned as-it-is. Most likely it's invalid/incomplete/outdated and should be re-fetched.
2. as a placeholder for name and namespace - this usage could be replaced with optional parameters "name" and "ns" - however the resource is the only source of truth here
The requirement to provide the complete resource has the side effect that the callbacks/memos need to be re-created with every resource modification. This PR substitutes the resource with a stub which results in stable references and prevents re-renders.
Reference-Url: …
> Provide stable reference for toggleFeature

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/utils/components/InstanceTypeModal/InstanceTypeModal.tsx
- src/utils/components/InstanceTypeModal/utils/types.ts
- src/utils/components/InstanceTypeModal/utils/util.ts
- src/utils/resources/instancetype/selectors.ts
- src/utils/resources/instancetype/types.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/utils/types.ts
Extend safeguards and consolidate existing types.
The crash while editing custom InstanceType should be already prevented with #2503     
For non-Red Hat InstanceType and/or instance type not following the naming convention there will be no initial selection (see the screenshot below).
Editing  a VM based on custom InstanceType `foointancetype`
> CNV-58306: Use stricter typing for InstanceTypeModal

- src/utils/components/CloneVMModal/utils/helpers.tsx
- src/utils/models/index.ts
- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabSnapshots/component/SnapshotDeleteModal.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/modal/RestoreModal.tsx
- src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotModal.tsx
- src/views/virtualmachines/details/tabs/snapshots/hooks/useSnapshotData.ts
- src/views/virtualmachines/details/tabs/snapshots/utils/helpers.ts
Upgrading on 4.16 the kubevirt-api led to using a v1beta1 version for snapshot and restore that do not match with what we should use on 4.16 clusters. 
https://github.com/user-attachments/assets/fb77bbc4-ed36-4fc0-8bb5-891c65591f78
> [release-4.16] CNV-56674: use v1alpha1 snapshot and restore on 4.16 plugin

- src/utils/resources/vm/utils/disk/rowData.ts
Use PVC size first because if we catch the PVC, its the more reliable way to know the disk size.
If the PVC do not exist because we are in the wizard or something with that, fetch it from the dv.
DV size its true only in the creation process. IF the PVC disk changes, its not correct anymore
> CNV-55748: fix pvc size on disk table

- src/utils/hooks/useHyperConvergeConfiguration.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/TemplatesAndImagesManagement/components/AutomaticImagesDownload/AutomaticImagesDownload.tsx
- enable switch even when the feature is not set in the configuration. before this change, the switch was enabled only when the featuregate was manually set true or false
- use the `spec.enableCommonBootImageImport` field as `spec.featureGates.enableCommonBootImageImport` is deprecated
> CNV-58333: Enable automatic image

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineBulkActionButton.tsx
- src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
- src/views/virtualmachines/list/hooks/useExistingSelectedVMs.ts
Actually fixes https://issues.redhat.com/browse/CNV-57968. Guohua found out that the state of selected VMs does not reflect changes to the VMs list from CLI. 
I kept the previous fix https://github.com/kubevirt-ui/kubevirt-plugin/pull/2515 (which was only fixing deletion from UI) so we don't keep unnecessary deleted VMs inside `selectedVMs` signal.
Before:
https://github.com/user-attachments/assets/97fdfd6f-12c5-4a2b-b90f-22405154b142
After:
https://github.com/user-attachments/assets/3d2d583a-fbff-46b0-84de-850a7961aea4
> CNV-57968: fix selected VMs state after deletion from CLI

- src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
Stop propagation. When user right clicks on folder, it propagate in all namespace VMs as the right click event propagate to the higher hierarchy element in the treeview
> CNV-58601: right click treeview stop propagation

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/AutomaticSubscriptionRHELGuests.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionCustomUrl/AutomaticSubscriptionCustomUrl.tsx
Hides previously disabled checkbox when "Enable predictive analytics" option is selected
Not sure whether to add some bottom margin, or is it ok like this?
Before:
https://github.com/user-attachments/assets/260666df-b4d6-4121-9b62-09364f481616
After:
https://github.com/user-attachments/assets/c7a98d59-1e8d-4746-bb36-16a88d1d020a
> CNV-58162: hide checkbox from "Enable predictive analytics"

- src/utils/styles/cursor.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
Doesn't disable switch while waiting for the option to change.
I am not sure if this fix doesn't break something, and whether it should rather stay disabled while loading. We could make it disabled, but not apply the disabled styles.
Before:
https://github.com/user-attachments/assets/8ff4d98d-ca36-40d0-b3b6-9b37d9ef492c
After:
https://github.com/user-attachments/assets/edac3da3-e58f-49dc-ba97-2f855b7e6c76
> CNV-58425: don't disable switch on click

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ListPageFilter/ListPageFilter.tsx
- src/utils/components/ListPageFilter/RowFilters.tsx
- src/utils/hooks/useContainerWidth.ts
- src/utils/styles/list-managment-group.scss
- src/views/virtualmachines/list/VirtualMachinesList.scss
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineEmptyState/VirtualMachineEmptyState.tsx
- src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
- src/views/virtualmachines/list/components/VirtualMachineSelection/virtual-machine-selection.scss
- src/views/virtualmachines/list/listManagementGroupSize.ts
- src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
- src/views/virtualmachines/tree/VirtualMachineTreeView.scss
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
Updates VirtualMachines page UI according to [this doc](https://docs.google.com/document/d/1ZSfyxDfPxRuRNWggAKJ504wLe_t45MAd85jtsdZ34xw/edit?tab=t.0#heading=h.d7oxg5i37fkv).
Before:
After:
> CNV-56949: tree view UI changes

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/utils/constants.ts
- src/utils/resources/instancetype/types.ts
The type was skipped in the mapper. Once stricter typing was added in #2535 this was explicitly captured with `Exclude<InstanceTypeSeries, 'rt1'>` .
> CNV-59276: Recognize RT series predefined instance type as Red Hat provided

- src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
- src/views/virtualmachines/list/components/VirtualMachineUsageItem/VirtualMachineUsageItem.scss
- src/views/virtualmachines/list/components/VirtualMachineUsageItem/VirtualMachineUsageItem.tsx
- src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
- src/views/virtualmachines/list/utils/processVMTotalsMetrics.ts
- src/views/virtualmachines/list/utils/totalsQueries.ts
Adds summary of CPU, Memory and Storage usage for the current namespace.
- also fixes a bug in Overview -> StorageUtil panel, which was counting too much storage because of duplicate mount points - it would get a sum of these:
**Question:**
For memory capacity I used a sum of rounded values for each VM, not an actual metric. For storage capacity however, I did use the metric value.
I based this on the Utilization board in VM details:
Should I rather use a rounded value for storage too? Or the metric for memory?
Before:
After:
https://github.com/user-attachments/assets/d7cdf7c5-0ca3-426a-b3a8-39cb4a329e5f
> CNV-56841: show VirtualMachine utilization summary

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.scss
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
Changes:
1. modifier "fitContent" to narrow down the favourites column. This change fixes problems with custom CSS incorrectly styling name column when the favourite column was hidden (#1653).
2. flex layout with columnGap and alignItems props. This fixes incorrect alignment of text wrapped in components (#2497).
3. setting isFavourite flag based on column ID. Before the sort was determined only on the column index which resulted in incorrect sort if the favourite column was hidden (#1637).
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/1653
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2497
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/1637
> CNV-58240: Use built-in styling for BootableVolume table

- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
- src/views/virtualmachines/tree/components/TreeViewToolbar.tsx
- src/views/virtualmachines/tree/hooks/useTreeViewData.ts
**Current status**
When the user have no personal namespace but only system namespaces, the switch will not be clickable
When the user have personal namespaces, it will be available and it will show in the treeview, projects that do not have vms .
**Change**:
When the user have no personal namespace and the switch cannot be enabled, just hide it
**Example without switch**
> CNV-59236: hide project switch in treeview

- src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect/NetworkInterfaceNetworkSelect.tsx
- src/utils/components/NetworkInterfaceModal/utils/helpers.ts
Fixed use cases:
1. editing NADs from the same namespace as the VM - when retrieved from network.multus.networkName they are not prefixed with namespace
2. adding NADs from global namespace other then "default" - currently it's openshift-multus and openshift-sriov-network-operator
3. filtering out already used NADs from the same namespace as the VM
Reference-Url: https://github.com/kubevirt-ui/kubevirt-api/blob/ee8a84b48b35930556b0df632909563fa2021b61/kubevirt/models/V1MultusNetwork.ts#L29
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/blob/c1bb89119db643b35379b33fca47091fcde107a8/src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts#L10
https://github.com/user-attachments/assets/9d52da54-218d-4f5c-a626-0bb56330546c …
> CNV-56712: Fix network namespace handling in NetworkInterfaceNetworkSelect

- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Fixes a bug I accidentally introduced in [this PR](https://github.com/kubevirt-ui/kubevirt-plugin/pull/2565/files).
`initialOptions` could have been undefined (coming from `folderOptions` in FolderSelect.tsx), causing an infinite loop in the useEffect in SelectTypeahead - therefore the input component was constantly reloading so it seemed like it was disabled.
> CNV-60407: folder input fix

- src/utils/utils/constants.ts
- src/views/virtualmachines/actions/components/VirtualMachineMigration/hooks/useMigratableStorageClasses.ts
- src/views/virtualmachines/actions/components/VirtualMachineMigration/tabs/VirtualMachineMigrationDestinationTab.tsx
Disable storageclasses that do not support RWX. RWX is mandatory for the migration to succeed
> CNV-59218: disable non migratable storageclasses

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineSelection/VirtualMachineSelection.tsx
- fixes a bug where Actions button and pagination disappears if VMs are moved to some folder and then are moved back to project root
--> just do not hide it in any case, even if there are no VMs shown it doesn't make sense to hide the items from the layout
- also fixes a bug where BulkSelect was checked if no VMs are shown
Before:
After:
> CNV-60409: don't hide Actions button and pagination in VM list

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/CapacityInput/CapacityInput.tsx
- src/utils/components/CapacityInput/utils.ts
- src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
- src/utils/components/DiskModal/components/DiskSizeInput/usePVCDefaultSize.ts
- fixes a bug, where clicking ` + ` in the Number input resulted in resetting the number to the initial value ([CNV-59559](https://issues.redhat.com//browse/CNV-59559))
- it was because strings were compared instead of numbers
- another bug which is fixed was that user can't manually type in a smaller number ([CNV-59558](https://issues.redhat.com/browse/CNV-59558)) e.g. if the capacity is 4 GiB and you wanna set it to 12 GiB, when you type in "1" it results in the reset back to 4 GiB
- also you couldn't change the unit to e.g. MiB, you have to write a bigger value first and then change it to MiB (e.g. if you wanna move from 4 GiB to 5.5 GiB you have to use MiB, because it doesn't support decimal values)
- there is a bug that the size of a created disk is larger than what was specified in …
> CNV-59558: CNV-59559: fix disk modal CapacityInput

- src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/QuickStartsSection.tsx
- src/views/clusteroverview/OverviewTab/getting-started-card/quick-starts-section/utils.ts
This PR fixes a bug where the Quick Starts section of the Getting Started card disappears after completing the "Create a virtual machine from a volume" QuickStart. The card disappeared because that's the only QuickStart and QuickStarts were being hidden once completed.
To fix the problem I changed the behavior to show completed QuickStarts at the bottom of the list.
Jira: https://issues.redhat.com/browse/CNV-57378
[quick-starts-bug--BEFORE--2025-04-23 10-32.webm](https://github.com/user-attachments/assets/9c7f695e-4abd-4166-941d-91fadf6b1aa6)
[quick-starts-bug--AFTER--2025-04-23 10-26.webm](https://github.com/user-attachments/assets/0bceeead-07c0-46e7-9733-1eef3f583876)
> CNV-57378: Show completed QuickStarts in Getting Started card

- src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
If no kubevirtUserSettings value exists for a specific column ID all columns are displayed. This PR changes that behavior to only show the default columns. 
Jira: https://issues.redhat.com/browse/CNV-60543
> CNV-60543: Only show default columns if no kubevirtUserSettings values exist

- src/views/checkups/network/details/tabs/details/CheckupsNetworkDetailsPageSection.tsx
This PR fixes a bug where the maximum latency field was reporting the minimum latency.
Jira: https://issues.redhat.com/browse/CNV-57314
> CNV-57314: Display correct max latency value on network checkup page

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
Fix rerendering of VM details page
1. missing use memo over pages - as every props change create new array and new array did unmount and mount.
2. useParams act strange - it keep creating new object with each prop change even if params didn't changed - created a workaround to only change params if its really changed value. 
> CNV-60605: Fix rerendering all over vm details

- src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
This PR fixes a bug that caused an error to be displayed when adding a new SSH Secret to a Template by file upload.
Jira: https://issues.redhat.com/browse/CNV-60945
[ssh-secret-file-upload-bug--BEFORE--2025-05-01 11-10.webm](https://github.com/user-attachments/assets/03d4ac69-ea4c-4292-9a3d-66ab0a99a14f)
[ssh-secret-file-upload-bug--AFTER--2025-05-01 11-08.webm](https://github.com/user-attachments/assets/b7b46ef0-17b0-4bb1-9ce4-1aef5c4ce44c)
> CNV-60945: Fix add new SSH key by file upload for Templates

- src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
- src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
- src/utils/components/Charts/utils/utils.ts
The change applied to memory and storage charts in VM details.
Calculate the number of digits that should be displayed after decimal point based on a static list of threshold values.
The general rule is to keep the displayed number at 3 ciphers or less. Threshold list:
1. x < 1 GiB :  0
2. 1 GiB <= x < 10 GiB : 2
3. 10 GiB <= x < 100 GiB : 1
4. 100 GiB <= x < 1 TiB : 0
5. 1 TiB <= x < 10 TiB : 2
6. 10 TiB <= x < 100 TiB : 1
7. 100 TiB <= x < 1 PiB :  0
8. x > 1 PiB : 2
> CNV-56585: Change format for Y axis tick based on max value

- src/utils/components/CPUMemoryModal/components/CPUInput/components/CPUTopologyInput/components/TotalCPUHelperText/CPUTopologyHelperText.tsx
- src/utils/components/CPUMemoryModal/components/CPUInput/utils/utils.ts
- src/utils/resources/template/utils/flavor.ts
Jira: https://issues.redhat.com/browse/CNV-56688
> CNV-56688: Avoid CPU helper text error if CPU threads is undefined

- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.scss
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
1. rely on component level styling (FlexLayout)
2. separate remaining styling from template list to avoid future
regressions
3. use compact label styling for all state labels
> CNV-59955: Fix alignment of state labels in the bootable volume list

- src/utils/resources/vmim/selectors.ts
- src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
This PR fixes a bug that caused the source and target nodes for multiple migrations of the same VMI as those of the last migration.
Jira: https://issues.redhat.com/browse/CNV-58790
> CNV-58790: VMI migration source and target node reported incorrectly on Migrations tab

- src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
- src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
- src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
In case of loading error the useK8sWatchResource hook returns the previous value. For temporary errors this may be beneficial but unfortunately the same happens for a permanent shutdown.
Disabling the fetch:
1. fixes problems with stale VMI resource in the UI
2. prevents unnecessary fetch requests (resulting in 404 error)
https://github.com/user-attachments/assets/54bb7557-19c9-49d9-b8aa-6b50fdc7ec3c
https://github.com/user-attachments/assets/cebc7103-360d-40d9-b17c-0d8372dcd220
> CNV-52010: Fetch VMI resource only for running VMs

- src/utils/hooks/useHyperConvergeConfiguration.ts
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/utils/utils.ts
Use the same approach as for the persistentReservation feature.
https://github.com/kubevirt-ui/kubevirt-plugin/blob/b5f0400f4e921b5facf3ac399150b35fbd0ba4e9/src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx#L43
https://github.com/user-attachments/assets/599e7e51-f4e3-4b5d-8802-c562b538a33a
https://github.com/user-attachments/assets/45a5c7ac-a17c-4066-a2b7-ff84840fcbd8
> CNV-61191: Toggle autoResourceLimits feature by replacing only the flag value

- src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
- src/utils/components/PendingChanges/utils/helpers.ts
- src/utils/resources/preference/helper.ts
- src/views/virtualmachines/details/tabs/configuration/details/components/DetailsSectionBoot.tsx
Fixed issues:
1. UEFI mode used as default boot mode in the customization details. Fixed by strict check in getPreferredBootmode()
2. BIOS mode used as default mode (regardless of preference) in the edit modal. Fixed by passing the preferred boot mode (already available).
3. pending changes warning displayed after creating a VM with preference that includes boot mode. Fixed by detecting that no override was provided in the VM resource.
Additionally, the preference resolving policy was changed. Before, the default was VirtualMachinePreference (if cluster preference was not matched). After this PR, the default is VirtualMachineClusterPreference. The reason for this change: some of the data source volumes are not providing the instancetype.kubevirt.io/default-preference-kind label which …
> CNV-61190: Use default boot mode from the preference

- src/utils/resources/vmim/selectors.ts
- src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx
This PR fixes a bug that caused the source and target nodes for multiple migrations of the same VMI as those of the last migration.
Jira: https://issues.redhat.com/browse/CNV-58790
> [release-4.18] CNV-58790: VMI migration source and target nodes reported incorrectly on Migrations tab

- src/views/virtualmachines/list/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
Looks like the `textMaxWidth="6ch"` was intentional, if we remove it, the labels can go over multiple lines, I think it is ok like this, but let me know what do you think @avivtur as you did this change.
Before
After
> CNV-60994: condition labels remove width limit

- cypress/support/commands.ts
- cypress/tests/downstream/vm-tab.cy.ts
- cypress/tests/downstream/vm-tabs/network.cy.ts
- cypress/tests/e2e/a-setup.cy.ts
- cypress/views/tab.ts
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
The test cannot pass in upstream, so add a new folder 'downstream' for this test.
test interface link state, it pass locally:
Running:  tab.cy.ts                                                                       (1 of 1)
Set network down/up
Logging in as kubeadmin
✓ navigate to network tab (143239ms)
✓ set network link down (8313ms)
✓ set network link up
> CNV-55855: test interface link state

- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/utils/utils.ts
This PR changes the conditions filtering criteria to include showing the "LiveMigratable=True" condition label in the VirtualMachines list. It manually excludes the "LiveMigratable=False" condition to avoid it being displayed if the `reason` field for that condition exists.
Jira: https://issues.redhat.com/browse/CNV-58916
> CNV-58916: Show LiveMigratable=True label in VMs list

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/ColumnManagementModal/ColumnManagementModal.tsx
- src/utils/components/ColumnManagementModal/constants.ts
- src/utils/components/ColumnManagementModal/utils.ts
Shows correct max number of columns to select in `ColumnManagementModal`. 
Adjusts the number based on number of "empty" columns, like the three-dots action button (and checkbox in case of VMs table).
> CNV-59121: show correct max number of columns to select

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GeneralSettings/SSHConfiguration/SSHConfiguration.tsx
This PR moves the node address text input under the "SSH over NodePort service" heading on the settings page.
Jira: https://issues.redhat.com/browse/CNV-58160
> CNV-58160: Move text input under the "SSH over NodePort service" heading on the settings page

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/MoveVMToFolderModal/MoveBulkVMsToFolderModal.tsx
- src/utils/components/MoveVMToFolderModal/MoveVMToFolderModal.tsx
- src/utils/components/MoveVMToFolderModal/hooks/useRemoveFolderQuery.ts
- src/utils/hooks/useVMsInNamespace.ts
- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/utils.ts
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineBulkActionButton.tsx
- src/views/virtualmachines/tree/hooks/dragndrop.ts
- src/views/virtualmachines/tree/hooks/useTreeViewItemActions.ts
- src/views/virtualmachines/tree/hooks/utils.ts
- Removes folder filter after VMs are moved out of folder
- disables the "Move to folder" option if VMs to move are in different namespaces
After:
https://github.com/user-attachments/assets/8295c181-e4c6-4b52-a2da-7dab8f478803
https://github.com/user-attachments/assets/7d8689e9-75b6-4486-a505-70bb3780e0bd
> CNV-60417: remove folder filter after VMs are moved out of folder

- i18n-scripts/dummy-locale.js
- package.json
Port dummy-locale script developed for VM Portal. The script reads English translations and generates test messages by adding special chars as prefix/suffix. By default Spanish and French locales are replaced.
Usage: yarn i18n-dummy-locale
Reference-Url: https://github.com/oVirt/ovirt-web-ui/blob/dfe0c4b8c92638f6e41b9fe0b09e0d07509618ae/scripts/intl/dummy-locale.js
https://github.com/user-attachments/assets/e8fdb197-f34c-4d05-898d-12d133df42ac
> Add script for creating test translations

- src/utils/resources/bootableresources/selectors.ts
- src/utils/resources/vm/hooks/disk/useDisksSources.ts
- src/utils/resources/vm/hooks/disk/useDisksTableData.ts
- src/utils/resources/vm/hooks/disk/utils.ts
- src/utils/resources/vm/utils/disk/constants.ts
- src/utils/resources/vm/utils/disk/rowData.ts
This PR addresses a bug where the disk size is reported incorrectly for VMs created from instance types whose bootable volume uses filesystem-based storage.
Jira: https://issues.redhat.com/browse/CNV-57330
> CNV-57330: Display disk size from DataVolume over PVC for VM disks list

- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
After VM deletion, the redirection back to VM list doesn't occur. Also when deleting from the main VM list itself, the filter is not removed anymore.
After:
https://github.com/user-attachments/assets/a6646418-0d53-4954-a9f5-c2057cc88114
> CNV-61532: fix clearing search results

- src/views/virtualmachines/list/VirtualMachinesList.tsx
- Fixes filtering with advanced search fields, such as `projects` and `description` in case a proxy pod is used.
TODO (in a followup):
Extend `filterOptions` variable passed to `useKubevirtWatchResource` by advanced search fields.
```
{
labels: 'metadata.labels',
name: 'metadata.name',
'rowFilter-instanceType': 'spec.instancetype.name',
'rowFilter-live-migratable': 'status.conditions',
'rowFilter-os': 'spec.template.metadata.annotations.vm\\.kubevirt\\.io/os',
'rowFilter-status': 'status.printableStatus',
'rowFilter-template': 'metadata.labels.vm\\.kubevirt\\.io/template',
}
```
> CNV-61395: fix advanced search when isProxyPodAlive

- src/utils/resources/bootableresources/selectors.ts
- src/utils/resources/vm/utils/disk/constants.ts
- src/utils/resources/vm/utils/disk/rowData.ts
- src/views/virtualmachines/details/tabs/configuration/storage/components/tables/disk/DiskRow.tsx
This PR fixes a bug where the disk size shown in the VM disks list didn't match the actual capacity of the PVC linked in the source column. It does this by:
1. Reporting the actual capacity of the PVC instead of the requested capacity
2. Linking to the DataVolume instead of the PVC if one exists (Per [CNV-57330](https://issues.redhat.com/browse/CNV-57330)) 
Jira: https://issues.redhat.com/browse/CNV-57942
> CNV-57942: Show actual storage capacity in VM disks list

- src/utils/components/DurationOption/DurationDropdown.tsx
- src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx
- src/utils/components/SelectTypeahead/SelectTypeahead.tsx
Adds `isScrollable` to Select components that have a variable length of options, or too many options + don't close select typeahead text input on clicking it
Before:
https://github.com/user-attachments/assets/b671d10c-d9e7-44f5-b52a-52573f7b8ec1
After:
https://github.com/user-attachments/assets/bcc9d0b6-84a4-412e-b312-a4451bea9d60
> [release-4.18] CNV-62082: make Selects scrollable

- src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/HTTPSource.tsx
- src/utils/components/AddBootableVolumeModal/utils/constants.ts
- src/utils/components/AddBootableVolumeModal/utils/utils.ts
This adds the option to create a new DataSource from a URL to the bootable volumes modal.
Jira: https://issues.redhat.com/browse/CNV-46434
[create-bootable-volume-http--AFTER--2025-05-20 07-09.webm](https://github.com/user-attachments/assets/0e200c5e-e7ab-4072-ada9-9337d3605bd5)
> CNV-46434: Add HTTP DataSource option to the bootable volumes modal

- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
[CNV-62160](https://issues.redhat.com//browse/CNV-62160): disabling right click project menu actions when project is empty
before: 
after:
> CNV-62160: disabling right click project menu actions when project is empty

- src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
This PR fixes a bug wherein bootable volumes created from a URL disappeared from the list during the import phase.
Jira: https://issues.redhat.com/browse/CNV-62204
Catalog page
[http-volumes-disappear-temporarily--catalog--BEFORE--2025-05-21 09-31.webm](https://github.com/user-attachments/assets/3f2bc54f-e97e-4cbc-8504-0ab9526f8702)
Bootable volumes list page
[http-volumes-disappear-temporarily--bv-list--BEFORE--2025-05-21 09-33.webm](https://github.com/user-attachments/assets/2019d787-07f1-4068-8957-420d72f7519d)
Catalog page
[http-volumes-disappear-temporarily--catalog--AFTER--2025-05-21 09-20.webm](https://github.com/user-attachments/assets/4da7c876-2fc6-4ea7-b5d0-40f7bdc7ab55)
Bootable volumes list page
[http-volumes-disappear-temporarily--bv-list--AFTER--2025-05-21 …
> CNV-62204: Stop HTTP-created bootable volumes from disappearing temporarily during import

- src/views/dashboard-extensions/Inventory.tsx
Fixes a link from the dashboard to filtered VMs: `rowFilter-vm-status` -> `rowFilter-status`
Before:
https://github.com/user-attachments/assets/35aca9b6-b3e4-4c5f-ba89-2f8306c4e958
After:
https://github.com/user-attachments/assets/079acd5a-e5ff-44b3-815d-61a895f25567
> CNV-56886: fix dashboard links to VMs with status

- src/views/virtualmachines/actions/BulkVirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
- src/views/virtualmachines/actions/hooks/useMultipleVirtualMachineActions.tsx
- src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
- src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
- Adds the "Edit labels" option for single VM.
Note: I am not sure if the `accessReview: asAccessReview(VirtualMachineModel, vm, 'patch')` is the correct accessReview for this option (I copied it from other options and it seemed reasonable).
https://github.com/user-attachments/assets/e1011d0a-9e0c-4d21-b39c-0618a4712b62
> CNV-62150: add option to edit labels on single VM

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
- src/views/clusteroverview/MigrationsTab/MigrationsTab.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/BandwidthConsumptionCharts.tsx
- src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/components/MigrationsUtilizationChart.tsx
- remove the main "Bandwidth consumption" title
- rename "Network consumption" subtitle to "Bandwidth consumption"
- always shows the two sections: "Bandwidth consumption" and "Running migrations"
Before - no data:
After - no data:
Before - chart:
After - chart:
> CNV-58804: migrations chart change Bandwidth consumption title

- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/utils/resources/bootableresources/helpers.ts
- src/utils/resources/bootableresources/hooks/useBootableVolumes.ts
- src/utils/resources/bootableresources/selectors.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
- src/views/catalog/CreateFromInstanceTypes/state/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
This PR updates the Instance Types VM creation flow logic to use the size of the DataVolume over that of the PVC if it exists. The size of PVCs created using a filesystem-based storage class have already been increased to include overhead, so using the already increased size would result in double the overhead.
Jira: https://issues.redhat.com/browse/CNV-57330
> CNV-57330: Use DataVolume size for InstanceType VM creation

- src/utils/constants/window.ts
- src/utils/hooks/useIsSmallScreen.ts
- src/views/virtualmachines/tree/VirtualMachineTreeView.scss
- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
- src/views/virtualmachines/tree/components/TreeViewContent.tsx
Fixes a bug where tree view drawer panel was covering whole screen on smaller screen size. It is done by design of the PF drawer component. This fix checks the width of screen and conditionally sets the `isExpanded` prop on Drawer and hides / shows other components.
Tree view on small screen is above summary and VM table.
Before:
https://github.com/user-attachments/assets/1f7a3bbc-acb9-47b6-adbf-b0703a810f06
After:
https://github.com/user-attachments/assets/fe745cb4-0399-4756-98e2-cdcad2208d2d
> CNV-59145: fix tree view panel covering whole screen

- start-console.sh
```
declare -A plugins=(["monitoring-plugin"]="https://github.com/openshift/monitoring-plugin.git", ["networking-console-plugin"]="https://github.com/openshift/networking-console-plugin.git")
declare -A runningPlugins=(["podman-linux"]="kubevirt-plugin=http://localhost:9001", ["podman"]="kubevirt-plugin=http://host.containers.internal:9001", ["docker"]="kubevirt-plugin=http://host.docker.internal:9001")
```
is not compatible with zsh. Me and others use that
> Make start-console script compatible with zsh

- src/utils/hooks/useCDIUpload/utils.ts
Increases timeout for DataVolume to be ready to upload. From 60 seconds (30 checks every 2 seconds) to 300 seconds (150 checks every 2 seconds).
This aligns with [virtctl code](https://github.com/kubevirt/kubevirt/blob/e6e2df8983c877b6ae4134a06ca0f74e33b595c4/pkg/virtctl/imageupload/imageupload.go#L136)
> CNV-62819: increase timeout for DataVolume to be ready to upload

- src/views/catalog/wizard/tabs/network/utils/utils.ts
The problem occurs during VM creation from instance type.
Split from #2662.
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2662
See #2662
> CNV-61727: Fix setting link state on already added network interface

- src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
- src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
- src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
- src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
- src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
- src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
Show disk size in TiB and not bytes in Templates / Catalog templates -> Disks
- refactoring of duplicated code, ideally we should use `useDisksTableData` hook everywhere, but there are some differences so for now I only reused `useWizardDisksTableData` in `useTemplateDisksTableData`
- remove of unused class
Before:
https://github.com/user-attachments/assets/5d86c540-f093-4969-94f0-339503ffdbf5
After:
https://github.com/user-attachments/assets/69a362ec-13d5-41cd-8500-c9350a65888a
> CNV-39729: show disk size in TiB and not bytes

- jest.config.ts
- src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
- src/views/checkups/network/details/tabs/details/CheckupsNetworkDetailsPageSection.tsx
- src/views/checkups/network/hooks/useCheckupsNetworkListColumns.ts
- src/views/checkups/network/list/CheckupsNetworkListRow.tsx
- src/views/checkups/utils/utils.ts
When running a network checkup on some pre-selected Nodes, they will now appear during the checkup in the table or details.
- also fixes sorting of Checkups 
**TODO** use sorting from https://github.com/kubevirt-ui/kubevirt-plugin/pull/2730
- removes duplicate `pf-v6-c-description-list*`classes
BEFORE:
Nodes:
https://github.com/user-attachments/assets/d0fe7890-d80b-4e2e-987d-5f67c4971758
Sorting:
https://github.com/user-attachments/assets/8ebb7783-3038-47d4-953f-1a8e8a3788c1
AFTER:
Nodes:
https://github.com/user-attachments/assets/652aa6c3-29ef-47f2-813f-6425c3d25c5a
Sorting:
https://github.com/user-attachments/assets/3a29ea63-04ad-4bba-a317-f93ed17933fc
> CNV-61746: selected Nodes appear during network checkup

- src/utils/resources/vm/hooks/disk/useDisksSources.ts
after adding a blank disk to a vm and then editing the size, the size would not update correctly, it was receiving and storing the right volume size but displaying it incorrectly. I deleted code in useDisksSource that created a race condition displaying the dv instead.
before:
after:
> CNV-57953: fixed disk size display in storage to reflect the right size after edit

- src/utils/components/CPUMemory/CPUMemory.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabService/VirtualMachinesOverviewTabService.tsx
- src/views/virtualmachinesinstance/details/tabs/details/components/Services/Services.tsx
CPU|Memory field of VM details page shows value of previously clicked VM - if the previous clicked VM comes from InstanceType and the latter from Template. VM from InstanceType value overrides the VM from Template value.
in CPUMemory I prioritized vmi to make sure the right information is being displayed and I added a check to make sure the instanceType was only being used if it matches the current vm to prevent the previous vm's cpu and memory details from being displayed when switching vm's from different types. 
before:
https://github.com/user-attachments/assets/d8e5035d-1c57-48d2-90cb-9ac3e550e324
after:
https://github.com/user-attachments/assets/797fdf7f-6fee-4ba6-b101-3842690b5dc9
> Cnv 62718 fix cpu display

- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestManagementSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
- src/views/clusteroverview/SettingsTab/settings-tab.scss
changing position of " guest system log button option" to appear above " automatic subscription or RHEL mvirtualMachines" in the guest managment tab of cluster settings
before:
after:
> CNV-58161: moved guest system log above automatic subscription in settings- guest managment

- src/utils/components/AlertsCard/AlertsCard.tsx
- src/utils/components/AlertsCard/utils/constants.ts
- src/utils/constants/constants.ts
- src/utils/constants/prometheus.ts
- src/views/clusteroverview/OverviewTab/status-card/StatusCard.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/KubevirtHealthPopup.tsx
- src/views/dashboard-extensions/KubevirtHealthPopup/utils/utils.ts
- src/views/virtualmachines/details/tabs/overview/utils/hook/useVMAlerts.tsx
This PR fixes an issue with links to the Alerts monitoring page from the Virtualization perspective. The base path for the Alerts monitoring page is now different based on which perspective you are in.
Jira: https://issues.redhat.com/browse/CNV-58719
[alerts-page-from-virt-perspective--BEFORE--2025-06-11 09-37.webm](https://github.com/user-attachments/assets/c761f866-48a0-48fc-9021-036a83e99245)
[alerts-page-from-virt-perspective--AFTER--2025-06-11 09-38.webm](https://github.com/user-attachments/assets/26cd75e4-7962-4028-856b-ad698519116b)
> CNV-58719: Fix broken Alerts links in the Virtualization perspective

- locales/en/plugin__kubevirt-plugin.json
- src/utils/components/CapacityInput/CapacityInput.tsx
- src/utils/components/CapacityInput/utils.ts
- src/utils/components/DiskModal/components/DiskSizeInput/DiskSizeInput.tsx
- src/utils/components/DiskModal/components/DiskSizeInput/ExpandPVC.tsx
- src/utils/components/DiskModal/components/DiskSizeInput/utils.ts
- src/utils/utils/units.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DiskSize.tsx
- applies changes from https://github.com/kubevirt-ui/kubevirt-plugin/pull/2574 to 4.18 with some improvements
- fixes ability to expand disk to any size
- fixes ability to type in any number, e.g. if min size is 4 and we want to increase to 12, typing in "1" was not possible before
- fixes problems with localized strings, before disk size of e.g. 1000 GiB (1,000) would show as 1 GiB
Before:
https://github.com/user-attachments/assets/fce2377d-4d80-409d-a6cf-44dc7b0cc971
After:
https://github.com/user-attachments/assets/2d67a1f5-c60d-4e5a-925f-2f70b4d0f25b
> [release-4.18] CNV-63430: fix expanding disk size

- src/utils/components/HorizontalNavbar/HorizontalNavbar.tsx
- src/utils/components/StateHandler/StateHandler.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
- src/views/virtualmachines/navigator/VirtualMachineNavigator.tsx
Changes:
1. show spinner only if no data - prevents re-creating page
2. migrate to Router v6 element syntax as it enables re-rendering optimizations i.e. it effectively fixes #2612 (re-renders occur but have no visual impact).
3. re-implement #2612 on VirtualMachineNavigator level. Extra re-renders are triggered by useActiveNamespace hook.
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2612
https://github.com/user-attachments/assets/5af5657f-8c90-4d55-a43f-4feb898a5746
https://github.com/user-attachments/assets/80242edb-0b7e-4711-a088-c35ed558ff35
> CNV-62163: Prevent refreshing details page on VM change

- src/views/storagemigrations/actions/useStorageMigrationActions.tsx
- src/views/storagemigrations/extensions.ts
- src/views/storagemigrations/list/components/StorageMigrationRow.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationModal.tsx
- src/views/virtualmachines/actions/components/VirtualMachineMigration/VirtualMachineMigrationStatus.tsx
Make sure storage migration is not a standalone page but it customize the migplan list page as migplan is only used for storage. 
So when users goes into migplan and then clicks on the breadcrum, it goes back to the storage migration page instead of default list page 
https://github.com/user-attachments/assets/bbe131c8-a98f-4544-b722-00b009f06ed2
> CNV-63622: customize the migplan list page with the storage migration

- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useConvertedVolumeNames.ts
- src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
When we delete a VM, that was previously restored from a snapshot and has hotplugged disks, the hotplugged disks are now reported in the deletion modal
Before:
https://github.com/user-attachments/assets/7e56c8b7-e317-4050-b524-10c5400d28d6
After:
https://github.com/user-attachments/assets/419ea720-ad2f-4e7a-ae07-a2284ee746dd
> CNV-57798: report also PVC disks in VM deletion modal

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
- src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeSource/components/SnapshotSource.tsx
- src/utils/components/CapacityInput/CapacityInput.tsx
- src/utils/components/SelectSnapshot/SelectSnapshot.tsx
When adding a bootable volume from "Volume snapshot", changing size of the disk had no effect - the size is always determined from the VolumeSnapshot size.
This PR disables the Disk size input when a "Volume snapshot" option is chosen and adjusts the size in the input + adds an info message for users.
Before:
https://github.com/user-attachments/assets/e65d8716-827d-4761-8cc5-0c1b03896cae
After:
https://github.com/user-attachments/assets/69c1dfbb-03a0-49ca-bdb5-0540abfa973c
> CNV-57475: make disk size not editable when using volume snapshot

- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/VolumeMetadata.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeDrilldownSelect/InstanceTypeDrilldownSelect.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/hooks/usePreferenceSelectOptions.ts
- src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/utils/utils.ts
- src/utils/components/FilterSelect/components/InlineFilterSelectOptionContent.tsx
- src/utils/components/FilterSelect/utils/types.ts
- src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
This PR fixes a bug in the Preferences select menu in the bootable volumes modal where the UI was unable to tell whether the user Preference or cluster Preference was selected if they had the same name. It also fixes a bug where the `instancetype.kubevirt.io/default-instancetype-kind` label wasn't set when an Instancetype was selected in the bootable volumes modal.
Jira issues: 
- https://issues.redhat.com/browse/CNV-61710
- https://issues.redhat.com/browse/CNV-64350
> CNV-64350: CNV-61710: Fix bugs in bootable volumes Preferences select menu

- src/utils/resources/bootableresources/constants.ts
- src/utils/resources/bootableresources/helpers.ts
- src/utils/resources/preference/types.ts
- src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
- src/views/bootablevolumes/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeTable/BootableVolumeTable.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsLeftGrid.tsx
- src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts
- src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx
- src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourcePreferenceLink.tsx
- fixes link to a VirtualMachinePreference (VMP) in Bootable volume details
- BootableVolumeTable shows correct icon + Operating system for a volume with a VMP; sorting is fixed
- Catalog -> InstanceTypes -> VM details shows correct Operating system
BEFORE:
https://github.com/user-attachments/assets/a886296c-a3cd-4e1b-9dba-80cd0ab74445
AFTER:
https://github.com/user-attachments/assets/d2227fce-3266-4d37-9a14-2cb65b1edcc6
> CNV-61770: fix linking to User Preferences in Bootable volumes

- src/utils/hooks/useFeatures/createFeaturesConfigMap.ts
- src/utils/hooks/useFeatures/useFeatures.ts
- src/utils/hooks/useFeatures/useFeaturesConfigMap.ts
>
1. handle rejected update promise - the catch statement was not part of async flow
2. prevent subsequent creation attempts if the first atempt failed
3. prevent creation attempts if the first attempt is in progress
https://github.com/user-attachments/assets/fbf64ca0-e428-4822-a337-eeb53986b085
https://github.com/user-attachments/assets/eb5ff1fb-8690-4ebc-8cf3-991cd12b4e98
> CNV-64583: Fix error handling in re-creating features config map

- src/utils/resources/vm/utils/disk/rowData.ts
Fixing the UI display of the vm's disk size in the vm's details overview storage tab and configuration storage table.
Before:
After:
> CNV-62944: Fixing the disk size display in vm details to display the right size

- src/utils/constants/constants.ts
- src/utils/hooks/useUserPreferences.ts
- src/utils/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
When preference fetch is in error, the page keeps loading instead of showing the error.
This as `loaded` from `useK8sWatchResource` is false when the fetch go into the error state but we keep showing the spinner if not loaded 
note: on upstream we should fetch volums fron the upstream namespace
> Fix preferences loading with error

- README.md
Adds instructions to set the BRIDGE_BRANDING=openshift environment variable in both terminals when using Option 1 for local development.
> doc: include BRIDGE_BRANDING=openshift for local development

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/components/FirmwareBootloaderModal/utils/constants.ts
Two last "Boot mode" dialog options have the same description text, without explaining the difference between UEFI and UEFI (secure).     I spoke with Ronen sde-or who told me ti ask Igor Bezukh . Igor said to put in the UFEI :Use UEFI when bootloading the guest OS
before 
after
> CNV-60059: Descriptions for UEFI and UEFI (secure) are the same

- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
- src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsItem.tsx
- src/utils/components/Consoles/components/CloudInitCredentials/InlineCodeClipboardCopy.tsx
- src/utils/components/Consoles/utils/utils.ts
Moving the copy button out of the hidden text field by creating new copy buttons and hiding only the credential text instead of the whole component, making the copy button always visible while only toggling the text display.
Before: 
After:
> CNV-64839: Moving the copy button out of text element making it always visible

- src/views/virtualmachines/tree/VirtualMachineTreeView.scss
- src/views/virtualmachines/tree/VirtualMachineTreeView.tsx
fixing design to account for footer height in tree view so it is able to see all of the listed vm's
Before:
After:
> fixing the tree-view scroll to see all vm's blocked by footer

- package.json
- yarn.lock
This fix resolves the TypeError: _delaunator.default is not a constructor that occurs when a user hovers over charts. 
The problem was caused by a dependency conflict where @patternfly/react-charts and @patternfly/react-topology were relying on different major versions of the delaunator package.
By explicitly restricting the version to 4.0.1 within the dependency tree, we've ensured that both libraries use a compatible version, allowing chart tooltips to function correctly again.
https://github.com/user-attachments/assets/997cfd15-e824-4fe9-adb6-21a6bfb625ed
> CNV-67857: PatternFly Chart hover broken due to delaunator package version conflict

- src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
Depends on: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2875
Until #2869 it was not possible to change the binding. With adding Passt this limitation was removed but still user was not allowed to switch back to `l2bridge` binding.
Steps to reproduce:
1. edit Pod network - switch to Passt binding
2. restart the VM - the change should get applied
3. edit Pod network - switch back to `l2bridge` binding
4. restart the VM - the interface type will be `Bridge` (the default) as the change was blocked
https://github.com/user-attachments/assets/162a7c70-bf32-43dd-beec-c26e282a3ddf
https://github.com/user-attachments/assets/6bbb6482-ef0d-4a73-a149-4cc2d5ae6912
> CNV-52151: Allow changing NIC binding to l2bridge

- src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
If the Pod Network is added via `autoattachPodInterface` then it's possible to add a second Pod Network.
https://github.com/user-attachments/assets/7cb43065-b2de-4ff4-93fc-7e875e023f4f
https://github.com/user-attachments/assets/fb7ec306-d982-4fd2-981f-c924eed1474e
> CNV-67947: Detect autoattached Pod Network

- src/views/virtualmachines/tree/VirtualMachineTreeView.scss
Added padding to the bottom of the VM list. 
Without the fix: 
After applying it:
> CNV-68078: Add padding to the bottom of the tree view body

- src/views/catalog/CustomizeInstanceType/components/CustomizeITVMFooter.tsx
Updating the "Start this VirtualMachine after creation" flag when customizing a new VM. 
Previously, the runStrategy flag was not updated when creating the customized VM. 
https://github.com/user-attachments/assets/4fe331ba-79c9-4485-a834-4a0954c9de98
> CNV-68079: Add run strategy update on start VM checkbox change

- package.json
- src/multicluster/constants.ts
- src/multicluster/extensions.ts
- src/multicluster/urls.ts
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- yarn.lock
- Updates @stolostron/multicluster-sdk to version 0.6.2
- Adds extensions to declare the multicluster VM route to ACM/multicluster-SDK so that links and search results for VMs/VMIs can go to the correct page (removes hardcoding of these routes from SDK)
- Updates ManagedCluster links to use the main API group instead of the `clusterview` group for the aggregate API and adds a missing case
> ACM resource routes

- src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
- src/utils/components/Consoles/components/AccessConsoles/utils/accessConsoles.tsx
- src/utils/components/Consoles/components/vnc-console/actions.ts
After pasting values to console we automatically focus on the console, improving the user experience. 
Previously before this enhancement the user had to click on the console in order to gain focus and be able to type inside.
https://github.com/user-attachments/assets/98d7b597-f033-417d-8fc7-6dec5432a1a1
> CNV-68329: Enable focus after pasting values to console

- locales/en/plugin__kubevirt-plugin.json
- locales/es/plugin__kubevirt-plugin.json
- locales/fr/plugin__kubevirt-plugin.json
- locales/ja/plugin__kubevirt-plugin.json
- locales/ko/plugin__kubevirt-plugin.json
- locales/zh/plugin__kubevirt-plugin.json
- src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
- src/utils/components/Charts/utils/queries.ts
- src/utils/hooks/useVMQueries.ts
- src/utils/resources/vm/utils/utils.ts
- src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts
- src/views/clusteroverview/TopConsumersTab/utils/queries.ts
- src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
- src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx
- src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/UtilizationThresholdCharts.tsx
- src/views/virtualmachines/list/components/VirtualMachineListSummary/VirtualMachineListSummary.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/hooks/sortColumns.ts
- src/views/virtualmachines/list/hooks/useVMMetrics.ts
- src/views/virtualmachines/list/hooks/useVMTotalsMetrics.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/list/metrics.ts
- src/views/virtualmachines/list/utils/processVMTotalsMetrics.ts
- src/views/virtualmachines/list/utils/totalsQueries.ts
For CPU requested metric we don't have to fetch it form prometheus using `kube_pod_resource_request` 
We need to take it from the VMI. `kube_pod_resource_request` is not directly related to the VMI CPU requested, but it's scaled using HCO configuration. 
For memory we ofter use `kubevirt_vmi_memory_available_bytes - kubevirt_vmi_memory_usable_bytes` but the right metric is `kubevirt_vmi_memory_used_bytes`
> CNV-48181: fix CPU and memory metrics

- src/utils/hooks/usePVCMapper.ts
- src/utils/resources/constants.ts
- src/utils/resources/shared.ts
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/CPUPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/MemoryPercentage.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/components/NetworkUsage.tsx
- src/views/virtualmachines/list/hooks/sortColumns.ts
- src/views/virtualmachines/list/hooks/useExistingSelectedVMs.ts
- src/views/virtualmachines/list/hooks/useVMListFilters/useNodesFilter.ts
- src/views/virtualmachines/list/hooks/useVMMetrics.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
- src/views/virtualmachines/list/hooks/useVirtualMachineInstanceMapper.ts
- src/views/virtualmachines/list/metrics.ts
- src/views/virtualmachines/list/selectedVMs.ts
- src/views/virtualmachines/list/utils/filters/getIPFilter.ts
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/DefaultRightClickActionMenu.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/VMRightClickActionMenu.tsx
- src/views/virtualmachines/tree/components/TreeViewRightClickActionMenu/utils.ts
- src/views/virtualmachines/tree/utils/utils.tsx
- src/views/virtualmachines/utils/mappers.ts
- src/views/virtualmachines/utils/utils.ts
make sure the treeview ids and the mappers take into account the vm cluster . 
Without that, vms with the same name but into different clusters can have conflicts
Make sure to fetch pvcs and vmim with multicluster hooks
> CNV-68335: fix mappers identifiers by including cluster

- package.json
- yarn.lock
Make sure we use the new sdk that gives vms the new indexes parameters and now we can show the storageclassmigration
> Bump sdk version for storageclass migration name fix

- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/hooks/useInstanceTypeCardMenuSection.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/utils/types.ts
- fixes a bug where menus in Catalog -> Select InstanceType cards were not closing on clicking outside (when you clicked one menu toggle, then another one, then outside, the other toggle didn't close)
- issue was with `menuRef` being shared between multiple menus and then `menuRef.current` became `null` when we opened second menu
Before:
https://github.com/user-attachments/assets/fdf6a9e0-8696-446d-acf0-d0c7e2ea744d
After:
https://github.com/user-attachments/assets/6d699e6f-1b18-4264-91f2-f9078b518dbc
> CNV-68934: close menu on clicking outside in Catalog cards

- src/multicluster/urls.ts
- src/utils/components/SSHSecretModal/components/SSHKeyUpload/SSHKeyUpload.tsx
- src/utils/hooks/useActiveNamespace.ts
- src/utils/resources/vm/utils/utils.ts
- src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/hooks/useGeneratedVM.ts
`useActiveNamespace` have been replaced by `useNamespaceParam` in a previous pr to support the namespace when the catalog page is in a multicluster mode. In the multicluster, we can't use `useActiveNamespace`.  [HERE](https://github.com/kubevirt-ui/kubevirt-plugin/pull/2935)
The multicluster catalog do not follow the console active namespace so active namespace can be different from what the user select.
To have a valid workaround for the future, i created in this pr a hook that returns the namespace if it's selected and  `ALL_NAMESPACES_SESSION_KEY` when the all-namespace is selected. Using the same name so it will be easier to replace in other pages
**BUG**
https://github.com/user-attachments/assets/2904d561-85c3-41bc-af13-ae6dc623cee6
> CNV-69002: make sure catalog works with all namespaces selected

- src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
- src/utils/resources/vm/utils/network/selectors.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
- src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
- src/views/virtualmachines/details/tabs/configuration/network/utils/utils.ts
Before, removing the last NIC resulted in disabling also autoattachPodInterface flag. The approach was used for both existing VMs and while creating a VM from instance types.
Problems:
1. for existing but shutdown VM only NICs defined explicitly are shown. The auto-attached Pod Network is not visible. Removing the last explicitly defined NIC resulted also in toggling the flag and effectively dropping Pod Network.
2. for creating VM: it was not possible to delete the auto-attached Pod Network until all other NICs were deleted.
Related fix:
When creating a VM from instance type, missing autoattachPodInterface
flag (undefined) was treated as disabled. As a result the Pod Network
was missing in the presented table.
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2062 …
> CNV-69369: Fix disabling autoattachPodInterface on deleting Pod Network

- src/utils/utils/architecture.ts
- src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/hooks/useGeneratedVM.ts
- src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/components/RedHatProvidedInstanceTypesSection/components/RedHatSeriesMenuCard/RedHatSeriesMenuCard.tsx
- src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
- src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/hooks/useCreateDrawerForm.tsx
- src/views/catalog/utils/quick-create-vm.ts
Populate architecture property on vm spec instead of applying nodeSelector 
> CNV-68997: spec.architecture doesn't auto-populate on ARM clusters despite kubernetes.io/arch=arm64

- plugin-extensions.ts
- plugin-metadata.ts
- src/perspective/VirtualizationLandingPage.tsx
- src/perspective/extensions.ts
- src/perspective/perspective.ts
Fixing the routing to virtualization perspective to eliminate the automatic routing to all-projects before re-directing to the correct name space by privilege. 
when in virtualization perspective the routing is done according to permissions and available projects.
Before:
https://github.com/user-attachments/assets/a7e17a05-8e0e-4d2b-b230-7f44c0ef4e58
After:
https://github.com/user-attachments/assets/2d406919-3be1-4f1c-973d-b898521f4ad2
> CNV-63859: Fixing the virtualization perspective route for non-priv users

- src/utils/resources/vm/utils/disk/utils.ts
fixing logic to correctly identify empty container disk image,
allowing the eject action on an installation cd-rom with registry image. 
Before:
After:
> CNV-68471: Fixing installation CD-ROM with registry image to allow eject action

- src/utils/resources/vm/utils/disk/useDriversImage.ts
[CNV-69687](https://issues.redhat.com/browse/CNV-69687): Mount Windows drivers disk checkbox is not loaded on initial load (a loading indicator is displayed). 
Before:
https://github.com/user-attachments/assets/ec53c2ac-e1e1-42cd-bd69-7812585f3a98
After:
https://github.com/user-attachments/assets/c3e0600b-0cc0-4c71-a932-b10b188310a4
> CNV-69687: use state management for setting loadingDriverValue and driverImageValue in useDriversImage

- src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
- fixes incorrect redirecting from multicluster tree view to normal tree view page 
- after deleting a VirtualMachine
- link to VM details from hub cluster
- fixes incorrect "all-namespaces" project
note: `useClusterParam` and `useNamespaceParam` don't work when called in `DeleteVMModal`, so params are passed as props
Before:
https://github.com/user-attachments/assets/82ad4402-d537-4d60-b19c-82a41d086a4b
https://github.com/user-attachments/assets/0a17ba47-d19b-4d29-bf75-fca4edecf5b3
https://github.com/user-attachments/assets/13e0ee30-9e74-4064-8c2a-0cb6052ceb82
After:
https://github.com/user-attachments/assets/56715ef5-4ca4-40f2-b9a4-82961d1c3372
https://github.com/user-attachments/assets/1c41a20d-7d08-4465-9e8c-929b6bb283ef
> CNV-69014: fix multicluster tree view VM links

- src/utils/components/DiskModal/utils/form.ts
- src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
- src/utils/resources/instancetype/helper.ts
- src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
- src/views/virtualmachines/details/tabs/configuration/details/DetailsSection.tsx
- src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSectionRightGrid.tsx
VMs with preference but no instancetypes are having an infinite loading issue.
The fix is to make sure the code waits for the expanded spec VM instead of searching for the instancetype vm (that its `undefined`)
In case we don't have an expanded spec VM because of an error or something, the Horizontal NavBar will present an error
instead of the details tab 
Note: would like in the future to rename all the `instancetypeVM` to `expandedSpecVM` as the vm can also be expanded but not connected to an instancetype. I would not do that now as i can disrupt a release 
**BEFORE**
https://github.com/user-attachments/assets/82424837-0b32-4dd4-8b45-fd9e3e35eefb
**AFTER**
> CNV-69441: infinite loading on vm with preference but no instancetype

- src/utils/components/NetworkInterfaceModal/utils/helpers.tsx
- src/utils/constants/network-columns.tsx
- src/utils/resources/vm/utils/network/network-columns.tsx
- src/utils/resources/vm/utils/network/selectors.ts
- src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
- src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
Fix disabling hot-unplug for Pod Network  - drop assumption that the Pod Network has the first interface and detect only based on the `pod` property.
https://github.com/user-attachments/assets/8aa1bad3-b2d8-48eb-9377-c7283cb3386c
https://github.com/user-attachments/assets/53b91c32-26da-4bd5-876c-00ac7c586cf3
> CNV-69370: Disable hot-unplug for Pod Networks

- src/utils/components/FormPFSelect/FormPFSelect.tsx
- src/utils/resources/vmi/utils/ips.ts
- src/utils/utils/utils.test.ts
- src/utils/utils/utils.ts
- src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
- src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
- src/views/virtualmachines/utils/utils.ts
Filter all IP addresses that start with fe80::/10 as defined in section 2.5.6 of RC4291.
Replaces #2895.
Related fix - skip IP addresses that are empty string.
Reference-Url: https://www.rfc-editor.org/rfc/rfc4291#section-2.5.6
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/2895
> CNV-64588: Filter out IPv6 link-local addresses

- src/utils/components/ExpandSectionWithCustomToggle/ExpandSectionWithCustomToggle.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/GuestManagmentSection/GuestSystemLogsAccess/GuestSystemLogsAccess.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/PersistentReservationSection/PersistentReservationSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/AutoComputeCPULimits/AutoComputeCPULimits.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/ResourceManagementSection/components/KernelSamepageMerging/KernelSamepageMerging.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/VirtualizationFeaturesSection.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesList/components/FeaturedOperatorItem.tsx
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/FeatureSummaryItem/FeatureSummaryItem.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/HighAvailabilitySection/HighAvailabilitySummarySection.scss
- src/views/clusteroverview/SettingsTab/ClusterTab/components/VirtualizationFeaturesSection/VirtualizationFeaturesWizard/components/SummaryStep/components/HighAvailabilitySection/HighAvailabilitySummarySection.tsx
- src/views/clusteroverview/SettingsTab/ExpandSection/ExpandSection.scss
- src/views/clusteroverview/SettingsTab/settings-tab.scss
- applies general styling for expandable sections indentation, so setting `className="settings-tab--indented"` on individual Split components is not necessary
- key thing is applying `margin-left: -0.5rem` on toggles
- these toggles use link Button under the hood, so they have an "invisible" padding of 0.5 rem, which is only visible on hover -> in default state it looks misaligned
- fixes indentation of "Load balance" under "Virtualization features"
- note: the negative margin only applies to second and more nested expandable sections. The top level stays as before. In `.high-availability-summary-section` (in Wizard modal in video) it is an exception, because it is on the first level and it is aligned with other text
- instead we could apply the style on the first level too and don't have …
> CNV-68854: improve expandable sections indentation

- package.json
- src/utils/resources/vmi/utils/ips.ts
- src/utils/utils/utils.ts
- src/views/virtualmachines/utils/utils.ts
- yarn.lock
Add explicit dependency to ipaddr.js@2.2.0. The library is already used as dev dependency by webpack-dev-server.
Related refactoring: use ippaddr.js for isIPV6LinkLocal() helper
Reference-Url: https://github.com/kubevirt-ui/kubevirt-plugin/pull/3023
https://github.com/user-attachments/assets/609125b7-f3b2-4750-b6fa-40738ea7bb3f
https://github.com/user-attachments/assets/62ad8c92-4563-40fd-aaa1-d6e4b06e049c
> CNV-69840: Search IPv6 addresses by CIDR

- src/utils/components/ListPageFilter/components/CheckboxSelectFilter.tsx
- src/utils/components/ListPageFilter/hooks/useAdvancedFiltersParameters.ts
- src/utils/components/ListPageFilter/hooks/useApplyFiltersWithQuery.ts
- src/views/virtualmachines/search/VirtualMachineFilterToolbar.tsx
- fixes VirtualMachine summary filters, which were not clearing
- issue was that to `onFilterChange` `type` argument used in "clear filters" function, we were passing `"rowFilter-status"`, but in VM summary filters, `type` argument was just `"status"`
- Solution: don't wrap `type` argument in `onFilterChange` function with the `"rowFilter-"` preposition (`getRowFilterQueryKey` helper)
- `getRowFilterQueryKey` helper should be used only to create query string, not as a filter type
Before:
https://github.com/user-attachments/assets/b4c46cc3-061c-48e7-999c-353c7ba55f27
After:
https://github.com/user-attachments/assets/1053b930-5948-4908-895b-a5ffeae80bdc
> CNV-69947: fix VirtualMachine summary filters not clearing

- src/utils/hooks/useKubevirtWatchResource/useKubevirtWatchResource.ts
- src/views/virtualmachines/list/VirtualMachinesList.tsx
- src/views/virtualmachines/list/utils/constants.ts
- improves unnecessary recalculation of `shouldUseProxyPod` variable in `useKubevirtWatchResource`
- use boolean in the dependency array instead of `filterOptions` object
- make `filterOptions` param in VirtualMachinesList a constant, so the object reference doesn't change with rerenders
Before:
https://github.com/user-attachments/assets/bd2590be-0bd6-4751-b732-90965842f093
After:
https://github.com/user-attachments/assets/9461e95f-9193-4e28-b40b-e2ae5be3481c
> CNV-70162: improve recalculation of shouldUseProxyPod

- src/utils/store/customizeInstanceType.test.ts
- src/utils/store/customizeInstanceType.ts
- src/utils/store/customizeInstanceType/utils/utils.ts
Jira Ticket: [CNV-70233](https://issues.redhat.com/browse/CNV-70233)
When customizing a new VM - changing the boot order corrupts the YAML due to an improper handling of `updateCustomizeInstanceType`. 
The test case of the exact scenario that caused the YAML corruption is tested in the test file under `object corruption prevention`
Before:
https://github.com/user-attachments/assets/d36445ec-05e3-4d06-9004-1b16d4613aea
After:
https://github.com/user-attachments/assets/cfe40033-7a50-40e8-a2fb-fab18896fce1
> CNV-70171:  Prevent YAML corruption when changing boot order while customizing a new vm

- src/utils/components/GuidedTour/GuidedTour.tsx
- src/utils/resources/vm/hooks/useInstanceTypeExpandSpec.ts
- src/views/virtualmachines/details/VirtualMachineNavPage.tsx
Jira: [CNV-70150](https://issues.redhat.com/browse/CNV-70150)
This PR fixes two issues; 
1. The original issue in the Jira ticket - the VM gets stale data from the `useInstanceTypeExpandSpec` hook, leading to incorrect data for the boot mode (and potentially other parts which show incorrect data as well). 
2. Right clicking a VM in the list after reloading the page while selecting the configuration tab crashes the app. 
Before:
https://github.com/user-attachments/assets/536f1df3-78e5-400a-b50b-408ea1f20467
After:
https://github.com/user-attachments/assets/b7851a36-4086-4434-ac01-75e7882a8e26
> CNV-70150: Fix stale vm data in in useInstanceTypeExpandSpec hook
