kubevirt-ui/kubevirt-plugin

.eslintrc.json
locales/en/plugin__kubevirt-plugin.json
src/components/VMStatusConditionLabel.tsx
src/components/vms/vm-page.tsx
src/types/vm/index.ts

add conditions column

---

README.md

WIP: update readme bug

---

README.md

add size label action

---

console-extensions.json

Add virtual machine instance and template links

Add nav items

---

.github/workflows/ci_checks.yml
locales/en/plugin__kubevirt-plugin.json

Adds i18n diff check to status checks of PRs

add i18n test to github actions

---

__mocks__/react-i18next.ts
__mocks__/react-router-dom.ts
jest.config.ts
package.json
src/utils/models/index.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilterGroup.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/templatescatalog/hooks/useVmTemplates.tsx
src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/tests/mocks.ts
src/views/catalog/templatescatalog/types/template.ts
src/views/catalog/templatescatalog/utils/helpers.ts
tsconfig.json
yarn.lock

- Added test for `TemplatesCatalog`
- Updated `kubevirt-api` to 0.0.34. Now using `V1Template`

add unit-test to templates catalog

---

console-extensions.json
package.json
src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPage.tsx
src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPageHeader.tsx
src/views/virtualmachinesinstances/page/hooks/useVirtualMachinesInstancesTabs.ts
src/views/virtualmachinesinstances/page/tabs/console/VirtualMachinesInstancesPageConsoleTab.tsx
src/views/virtualmachinesinstances/page/tabs/details/VirtualMachinesInstancesPageDetailsTab.tsx
src/views/virtualmachinesinstances/page/tabs/disks/VirtualMachinesInstancesPageDisksTab.tsx
src/views/virtualmachinesinstances/page/tabs/events/VirtualMachinesInstancesPageEventsTab.tsx
src/views/virtualmachinesinstances/page/tabs/network/VirtualMachinesInstancesPageNetworkTab.tsx
src/views/virtualmachinesinstances/page/tabs/yaml/VirtualMachinesInstancesPageYAMLTab.tsx

Added routing and structure for VMI page.

Routing and structure of VMI page

---

README.md
src/utils/hooks/useKubevirtTranslation.ts
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachinesinstances/page/VirtualMachinesInstancesPageHeader.tsx
src/views/virtualmachinesinstances/page/hooks/useVirtualMachinesInstancesTabs.ts

This replaces `useTranslation('plugin__kubevirt-plugin')` with `useKubevirtTranslation()`

add useKubevirtTranslation hook

---

package.json
yarn.lock

bump console dynamic sdk versions

bump sdk versions

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/utils/quick-create-vm.ts

Add QuickCreate function for Virtual machine in the Catalog Drawer
https://user-images.githubusercontent.com/24938324/155114676-fcbf9fe3-f0b1-4e49-b62c-8ab71dc606e9.mov

Add vm quick create function

---

codecov.yml

codecov don't wait for CI to finish before PR status check

codecov don't wait for CI to finish before PR status check

---

console-extensions.json
locales/en/plugin__kubevirt-plugin.json
package.json
src/views/catalog/wizard/Wizard.tsx
src/views/catalog/wizard/tabs.tsx
src/views/catalog/wizard/tabs/advanced/WizardAdvancedTab.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx
src/views/catalog/wizard/tests/Wizard.test.tsx

Add review page router

---

src/views/catalog/customize/components/CustomizeForm.tsx
src/views/catalog/customize/tests/CustomizeForm.test.tsx

No loading spinner on error

---

console-extensions.json
package.json
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/actions/actions.ts
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
src/views/virtualmachines/actions/tests/actions.test.ts
src/views/virtualmachines/actions/tests/mocks.ts
src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
yarn.lock

exposing VM actions in console-extentions, 
creating an action provider hook,
creating VM action factory
creating API requests for vm start/stop/restart (for now)
no demo at this point.

Add VM actions example PR

---

.github/workflows/ci_checks.yml

Add standalone i18n github action for better status reporting in PRs

Add standalone i18n github action

---

locales/en/plugin__kubevirt-plugin.json
package.json
src/views/virtualmachinesinstance/details/tabs/disks/VirtualMachinesInstancePageDisksTab.tsx
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableColumns.ts
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableDisks.ts
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableColumns.ts
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableGuestOS.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTable.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableTitle.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableRow.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTableTitle.tsx
src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts
src/views/virtualmachinesinstance/details/tabs/disks/virtual-machines-insance-page-disks-tab.scss
yarn.lock

vmi disk tab

---

src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableColumns.ts
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useDisksTableDisks.ts
src/views/virtualmachinesinstance/details/tabs/disks/hooks/useFileSystemTableColumns.ts
src/views/virtualmachinesinstance/details/tabs/disks/table/file-system/FileSystemTable.tsx
src/views/virtualmachinesinstance/details/tabs/disks/utils/virtualMachinesInstancePageDisksTabUtils.ts

> Sorting will now use default sorting of columns

Change sorting on disk tab

---

package.json
src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
src/views/virtualmachinesinstance/list/hooks/useVirtualMachinesInstancesColumns.tsx
yarn.lock

> Added sorting for VMI list table headers.

Adding sorting to VMI list

---

package.json
src/views/catalog/customize/utils.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/templatescatalog/hooks/useProcessedTemplate.ts
src/views/catalog/utils/quick-create-vm.ts
src/views/catalog/utils/vm-template-source/useVmTemplateSource.ts
src/views/catalog/utils/vm-template-source/utils.ts
yarn.lock

bump sdk packages to 0.0.6

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachinesinstance/details/tabs/network/VirtualMachineInstancePageNetworkTabRow.tsx
src/views/virtualmachinesinstance/details/tabs/network/VirtualMachinesInstancePageNetworkTab.tsx
src/views/virtualmachinesinstance/details/tabs/network/hooks/useVirtualMachineInstanceNetworkTab.ts
src/views/virtualmachinesinstance/details/tabs/network/hooks/useVirtualMachineInstanceNetworkTabColumns.ts
src/views/virtualmachinesinstance/details/tabs/network/utils/virtualMachineInstancePageNetworkTabUtils.ts
src/views/virtualmachinesinstance/details/tabs/network/virtual-machines-insance-page-network-tab.scss

> Add network tab table to VMI page

Adding network tab to VMI page

---

src/views/virtualmachines/details/components/overview/VirtualMachinesOverviewTab.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlerts.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabHardwareDevices/VirtualMachinesOverviewTabHardwareDevices.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfaces.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabSnapshots/VirtualMachinesOverviewTabSnapshots.tsx
src/views/virtualmachines/details/components/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
src/views/virtualmachines/details/tabs.tsx

> VM overview page files and grid structure

CNV-16678 - Create VM overview tab grid

---

package.json
yarn.lock

> Update internal package to new version

Update inter package to 0.0.5 version

---

src/views/catalog/utils/WizardVMContext.tsx
src/views/catalog/wizard/tabs/advanced/WizardAdvancedTab.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx

Add backend validation to vm context.
Now with each change of the context we make a dry run API call that creates a VM.
This will help us validate the vm object with the backend

Add backend validation to vm context

---

src/utils/components/Loading/Loading.tsx

Add loading component

---

console-extensions.json
package.json
src/views/virtualmachinesinstance/actions/VirtualMachinesInstanceActions.tsx
src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx
src/views/virtualmachinesinstance/list/VirtualMachinesInstancesRow.tsx
src/views/virtualmachinesinstance/list/hooks/useVirtualMachinesInstancesColumns.tsx

> Actions infustructre for VMI.
Missing createModalLauncher for annotations, labels, and delete modals.
Missing console standalone path and console component. 
Those missing components will be added to the internal package and to our plugin in different PRs. 
Once they will be added this infrastructure should be modified to utilize those components.

Actions for VMI

---

src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/actions/tests/useVirtualMachineActionsProvider.test.tsx
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx

exposing actions to UI in VM list view and in the details tabs header
@glekner @metalice @yaacov @pcbailey @upalatucci @hstastna please review :) 

expose VM actions in VM list view and tabs view

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/overrides.tsx
src/views/catalog/customize/utils.tsx

Fix Namespace overriding

---

package.json
src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
yarn.lock

bump kubevirt api

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/TabModal/TabModal.tsx

tab modal fixes

---

src/views/catalog/utils/useVmCreate.ts

add immerJS Deep updates to useVmCreate, as usually the hook is getting the immutable version from the vm context

add Deep updates to useVmCreate

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DescriptionModal/DescriptionModal.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

Add description modal

---

src/views/catalog/utils/tests/vm-produce.test.ts
src/views/catalog/utils/vm-produce.ts
tsconfig.json

> Immer based helper functions to ensure the existence of certain paths and arrays

Produce helper functions to edit vm networks and disks

---

locales/en/plugin__kubevirt-plugin.json
package.json
src/utils/components/LabelsModal/LabelsModal.tsx
src/utils/components/LabelsModal/utils.ts
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/metadata/components/WizardMetadataLabels.tsx
yarn.lock

Add labels modal to VM wizard

---

src/utils/resources/vm/utils/operation-system/operationSystem.ts
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

Moving os helper to global utils

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachinesinstance/actions/VirtualMachinesInstanceActions.tsx

remove usage of LazyActionsMenu as not working properly at the moment

change LazyActionsMenu from SDK to Dropdown from PF

---

src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx

Added support for namespace VMI list

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

add cpu modal to wizard overview tab

add cpu modal to wizard overview tab

---

src/utils/resources/vmi/utils/index.ts
src/utils/resources/vmi/utils/ips.ts
src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
src/views/virtualmachines/list/components/FirstItemListPopover/FirstItemListPopover.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx

Moved VMI get ips function to global

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx

when getting an error for first time, we need to clear the error when we want to submit again

reset error when submitting

---

src/views/catalog/wizard/tabs/overview/components/WizardOverviewDisksTable/WizardOverviewDisksTable.tsx

fix disks size not showing in wizard overview tab

fix disks size in wizard overview tab

---

src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx

if cloudinitdisk is deleted or doesn't exist, we need to re-create it when editing in the Scripts tab

fix cloudinit disk creation if missing

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithCD.tsx
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithDisk.tsx
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/constants.ts
src/views/catalog/customize/drivers.ts
src/views/catalog/customize/tests/CustomizeSource.test.tsx
src/views/catalog/customize/utils.ts

> Add windows drivers using the checkbox
https://user-images.githubusercontent.com/29160323/160368123-9738ebd0-9ec4-45f2-b010-1f1466e6e809.mp4

Mount windows drivers

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/overview/VirtualMachinesOverviewTab.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisks.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisksRow.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/hooks/useVirtualMachinesOverviewTabDisksColumns.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/virtual-machines-overview-tab-disks.scss

https://issues.redhat.com/browse/CNV-16679
First PR of this card

CNV-16679: Adding disk card to VM overview page

---

cypress/consts.ts
cypress/tests/overview.spec.ts
cypress/views/overview.ts

add tests for overview page

---

src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts

Fix catalog loading when there are no available templates with source

Fix catalog loading when there are no available templates with source

---

src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

update wizard modals with useModal
Also added new Add disk modal to Disks tab

update wizard modals with useModal

---

src/utils/components/DescriptionModal/DescriptionModal.tsx
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

Consume description modal for VM details tab

---

src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx

Removed extra padding

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/vm/utils/selectors.ts
src/views/catalog/utils/WizardVMContext/WizardVMContext.tsx
src/views/catalog/wizard/components/WizardFooter.tsx
src/views/catalog/wizard/tabs.tsx
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/environment/components/EnvironmentEditor.scss
src/views/catalog/wizard/tabs/environment/components/EnvironmentEditor.tsx
src/views/catalog/wizard/tabs/environment/components/EnvironmentSelectOption.tsx
src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabFooter.scss
src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabFooter.tsx
src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabTitle.tsx
src/views/catalog/wizard/tabs/environment/constants.ts
src/views/catalog/wizard/tabs/environment/hook/useEnvironments.ts
src/views/catalog/wizard/tabs/environment/hook/useEnvironmentsResources.ts
src/views/catalog/wizard/tabs/environment/utils.ts
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts

> Environment tab. Add, remove and edit environments (configmaps, secrets and serviceAccounts)
https://user-images.githubusercontent.com/29160323/160882299-a539deb0-d8bf-4d7a-b329-99c7f1af9029.mp4

Wizard environment tab

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/wizard/components/WizardFooter.tsx
src/views/catalog/wizard/tabs.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

Add confirm prompts to wizard exit
Add template's name and namespace to context so the user can go back to the customize form.
Add template's display name for the overview tab OS section

Add confirm prompts to wizard exit

---

src/views/catalog/templatescatalog/TemplatesCatalog.scss
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
src/views/catalog/templatescatalog/hooks/useTemplatesCatalogColumns.ts
src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/utils/consts.ts

Add list view to templates catalog with a toggle
https://user-images.githubusercontent.com/24938324/161417024-4da0ed10-6c25-43f8-8bea-e44a71538ea5.mov

Add list view to templates catalog

---

src/utils/components/LabelsModal/LabelsModal.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/Labels.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/labels.scss

Adding labels modal to vmi details tab

---

src/utils/components/DescriptionModal/DescriptionModal.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/Description.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/description.scss
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx

Adding description modal to vmi details tab

---

src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceActions.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
src/views/virtualmachines/details/tabs/snapshots/SnapshotListPage.tsx
src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx
src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotRow.tsx

switch to `useModal` hook instead of using a state for each modal

consume useModal hook

---

src/views/virtualmachinesinstance/details/tabs/details/components/Details/Annotations/Annotations.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Description/Description.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Labels/Labels.tsx

Adding annotations modal to vmi details tab + change other modals to use createModal

---

src/utils/resources/template/hooks/useVmTemplates.tsx

remove redundant line in useVmTemplates

remove redundant line in useVmTemplates

---

.devcontainer/docker-compose.yml

copy gh authentication to dev container

copy gh authentication to dev container

---

src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
src/utils/components/HardwareDevices/HardwareDevices.tsx
src/utils/components/HardwareDevices/HardwareDevicesModal.tsx
src/utils/components/HardwareDevices/HardwareDevicesTable.tsx
src/utils/components/HardwareDevices/hardware-devices-table.scss
src/utils/components/HardwareDevices/hooks/useHCPermittedHostDevices.ts
src/utils/components/HardwareDevices/list/HardwareDevicesList.tsx
src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesColumns.tsx
src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

Overview Hardware Devices

---

src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.scss
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx

update scripts tab section design (increased title font size)
before:
after:

update scripts tab section design

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/environment/VirtualMachineEnvironmentPage.tsx
src/views/virtualmachines/details/tabs/environment/components/EnvironmentEditor.scss
src/views/virtualmachines/details/tabs/environment/components/EnvironmentEditor.tsx
src/views/virtualmachines/details/tabs/environment/components/EnvironmentSelectOption.tsx
src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabFooter.scss
src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabFooter.tsx
src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.tsx
src/views/virtualmachines/details/tabs/environment/hooks/useEnvironments.ts
src/views/virtualmachines/details/tabs/environment/hooks/useEnvironmentsResources.ts
src/views/virtualmachines/details/tabs/environment/utils/constants.ts
src/views/virtualmachines/details/tabs/environment/utils/utils.ts

adding environment tab to VM details
https://user-images.githubusercontent.com/67270715/162177113-00ced9b4-8880-4724-ba75-4ee7d790ee6f.mp4

add evnironment tab to VM details

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.scss
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/VirtualMachineLabels/VirtualMachineLabels.scss
src/views/virtualmachines/details/tabs/details/components/VirtualMachineLabels/VirtualMachineLabels.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

fixing stying to labels component on VM details page

fix labels styling on VM details page

---

locales/en/plugin__kubevirt-plugin.json
package.json
src/utils/utils/debounce.ts
src/utils/utils/utils.ts
src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/BlueArrowCircleUpIcon.tsx
src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SourceMissingStatus.tsx
src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SubscriptionStatus.tsx
src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/UpgradeApprovalLink.tsx
src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/WarningStatus.tsx
src/views/clusteroverview/overview/components/details-card/hooks/useDebounceCallback.ts
src/views/clusteroverview/overview/components/details-card/hooks/useKubevirtCSVDetails.ts
src/views/clusteroverview/overview/components/details-card/utils/types.ts
src/views/clusteroverview/overview/components/getting-started-card/GettingStartedCard.tsx
yarn.lock

This PR adds the details card to the cluster overview page.

Add details card to the cluster overview

---

src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Scheduling/Scheduling.tsx

Adding gutter to vmi details tab

---

.devcontainer/init.sh
start-console.sh

Pull latest console image with every run.
This will ensure the dev environment has the latest fixes and features.

Pull latest console image with every run

---

i18next-scanner.config.js
locales/en/plugin__kubevirt-plugin.json
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx

--------------------------
with error:

Add Wizard YAML tab

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx

Update catalog search input
before:
-------------------------
after:

Update catalog search input

---

src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabSkeleton.tsx
src/views/catalog/wizard/tabs/environment/components/WizardEnvironmentTabTitle.tsx

Add skeleton to Wizard Environment tab
before
https://user-images.githubusercontent.com/24938324/162695467-27016654-5331-4e51-8ed3-f20a0a105810.mov
-----------------------------
after
https://user-images.githubusercontent.com/24938324/162695494-cbc94da0-b7e3-45d7-ba3c-ddddd03f54a0.mov

Add skeleton to Wizard Environment tab

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx

fix vm list to fetch vmis, this improves the loading time, instead of making a call for each row with vmi  
before:
https://user-images.githubusercontent.com/67270715/162766235-f43d582a-2b11-454d-bd35-e791c8d1d1d7.mp4
after:
https://user-images.githubusercontent.com/67270715/162766392-146f0e4f-2adc-4b98-baab-a005b133fc07.mp4

fix vm list rows

---

src/views/catalog/wizard/Wizard.scss

update wizard footer css
This fixes dark mode showing a white footer.

update wizard footer css

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx

add dedicated, eviction modals to wizard scheduling tab

Add dedicated, eviction modals to wizard scheduling tab

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/HardwareDevices/list/hooks/useHardwareDevicesColumns.tsx
src/utils/components/TabModal/TabModal.tsx
src/views/catalog/customize/components/FormActionGroup.tsx
src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
src/views/templates/list/components/VirtualMachineTemplateSupport.tsx
src/views/virtualmachines/details/tabs/network/hooks/useNetworkColumns.ts

- Fix wrong translation hooks
- Fix loading buttons not being disabled

Fix wrong translation hooks

---

src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
src/views/catalog/customize/components/ExpandableOptionalFields.tsx

> Indent Expandable sections
> minor fix on select option 'Upload a new file'

Fix expandable sections

---

src/utils/resources/template/utils/selectors.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/scripts/components/cloud-init.scss

- Fix Scripts Tab default expanded section on Windows VMs. (Sysprep is now default)
- Fix Spacing and styling.

Fix Scripts Tab default expanded section on Windows VMs

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/template/utils/annotations.ts
src/utils/resources/template/utils/selectors.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts
src/views/catalog/customize/tests/CustomizeSource.test.tsx
src/views/catalog/customize/tests/mocks.ts
src/views/catalog/customize/utils.ts

> Use the annotations `template.kubevirt.io/images` and `template.kubevirt.io/containerdisks` to provide helper text in the form storage section

Add helper text to Customization form

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.scss
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx

Add Success Alert on YAML Wizard

---

src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/Wizard.tsx
src/views/catalog/wizard/components/WizardFooter.tsx
src/views/catalog/wizard/tabs.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx

Remove redundant wizard logic
- Remove redundant arguments from `createVM`
- Improve Wizard Tabs types
- Make `tabs.tsx`, `useVmWizardCreate`, and `WizardFooter` more readable

Remove redundant wizard logic

---

src/views/catalog/templatescatalog/TemplatesCatalog.scss
src/views/catalog/templatescatalog/TemplatesCatalog.tsx

Scrollable table and grid

---

src/utils/resources/template/hooks/useVmTemplateSource/utils.ts

fix datavolume find inside getTemplateBootSourceType

fix datavolume find inside getTemplateBootSourceType

---

console-extensions.json
package.json
src/views/templates/details/TemplateNavPage.tsx
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/details/VirtualMachineTemplatesDetailsPage.tsx
src/views/templates/details/hooks/useTemplateTabs.ts
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disk/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx

Template tabs page

---

src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx

Template yaml Editor

---

src/utils/resources/vmi/utils/index.ts
src/utils/resources/vmi/utils/pod.ts
src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Pods/Pods.tsx

VMI details page will now show one pod

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceList.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx
src/views/templates/details/tabs/network/components/modal/EditNetworkInterfaceModal.tsx
src/views/templates/details/tabs/network/components/modal/NetworkInterfaceModal.tsx
src/views/templates/details/tabs/network/components/modal/components/NameFormField.tsx
src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceMacAddressInput.tsx
src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceModelSelect.tsx
src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx
src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceTypeSelect.tsx
src/views/templates/details/tabs/network/components/modal/utils/constants.ts
src/views/templates/details/tabs/network/components/modal/utils/helpers.ts
src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
src/views/templates/details/tabs/network/hooks/useNetworkRowFilters.ts
src/views/templates/details/tabs/network/template-network-page.scss
src/views/templates/details/tabs/network/utils.ts

Template network tab

---

src/views/virtualmachinesinstance/details/tabs/yaml/VirtualMachinesInstancePageYAMLTab.tsx

Added YAML editor component to YAML tab at VMI details

Adding YAML editor to YAML Tab VMI

---

src/utils/components/AnnotationsModal/AnnotationsModalRow.tsx
src/utils/components/TabModal/TabModal.tsx
src/views/catalog/wizard/components/WizardNoBootModal.tsx

Update tab modal
- Fix buttons group size and spacing
- Add form and change submit button to `type=submit` (Now when clicking Enter on some forms, the modal triggers a submit)
- Add optional `positionTop` prop

Update tab modal

---

src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
src/views/catalog/wizard/components/WizardHeader.tsx

fix catalog breadcrumb css

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/vmi/utils/index.ts
src/utils/resources/vmi/utils/services.ts
src/views/virtualmachinesinstance/details/tabs/details/VirtualMachinesInstancePageDetailsTab.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Services/Services.tsx

Added services table to VMI details tab

Adding services table to vmi details tab

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx

add node selector modal to wizard scheduling

add node selector modal to wizard scheduling

---

cypress/cypress.json
cypress/reporter-config.json
cypress/tests/catalog/filter.spec.ts
src/utils/resources/template/hooks/useVmTemplates.tsx
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx

- fix templates hook returning 0 items in some cases
- make namespace switching faster
- use `groupVersionKind` instead of deprecated `kind`
- Add `TemplatesCatalogItems` Component

Improve `useVmTemplates`

---

src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
src/views/virtualmachines/details/tabs/details/components/sections/ServicesSection.tsx

Im adding sevices table to vm details tab

adding services table to vm details tab

---

package.json

https://github.com/openshift/console/pull/11273 is merged.
We can now combine the extensions of the static and dynamic plugin.

Stop disabling static plugin

---

src/views/catalog/utils/useWizardSourceAvailable.ts
src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx

- fix disks tab crashing when disks array is empty
- fix cloud init tab carshing when volumes array is empty
- boot source availability should set to false if no type is found

fix disks tab crashing when disks array is empty

---

src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
src/views/catalog/customize/components/CustomizeVirtualMachineSkeleton.tsx
src/views/catalog/customize/tests/CustomizeSource.test.tsx
src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx

fix customize skeleton and upload button
upload button would only trigger if you click on the text (won't trigger if you click the option)
new skeleton:

fix customize skeleton and upload button

---

src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/utils/resources/vm/utils/selectors.ts
src/utils/resources/vm/utils/source.ts

fix boot source selector for quick create and wizard

fix boot source selector

---

src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
src/views/virtualmachinesinstance/details/tabs/console/VirtualMachinesInstancePageConsoleTab.tsx

Chaining the space in vmi tab and in vm console tab

chainging the space in vmi console tab and in vm console tab

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx

add affinity modal to scheduling tab

add affinity modal to scheduling tab

---

src/views/virtualmachinesinstance/details/VirtualMachinesInstancePage.tsx
src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx

Adding title status in vmi page

adding title status in vmi

---

cypress/support/login.ts

[e2e] test navigate to virtualization overview

---

src/utils/components/DiskModal/EditDiskModal.tsx
src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
src/utils/components/DiskModal/utils/helpers.ts

fix edit disk modal #1

---

console-extensions.json
package.json
src/utils/components/Consoles/ConsoleStandAlone.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
src/views/virtualmachinesinstance/actions/VirtualMachinesInstanceActions.tsx
src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx

Added console stand-alone route and fix needed links and actions.

Adding console standalone route and fix links and actions

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts

Added support for ctrl + alt +1 , ctrl + alt +2 keys combination to console actions.

Added ctrl+alt+1 ctrl+alt+2 keys combination console:

---

src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/disks/components/DiskRow.tsx
src/views/templates/details/tabs/disks/components/DiskRowActions.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceRow.tsx

Common Template No Editable

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceEmptyState/VirtualMachineInstanceEmptyState.tsx

Adding virtual machine instance empty state

adding virtual machine instance empty state

---

src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx

wizard- move tolerations to scheduling

---

package.json
yarn.lock

update sdk 0.0.8

---

src/views/virtualmachinesinstance/details/VirtualMachinesInstancePage.tsx
src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceActions/VirtualMachineInstanceAction.tsx

adding actions to vmi page

---

src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineSchedulingLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineSchedulingRightGrid.tsx
src/views/virtualmachines/details/tabs/details/components/sections/SchedulingSection.tsx

Disable scheduling modal while VM is running 
https://user-images.githubusercontent.com/67270715/164980650-a34fbc60-472d-4145-9ec9-4bf08fdde415.mp4

Disable scheduling modal while VM is running 

---

src/utils/resources/vmi/utils/guest-agent.ts
src/utils/resources/vmi/utils/index.ts
src/views/virtualmachinesinstance/details/hooks/useGuestOS.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/UserList/ActiveUserList.tsx

Improved guest agent checks before requesting guest os. 
After:
Before:

Improve useGuestOS hook with guest agent check

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scheduling/components/Descheduler.tsx

add descheduler to wizard scheduling tab

add descheduler to wizard scheduling tab

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx
src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceEmptyState/VirtualMachineInstanceEmptyState.tsx

Fixed a bug in vmi creation

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx

The copy ssh command is now connected and if the command is available and the machine is running will copy the command to the clipboard.

Connecting copy ssh command button in vm overview tab

---

src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts

Changing the events tab location with the disks tab location in vmi

Changing the events tab with the disks tab in vmi

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/utils/resources/template/utils/helpers.ts
src/utils/resources/template/utils/index.ts
src/views/templates/actions/VirtualMachineTemplatesActions.tsx
src/views/templates/actions/editBootSource.ts
src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
src/views/templates/details/TemplateActions.tsx

Some logic to determine if template has editable boot source
- Template has a data volume related to the `rootdisk` Disk 
- That data volume has a `DataSource` as `sourceRef` 
- That `DataSource` has no `dataImportCron` job
Loading state:

Determine if template has editable Boot Source

---

src/utils/resources/shared.ts
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachinesinstance/actions/hooks/useVirtualMachineInstanceActionsProvider.tsx

Bug 2079783: Actions are broken in topology view

Bug 2079783: Actions are broken in topology view

---

src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/events/VirtualMachinePageEvents.tsx
src/views/virtualmachinesinstance/details/tabs/events/VirtualMachinesInstancePageEventsTab.tsx

Adding events tab to vmi and vm

Adding events tab to vm and vmi

---

package.json
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
webpack.config.ts
yarn.lock

fix slow SVG load in template catalog

fix slow SVG load in template catalog

---

src/views/virtualmachines/list/components/VMStatusConditionLabel/VMStatusConditionLabel.tsx
src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/VMStatusConditionLabel.test.tsx
src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabel.test.tsx.snap
src/views/virtualmachines/list/components/VMStatusConditionLabel/tests/__snapshots__/VMStatusConditionLabelList.test.tsx.snap

VM conditions column had wrong value. 
I changed the reason for type.
And I added in the pophover if there is no message that will appear the reason.
Before:
After:

Fixing the conditions column in vm

---

src/utils/resources/template/hooks/useVmTemplates.tsx
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts

Improve available source catalog performance
- Do not wait for projects if user is an admin
- Start fetching available sources before user checks checkbox
- Respect the `onlyDefault` filter when fetching available sources resulting in fewer API calls

Improve available source catalog performance

---

src/utils/resources/template/hooks/useVmTemplates.tsx
src/views/catalog/templatescatalog/hooks/useAvailableSourceTemplates.ts
src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/components/VirtualMachineTemplatesSource.tsx

Bug 2070864: non-privileged user cannot see catalog tiles
- Also improves performance of available sources in Template List

Bug 2070864: non-privileged user cannot see catalog tiles

---

src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
src/views/catalog/wizard/tabs/scripts/utils/cloudint-utils.ts

switch scripts tab ssh to new api

switch scripts tab ssh to new api

---

src/utils/hooks/useIsAdmin.ts
src/utils/resources/template/hooks/useVmTemplates.tsx
src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx

fix use isAdmin to use `useFlag`

fix useIsAdmin to use `useFlag` 

---

.gitignore
cypress/tests/inclusive-language.spec.ts

Migrated inclusive-language t2 test.

[e2] added test for inclusive language

---

src/utils/components/DebouncedTextInput/DebouncedTextInput.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx

create DebouncedTextInput component

create DebouncedTextInput component

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/wizard/components/WizardHeader.tsx

fix wizard header title

---

src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts

fix templates list filters and namespace changing

fix templates list filters and namespace changing

---

package.json
yarn.lock

bump kubevirt-api

---

src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/parameters/ParameterEditor.tsx
src/views/templates/details/tabs/parameters/ParameterValueEditor.tsx
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/parameters/template-parameters-page.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx

Bug 2081409: Template tabs with alert for common templates

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
src/views/templates/details/tabs/NoEditableTemplateAlert.tsx
src/views/templates/details/tabs/no-editable-template-alert.scss

Clone template modal in common template alert

---

src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx

fix template details page crash if no description available

fix template details page crash if no description available

---

src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
src/views/clusteroverview/overview/components/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
src/views/clusteroverview/overview/utils/utils.ts

Non-privileged users can not reach resources that are not on the projects they are project-admin on, thus can't watch resources without listing available projects first.
before:
after:

fix loading error for overview resources

---

src/views/catalog/wizard/tabs/scripts/components/CloudInit.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
src/views/catalog/wizard/tabs/scripts/components/cloud-init.scss

show ssh from in cloudinit editor view

show ssh form in cloudinit editor view

---

src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/utils/virtualMachineRowFilter.ts

Adding filter options by OS/Node to VM list view 

Add OS and Node filter to VM list view

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/views/catalog/customize/cd.ts
src/views/catalog/customize/constants.ts

Wizard Customize boot order

---

src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts

> When project is selected, no namespace column in the template list (like in other lists)

No namespace template list when in project

---

src/views/catalog/customize/drivers.ts
src/views/catalog/customize/utils.ts

Fix Windows drivers in customize wizard

---

src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
src/views/catalog/utils/tests/vm-produce.test.ts
src/views/catalog/utils/useWizardVmCreate.ts

move wizard create logic

---

src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts
src/views/catalog/customize/components/ExpandableOptionalFields.tsx
src/views/catalog/customize/tests/CustomizeForm.test.tsx
src/views/catalog/customize/tests/CustomizeSource.test.tsx
src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx

> Instead of leaving invariant the disk source, on checkbox checked, the disk source get changed on blank

Blank disk source on bootfromcd checkbox checked

---

src/utils/components/PendingChanges/utils/constants.ts
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudInit.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudInitAuthKeyHelp.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/CloudInitEditor.scss
src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/CloudInitEditor.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudInitEditor/index.ts
src/views/virtualmachines/details/tabs/scripts/components/CloudInitNetworkForm.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudinitForm.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudinitInfoHelper.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/CloudInitSSHKeyForm.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/SSHPopover/SSHPopover.tsx
src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/SSHPopover/ssh-popover.scss
src/views/virtualmachines/details/tabs/scripts/components/CloudinitSSHKeyForm/ssh-form-key.scss
src/views/virtualmachines/details/tabs/scripts/components/ScriptsTabFooter.tsx
src/views/virtualmachines/details/tabs/scripts/components/cloud-init.scss
src/views/virtualmachines/details/tabs/scripts/utils/cloud-init-data-helper.tsx
src/views/virtualmachines/details/tabs/scripts/utils/cloudint-utils.ts
src/views/virtualmachines/details/tabs/scripts/utils/use-cloudinit-validations.ts

VM Scripts tab

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/templatescatalog/TemplatesCatalog.scss
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx

add source available badge to catalog tiles

add source available badge to catalog tiles

---

src/views/catalog/wizard/tabs/scripts/components/CloudInitEditor/CloudInitEditor.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudInitNetworkForm.tsx
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx

Bug 2081202: cloudinit undefined for windows vms

---

src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
src/views/clusteroverview/overview/components/inventory-card/utils/vm-status-section/VMStatusInventoryItem.tsx
src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx
src/views/clusteroverview/overview/utils/utils.ts

buttons we leading to incorrect URLs
before:
https://user-images.githubusercontent.com/67270715/167864874-d264f217-3593-4343-b25e-b01a6d2396d9.mp4
https://user-images.githubusercontent.com/67270715/167864878-97fc084b-411c-48b3-8897-8eedd9112046.mp4
https://user-images.githubusercontent.com/67270715/167865682-0ed8d9d3-80a0-450b-a833-79d7e1ec783c.mp4
after:
https://user-images.githubusercontent.com/67270715/167864951-c13c338f-4c46-49c8-8bf6-195fa2828e65.mp4
https://user-images.githubusercontent.com/67270715/167864954-2d3acebc-a898-4246-a598-fb91026c19ae.mp4
https://user-images.githubusercontent.com/67270715/167864956-53bf1f50-c15e-43aa-821f-b86e93610e03.mp4

Bug 2076908: Fix overview urls

---

src/utils/components/CloudInit/components/CloudInitNetworkForm.tsx
src/utils/components/CloudInit/components/CloudinitForm.tsx
src/utils/components/CloudInit/utils/cloudint-utils.ts
src/views/catalog/wizard/tabs/scripts/components/CloudinitForm.tsx
src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
src/views/virtualmachines/details/tabs/scripts/utils.ts

Bug 2084476: VM scripts tab Auth SSH Key fetch

---

src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx
src/views/catalog/customize/tests/PersistentVolumeClaimSelect.test.tsx

- Windows Driver checkbox only for windows templates
- URL as first option on cd book check 
- just some ids for tests

Customize Form other fixes

---

src/views/catalog/templatescatalog/TemplatesCatalog.scss
src/views/catalog/templatescatalog/components/TemplateRowAvailableSource.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
src/views/catalog/templatescatalog/hooks/useTemplatesCatalogColumns.ts
src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts

Adds Boot source available column to the Catalog table view

update catalog table view

---

src/utils/components/AffinityModal/utils/helpers.ts

Adding affinity rules was creating the entire affinity object even if terms were empty
before:
https://user-images.githubusercontent.com/67270715/168469239-8875f3ab-606f-41ae-bb8f-b1579a122313.mp4
after:
https://user-images.githubusercontent.com/67270715/168469246-2e2a1dfb-dd64-4f9d-b939-584d0f5d3bc0.mp4

Bug 2079674: Configuring preferred node affinity in the console results in wrong yaml and unschedulable VM

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx

change VM migrate action label
before:
after:

Bug 2071488: "Migrate Node to Node" is confusing.

---

src/utils/resources/template/utils/selectors.ts
src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/utils/helpers.ts

Adding custom templates to show also under 'Default templates' filter option
before:
https://user-images.githubusercontent.com/67270715/168559030-dd926657-6969-4186-8f2e-194fc7814bff.mp4
after:
https://user-images.githubusercontent.com/67270715/168559066-217c5e97-1376-472f-a772-e56b746c0b29.mp4

Add custom templates to 'Default template' filter

---

src/utils/resources/template/utils/constants.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/utils/quick-create-vm.ts

> Labels to retrieve template info after VM creation

Bug 2086769: Adding labels during wizard vm creation

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

adding support for BIOS/UEFI for templates
https://user-images.githubusercontent.com/67270715/168588908-7c72845a-05d4-4c8d-98b4-2b603db284aa.mp4
https://user-images.githubusercontent.com/67270715/168588919-d3ed0baa-c03e-49df-8c92-2625e07e2de7.mp4
@yaacov please review

Add BIOD/UEFI support for templates

---

src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.scss
src/utils/styles/_secondary-editor.scss
src/views/catalog/wizard/Wizard.scss

add custom css to wizard editor buttons
**Before**
**After**

add custom css to wizard editor buttons

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
src/utils/resources/template/utils/constants.ts

https://bugzilla.redhat.com/show_bug.cgi?id=2086803

Bug 2086803: Update VM Labels on template cloning

---

src/utils/components/CloudinitModal/CloudinitModal.tsx
src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
src/utils/components/CloudinitModal/utils/useCloudInit.ts

fix cloudinit modal overriding chpasswd value

fix cloudinit modal overriding chpasswd value

---

console-extensions.json
package.json
src/templates/index.ts
src/templates/vm-template-yaml.ts
src/templates/vm-yaml.ts

> YAML example template for the 'Create with YAML' VM page

Bug 2086849: Create VM yaml with something working

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/hooks/useTemplateTabs.ts
src/views/templates/details/tabs/scripts/TemplateYAMLPage.tsx

Template Scripts Tab

---

src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx

Bug 2087584: Template provider should not be mandatory

---

src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
src/utils/resources/template/utils/constants.ts
src/utils/resources/vm/utils/source.ts
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/utils/useWizardSourceAvailable.ts
src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts

**Boot source change label**: No "PVC (auto upload)" for template with data source that does not have the label `cdi.kubevirt.io/dataImportCron` (Windows and RHEL 7 templates in the screenshot)

Bug 2078700: PVC (auto upload) fix

---

src/utils/components/DiskModal/DiskFormFields/DiskInterfaceSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceContainer.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx
src/utils/components/DiskModal/DiskFormFields/DiskTypeSelect.tsx
src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx
src/utils/components/DiskModal/DiskFormFields/utils/Filters.tsx
src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
src/views/catalog/customize/components/CustomizeSource/VolumeSize.tsx
src/views/catalog/customize/components/FieldGroup.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx

Adding "data-test-id" to elements.

Bug 2084102: Adding data-test-id to elements

---

console-extensions.json
locales/en/plugin__kubevirt-plugin.json
src/templates/vm-template-yaml.ts
src/views/templates/list/VirtualMachineTemplatesList.tsx

Bug 2088407: Create Template button

---

console-extensions.json
src/utils/hooks/constants.ts
src/utils/hooks/useLastNamespace.ts
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
src/views/virtualmachinesinstance/details/VirtualMachinesInstancePageHeader.tsx
src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx

before: click on template => template detail (in the template namespace) => click on the template menu -> template list in the template namespace
now clicking on template menu you get redirected always to template list in all-namespaces

Bug 2087232: all-namespace back to template list

---

src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsoleConnect.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/virtual-machines-overview-tab-details.scss

Align the single VM overview page- details card, follow a design update.

Bug 2087603: Align single vm details card with updated design

---

src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/RunningVMsChartLegendLabel.tsx

Bug 2087559: template in "VMs per template" should take user to vm list

Bug 2087559: template in "VMs per template" should take user to vm list

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

> Hide edit pencil if no running vm

Bug 2084431: no ssh service edit if no running vm

---

src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx

> windows drivers checkbox will be showed in the customize form in any template

Bug 2089789: windows drivers checkbox for all templates

---

src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachines/list/components/VirtualMachineActions/VirtualMachineActions.tsx

Adding more data-test-id to elements.

Bug 2084102: Adding more data-test-id to elements

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/actions/components/EditBootSourceModal.tsx

Bug 2087717: Message when editing template boot source is wrong

Bug 2087717: Message when editing template boot source is wrong

---

src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/utils/quick-create-vm.ts

Create VM from catalog does not respect the storageclass

Bug 2088379: Create VM from catalog does not respect the storageclass

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx

>We have to take this info from the template
Without guestagent
With guestagent

Bug 2089963: Add VM os label and annotations from template

---

src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/EditDiskModal.tsx
src/utils/hooks/useCDIUpload/useCDIUpload.ts
src/utils/hooks/useCDIUpload/utils.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/components/FormActionGroup.tsx
src/views/catalog/customize/tests/CustomizeForm.test.tsx
src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
src/views/catalog/utils/WizardVMContext/WizardVMContext.tsx
src/views/catalog/utils/WizardVMContext/useWizardVMEffects.ts
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx

fix upload in wizard not adding owner references

---

src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/AffinityEditRow.tsx
src/utils/components/AffinityModal/components/AffinityEditModal/AffinityForm/components/affinity-edit-row.scss

https://bugzilla.redhat.com/show_bug.cgi?id=2090131

Bug 2090131: Affinity chips style

---

src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/EditDiskModal.tsx
src/utils/components/DiskModal/utils/editDiskModalHelpers.ts
src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx

fix upload disk hotplug promise

fix upload disk hotplug promise

---

src/utils/resources/vm/utils/selectors.ts

Bug 2090056:  "Something went wrong" shows on VM "Environment" tab

---

src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx

> Don't change namespace after VM deleted
Before:
After

Bug 2091058: same namespace in vm delete

---

src/utils/resources/vmi/utils/services.ts
src/utils/resources/vmi/utils/tests/mocks.ts
src/utils/resources/vmi/utils/tests/services.test.ts

Bug 2090054: Services “kubernetes" and "openshift" should be hidden

---

src/utils/components/DiskModal/DiskModal.tsx
src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts

fix wizard disks tab not showing URL source

fix wizard disks tab not showing URL source

---

src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

Adding link to vm template in vm details page
Before:
After:

Bug 2090055: Adding link to vm template in vm details page

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/SSHAccess/SSHAccessModal.tsx

Remove VM name from SSH modal.
After:
Before:

Bug 2089982: Remove VM name from SSH modal

---

src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts
src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts

Bug 2087583: Show more info about boot source in template list

Bug 2087583: Show more info about boot source in template list

---

src/views/templates/details/NoEditableTemplateAlert.tsx
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/details/no-editable-template-alert.scss
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scripts/TemplateYAMLPage.tsx
src/views/templates/details/tabs/yaml/TemplateYAMLPage.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2091762
> Alert notification on top details page and not anymore in the tabs body

Bug 2091762: Template alert on details title

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts

Added time span of 5 minutes for utilization card at VM overview

Bug 2089877: Adding 5 minutes timespan utilization card VM overview

---

src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx

when we are at Template's details page and we delete the template, we should be led to template's list
https://user-images.githubusercontent.com/67270715/171168625-ffb2efec-02f8-4b06-8ba6-3e74e23319ca.mp4
https://user-images.githubusercontent.com/67270715/171168669-3d157cc8-bf58-4141-95d1-4cba1dcdb441.mp4

Bug 2091945: delete a template should lead to templates list

---

src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
src/views/catalog/wizard/components/WizardHeader.tsx

Bug 2092052: Virtualization should be omitted in Calatog breadcrumbs

---

src/utils/components/DiskModal/utils/editDiskModalHelpers.ts

fix undefined edit disk modal data volume templates

fix undefined edit disk modal data volume templates

---

src/utils/components/UserCredentials/useSSHCommand.ts

follow-up fix to https://github.com/kubevirt-ui/kubevirt-plugin/pull/478
@yaacov @upalatucci please review

Bug 2081182: fix ssh string undefined

---

src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx

Bug 2092359: Data-test-id pvc name

---

src/utils/components/SSHAccess/SSHAccessModal.tsx
src/utils/components/SSHAccess/utils.ts
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/SSHAccess/SSHAccess.tsx

Adding ownerRef to ssh service

Bug 2091003: Delete ssh service after vm delete

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts

VM overview - Network, CPU, and Memory ThresholdCharts will now be linked to metrics

Bug 2089942: Utilization chart links to metrics

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/template/utils/constants.ts
src/utils/resources/template/utils/helpers.ts
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts

> Deprecate badge
> Wider name column
Before
After

Bug 2092230: Template list deprecated badge

---

src/views/catalog/wizard/tabs/environment/utils.ts

Console crash when no serial is found in environment tab

Bug 2093773: Console crash when no serial at environment tab

---

src/views/catalog/wizard/tabs/environment/utils.ts

Secret or ConfigMap names cant contain dots, replaced with dash.

Bug 2094678: Secret or ConfigMap name replace dots

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AffinityModal/AffinityModal.tsx

Bug 2094491: change affinity modal primary button text

---

src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectCDSourcePopOver.tsx
src/views/catalog/customize/components/CustomizeSource/SelectDiskSourcePopOver.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx

> helpicon after required form input symbol ( * )  
Before
After

Bug 2094222: Popover in formgroup with labelIcon

---

src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx

Bug 2094471: Node selector modal for non-privileged user

---

src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

No node column in VM list for use that does not have access to nodes

Bug 2095532: Hide Node column in vm list if no-prov

---

src/utils/components/CloudinitDescription/CloudInitDescription.tsx

Hide cloudinit password
Before:
After:

Bug 2094813: Hide cloudinit password

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

No node info in VM detail if user has no access to nodes
**Before**
**After**

Bug 2095570: No node in vm detail if no-priv

---

src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx

1. Fix Blank VM Details name until k8s hook succeeds
2. Fix Wrong size of Create Template button in list page
Fixed the following:

Fix VM Details blank name

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx

VM single overview - the console will be auto connect now

Bug 2096801: VM overview VNC autoconnect

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/Consoles.tsx
src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
src/utils/components/Consoles/components/vnc-console/vnc-console.scss

Ig a VM has VGPUS we will provide the options to switch to screen1 and screen2 , same as clicking ctrl+alt+1/2
Before:
After:

Bug 2095955: Adding console screen1 and screen2 tabs

---

src/views/catalog/templatescatalog/utils/helpers.ts

Bug 2096208: Templates in the catalog list are not sorted

Bug 2096208: Templates in the catalog list are not sorted

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts

Bug 2092663: no hyperlink for URL example in disk source

Bug 2092663: no hyperlink for URL example in disk source

---

src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx

Bug 2093282: No inventory links for no-priv user

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/actions/components/EditBootSourceModal.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2096781
Provider input useless

Bug 2096781: Remove provider input

---

src/utils/components/CloudinitDescription/CloudInitDescription.tsx

Bug 2096845: Windows templates scripts tab is crashed

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/components/AccessConsoles/AccessConsoles.tsx
src/utils/components/Consoles/components/AccessConsoles/access-consoles.scss
src/utils/components/Consoles/components/vnc-console/VncConsoleActions.tsx
src/utils/components/Consoles/components/vnc-console/vnc-console.scss

Moving consoles buttons
After:
Before:

Bug 2095953: Moving consoles buttons

---

src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/virtual-machine-row-layout.scss
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

With no condition there were some width problems 
**Before**
https://bugzilla-attachments.redhat.com/attachment.cgi?id=1889701
**After**

Bug 2095530: fix empty column width

---

src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx

Remove the 'Restore default settings' button. 
Default settings are the template settings and we are editing them so this button has sense only in the VM detail

Bug 2096502: No 'Restore default settings' in template

---

src/utils/components/LabelsModal/LabelsModal.tsx
src/views/catalog/templatescatalog/TemplatesCatalog.scss
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss

Also added border for template grid items in dark mode
fixed quick create footer border in dark mode

Bug 2086286: [dark mode] The contrast of the Labels

---

src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx

`Learn more about Operators`: `https://access.redhat.com/documentation/enus/openshift_container_platform/4.10/html/operators/`
Needs to be updated when 4.11 documentation will be released

Bug 2092789: Overview learn more

---

src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx

Bug 2094217: YAML view should reflect shanges in SSH form

---

src/views/catalog/wizard/tabs/environment/utils.ts
src/views/virtualmachines/details/tabs/environment/utils/utils.ts

add array fallback to environment utils

---

src/views/catalog/utils/useWizardSourceAvailable.ts

https://user-images.githubusercontent.com/67270715/174023290-405ba9c1-14b6-4643-9436-848d7aa3a759.mp4
https://user-images.githubusercontent.com/67270715/174023356-0abd1c88-f6c7-4221-a2f1-941e087df5cc.mp4

Bug 2096510: VM can be created without any disk

---

src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx

**Before**
**After** 
Only for no priv users
With external links to the relative operator documentation

Bug 2092787: No operators links for no-priv user

---

src/utils/hooks/constants.ts
src/utils/hooks/useLocalStorage.ts
src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx
src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx
src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumersGridRow.tsx
src/views/clusteroverview/overview/components/top-consumers-card/utils/constants.ts
src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerMetric.ts
src/views/clusteroverview/overview/components/top-consumers-card/utils/topConsumerScope.ts
src/views/clusteroverview/overview/components/top-consumers-card/utils/utils.ts

This PR persists settings for the top consumers card to local storage to prevent resetting of the layout.

Bug 2089825: Persist top consumer card settings

---

src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts

Bug 2098134: Workload column more visible

---

src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

Bug 2090042: Move pencil icon for BootOrder

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/utils/components/VMAuthorizedSSHKeyModal/VMAuthorizedSSHKeyModal.tsx
src/utils/utils/utils.ts

SSH input was missing validation for key

Bug 2094208: Adding ssh public key validation to input field

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts

When trying to create a VM from a template with no disks, we get an error when clicking on review and create VirtualMachine
https://user-images.githubusercontent.com/67270715/174563523-07ee9ea2-45c2-4039-8aaa-d2a5d091698e.mp4
https://user-images.githubusercontent.com/67270715/174563566-1b0fa422-5be5-42f7-bcea-7d3a3634130e.mp4

Bug 2096510: template with no disks cant create VM

---

src/utils/components/DiskModal/EditDiskModal.tsx
src/utils/components/TabModal/TabModal.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2098282
minor fix

Bug 2098282: Ensure onUploadedDataVolume exist

---

src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/environment/utils.ts
src/views/virtualmachines/details/tabs/environment/VirtualMachineEnvironmentPage.tsx
src/views/virtualmachines/details/tabs/environment/utils/utils.ts

Console crash when no serial at environment tab VM page

Bug 2093773: Console crash when no serial at environment tab VM page

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss

Align key-value pairs.
After:
Before:

Bug 2087616: Fix some css regarding utilization card

---

src/templates/vm-template-yaml.ts
src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
src/utils/resources/vm/utils/disk/selectors.ts

https://bugzilla.redhat.com/show_bug.cgi?id=2099443
**Cause**
- Required parameter for template yaml example
- ContainerDisk ignored as ready-to-be-used boot source
**Solution**
- Manage containerDisk boot sources
- Template YAML example with no required parameters

Bug 2099443: Quick create for template examples

---

src/utils/components/DiskModal/DiskFormFields/EnablePreallocationCheckbox.tsx
src/utils/components/SSHAccess/constants.ts
src/views/virtualmachines/details/tabs/snapshots/components/modal/SnapshotSupportLink/SnapshotSupportLink.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2099633
Just a little update of doc links from 4.9 to 4.10

Bug 2099633: Doc links 4.9 -> 4.10

---

src/utils/components/DiskModal/EditDiskModal.tsx

Replicate the DiskModal condition also for EditDiskModal

Bug 2099539: Upload file storage option in edit modal

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/utils/utils.ts

Adding times as X axe and tick to threshold lines.
After:

Bug 2095537: Utilization charts adding hours to charts

---

src/views/catalog/customize/components/FormError.tsx

CDI certificate link will be open in a new tab

Bug 2099535: CDI certificate link will open in a new tab

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/UserCredentials/UserCredentials.tsx

Remove ssh user line above the ssh command
After:
Before:

Bug 2099639: remove ssh user line above ssh command

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloudinitModal/CloudinitForm.tsx
src/utils/components/CloudinitModal/CloudinitModal.tsx

Remove default user message, making field required.

Bug 2094202: cloudinit username default

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/NoEditableTemplateAlert.tsx

Change text in uneditable templates alert message
After:
Before:

Bug 2099573: Change text in uneditable templates alert message

---

src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
src/utils/components/AuthorizedSSHKeyModal/auth-ssh-key-modal.scss
src/utils/components/AuthorizedSSHKeyModal/utils.ts
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx

Add secret selection in the 'Authorized SSH Key' modal (scripts tab)

Wizard auth secret selector

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
src/views/templates/details/hooks/useTemplateTabs.ts
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx

Adding secret selection in template scripts tab

Bug 2096780: Template Auth SSH Service

---

src/views/catalog/customize/components/ExpandableOptionalFields.tsx

**Cause**
No optional parameters. All required. (name parameter does no count)
**Solution**
Fix optional fields component

Bug 2101430: Fix customize form crash

---

OWNERS

Add avivtur to approvers

---

src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts

Fix `Source available` label in the template list. (if PVC does not exist or there is no boot source don't show the label)
Also in templatecatalog don't show the label when boot source not available

Bug 2101681: Template list fix source available

---

src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx

Bug 2101394: Changing the data-test-id

---

src/views/catalog/templatescatalog/hooks/useTemplatesWithAvailableSource.ts
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts

backporting [this](https://github.com/kubevirt-ui/kubevirt-plugin/pull/691)

[release-4.11] Bug 2102129: Template list fix source available

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

showing the DV size instead of the actual size that exists in the PVC
https://user-images.githubusercontent.com/67270715/176427171-56277c82-e022-491a-9d04-95192d2546a5.mp4
https://user-images.githubusercontent.com/67270715/176427201-602accbe-567d-4509-8d67-3cc56d815236.mp4

Bug 2102125: vm clone modal is displaying DV size instead of PVC size

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelectName.tsx

backporting [this](https://github.com/kubevirt-ui/kubevirt-plugin/pull/688)

[release-4.11] Bug 2102122: DataSource selection with parameter

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/VirtualMachinesOverviewTabAlerts.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/utils/utils.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabAlerts/virtual-machines-overview-tab-alerts.scss

The label component will now be using patternfly setting for colors, so in the dark mode, the colors will adjust automatically. 
After:
Before:

Bug 2101164: VM overview alerts title - dark mode

---

src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
src/views/templates/details/tabs/scheduling/components/Tolerations.tsx

[release-4.11] Bug 2102116: Adding data-test-id on Template Scheduling tab

---

src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx

backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/701

[rls-4.11] Bug 2102127: Template adding nic keep loading for test user

---

src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx

[release-4.11] Bug 2102117: Adding data-test-id on vm Scripts tab

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx

On VM clone, redirect to cloned VM details

Bug 2102737: On VM Clone redirect to vm details

---

src/views/virtualmachines/utils/virtualMachineRowFilter.ts
src/views/virtualmachines/utils/virtualMachineStatuses.ts

Bug 2100436: VM list filter failed vms

---

src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx

Exception raised one time for `undefined has no method getDropdownLabel`

Fix top consumer exception

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss

Center title.
Make pie chart smaller.
Make threshold charts smaller.
Enlarge font of ticks
After:
Before:

Bug 2102132: align utilization charts

---

src/views/clusteroverview/overview/components/OverviewTab/details-card/DetailsCard.tsx
src/views/clusteroverview/overview/components/OverviewTab/details-card/hooks/useKubevirtCSVDetails.ts
src/views/clusteroverview/overview/components/SettingsTab/General Tab/GeneralTab.tsx
src/views/clusteroverview/overview/components/SettingsTab/SettingsTab.tsx

This is the first pr for this part of the feature.
Adding a general tab, with no content, editing the kubevirt csv hook.
Next prs will be moving the hook to a more suitable location, adding content to general tab

CNV-19412: Add general tab , editing kubevirt csv hook

---

src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/constants.ts
src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/hooks/useKubevirtStorageOperatorCSVs.ts
src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/storage-health-item/StorageHealthItem.tsx
src/views/clusteroverview/overview/components/OverviewTab/status-card/utils/utils.tsx

This PR fixes a bug that prevented the correct reporting of the ODF operator's status on the overview page.
Screenshot:

Bug 2104422: Fix ODF operator status on overview page

---

src/views/clusteroverview/overview/components/status-card/utils/constants.ts
src/views/clusteroverview/overview/components/status-card/utils/hooks/useKubevirtStorageOperatorCSVs.ts
src/views/clusteroverview/overview/components/status-card/utils/storage-health-item/StorageHealthItem.tsx
src/views/clusteroverview/overview/components/status-card/utils/utils.tsx

This PR fixes a bug that prevented the correct reporting of the ODF operator's status on the overview page.
Screenshot:

Bug 2104617: Fix ODF status reporting on overview page

---

src/views/catalog/wizard/tabs/disks/components/DiskListTitle.tsx

Bug 2104785: Disks wizard title in new line

---

src/utils/resources/template/utils/helpers.ts
src/views/templates/details/tabs/scripts/SysPrepDescription.tsx
src/views/templates/details/tabs/scripts/SysPrepItem.tsx
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
src/views/templates/details/tabs/scripts/sysprep-utils.ts

Template existing sysprep selection

Bug 2096780: Template sysprep selection

---

src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/DurationDropdown.tsx

Bug 2106175: All pages are crashed after visit Virtualization -> Overview

---

src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx

Bug 2106258: add dropdown label safetynet 4.11

---

src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts
src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts

for `containerDisk`(EPHEMERAL) and `persistentVolumeClaim` (PERSISTENT_VOLUME_CLAIM) volume source, the `isBootDisk` flag was not used

Bug 2107279: Fix disk modal is boot source

---

src/views/virtualmachines/list/VirtualMachinesList.scss
src/views/virtualmachines/list/VirtualMachinesList.tsx

fix vm list create dropdown margin
Before:
------------------------------------------------------
After:

fix vm list create dropdown margin

---

src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/TopConsumersChartList.tsx
src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/queries.ts
src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/utils.ts

Bug 2106258: All pages are crashed after visit Virtualization -> Overview

---

src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsChartDonut/MigrationChartLegend.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsChartDonut/MigrationsChartDonut.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/hooks/useMigrationCardData.ts

Fixing the filtering via the migration donut chart legend.
https://user-images.githubusercontent.com/67270715/180035020-7ed00833-1f15-444b-bb66-06c32b923aab.mp4
https://user-images.githubusercontent.com/67270715/180035040-3f7d905c-7128-46af-a8b2-eefa640b7ad5.mp4

Add filters to migrations donut chart legend

---

src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
src/utils/components/StartPauseModal/StartPauseModal.tsx
src/utils/resources/shared.ts
src/views/clusteroverview/OverviewTab/activity-card/hooks/useDashboardPrometheusActivities.ts
src/views/clusteroverview/OverviewTab/status-card/utils/hooks/useDashboardSubsystems.ts
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

fix eslint warnings 0722

---

src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
src/views/templates/details/tabs/disks/components/DiskRow.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTableRow.tsx

Bug 2103806: PVC 404

---

src/utils/components/Charts/utils/utils.ts
src/utils/components/DurationOption/DurationDropdown.tsx
src/utils/components/DurationOption/DurationOption.ts
src/views/clusteroverview/MonitoringTab/migrations-card/MigrationsCard.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/utils/utils.ts
src/views/clusteroverview/MonitoringTab/top-consumers-card/TopConsumersCard.tsx
src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx
src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/TimeDropdown.tsx

Moving durationoption and dropdown to shared location

Moving durationoption to share location

---

src/utils/resources/vmi/utils/ips.ts

Fix vm list crash

---

src/utils/components/LabelsModal/LabelsModal.scss
src/utils/components/LabelsModal/LabelsModal.tsx

fix labels modal height
before
after

fix labels modal height

---

src/utils/components/BootOrderModal/BootOrderModalBody.tsx
src/utils/components/PendingChanges/utils/helpers.ts

Pending changes should not appear if nothing relevant has changed.
Before:
After:

Bug 2101445:  Pending changes should not appear if nothing relevant has changed

---

src/views/catalog/customize/cd.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
src/views/templates/details/tabs/network/utils.ts

Bug 2060499: Replace vm object correctly into template

---

src/utils/components/EnvironmentEditor/components/EnvironmentFormSkeleton.tsx

fix environments tab skeleton wrong padding
before
after

fix environments tab skeleton

---

src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
src/views/catalog/customize/drivers.ts
src/views/catalog/customize/utils.ts
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
src/views/templates/details/tabs/scheduling/components/EvictionStrategyModal.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx
src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx

Template with multiple objects can have the vm at any index

Bug 2060499: getTemplateVirtualMachineObject instead of objects[0]

---

src/utils/resources/template/utils/helpers.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/utils/quick-create-vm.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/utils/utils.ts

Create additional template objects in wizard

Create additional template objects in wizard

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AdditionalResources/AdditionalResources.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx

Show which objects will be created alongside the VM

Bug 2060499: Template additional resources

---

src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
src/utils/resources/template/utils/constants.ts

Cloned templates carry a common template label.
This fix will change from common-template value of the label to custom-template
After:
Before:

Bug 2111744: change cloned template label

---

src/utils/components/DurationOption/DurationOption.ts

Adding a missing check to milliseconds in case it's undefined. 

Bug 2114683: Overview crash -milliseconds time

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DeleteModal/DeleteModal.tsx
src/views/migrationpolicies/actions/hooks/useMigrationPoliciesActionsProvider.tsx
src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/BandwidthInput/BandwidthInput.tsx
src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/CompletionTimeoutInput/CompletionTimeoutInput.tsx
src/views/migrationpolicies/components/MigrationPolicyConfigurationsFormGroup/MigrationPolicyConfigurationsFormGroup.tsx
src/views/migrationpolicies/components/MigrationPolicyEditModal/MigrationPolicyEditModal.tsx
src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/constants.ts
src/views/migrationpolicies/components/MigrationPolicyEditModal/utils/utils.ts
src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyProjectLabels.tsx
src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyVirtualMachineLabels.tsx
src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/MigrationPolicyCreateForm.tsx
src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/utils/utils.ts
src/views/migrationpolicies/utils/utils.ts

This PR includes:
Adding edit MigrationPolicy configuarions modal (spec section).
Fixing DeleteModal to route to correct page after delete action is created
Restructing migrationpolicies directory
https://user-images.githubusercontent.com/67270715/183411488-01145732-9993-49c7-aa22-be251b82f3b1.mp4

CNV20022: Edit MigrationPolicy action and modal

---

src/views/templates/utils/utils.ts
src/views/virtualmachinesinstance/details/tabs/scheduling/Descheduler/Descheduler.tsx

Descheduling page crash

---

src/views/clusteroverview/OverviewTab/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx

changing operator hub filter keyword from ocf to odf

Bug 2116225: Changing link from OCS to ODF

---

.github/workflows/ci_checks.yml
package.json
src/utils/components/EnvironmentEditor/components/EnvironmentEditor.tsx
src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
src/utils/components/EnvironmentEditor/tests/mocks.ts
src/utils/components/EnvironmentEditor/tests/useEnvironments.test.tsx
src/utils/components/EnvironmentEditor/tests/utils.test.ts
src/utils/components/EnvironmentEditor/utils.ts

**Cause**
Save button enabled and disabled at the wrong moment
- vm update return environments with a different order.
- Comparison of new and old envs based on the index
**Solution**
Does not base the comparison on the index

Bug 2104402: Envs Save button fix

---

src/utils/components/TolerationsModal/TolerationModalDescriptionText.tsx

Change toleration modal link

---

src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

Bug 2092796: Change cpu and memory appearance values

---

console-extensions.json

Fixing this according to [this pr](https://github.com/openshift/console/pull/11793)

Fix template console-extensions model

---

src/utils/components/SysprepModal/sysprep-utils.ts
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
src/views/catalog/wizard/tabs/scripts/components/sysprep-utils.ts
src/views/templates/details/tabs/scripts/components/SysPrepItem/sysprep-utils.ts

same as #831  but for sysprep.
User can edit and detect sysprep config using template objects array

Bug 2096780: Wizard with sysprep in additionalResources

---

src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
src/views/virtualmachinesinstance/details/tabs/disks/table/disks/DisksTable.tsx

In the Disks tabs we don't need the option to filter by label.
Before: 
After:

Bug 2120907: Remove the option to filter by label in the Disks tabs

---

Dockerfile
cypress/tests/catalog/filter.spec.ts
cypress/utils/const/template.ts
deploy-kubevirt-gating.sh
test-prow-e2e.sh

Bug 2115280: Fix ci HCO version

---

src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/details/virtual-machine-page-title.scss

Vertical align label

---

cypress/support/nav.ts
cypress/support/project.ts
cypress/support/selectors.ts
cypress/tests/check-tabs.spec.ts
cypress/tests/overview.spec.ts
cypress/utils/const/index.ts
cypress/views/selector.ts
cypress/views/tab.ts
cypress/views/vm.ts

To test that all pages are loaded normally:
1. revert overview test to ensure overview page is loaded
2. add new tests about VM/VMI tabs and template's tabs
3. the catalog tests should already cover the catalog page

check all pages can be loaded normally

---

src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/actions/hooks/useVirtualMachineInstanceMigration.ts
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/MigrationProgressPopover.tsx
src/views/virtualmachines/list/VirtualMachinesList.scss
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts
src/views/virtualmachines/list/hooks/utils/utils.ts
src/views/virtualmachines/utils/index.ts
src/views/virtualmachines/utils/utils.ts
src/views/virtualmachines/utils/virtualMachineRowFilter.ts

- Added pagination 
- VMI, VMIM mappers - instead of using find on each for every vm
- Removing VMIM request for each VM
- Improve filters results and logic include sorting

Improving virtual machine list performance

---

src/views/datasources/list/CreateDataSourceModal/CreateDataSourceForm.tsx
src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx

1. remove docker:// from the example URL
2. add a check that if docker://doesn't exist, it will be added otherwise not.
After:
Before:

Bug 2124594: Docker prefix - create datasource

---

locales/en/plugin__kubevirt-plugin.json
src/views/datasources/list/DataSourcesList.tsx

Bug 2124597: Datasource Typo

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/EnvironmentEditor/utils.ts

Specify the bus type in order to avoid the error

Bug 2106963: Env bus type fix

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/SidebarEditor/SidebarEditor.tsx
src/utils/components/SidebarEditor/SidebarEditorContext.tsx
src/utils/components/SidebarEditor/SidebarEditorSwitch.tsx
src/utils/components/SidebarEditor/sidebar-editor.scss
src/utils/components/SidebarEditor/utils.ts
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx
src/views/virtualmachines/details/tabs/details/components/sections/DetailsSection.tsx
src/views/virtualmachines/details/tabs/scheduling/VirtualMachineSchedulingPage.tsx
src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.tsx

Form - yaml editor side by side.
The user should be able to see how the changes in the forms affect the yaml
We have here 3 new components.
Context, Switch, and Editor
Follow-up pr would add this feature also to the wizard and to the templates

CNV-19687: Sidebar editor

---

src/views/virtualmachines/utils/virtualMachineRowFilter.ts

Fix filter by OS that was broken- VM list.

Bug 2124582: Fix filter by OS - VM list

---

src/utils/components/AnnotationsModal/AnnotationsModal.tsx

Datasource are created without annotations, and annotations modal was missing default empty object value fo case there aren't annotations on an object.

Bug 2124572: Datasource add annotations fix

---

src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/components/MigrationPolicyDescriptionItem.tsx

Added description to the migration policy page
After:
Before:

Bug 2124557: Add description of migration policy to migration policy page

---

Dockerfile

Backport of dockerfile fix from https://github.com/kubevirt-ui/kubevirt-plugin/pull/854

Match http path to nginix configuration path

---

console-extensions.json
package.json
src/views/clusteroverview/ClusterOverviewPage.tsx
yarn.lock

This PR adds the namespace bar to the overview page and modifies its extension to make it namespace aware.

Make overview page namespace aware

---

src/utils/components/SidebarEditor/SidebarEditor.tsx
src/views/virtualmachines/details/tabs/disk/DiskListPage.tsx
src/views/virtualmachines/details/tabs/disk/disk-list-page.scss
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx
src/views/virtualmachines/details/tabs/network/NetworkInterfaceListPage.tsx
src/views/virtualmachines/details/tabs/network/network-interface-list-page.scss
src/views/virtualmachines/details/tabs/scripts/ScriptsTab.tsx
src/views/virtualmachines/details/tabs/scripts/scripts-tab.scss

Sidebar editor in VM tabs: 
- scripts
- disk
- network
ps: in disk and network the 'live' effect is not so great. Can cause throws of exception. So its disabled in these two cases

CNV-19687: Sidebar editor in other vm page tabs

---

src/views/catalog/wizard/tabs/environment/hook/useEnvironments.ts
src/views/virtualmachines/details/tabs/environment/hooks/useEnvironments.ts

**Cause**
Save button enabled and disabled at the wrong moment. Don't use index to compare new and old envs array. The update can change the order

[release-4.11] Bug 2119607: Env save button fix

---

src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx

Adding source PVC to datasource details page
After:
Before:

Bug 2127787: Adding source pvc to datasource details page

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisksRow.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/hooks/useVirtualMachinesOverviewTabDisksColumns.ts

Adding disks interface column to disks card on the overview page.
Before: 
After:

CNV 21085: Adding disks interface column

---

src/utils/components/SidebarEditor/SidebarEditor.tsx
src/utils/components/SidebarEditor/SidebarEditorContext.tsx
src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
src/views/templates/details/TemplateNavPage.tsx
src/views/templates/details/tabs/details/TemplateDetailsPage.scss
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/disks/components/DiskRow.tsx
src/views/templates/details/tabs/disks/template-disk-tab.scss
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/template-network-tab.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
src/views/templates/details/tabs/scripts/template-scripts-tab.scss

Sidebar editor for template tabs

CNV 19687: SidebarEditor for templates

---

src/views/clusteroverview/SettingsTab/LiveMigrationTab/Network/Network.tsx

Bug 2127843: Fixed UI crash when selecting Live migration network

---

src/utils/components/SidebarEditor/SidebarEditor.tsx
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/parameters/template-parameters-page.scss

Sidebar editor for parameters tab with only one save button

CNV 19687: Sidebar editor in template parameters tab

---

src/views/catalog/wizard/components/WizardDescriptionItem/WizardDescriptionItem.scss
src/views/catalog/wizard/components/WizardDescriptionItem/WizardDescriptionItem.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
src/views/catalog/wizard/tabs/disks/wizard-disk-tab.scss
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/metadata/wizard-metadata-tab.scss
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/network/wizard-network-tab.scss
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scheduling/components/WizardSchedulingGrid.tsx
src/views/catalog/wizard/tabs/scheduling/wizard-scheduling-tab.scss
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.scss
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/templates/details/tabs/details/TemplateDetailsPage.scss

Sidebar editor for wizard tabs: schedule, metadata, networks ,disks

CNV 19687: Wizard sidebar editor other tabs

---

src/views/virtualmachines/utils/virtualMachineRowFilter.ts

New status filter: Failed (removed previously i think by mistake https://github.com/kubevirt-ui/kubevirt-plugin/pull/850)
Filter failed vms only on Failed status

Bug 2129084: Fix vm status filters

---

src/utils/components/CloudinitModal/utils/useCloudInit.ts

On uncheck 'Add network data' the network data are not canceled for the vm

Bug 2129301: Fix cloud-init add network data checkbox

---

console-extensions.json
src/templates/datasource-yaml.ts
src/templates/index.ts

Default yaml of DS is missing source :{} in order to create example DS
After:

Bug 2128948: Missing source at datasource yaml

---

src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
src/utils/components/Charts/MigrationUtil/MigrationThresholdChart.tsx
src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
src/utils/components/Charts/StorageUtil/StorageIOPSTotalThresholdChart.tsx
src/utils/components/Charts/StorageUtil/StorageReadThresholdChart.tsx
src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
src/utils/components/Charts/StorageUtil/StorageWriteThresholdChart.tsx
src/utils/components/Charts/utils/utils.ts
src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
src/views/virtualmachines/details/tabs/metrics/NetworkCharts/hook/useNetworkData.tsx
src/views/virtualmachines/details/tabs/metrics/hooks/useDuration.tsx

Added range domain to charts, so dates longer the machine exists will be shown correctly.
After:
Before:

Fix charts domain range

---

src/views/datasources/list/DataSourcesList.tsx
src/views/datasources/list/DataSourcesListFilters.ts

Fix the incorrect type of the `t` function, used as the argument of `getDataImportCronFilter`,
also fix some antipattern in `getDataImportCronFilter`.
**Before:**
**After:**

Fix type of the t function as the argument of getDataImportCronFilter

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/utils/components/DiskModal/state/initialState.ts

Bug 2132932: VM disk size "dynamic" only on ephemeral

---

src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts

`setLoaded(true)` on boot source URL, registry, container disk

Bug 2132783: Template Source loaded with registry, URL, containerDisk

---

cypress/tests/check-tabs.spec.ts

remove tests about VMI as the VM cannot be scheduled in CI.
It should fix test failures see in https://github.com/kubevirt-ui/kubevirt-plugin/pull/787#issuecomment-1272354284

remove tests about vmi

---

src/utils/components/SSHAccess/components/SSHCheckbox.tsx
src/utils/components/SSHAccess/components/SSHCommand.tsx

disable the ssh command checkbox on loading and have an optimistic value during the request
**Before**
[Screencast from 03-10-2022 16:54:25.webm](https://user-images.githubusercontent.com/29160323/193608897-70c493b8-44d8-4e3e-8eef-c13ca8e64fe5.webm)
**After**
[Screencast from 03-10-2022 16:53:31.webm](https://user-images.githubusercontent.com/29160323/193608936-0397fc6f-e6bb-4e99-8e7e-4226ab4e5c2a.webm)

Disabled SSH command checkbox

---

src/templates/vm-template-yaml.ts
src/templates/vm-yaml.ts

> Fix resource name to example for both VM YAML example and VM Template YAML example

Bug 2132682: Default YAML entity name convention.

---

src/views/templates/actions/components/SelectSource.tsx
src/views/templates/actions/editBootSource.ts

Fixing in the Edit boot source reference the added docker prefix once more if a letter or sign is deleted from- "docker://".
Before:
After:

Bug 2137243: Fixing registry input in Edit boot source reference

---

src/views/catalog/utils/utils.ts

filters resources array splitting VM with other resources (we need or not and)

Bug 2138664: Fix additional resources creation

---

src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx

Bug 2138653: Prevent default on parameters form submit

---

src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx

Bug 2134672: Changing the data-test-id to the closest element

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts

> Add 'Red Hat - Tech Preview' provider filter to Template list view
https://user-images.githubusercontent.com/67270715/198975445-f8084c9a-cd5f-4672-9871-d910621caafa.mp4

Bug 2138199: Add 'Red Hat - Tech Preview' provider filter

---

src/utils/hooks/useDefaultStorageClass/constants.ts
src/utils/hooks/useDefaultStorageClass/useDefaultStorageClass.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/utils/quick-create-vm.ts

Backporting of https://github.com/kubevirt-ui/kubevirt-plugin/pull/820

Bug 2128554: Backporting default storage class usage in quick create

---

src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts

non-priv user does not have access to other namespaces so we have to process template in the selected namespace
This fix targets also [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=2139299)

Bug 2139306: Process template on selected project

---

src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx

Bug 2139260: Fixing the clone button will be enable while the vm is running

---

src/utils/hooks/useLastNamespacePath.ts

Bug 2140521: Fixed the breadcrumbs for VirtualMachines that the vm switched to a defined project.

---

src/utils/resources/template/hooks/useVmTemplateSource/useVmTemplateSource.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeForm.tsx

Fix template catalog for template with no bootsource

Bug 2139574: Fix catalog for template no bootsource

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogEmptyState.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx

Bug 2139687: catalog shows template list for non-priv users

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx

Bug 2140534: Disable VNC play button and  the standalone view button in overview tab

---

src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx

Bug 2141494: Adding the "Start in pause mode" option to review page

---

src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx

Bug 2142468: Fixing the stop action to be enabled while vm is in pause mode

---

package.json
yarn.lock

> Update dynamic-plugin-sdk package to 0.0.18 and dynamic-plugin-sdk-webpeck to 0.0.9

Update SDK packages

---

src/utils/constants/constants.ts
src/utils/resources/template/hooks/useProcessedTemplate.ts
src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
src/utils/tests/resource.test.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/components/CustomizeVirtualMachineHeader.tsx
src/views/catalog/customize/constants.ts
src/views/catalog/customize/utils.ts
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
src/views/catalog/utils/quick-create-vm.ts
src/views/catalog/wizard/components/WizardHeader.tsx
src/views/datasources/dataimportcron/details/DataImportCronPageTitle.tsx
src/views/datasources/details/DataSourcePageTitle.tsx
src/views/datasources/list/CreateDataSourceModal/CreateDataSourceModal.tsx
src/views/datasources/list/DataSourcesList.tsx
src/views/templates/actions/components/SelectSourceOption.tsx
src/views/templates/actions/editBootSource.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachinesinstance/list/VirtualMachinesInstancesList.tsx

falling back to `default` namespace if the namespace is not selected (non-admin user can not click create for all projects so the `default` namespace won't apply as he must select a namespace to create)
https://user-images.githubusercontent.com/67270715/203059012-9ebbd78b-fd5d-4c82-b49e-30d65b2a6473.mp4

Bug 2143498: Could not load template while creating VM from catalog

---

src/utils/components/AlertsCard/AlertsDrawer.tsx

Clicking on the alerts options will open the details of the specific alert.
Before:
After:

Bug 2142511: Fixing the alerts card dropdown on the overview page

---

src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
src/views/templates/details/tabs/details/components/Annotations.tsx
src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
src/views/templates/details/tabs/details/components/CPUMemory.tsx
src/views/templates/details/tabs/details/components/Description.tsx
src/views/templates/details/tabs/details/components/DisplayName.tsx
src/views/templates/details/tabs/details/components/Labels.tsx
src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
src/views/templates/details/tabs/scheduling/components/Tolerations.tsx

If user has no permission, disable the pencil instead of removing it.
Following pr will do the same thing with VM and other kubevirt resources

Bug 2143216: Template disable pencil instead of remove it

---

src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts

Make the template list responsive on boot source change. 
No screenshots as I just changed the code. 
When the user is on the template list, the 'Source available' label will appear or disappear if the data source will become available or not. 
Next pr will add the label 'Clone in progress' when data sources would be in other states.
When the user edits the boot source reference, will see the label 'Clone in progress' 
Bonus: we cache those requests in redux using `useK8sWatchResources`
Video (I've waited for 40 s for the DS import)
[Screencast from 28-11-2022 09:13:36.webm](https://user-images.githubusercontent.com/29160323/204227131-78a6de8f-ebb8-44be-89e9-898819d8e22d.webm)

CNV-21974: Part I - watch boot source in template list

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts
src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.scss
src/views/catalog/templatescatalog/TemplatesCatalog.scss

Enabling VM create with instance type and preference,
also fixing some bugs like non working pagination, adjusting page height for both tabs, fetching DS only with default preference label
https://user-images.githubusercontent.com/67270715/213920937-f726b7c6-0e76-4307-818e-7827cd934416.mp4
https://user-images.githubusercontent.com/67270715/213920938-47502b44-103a-4829-88c4-8dfee66bc486.mp4
cc:// @pcbailey

Introduce VM create with instance type and preference

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.scss
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/utils/types.ts
src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

This PR adds the SSH section to the VM Details section of the Instancetypes tab.

Add SSH section to VM Details section of Instancetypes tab

---

.gitignore
oc-manifest.yaml
scripts/oauth-client.yaml
start-console-auth-mode.sh

Adding the option to start console locally in auth mode

---

src/utils/components/BootOrderModal/BootOrderModal.tsx
src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
src/utils/components/DeschedulerModal/DeschedulerModal.tsx
src/utils/components/DiskModal/utils/helpers.ts
src/utils/components/EnvironmentEditor/hooks/useEnvironments.ts
src/utils/components/EvictionStrategyModal/EvictionStrategyModal.tsx
src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
src/utils/components/HostnameModal/HostnameModal.tsx
src/utils/components/NodeSelectorModal/NodeSelectorModal.tsx
src/utils/components/StartPauseModal/StartPauseModal.tsx
src/utils/components/TolerationsModal/TolerationsModal.tsx
src/utils/utils/utils.test.ts
src/utils/utils/utils.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
src/views/catalog/utils/utils.ts
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/components/DiskRowActions.tsx
src/views/datasources/dataimportcron/details/DataImportCronManageModal/utils.ts
src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
src/views/templates/details/tabs/details/components/DisplayName.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
src/views/templates/utils/utils.ts
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

two `ensurePath` functions used all over the repo.
Just move it to utils

fix: move ensurePath to utils

---

src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx

Bug 2166165: Changing the data-test-id on VM creation page

---

console-extensions.json
package.json
src/views/dashboard-extensions/Activity.tsx
src/views/dashboard-extensions/ActivityProgress.tsx
src/views/dashboard-extensions/Inventory.tsx
src/views/dashboard-extensions/inventory.scss
src/views/dashboard-extensions/utils.ts

Moving dashboard extension from old console to ours

CNV-20215: Moving dashboard extension from old console to ours

---

src/utils/components/Charts/utils/utils.ts

Bug 2151831: Changing the time format in charts

---

src/utils/components/SSHAccess/SSHAccess.tsx
src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
src/utils/components/SSHAccess/utils.ts

Bug 2151508: Adding user name to virtctl ssh command

---

src/utils/components/AlertsCard/AlertsDrawer.tsx

Bug 2167661: Changing the Alerts card if there are no alerts

---

src/utils/hooks/useCDIUpload/utils.ts

Since there is a GC for DV's , we don't need to add ownership to DV when creating a machine with an upload image.
The ownership is currently failing as the DV doesn't exist. which causes the VM creation to succeed but the user is still in wizard as the ownership that is submitted only after successful VM creation is failing.

Bug 2151759: Remove adding DV ownership when creating VM

---

src/utils/components/VMAuthorizedSSHKeyModal/utils.ts

Don't add owner reference when select external secrets as auth secrets in scripts tab

Bug 2150364: External Secret should not have vm as owner

---

src/utils/components/SSHAccess/components/SSHServiceSelect.tsx

Bug 2169699: Add ssh select id for testing purposes

---

cypress/tests/check-tabs.spec.ts
cypress/views/tab.ts

adjust tests as VM tabs changed

---

src/utils/hooks/useKubevirtWatchResource.ts

Bug 2173595: Fixed the vm list page stuck loading for reader user

---

src/utils/components/SysprepModal/SelectSysprep.tsx
src/utils/components/SysprepModal/SysprepModal.tsx
src/views/catalog/wizard/tabs/scripts/components/Sysprep.tsx
src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx

[release-4.12] Bug 2173574: take namespace from vm instead of useParams

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

Apply the SC to the VM's DataVolumeTemplate section from the underlying PVC
https://user-images.githubusercontent.com/67270715/221886955-fd368a40-04e0-4820-af5f-476ac1c38a6b.mp4

Create VM from boot source with correct SC

---

src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx

Bug 2168490: Changing the font size in the Bandwidth consumption graph

---

src/utils/components/CloudinitModal/utils/useCloudInit.ts

user get errors on editing cloud-init info to vm without any cloud-init volume 
No more errors now

Bug 2151053: Cloud init fix

---

src/templates/vm-template-yaml.ts

Bug 2151521: add user on vm template example

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts

Bug 2159975: Fixing the prefix docker while editing the regstiry

---

src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx

After:
https://user-images.githubusercontent.com/67270715/222400730-7428e6f5-8ece-4af8-a994-30ae91a0512d.mp4

Bug 2174288: No storageClass is selected by default while adding/editing a disk

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/metrics/StorageCharts/StorageCharts.tsx

Bug 2168561: Changing iosp to uppercase letters in metrics tab 

---

src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx

Fix bug: https://bugzilla.redhat.com/show_bug.cgi?id=2175651
After:
Before:

Bug 2175651: Sending props to isEdit on network modal

---

src/utils/components/HardwareDevices/HardwareDevices.tsx
src/utils/components/HardwareDevices/HardwareDevicesHeadlessMode.tsx
src/utils/components/HardwareDevices/modal/HardwareDevicesHeadlessModeModal.tsx
src/utils/components/PendingChanges/utils/helpers.ts

Fixing the headless mode option in the catalog. Compare if the field exists in yaml.

Bug 2176353: Fix headless mode in catalog

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/utils/utils.ts
src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsoleConnect.tsx

Added console is disabled while in headless mode and removed play button

Bug 2173562: show msg when headless mode in on and remove play button 

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/SSHAccess/components/SSHServiceSelect.tsx

small fixes from doc team
LoadBalancer option first and `any traffic sent` instead of `any traffic that is sent` in description of NodePort

small doc fix

---

src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx

Remove loading from add volume button to have the same behavior as the other add buttons.

Bug 2175643: Remove loading from add volume button

---

cypress/tests/catalog/filter.spec.ts
package.json
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/migrationpolicies/list/components/MigrationPolicyCreateForm/copmonents/SelectorLabelMatchGroup/SelectorLabelMatchGroup.tsx
yarn.lock

Patternfly probably has changed and updated since this search input has created.
I updated patternfly again to fix a bug in typescript they had.
Because of the update had to change in migration policy files to match the new patternfly typescript and components change.
After:
Before:

Bug 2170703: Fix template catalog search

---

src/utils/components/HardwareDevices/HardwareDevices.tsx

Removing headless mode from catalog drawer

Bug 2176353: remove headless mode in catalog drawer

---

src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx

Order of name and namespace when adding out of scope nad was wrong. 

Bug 2158424: Replace name and namespace places

---

src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/details/virtual-machine-page.scss

Adding a hack for an icon for the configuration tab until pattern fly updates their component.

Addin an icon to configuration tab - vm details

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndDataSources.ts
src/utils/components/DiskModal/DiskFormFields/hooks/useProjectsAndPVCs.ts
src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx
src/views/templates/actions/components/PersistentVolumeClaimSelect/utils.tsx

Fix sorting to present alphabetical order of names of projects, ds and pvcs.
While fixing it, I noticed a lot of replicated code, especially between the template and modal and some disk modal which should be revised to use the same component as they are doing precisely the same!

Bug 2158060: Fix sorting pvcs, ds, projects

---

src/views/virtualmachines/details/virtual-machine-page.scss

Another part where the editor does not have the right height
**Before**
**After**

fix: editor height

---

src/views/clusteroverview/SettingsTab/GeneralTab/GeneralTab.tsx
src/views/clusteroverview/utils/constants.ts
src/views/clusteroverview/utils/hooks/useKubevirtCSVDetails.ts

Improving setting tab loading speed by splitting the network call and changing to more specific calls so they will fetch less data, unneccessry data, and we avoid running on arrays.

Bug 2166507: Improving setting tab loading speed

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/EditButtonWithTooltip.tsx
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.scss
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

Use instancetype to show CPU and memory if the memory use instancetype.
Disable editing for vms with instancetype

Bug 2159715: Instancetype cpu memory

---

src/utils/components/PendingChanges/utils/constants.ts
src/utils/components/PendingChanges/utils/helpers.ts

Fix network routing URL to point to /network instead of /network-interface

Bug 2176706: Fix netwrok routhing

---

src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticVolumeStatusTableColumns.ts
src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss

Removing filter and column management for diagnostic volume status
After:
Before:

Bug 2179626: Removing filtering from diagnostic volume status

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss

fix not migratable label

---

src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
src/utils/components/HardwareDevices/HardwareDevices.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx

Bug 2177091: hide edit buttons on catalog drawer

---

src/utils/components/SSHSecretSection/utils/components/SecretDropdown/SecretDropdown.tsx

Append to parent cause the drop down when first opened to open up and not down.

Bug 2179225: Remove append to parent from ssh select instancetypes

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/hooks/useCloneVMResources.tsx
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

When cloning a new VM we also need to clone the pvcs, and not use the original ones  
After:
https://user-images.githubusercontent.com/67270715/228240033-a45dbc2f-f227-4afd-8db4-aac0b63db9b2.mp4

Bug 2182056: Cloned VM should not use the same PVC of the source VM

---

src/views/migrationpolicies/components/MigrationPolicyEditModal/MigrationPolicyEditModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2158550
Display _MigrationPolicy details_ page or _MigrationPolicies_ list correctly with no error, after changing the name of some MigrationPolicy resource (depending on the actual location while renaming the policy).
More details:
The core of the problem was [here](https://github.com/kubevirt-ui/kubevirt-plugin/compare/main...hstastna:BZ_Error_after_renaming_MigrationPolicy?expand=1#diff-906365722d2f2402e5af9725eba912cc2f461091e6ef03540f3335613903910cL54) where the original name of the policy was searched in the WHOLE URL and not at its end, where it belongs, so it was only logical that the first occurence of "a" was found "earlier" in the url string than expected and replaces by the new name, so "migraations" occurred in the url, …

Bug 2158550: Display MigrationPolicy page after renaming correctly

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/shared.ts
src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
src/views/catalog/templatescatalog/TemplatesCatalog.scss

Manual backport for PRs #1192 and #1217

[release-4.13] Bug 2182536: The volume in instanceTypes page should be selected automatically just after it's been added

---

src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss
src/views/virtualmachines/details/virtual-machine-page.scss

Bug 2183076: Adjust configuration inner tab apperance

---

src/utils/components/NetworkInterfaceModal/components/hooks/types.ts
src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts

https://github.com/kubevirt-ui/kubevirt-plugin/pull/1248 was prematurely merged due to my error. This PR finishes the modifications I intended to be in that PR.

Bug 2186462: Update fixes from premature merge

---

src/utils/components/PendingChanges/utils/helpers.ts

backporting https://github.com/kubevirt-ui/kubevirt-plugin/pull/1243

[release-4.12] Bug 2186132: Backport false pending state

---

.github/workflows/deploy.yml

push on quay.io image referring any created tag

fix: push on quay also for tags

---

package.json
yarn.lock

Bump kubevirt-api to v0.0.51

---

src/utils/components/Charts/utils/queries.ts

Fix for https://github.com/kubevirt-ui/kubevirt-plugin/pull/1307
[Screencast from 05-29-2023 02:46:33 PM.webm](https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/c038badd-d2ac-4abc-806b-ca0d031fd10f)
[Screencast from 05-29-2023 02:47:02 PM.webm](https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/bf7273cd-8c0f-4993-8b6c-35844359b31f)

Fix memory usage metric query

---

src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

Manual backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1316
[Jira issue](https://issues.redhat.com/browse/CNV-29469)

CNV-29469: Cloud-init username is always "fedora" when create VM from IT

---

src/utils/hooks/usePreviewFeatures/constants.ts
src/utils/hooks/usePreviewFeatures/usePreviewFeatures.ts

Manual backport of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1326
No visible changes

[release-4.13] Add preview feature mechanism

---

src/views/bootablevolumes/list/components/BootableVolumesRow.tsx

If the bootable resource is a DS, show the specific action

CNV-26881: Bootable Resources add ds specific actions

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/utils/components/AddBootableVolumeModal/components/SourceTypeSelection/SourceTypeSelection.tsx
src/utils/resources/bootableresources/hooks/useCanCreateBootableVolume.ts
src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx

Handle create permissions for user.
If has access to at least DS and PVC, show the create button
Disable the select type based on the permissions

CNV-26881: Handling bootable volume access

---

.eslintrc.json
src/utils/components/DurationOption/DurationOption.ts
src/views/clusteroverview/TopConsumersTab/utils/topConsumerMetric.ts
src/views/clusteroverview/TopConsumersTab/utils/topConsumerScope.ts

Linter change the class properties, this fix will restore a working version

CNV-29766: Fix metrics component caused by classes reorder 

---

oc-manifest.yaml

Remove proxy from manifest. hco taking care of it

Remove proxy manifest

---

src/utils/resources/vm/utils/selectors.ts
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

Manual backport of: #1378 
[Jira issue](https://issues.redhat.com/browse/CNV-30396)

[release-4.13] CNV-30396: Clone modal crashes if VM has only pvcs

---

src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx

CNV-28437: Fixing the username in the copy ssh command

---

cypress/views/tab.ts
src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
src/views/virtualmachines/details/tabs/configuration/utils/utils.ts

Description: 
https://issues.redhat.com/browse/CNV-30656
Before: 
After:

CNV-30656: Reorganization the order of the sub tabs on the configuration tab

---

src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferencePopoverContent.tsx
src/utils/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
src/views/datasources/details/components/DataSourceDetailsGrid.tsx/DataSourceDetailsGrid.tsx

Adding links to IT and Pref CRs under DataSource Details page
Before:
After:

CNV-30926: "DataSource details" page should show and link default instanceType and preference

---

src/views/bootablevolumes/list/BootableVolumesList.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-30959
Make _Manage columns_ feature in _Bootable resources_ list page work by using proper id for `columnLayout` prop of `ListPageFilter` component used in the page.
**Before:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/d3d36f45-be70-4efc-8cfd-2de7c8517f52
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/eddbc06c-ea32-4033-9599-fd6f6e434b72

CNV-30959: Make "Manage columns" in Bootable resources page work

---

console-extensions.json
locales/en/plugin__kubevirt-plugin.json

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2222290
_Jira:_
https://issues.redhat.com/browse/CNV-30894
Change "Instancetypes" to "InstanceTypes" under _Virtualization_ menu.
**Before:**
**After:**

CNV-30894: Change "Instancetypes" to "InstanceTypes" in top-level menu

---

package.json
src/utils/hooks/useKubevirtDataPod/hooks/useKubevirtDataPodHealth.ts
src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
src/utils/hooks/useKubevirtDataPod/useKubevirtDataPodFilters.ts
src/utils/hooks/useKubevirtWatchResource.ts
src/utils/hooks/useSingleNodeCluster.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx
yarn.lock

This PR will add the options to filter using our proxy, means filtering happen on BE side,
this is a temp solution to vm list, as this component should be rewritten as the component form console need to have a lot of adjustment in order to filter in BE side.

Adding ability to filter api server results

---

src/utils/components/Consoles/components/CloudInitCredentials/InlineCodeClipboardCopy.tsx
src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
src/utils/components/Consoles/components/utils/hooks/useCopyPasteConsole.ts
src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
src/utils/components/Consoles/utils/constants.ts
src/utils/components/Consoles/utils/utils.ts

The paste function on consoles wasn't working for firefox, this is due to firefox not supporting the full functionality of navigator.clipboard as chrome does, i used another approach of events in order to make it work for all browsers.

CNV-29307: Fix copy and paste to serial and vnc consoles

---

src/views/clusteroverview/SettingsTab/ClusterTab/components/LiveMigrationSection/Network/Network.tsx

Disable nad selection if no nads available
Before:
After:

CNV-28553: Disable nad selection if no nads available

---

src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

https://issues.redhat.com/browse/CNV-30872
Before: 
After:

CNV-30872: Fixing the cloned VM using PVC of another VM 

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/SettingsTab/ClusterTab/components/EnablePreviewFeaturesSection/EnablePreviewFeaturesSection.tsx

CNV-31242: Removing proxy checkbox - featuers flag

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

The clone VM action was constructing a new PVC based on the source PVC, instead of utilizing the DataVolumeTemplate's pvc property to clone an existing PVC 
Before:
After:

CNV-31188: Clone VM is cloning from the VMs DV source and not from the VM PVC

---

.eslintignore

Add folders eslint should ignore

Eslint ignore folders

---

src/utils/components/ErrorIcon/ErrorIcon.tsx
src/views/virtualmachines/utils/virtualMachineStatuses.ts

Error status icons should be red 
**Before**
**After**

CNV-30602: Add error icon color

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/customize/utils.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx

Template without a parameter section was getting errors on the quick create, customize, and parameters tab under the template details view.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/95101049-a682-46fa-8d4b-d69a176e8dd4
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/b6299e88-2a63-4c18-bb28-711f620501c7

CNV-28503: Console errors while using a template without parameters

---

src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceTypeSelect.tsx
src/utils/components/NetworkInterfaceModal/components/hooks/types.ts
src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
src/utils/components/NetworkInterfaceModal/utils/constants.ts
src/utils/components/NetworkInterfaceModal/utils/helpers.ts
src/utils/resources/vm/utils/network/constants.ts

Enable only the type according to the nad. if no nad type user can pick bridge/sriov .

CNV-31299: NIC type according to NAD type

---

src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts
start-console-auth-mode.sh

Adding websocket protocol according to windows protocol

Adding support for wss according to window protocol

---

src/utils/hooks/useKubevirtDataPod/useKubevirtDataPod.ts

Adding missing colon in wss ws check
