kubevirt-ui/kubevirt-plugin

README.md
i18next-parser.config.js
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/CatalogTemplateFilters.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/virtualmachines/list/VirtualMachinesList.tsx

I18n will now use 'plugin__kubevirt-plugin' as default namespace. no need to do useTranslation('plugin__kubevirt-plugin') anymore , useTranslation() is good.

added 'plugin__kubevirt-plugin' as default namespace

---

jest.config.ts
package.json
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/templatescatalog/hooks/useProcessedTemplate.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
webpack.config.ts
yarn.lock

Added `useIsTemplateSupportsQuickCreate` that detects if QuickCreate is supported by a given template.
The Drawer will show a skeleton until the hook detection completes
Here is a Demo with Network Throttled to demonstrate the loading experience
https://user-images.githubusercontent.com/24938324/154291800-e38f7d6c-22c1-4db2-8b20-60464f853b98.mov

Add hook that checks if Template supports QuickCreate

---

src/views/catalog/templatescatalog/utils/flavor.ts
src/views/catalog/templatescatalog/utils/helpers.ts
src/views/catalog/utils/vm-template-source/useVmTemplateSource.ts
src/views/catalog/utils/vm-template-source/utils.ts
tsconfig.json

Added `getTemplateBootSourceType` function and `useVmTemplateSource` hook.
`getTemplateBootSourceType` returns a `TemplateBootSource`
```ts
export enum BOOT_SOURCE {
PVC = 'PVC',
PVC_AUTO_UPLOAD = 'PVC_AUTO_UPLOAD',
URL = 'URL',
REGISTRY = 'REGISTRY',
}
export type TemplateBootSource = {
type: BOOT_SOURCE;
source: {
sourceRef?: V1beta1DataVolumeSourceRef;
pvc?: V1beta1DataVolumeSourcePVC;
http?: V1beta1DataVolumeSourceHTTP;
registry?: V1beta1DataVolumeSourceRegistry;
};
sourceValue?: {
sourceRef?: V1alpha1PersistentVolumeClaim;
pvc?: V1alpha1PersistentVolumeClaim;
http?: V1beta1DataVolumeSourceHTTP;
registry?: V1beta1DataVolumeSourceRegistry;
};
};
```
`useVmTemplateSource` fetches the boot source and checks for its availability if possible.
as of now availability check is for `PVC` and …

Add VM Template Source utils and hook

---

src/utils/resource.ts
src/utils/tests/resource.test.ts

Retuns a URL Path for a Resource
```ts
const vm = {
metadata: {
namespace: 'kube',
name: 'vm',
},
};
const url = getResourceUrl(VirtualMachineModel, vm);
// returns  => /k8s/ns/kube/kubevirt.io~v1~VirtualMachine/vm
```

add getResourceUrl method

---

console-extensions.json
package.json
src/views/catalog/Catalog.tsx

Combine Catalog routes into a single component with a nested Switch.
This will help us share state between these routes in a more efficient and isolated way.
Next step is to wrap the new Switch with a custom Context Provider

Combine Catalog routes to one Switch

---

codecov.yml

since SDK is available only by runtime, we can't unit-test all components relying on SDK components
lowering codecov target threshold as a workaround
none

lower codecov target threshold

---

src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesRowFilter.ts
src/views/virtualmachinesinstance/list/utils/virtualMachinesInstancesStatuses.ts

> If VMI is missing OS annotation a blank screen appears in VMI list. this fix this.

Missing OS annotation on VMI

---

src/views/catalog/utils/WizardVMContext.tsx
src/views/catalog/wizard/Wizard.scss
src/views/catalog/wizard/Wizard.tsx
src/views/catalog/wizard/tabs.tsx
src/views/catalog/wizard/tabs/advanced/WizardAdvancedTab.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/yaml/WizardYAMLTab.tsx

Add VM Context HOC for Tabs
This decouples the Tabs from the VM Context.
It also allows to render a loading state before the VM is ready for review.
Here is a loading VM

Add VM Context HOC for Tabs

---

package.json
src/views/catalog/utils/WizardVMContext.tsx
src/views/catalog/wizard/tabs/metadata/components/WizardAnnotationsModal/WizardAnnotationsModal.tsx
yarn.lock

Add immutability to VM Context
- add `immer` and `useImmer` to the vm object in the context state
- This change makes the vm object immutable (read only)
- Updating a vm is now simplified and fail-safe, we pass a callback that receives a vm draft, editing only the needed part without worrying about cloning the object's untouched parts beforehand
e.g. 
before:
```ts
updateVM({
...vmObj,
metadata: {
...vmObj.metadata,
annotations: updatedAnnotations,
},
};
``` 
after:
```ts
updateVM((vmDraft) => {
vmDraft.metadata.annotations = updatedAnnotations;
});
```

Add immutability to VM Context

---

src/views/catalog/customize/utils.tsx

Fix the type issue of the t-function for translations, in the `getVirtualMachineNameField` util, used in `CustomizeForm`
and `CustomizeFormWithDisk` components.
Before:

Fix type issue in getVirtualMachineNameField util

---

console-extensions.json
package.json
src/utils/components/ModalProvider/ModalProvider.tsx

Add global useModal. The hook can be used anywhere in the plugin.
This will help us open a modal programmatically without having to handle its state.
Example usage
```tsx
const { createModal } = useModal();
<Button
onClick={() =>
createModal(({ isOpen, onClose, appendTo }) => (
<ExampleModal isOpen={isOpen} onClose={onClose} appendTo={appendTo} />
))
}
/>
```

Add global useModal

---

src/utils/components/DeleteModal/DeleteModal.tsx
src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
src/utils/components/TabModal/TabModal.tsx
src/views/virtualmachines/details/tabs/network/copmonents/list/NetworkInterfaceActions.tsx
src/views/virtualmachines/details/tabs/snapshots/components/list/SnapshotActionsMenu.tsx

In this PR I:
- move the component to a separate file under _src/utils/components_.
- rename the component name to `DeleteResourceMessage`, 
- update the related code, where the component is used
- change the message from "... **from** namespace..." to "... **in** namespace...", according to the design updates
- add the missing `namespace` prop of the component, for deletion of VM NICs
**Screenshots**:
_Before:_
_After:_

Move DeleteResourceMessege to separate file

---

src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx

The Disks table will show an error even if it's not related to the Disks tab.
The `loadError` prop is meant for resource fetch errors, the wizard's vm is not fetched, so we should remove it from the Disks tab table.

remove vm error from disks tab table

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx
src/views/virtualmachines/details/tabs/yaml/VirtualMachineYAMLPage.tsx

adding console and yaml tabs to VM details navigation
consoles:
https://user-images.githubusercontent.com/67270715/162694116-1612e86f-dae7-4def-aea6-d2a74ff412c4.mp4
yaml editor:
https://user-images.githubusercontent.com/67270715/162688339-af881f26-94ea-4bc8-b940-d5dfbc812f85.mp4

add YAML editor and Console to VM details tabs

---

src/utils/resources/template/utils/selectors.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/templatescatalog/tests/mocks.ts
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

- Documentation link will now show `N/A` if link is not available
- Catalog Template will show `Other` if workload is not available
- Wizard Overview Tab - Operating system will show `Not available` if os is not available instead of template's name

Fix handling of undefined template annotations

---

src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx

Fix VM action font weight on VM details header

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx

fix migare button text
before:
after:

Bug 2071488: "Migrate Node to Node" is confusing.

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts
src/views/catalog/customize/tests/CustomizeSource.test.tsx

Missing docker:// prefix in image registry URL was causing VM creation to fail.

Bug 2074337: Missing docker:// prefix in vm creation from registry

---

src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx

Fix Template's URL at Virtualization overview inventory card
before:
https://user-images.githubusercontent.com/67270715/165523908-eed0a42d-efc2-441f-b67c-bd84cd2c2c40.mp4
after:
https://user-images.githubusercontent.com/67270715/165523962-2935cc21-cbd5-4f28-b32b-3213031115fe.mp4

Fix Template's URL at Virtualization overview inventory card

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/hooks/useTemplateTabs.ts
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
src/views/templates/details/tabs/scheduling/components/EvictionStrategy.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
src/views/templates/details/tabs/scheduling/components/TemplateSchedulingRightGrid.tsx
src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
src/views/templates/utils/index.ts
src/views/templates/utils/selectors.ts

Add _Scheduling_ tab and its content.
Add _Scheduling and resources requirements_ section, that contains the info about:
```
- Node selector    - Dedicated resources
- Tolerations      - Eviction strategy
- Affinity rules
```
_Note:_
Descheduler info will be added to Scheduling tab in a followup PR.

Add Scheduling tab to VM Template details page

---

src/views/templates/details/tabs/details/TemplateDetailsPage.tsx

Remove the extra space in VM Template's _Details_ tab above _VM Template Details_ section, that appears for uncommon Templates.
_Before:_
_After:_

Remove extra space in VM Template Details tab

---

src/views/templates/details/hooks/useTemplateTabs.ts

Place the tab in a correct place in the UI according to the design update.
**Before:**
**After:**

Move VM Template's Scheduling tab next to YAML tab

---

src/views/clusteroverview/overview/components/details-card/SourceMissingStatus/SubscriptionStatus.tsx

The Subscription CR is not available for non-privileged users, which causes the error for reaching an undefined property.
Adding optional chaining to the undefined property will prevent the crash.
before:
after:

fix overview page crashing

---

src/views/virtualmachinesinstance/details/hooks/useVirtualMachinesInstanceTabs.ts

Changing in the vmi page the location of the tabs like in vm page, first the event tab and then the console tab.
Before:
After:

Changing in vmi page the console and event tabs location

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx

missing `nodes` and `nodesLoaded` props caused the loader to get stuck
before:
https://user-images.githubusercontent.com/67270715/167392852-bc74b4c0-2673-43f8-8122-d89c6758dba9.mp4
after:
https://user-images.githubusercontent.com/67270715/167392872-a1d9e535-a630-442a-9eca-0bcb29b381f8.mp4

Bug 2083100: Something keeps loading in the 'node selector' modal

---

src/utils/resources/template/hooks/useVmTemplates.tsx
src/views/templates/list/VirtualMachineTemplatesList.tsx

when selecting a namespace as non-privileged user, and navigating to templates list, we get an error message for fetching templates if one of all namespaces that a user can list, has recieved an error.
before:
after:
https://user-images.githubusercontent.com/67270715/167402693-c4812c89-9732-4c6a-811c-8b3c9cf84497.mp4

Fix template's page to load templates for non-priv user

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
src/views/templates/utils/index.ts

Add the tooltip to the _Descheduler_ to inform the user that:
```
"To enable the descheduler, you must install the Kube Descheduler Operator from OperatorHub and enable one
or more descheduler profiles.", 
```
if the Descheduler is not installed, according to the new design.
Include some minor changes/fixes, regarding Descheduler:
- Remove the unnecessary check [here](https://github.com/kubevirt-ui/kubevirt-plugin/compare/main...hstastna:Template_Descheduler_tooltip?expand=1#diff-162e38124fe78686c5785f0692a79308cbd1f8218295b61c53ea4551428de71eL61), as this check was already present as the prop for the `Button` component [here](https://github.com/kubevirt-ui/kubevirt-plugin/compare/main...hstastna:Template_Descheduler_tooltip?expand=1#diff-162e38124fe78686c5785f0692a79308cbd1f8218295b61c53e …

Display Tooltip when VM Template Descheduler not installed

---

src/utils/components/CPUMemoryModal/hooks/useTemplateDefaultCpuMemory.ts
src/utils/components/CPUMemoryModal/utils/CpuMemoryUtils.ts
src/views/templates/details/tabs/details/components/CPUMemory.tsx
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
src/views/templates/details/tabs/details/components/cpu-memory-modal.scss
src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.tsx

Add missing _CPU | Memory_ option to the tab, to _VM Template Details_ section, according to the design update.
Add the modal to be opened when editing the values (**cpu cores** + memory), check if the fields are editable, let the changes to be saved.
Rename and update _getCPUCount_ function appropriately.
Edit _CPU | Memory:
Modal opened for editing the values:
Common templates are not editable:

Add CPU | Memory to VM Template Details tab

---

src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModalButton.tsx
src/views/templates/utils/index.ts

Display Template Descheduler's value "ON"/"OFF" according to annotation, no matter the operator installed or not, according to the design.
Only display the value for non admin user (cannot edit no matter the operator installed or not).
Before: Descheduler operator not installed but the annotation present:
After: The operator not installed but the annotation present:
Non admin can only see the value: (annotation not present)

Display Template Descheduler ON according to annotation

---

src/utils/components/TolerationsModal/TolerationsModal.tsx

when adding a toleration rule to a VM with a value input, the operator used is `Equals` which returned a pod error,
using `Equal` as an operator resolves this issue 
before:
https://user-images.githubusercontent.com/67270715/168466547-fe167244-b25e-4317-a31a-baf46242f3e1.mp4
after:
https://user-images.githubusercontent.com/67270715/168466563-b1459aca-a880-463c-b54a-e68fc4245d5a.mp4

Bug 2085320: Tolerations rules is not adding correctly

---

src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx

Enabling `Stop` and `Restart` actions when VM is on `Starting` status
before:
after:

Bug 2085322: Not able to stop/restart VM if the VM is staying in "Starting"

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/template/hooks/useProcessedTemplate.ts
src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogPageHeader.tsx
src/views/catalog/utils/quick-create-vm.ts

non-privileged user can not quick create VM (or customize create) when namespace is not selected and has no 'create' access to `default` project.
fix includes:
- disabling the templates drawer when namespace is not selected
- adding an alert that specify that a namespace needs to be selected
- fixing useProcessTemplate hook to use the current namespace if exists
before:
after:
https://user-images.githubusercontent.com/67270715/168477867-e87efd22-7ff6-4c3a-b969-81ef857920ee.mp4

Bug 2086303: non-priv user can't create VM when namespace is not selected

---

src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx

when navigating to Virtualization -> Catalog as non-privileged user we are displaied with all template items instead of default templates 
before:
https://user-images.githubusercontent.com/67270715/168478328-2c3dd5e0-408e-4a98-93d8-c3235b322bb8.mp4
after:
https://user-images.githubusercontent.com/67270715/168478344-771a5984-3ec4-4dc4-a9ff-c8efb633c7a5.mp4

display default templates for non priv user

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/CPUMemoryModal/constants.ts
src/utils/components/CPUMemoryModal/hooks/useTemplateDefaultCpuMemory.ts
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2083101
> "Restore default settings" button always disabled because no `vm.kubevirt.io/template.namespace` label

Bug 2083101: Restore CPU/Memory default settings

---

src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelectorModal.tsx
src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
src/views/templates/details/tabs/scheduling/components/TemplateSchedulingRightGrid.tsx

Make _Node selector_ field in Template's _Scheduling_ tab editable. Enable editing the labels if the template is not a common template.
Add the modal to edit the labels.
**Before:**
**After:**

Make Node selector field in VM Template's Scheduling tab editable

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/scheduling/components/AffinityRules.tsx
src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
src/views/templates/details/tabs/scheduling/components/NodeSelector.tsx
src/views/templates/details/tabs/scheduling/components/TemplateSchedulingLeftGrid.tsx
src/views/templates/details/tabs/scheduling/components/Tolerations.tsx
src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx
src/views/templates/utils/selectors.ts

Make _Tolerations_ and _Affinity rules_ fields editable, in the VM Template's _Scheduling_ tab, if the template is not a common template.
Add the appropriate modals to edit the fields.
**Before:**
The number of tolerations/affinity rules displayed, but no ability to edit:
**After:**
Tolerations/affinity rules editable:
Modal window to add/edit tolerations:
Modal window to add/edit affinity rules:

Make Tolerations and Affinity in Template's Scheduling tab editable

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AffinityModal/AffinityModal.tsx
src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/utils/components/CloudinitModal/CloudinitModal.tsx
src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
src/utils/components/SSHAccess/SSHAccessModal.tsx
src/utils/components/SysprepModal/SysprepModal.tsx
src/utils/components/TabModal/TabModal.tsx
src/utils/components/TolerationsModal/TolerationsModal.tsx
src/views/templates/actions/components/EditBootSourceModal.tsx
src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
src/views/templates/details/tabs/scheduling/components/AffinityRulesModal.tsx
src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2086479
Use "Save" string as the default submit button text for all of the modal windows we use, instead of "Submit", to achieve consistency in the UI.
Remove unnecessary optional `submitBtnText` prop when using `TabModal` component, as "Save" will be the default submit button text.
**Before:**
**After:**

Bug 2086479: Use "Save" submit button text in all modals

---

src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/details/components/Description.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx

Make _Description_ field editable, in VM Template's _Details_ tab.
Add using the appropriate modal to edit the description - in case that the VM Template is not a common template.
**Before:**
Dash displayed in case there was no any description + no editability:
**After:**
"None" string displayed in case there is no any description + editability present (only the pencil icon clickable): 
Modal window to add/edit the description, after clicking on "None" or pencil icon:
Description updated after changes in the modal saved (only the pencil icon clickable):

Make Template's Description field editable

---

src/utils/resources/vm/hooks/disk/useDisksTableData.ts
src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemList.tsx
src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListLayout.tsx

on the VM disks tab when switching from `Running` status to `Stopped` status, the watched VMI resource still exists even though the VM is at `Stopped` status and the VMI resource no longer exists in the cluster.
this causes to show incorrect data in the disk's and the filesystem's tables when deleting/creating disks.
to fix this we change the way to check for the VM status, now checking for the `status.printableStatus === "Running"` instead of checking the VMI resource existence.
this PR fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2084532
https://bugzilla.redhat.com/show_bug.cgi?id=2087188
after:
https://user-images.githubusercontent.com/67270715/169028288-bd1c7a36-9f25-4ec9-9639-1a566baef8d4.mp4

Bug 2084532: Console is crashed while detaching disk

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx

Bug 2087701: [RFE] Missing a link to VMI from running VM details page

---

src/views/clusteroverview/overview/components/running-vms-per-template-card/utils/utils.ts

According to https://bugzilla.redhat.com/show_bug.cgi?id=2088034 , the overview screen was crashing when VM didn't have any labels. this fix will promise no crash if VM has no labels.

Bug 2088034: Add optional chaining to getTemplateToVMCountMap

---

src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts

for SC doing explicit  check `storageclass.kubernetes.io/is-default-class = 'true'` 

Bug 2088355: disk modal shows all storage classes as default

---

src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/utils/resources/template/utils/constants.ts
src/utils/resources/vm/utils/source.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx

- `getVMBootSourceType` return always something
- Added `containerDisk` as boot source

Bug 2089376: No exception on Virtual Machine Template without boot source 

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx

`Cancel VirtualMachine migration` action was enabled only when `Migrating` status exists in `vm.status.printableStatus`. 
This behavior was changed to enable the `Cancel VirtualMachine migration` action when VirtualMachineInstanceMigration exists and a delete request to the VMIM resources hasn't made yet (checking `vmim.metadata.deleteionTimestamp` exists)
if `vmim.metadata.deleteionTimestamp` exists, a description text to the action will be added until the VMIM resource will be deleted 
https://user-images.githubusercontent.com/67270715/169856706-ec8ac959-d526-47b6-80c1-8ccd47126c23.mp4
https://user-images.githubusercontent.com/67270715/169856883-1082fa83-9e4c-4742-9085-45cd5d91faa5.mp4

Bug 2086488: Cannot cancel vm migration

---

src/utils/resources/vm/utils/source.ts

When removing all disks from VM customized wizard is crashing.
After:
Before:

Bug 2089745: When removing all disk from VM customized wizard is crashing

---

src/views/clusteroverview/overview/components/inventory-card/InventoryCard.tsx
src/views/clusteroverview/overview/components/inventory-card/hooks/useProjectNames.ts
src/views/clusteroverview/overview/components/inventory-card/hooks/useWatchedResourcesInventoryCard.ts
src/views/clusteroverview/overview/components/inventory-card/utils/ResourcesSection.tsx
src/views/clusteroverview/overview/components/inventory-card/utils/flattenTemplates.ts
src/views/clusteroverview/overview/components/inventory-card/utils/types.ts
src/views/clusteroverview/overview/components/inventory-card/utils/utils.ts
src/views/clusteroverview/overview/components/running-vms-per-template-card/RunningVMsPerTemplateCard.tsx
src/views/clusteroverview/overview/components/running-vms-per-template-card/hooks/useRunningVMsPerTemplateResources.ts
src/views/clusteroverview/overview/utils/utils.ts

changing the way we fetch resources for overview, if admin user - simply fetch all needed resources from all namespaces,
when non-admin (non-privileged) user is logged, we first list the namespaces and then fetch needed resources per namesapce.
this will fix the loading time when admin is logged (has access to all namespace so listing them one by one is taking more time for admin)
https://user-images.githubusercontent.com/67270715/169866451-1cb303c5-34a5-41f9-8c18-e7027398f96d.mp4
https://user-images.githubusercontent.com/67270715/169866536-1993f999-0504-4cf1-9466-a65fcdd8225c.mp4

Bug 2087577: 'VMs per template' load time is a bit long

---

src/views/clusteroverview/overview/components/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx
src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx

Changing the colors of the titles in the first card in Overview because in the dark mode there are not visible enough.
Before:
After:

Bug 2086272: Changing the colors of the titles in Overview for the dark mode

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/details/components/BootOrderItem.tsx

Add missing popover to _Boot order_ field in the Template's _Details_ tab to inform the user to edit the order in the Template's _Disks_ tab (if editable), according to the design.
**Before:**
**After**:

Add Template's Boot order popover to edit in Disks tab

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts

When creating a vm using customize wizard, default is referring to namespace of newly created vm instead of template namespace.
This fix will use the template namespace for openshift.
Before:
After:

Bug 2091406: Fixing the namespace label when customize new vm

---

src/utils/components/UserCredentials/useSSHCommand.ts

changing the hook that creates the string for SSH access command to follow doc [1] and using the VM's node IP address
[1] https://docs.openshift.com/container-platform/4.10/virt/virtual_machines/virt-accessing-vm-consoles.html#virt-accessing-vm-yaml-ssh_virt-accessing-vm-consoles

Bug 2081182: change to use node IP in ssh command

---

src/views/virtualmachines/details/tabs/disk/tables/disk/DiskListTitle.tsx
src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListTitle.tsx
src/views/virtualmachines/details/tabs/disk/tables/tables.scss
src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.scss
src/views/virtualmachines/details/tabs/environment/components/VirtualMachineEnvironmentTabTitle.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2090057
Display the Patternfly `HelpIcon` in size `small`, according to the design recommendations, in the title VirtualMachine _Environment_ and _Disks_ tabs' titles.
_More about PF Icons:_
https://www.patternfly.org/v4/guidelines/icons
**Before:**
VM _Environment_ tab:
VM _Disks_ tab:
**After:**

Bug 2090057: Make Help icon small in VM Environment, Disks tab

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/VirtualMachinesOverviewTabNetworkInterfacesRow.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabNetworkInterfaces/virtual-machines-overview-tab-interfaces.scss

Popover of network interfaces card at VM overview was missing some fields.
After:
Before:

Bug 2089967: Adding network and model to VM overview network interfaces cards - popover

---

src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx

after clone template, we want to route to cloned template details page
https://user-images.githubusercontent.com/67270715/171157625-bca21980-c976-4a3c-8aba-a99966e1f7b5.mp4
https://user-images.githubusercontent.com/67270715/171157665-2b309b9f-7197-4c1e-8c2a-74a10656690f.mp4

Bug 2091764: Clone a template should lead to the template details

---

src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx

Bug 2089979: adjust CPU|Memory pencil icon location

---

src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesFilters.ts
src/views/virtualmachines/utils/virtualMachineRowFilter.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2091758
Change the "OS" string to correct "Operating system", in the VM Template list filtering.
Change it the same way also in the Catalog and VirtualMachine list filtering, for consistency reasons.
**Before:**
**After:**

Bug 2091758: Rename OS to Operating system in filtering

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/actions/VirtualMachineTemplatesActions.tsx
src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
src/views/templates/details/TemplateActions.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2091765
Prevent "Edit boot source" dropdown action keeping in load, in the Template _Details_ tab.
Update the message for not editable boot source, as it was not 100% appropriate, because it showed "Boot cannot be edited for Red Hat templates" also for other than the Red Hat/common templates - that was misleading. Boot source editability check is a bit more complicated than just checking if the template is a common template.
**Before:**
**After:**

Bug 2091765: Prevent Edit boot source keeping in load

---

src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
src/utils/components/EvictionStrategyModal/EvictionStrategyModal.tsx
src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
src/utils/components/PendingChanges/utils/helpers.ts
src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
src/views/virtualmachines/details/tabs/scheduling/components/SchedulingSection/SchedulingSection.tsx
src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx

Making dedicated resources & eviction strategy modals editable when VM is running and including them as pending changes to VM.
https://user-images.githubusercontent.com/67270715/171652626-1f5c853a-5f7f-4296-ae8e-d9d5ba8c7b5d.mp4

Bug 2091754: making scheduling tab editable while VM is running- part 1

---

src/views/templates/details/tabs/details/components/DescriptionItem.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx

Add missing 'Hardware devices' title to the appropriate field, in the VM Template _Details_ tab.
**Before:**
**After:**

Add missing title to Template Hardware devices field

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2093691
When creating a VM, the drawer left padding in upper part disappeared. Fix the missing padding to display the content correctly.
**Before:**
**After:**
---
_Note:_
When investigating the problem, the relevant component had the following variable set:
`--pf-c-modal-box__body--PaddingLeft: 0 !important;`
Because of this, we cannot use the Patternfly `--pf-c-modal-box__body--PaddingLeft`, nor even `--pf-c-modal-box--PaddingLeft` to achieve the expected result, because this is actually not working correctly, doesn't set the expected padding when used.
Related PF doc:
https://www.patternfly.org/2020.06/documentation/core/components/modalbox

Bug 2093691: Add left padding to VM create drawer content

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
src/utils/components/PendingChanges/utils/helpers.ts

the pending alert is linked to the entire bootorder of all disks but we want to know only about the bootdisk when is changed

Bug 2093772: add env resource changes boot order pending alert

---

src/utils/components/DiskModal/utils/helpers.ts
src/utils/resources/vm/hooks/disk/useDisksTableData.ts
src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts

when adding a resource from the environment tab when VM is running the resource is not shown on the disks list

Bug 2094405: missing env resource from disks list

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/HardwareDevices/form/DeviceNameSelect.tsx

when trying to add HW device, and no devices are configured to the cluster, the dropwdown still shows the group headers

Bug 2094807: fix hw dropdown

---

src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx

Adding data-test-id on the Scheduling tab when vm is created, and rename the data-test-id on Scheduling tab on the catalog review page.
Before:
After:

Bug 2094646: data-test-id missing on Scheduling tab

---

src/views/templates/details/tabs/parameters/template-parameters-page.scss

The titles in the accordion in Parameters tab didn't visible enough on dark mode, I corrected by changing the style.
Before:
After:

Bug 2086293: [Dark mode] Titles in Parameters tab are not visible enough 

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2093866
Make VM creation work, VM creation from the template, that was created from the default yaml
(without any changes; with _vm-template-example_ as the default VM template name).
**Before:**
Error, cannot create a VM:
**After:**
VM created successfully:

Bug 2093866: Make VM creation from template from default yaml work

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx

When changing memory size on VM, the utilization charts reflect new memory before restarting.
Now instead of looking at VM resources, it will look at VMI resources.

Bug 2094440: Memory Utilization chart VM overview memory change

---

src/utils/resources/vmi/utils/cloud-init.ts

**Bug cause**
When the ssh key is added, the `cloudInitNoCloud` property is converted to `cloudInitConfigDrive` to support `accessCredentials`.
To find user credentials, there is a function that search only for `cloudInitNoCloud` volume ignoring credentials defined in a `cloudInitConfigDrive` volume
**Solution**
Find user credentials on cloudInitNoCloud and/or cloudInitConfigDrive property

Bug 2091897: Cloud Init noCloud and ConfigDrive

---

src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingRightGrid.tsx

this PR include fixes for:
- non-privileged users cant list nodes, so we do not show any info about the qualified nodes for a non-privileged user.
- disable the link to search for nodes as it will lead to an error.
- fixing title from `Dedicated Resources` to `Dedicated resources`

Bug 2094665: dedicated resources modal stuck loading for non priv user

---

src/utils/components/TolerationsModal/TolerationsModal.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/templates/details/tabs/scheduling/components/TolerationsModal.tsx

non-privileged user cant list nodes, so hiding the "Exploe nodes list" button in case of no nodes to show.
https://user-images.githubusercontent.com/67270715/172815627-f2ee4d74-ef93-4e53-94c4-8b46f24eb7ed.mp4

Bug 2094481: tolerations modal show nodes link to non-priv user

---

src/utils/resources/vm/utils/operation-system/operationSystem.ts
src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2095125
Display missing operating system name in the _Clone VirtualMachine_ modal.
Also add little improvements in the related files, such as renaming 'Operating **S**ystem' to 'Operating system' and 'Workload **P**rofile' to 'Workload profile', and adding a missing returning value type `string` to `getOperatingSystemName` function.
**Before:**
No any OS name, in the _Clone VirtualMachine_ modal:
**After:**

Bug 2095125: Display OS name in the Clone VM modal

---

src/templates/vm-template-yaml.ts

Bug 2093867: OS for template 'vm-template-example' should matching the version of the image

---

src/utils/resources/vm/utils/disk/size.ts

**Fixes**:
https://bugzilla.redhat.com/show_bug.cgi?id=2095129
Display the units instead of 'undefined', in the _Clone VirtualMachine_ modal, for the _Disks_ field in the _Configuration_ section.
Related PR: https://github.com/kubevirt-ui/kubevirt-plugin/pull/558
**Before:**
**After:**

Bug 2095129: Display disk size units in Clone VM modal

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/actions/components/EditBootSourceModal.tsx

Signed-off-by: yzamir <yzamir@redhat.com>
Update boot source reference modal title
a. The action "Edit boot source reference" now opens a modal with the same name
b. Opening a new tab for upload is deprecated and should be replaced with inline upload, removed the deprecated options to upload using a different tab.
Before:
After:

Bug 2096620: Update boot source reference modal title

---

src/templates/vm-template-yaml.ts
src/templates/vm-yaml.ts
src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/virtualmachines/list/VirtualMachinesList.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2096166
For VM and VM Template:
Template namespace now depends on the selected project. 
If `all-namespaces` is selected, the template will have namespace `default` pre-filled.

Bug 2096166: New Template namespace fix

---

src/views/clusteroverview/overview/components/getting-started-card/related-operators-section/RelatedOperatorsSection.tsx

Signed-off-by: yzamir <yzamir@redhat.com>
Align related operators icon
Before:
After:

Bug 2096333: Align releated opertors icon

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeSelectProject.tsx

fix validation for required fields in custom wizard in `Create VirtualMachine from Template` page
https://user-images.githubusercontent.com/67270715/173568559-7ea7ea43-01a1-47d5-867d-863778fed3eb.mp4
https://user-images.githubusercontent.com/67270715/173568578-f27c2add-adc9-4d42-b253-7b06b1d55efa.mp4

Bug 2093713: fix custom wizard validation

---

src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/disks/components/DiskRowActions.tsx

https://bugzilla.redhat.com/show_bug.cgi?id=2096492
Don't create ownerReference in dataVolumeTemplate when creating/editing VM template's disks.
VM template does not have uuid as the VM was not created yet.

Bug 2096492: No ownerReference in template

---

src/views/catalog/customize/components/ExpandableOptionalFields.tsx
src/views/catalog/customize/components/ExpandableOptionsFields.scss
src/views/catalog/customize/components/FieldGroup.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2093715
Display the expandable section _Optional parameters_, when customizing VM, correctly - with the correct bottom margin that was missing (except the last parameter). Add the missing Patternfly `Form` React component to achieve the expected look.
**Before:**
**After:**

Bug 2093715: Display Optional parameters correctly

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloudinitDescription/CloudInitDescription.tsx
src/utils/components/CloudinitModal/CloudinitForm.tsx

Cloudint user field was missing declarative text according to - https://bugzilla.redhat.com/show_bug.cgi?id=2094202
Text approve by @lkladnit

Bug 2094202: Adding declarative text to cloudinit user field

---

src/views/catalog/customize/cd.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/utils.ts

Bug 2094453: CD Source selection in VM creation flow is missing Upload option
you can now upload to both types simultaneously 
https://user-images.githubusercontent.com/24938324/173737807-bad32c7f-cf8c-4fbd-93da-c54c3af5c5b3.mov

Bug 2094453: CD Source selection in VM creation flow is missing Upload option

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/vm/utils/disk/constants.ts
src/utils/resources/vm/utils/disk/rowData.ts
src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
src/views/catalog/wizard/tabs/disks/hooks/useWizardDisksTableData.ts
src/views/templates/details/tabs/disks/components/DiskRow.tsx
src/views/templates/details/tabs/disks/hooks/useTemplateDisksTableData.ts
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/disk/DiskListPage.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx

Adding a label to identify environment disks to DiskRow component

Bug 2095573: Add label for env disk

---

src/views/catalog/customize/components/FieldGroup.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2097370
Display missing titles for optional parameters in wizard customization page.
**Before:**
**After:**

Bug 2097370: Display titles in Optional parameters accordion in wizard customization page

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/resources/vm/utils/disk/size.ts
src/utils/utils/units.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogRow.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogTile.tsx
src/views/catalog/wizard/tabs/disks/components/DiskRow.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/overview/components/WizardOverviewDisksTable/WizardOverviewDisksTable.tsx
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/templates/details/tabs/disks/components/DiskRow.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesCPUMemory.tsx
src/views/virtualmachines/details/tabs/details/components/CPUMemory/CPUMemory.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDisks/VirtualMachinesOverviewTabDisksRow.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2096263
Display the units for _Disks_ size/_Memory_ fields in various places across the UI correctly - by adding 'B' suffix to the unit and space between the numeric value and the unit. Display _Mi**B**/Gi**B**/Ti**B**_ units instead of _Mi/Gi/Ti_, and so improve the readability of this info in the UI.
**Before:** Example of a place with the problematic format of the units displayed in the table:
**After:**

Bug 2096263: Display correct units for Disks size/Memory field

---

src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts

editing a data volume disk is not giving the data volume's initial data for access mode and volume mode
https://user-images.githubusercontent.com/67270715/174075749-a7443b7b-06cf-40ae-bfe1-4813f5ff5470.mp4
https://user-images.githubusercontent.com/67270715/174075783-8a1d304f-4f7d-41b2-8b46-5bb1b0978f47.mp4

Bug 2097586: AccessMode should stay on ReadWriteOnce

---

src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx

This PR hides the details card in the cluster overview page for non-admins.

Bug 2092781: Hide the details card for non-admins

---

src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx

This PR hides the top consumers card in the cluster overview page for non-admins.

Bug 2092783: Hide the top consumers card for non-admins

---

src/utils/resources/template/utils/constants.ts
src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
src/views/templates/details/tabs/details/components/WorkloadProfileModal.tsx
src/views/templates/utils/constants.ts
src/views/templates/utils/selectors.ts

**Cause**
Catalog get template workload info from the template label `workload.template.kubevirt.io/${TEMPLATE_WORLOAD} = 'true'` 
Template details instead get this info from VM label `vm.kubevirt.io/workload` as in VM details 
**Solution**
On template details when the user changes the workload, the code should change also the template-related label `workload.template.kubevirt.io/${TEMPLATE_WORLOAD} = 'true'` 
NOTE: I've replaced `WorkloadProfileKeys` and `workloadProfiles` in `/views/template/utils` in favor of `WORKLOADS` and `WORKLOADS_LABELS` in `/utils/resources/template`

Bug 2098135: Template replace workload label

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/overview/components/details-card/DetailsCard.tsx
src/views/clusteroverview/overview/components/details-card/utils/constants.ts

This PR adds the `View details` link to the details card on the cluster overview page. The link leads to the page for the operator.

Bug 2094848: Add view details link to details card

---

src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx

When VM is stopped or VMI is missing, don't show a VNC connect button 
Before
After

Message VM is down when vm is down or on stop state

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawer.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRow.tsx
src/views/virtualmachines/details/tabs/disk/tables/tables.scss

The labels overlap each other as the page shrinks, so I fixed by lowering the label of the name.
Before:
After:

Bug 2090068: Lowering the label of the Name column in vm disks tab

---

src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx

DeschedulerModal is now enable even if vm is running
Requested by QE

Bug 2083595: DeschedulerModal is now enable even if vm is running

---

src/utils/components/DiskModal/DiskFormFields/ApplyStorageProfileSettingsCheckbox.tsx
src/utils/components/DiskModal/utils/helpers.ts
src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
src/views/templates/details/tabs/disks/hooks/useEditDiskState.ts

The "apply StorageProfile settings" checkbox in the disk modal / edit disk modal was not working correctly,
fixed to not have accessModes and volumeMode keys when checkbox is checked, and fixing edit modal showing if user marked this checkbox before creation or not.
https://user-images.githubusercontent.com/67270715/174799255-3ba20c18-4026-4f66-b1eb-be2eb2faf17b.mp4
https://user-images.githubusercontent.com/67270715/174799292-5a4aa1be-9e88-4705-bcfb-454d548c6ba8.mp4

Bug 2097586: fix storage profile settings checkbox

---

src/utils/utils/units.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2099608
Display 'Dynamic', not 'DynamicB' string in the VM _Disks_ card or VM _Disks_ tab - for the disk's _Size_ info,
in cases when the disk size is provided dynamically.
**Before:**
'DynamicB' in the VM _Overview_ _Disks_ card, _Size_ column:
'DynamicB' in the VM _Disks_ tab:
**After:**

Bug 2099608: Display Dynamic instead of DynamicB for dynamic disk size

---

src/utils/components/AffinityModal/utils/helpers.ts

Remove debugger command

---

src/utils/components/TabModal/TabModal.tsx
src/views/catalog/customize/components/FormError.tsx

Add target blank to open links of error in new tabs.

Bug 2099535: Adding target blank to error message href links

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/vm/utils/selectors.ts
src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

Display qemu machine type in the VM/Template _Details_ tab, the field is not editable. 
_Related doc:_
https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#machine-type
_Issue:_
https://issues.redhat.com/browse/CNV-12598
_Machine type_ field in the VM _Details_ tab:
_Machine type_ field in the VM Template's _Details_ tab:

Expose qemu machine type read-only in VM Details tab

---

.devcontainer/docker-compose.yml

The devcontainer environment has created a directory called `hosts.yaml` which caused some issues with the Github cli.
`hosts.yaml` is a github file and volumes can be only directories.

hosts.yml file not a directory

---

OWNERS

Add metalice to approvers

---

src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx

Display qemu machine type in the VMI _Details_ tab, the field is not editable.
_Related upstream doc:_
https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#machine-type
_Issue:_
https://issues.redhat.com/browse/CNV-12598
Machine type field in the VMI _Details_ tab:

Expose qemu machine type read-only in VMI Details tab

---

src/views/templates/details/tabs/network/components/modal/components/NetworkInterfaceNetworkSelect.tsx

VM object from a template is missing namespace. field kept loading forever.
field failed to get a proper response.
After:
Before:

Bug 2101499: Template adding nic keep loading for test user

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceDataSourceSelectName.tsx

**Cause**
Data source project value is a parameter so cannot load data sources
**Solution**
Disable the data source selection when the project is a parameter and display the data source select when is disabled without waiting to load other data sources.

Bug 2101628: DataSource selection with parameter

---

src/views/templates/details/tabs/details/components/WorkloadProfileModal.tsx
src/views/templates/utils/index.ts
src/views/templates/utils/selectors.ts

This is a small refactoring PR related to:
using `getTemplateVirtualMachineObject` function to get the VM object where needed, instead of hardcoced `template.objects[0]`, in the template utils/selectors.

Use getTemplateVirtualMachineObject in template utils

---

src/templates/vm-template-yaml.ts
src/utils/resources/template/utils/selectors.ts

Make sure the Template example is shown like a fedora template. 
- fedora icon for template example
- OS like other fedora distributions
- filtered as a fedora template
Getting the OS key:
Before: getting the os distro key from the VM metadata `vm.kubevirt.io/template` annotation (indicate the template name used to create the VM like fedora-desktop-small). 
After: use the proper annotation from VM -> spec -> template -> metadata -> annotation `vm.kubevirt.io/os` (annotation used to indicate the actual os key).

Bug 2102475: Template example like fedora

---

src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx

Display qemu 'Machine type' in the _Overview_ tab of the _Review and create VirtualMachine_ page. The field is not editable.
_Related upstream doc:_
https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#machine-type
_Issue:_
https://issues.redhat.com/browse/CNV-12598

Add Machine type field to Review and create VirtualMachine

---

src/views/clusteroverview/overview/components/ClusterOverviewPage.tsx
src/views/clusteroverview/overview/components/MonitoringTab.tsx
src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.scss
src/views/clusteroverview/overview/components/top-consumers-card/TopConsumersCard.tsx

This PR is renaming the `Performance` tab to `Monitoring` and removing redundant padding
For more info about this issue:
sub-task: https://issues.redhat.com/browse/CNV-19599
issue: https://issues.redhat.com/browse/CNV-18220

CNV19599: Rename overview performance tab to monitoring

---

src/utils/components/HardwareDevices/HardwareDevicesModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2100682
Delete only the appropriate hardware device (GPU device/Host device)
from the devices list, when clicking on the icon to delete
on the right in the modal.
Having 2 devices with the same _Name_ leading to the buggy scenario:
**Before:**
Deletion of the one of the devices caused deletion of all the devices with the same _Name_:
**After:**
Only the appropriate device deleted:

Bug 2100682: Delete only the appropriate HW device in the modal

---

src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/utils/virtualMachineStatuses.ts

Bug 2101335: Clone action enabled for CrashLoopBackOff

---

src/utils/components/HardwareDevices/HardwareDeviceTitle.tsx
src/views/catalog/wizard/components/WizardDescriptionItem/WizardDescriptionItem.tsx
src/views/virtualmachines/details/tabs/details/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2101167
Fix the area of Edit buttons in the VM _Details_ and _Scheduling_ tabs, also in the _Details_, _Scheduling_ and _Metadata_ tabs/pages of VM creation flow. Limit the clickable area only to the text and not the whole line, so clicking on the empty space is not possible anymore.
**Before:**
**After:**

Bug 2101167: Fix the clickable area for Edit buttons in VM pages

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2102740
Specify the submit button text for the _Clone VirtualMachine_ modal to be consistent with the appropriate action and with the button for _Clone template_ modal.
**Before:**
**After:**

Bug 2102740: Rename Save button to Clone in Clone VM modal

---

src/utils/components/WorkloadProfileModal/WorkloadProfileModal.tsx
src/utils/resources/vm/utils/selectors.ts
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/templates/details/tabs/details/components/WorkloadProfile.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

- Made template WorkloadProfileModal generic and moved into the utils folder
- use this modal in VM and wizard
Workload metadata Not available
Wizard
VM

Bug 2100684: Edit workload vm

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/PendingChanges/hooks/usePendingChanges.tsx

changing the `boot method` text to `Boot mode` as a follow up fix to https://github.com/kubevirt-ui/kubevirt-plugin/pull/422#discussion_r915674592

Change text 'boot method' to 'boot mode'

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx

Name the PVC source name the same as the VM name, according to the parameter NAME in the yaml used also for the PVC source name.
The problem was that the part of the processing template was omitted, when quick creating VM, comparing creating VM with the customization process. The parameter NAME was not properly set when quick creating VM.
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2103807
**Before:**
**After:**

Bug 2103807: Name PVC source same as VM name when creating VM quickly

---

src/views/clusteroverview/overview/components/top-consumers-card/utils/TopConsumerCard.tsx

This PR adds additional optional chaining operators to prevent further `undefined` errors in the top consumer card of the virtualization overview.

Bug 2108253: Add safety nets to topconsumercard

---

src/utils/components/SSHAccess/SSHAccessModal.tsx
src/utils/components/SSHAccess/constants.ts
src/utils/components/SSHAccess/useSSHService.tsx
src/utils/components/SSHAccess/utils.ts
src/utils/resources/vmi/utils/services.ts
src/utils/resources/vmi/utils/tests/services.test.ts
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/RunningVirtualMachineDetailsRightGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachines/details/tabs/details/components/sections/ServicesSection.tsx
src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx

Show services with stopped VM using `vm.spec.template.metadata.labels` instead of `vmi.metadata.labels` when vmi is not available (because vm not running)
Do you guys think we need both vm and vmi? Or we can just use `vm.spec.template.metadata.labels` ?

Bug 2100442: show ssh service even without running vm

---

src/utils/hooks/useDeschedulerInstalled.ts
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
src/views/templates/details/tabs/details/components/CPUMemory.tsx
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/templates/details/tabs/details/components/DisplayName.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsRightGrid.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/components/list/NetworkInterfaceActions.tsx
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResources.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx
src/views/templates/details/tabs/scheduling/components/Descheduler.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModal.tsx
src/views/templates/details/tabs/scheduling/components/DeschedulerModalButton.tsx
src/views/templates/details/tabs/scripts/SysPrepItem.tsx
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
src/views/templates/utils/utils.ts
src/views/virtualmachines/details/tabs/scheduling/components/VirtualMachineSchedulingLeftGrid.tsx
src/views/virtualmachinesinstance/details/tabs/scheduling/Descheduler/Descheduler.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2104424
Check correctly if the Kube Descheduler Operator is installed and enable/disable _Descheduler_ field appropriately on VMs/Templates _Scheduling_ tabs, also in the _Review and create VirtualMachine_ page - _Scheduling_ tab.
Additionaly, remove unnecessary title from the _Review and create VirtualMachine_ page - _Scheduling_ tab for UI consistency reasons.
**Before:**
Templates _Scheduling_ tab and _Descheduler_ field disabled even when the operator is installed:
_Review and create VirtualMachine_ page - _Scheduling_ tab with the unnecessary title, also _Descheduler_ field always editable no matter the operator installed:
**After:**

Bug 2104424: Check Descheduler Operator and enable/disable on pages

---

src/utils/hooks/useKubevirtWatchResource.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx

the `useK8sWatchResource` from SDK returns in-consistent data (especially when argument `isList: true` is set)
We get sometimes (not 100% reproducible) an object of `V1VirtualMachineList` instead of `V1VirtualMachine[]` which causing the VM list page to crash.
The solution is to wrap the `useK8sWatchResource` hook with extra logic to guarantee we get the list of resources as needed for the VirtualizedTable component.
Also changed the table to receive null as `loadError` prop since we're getting an error whenever the `useK8sWatchResource` return a non-expected result
NOTE: `loadError` variable contains the following error message:
```
TypeError: e.get(...).get is not a function
at main-chunk-38cf75c9479113bc6a73.min.js:1
at Set.forEach …
```

Bug 2111328: kubevirt plugin console crashed after visit vmi page

---

src/utils/hooks/useKubevirtWatchResource.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx

When a non-priv user reaches VM list page with no namespace selected the page is looks like it's stuck on loading
https://user-images.githubusercontent.com/67270715/182141872-68702a23-0767-4b3c-b517-e7edbb88df71.mp4

Fix vm list stuck loading

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2114516
Make the link in the "Example" for Fedora work, when editing template's disk and choosing "URL (creates PVC)" as _Source_ in the _Edit disk_ modal.
The core of the problem was missing some default value for the `os` (in some edge cases when it is `undefined`), comparing to what is returned for `getURLSourceHelpertText` function (used [in the affected component](https://github.com/kubevirt-ui/kubevirt-plugin/blob/main/src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx#L14)): Fedora OS related helper text. So the same OS was used as the default one also in the affected `URLSourceHelperText` component.
_Before:_
Nothing happens after clicking on **_Fedora cloud image list_** link. …

Bug 2114516: Open website after clicking on Fedora cloud image list link

---

jest.config.ts
src/utils/resources/template/utils/helpers.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
src/views/catalog/utils/quick-create-vm.ts

In a follow-up pr, I'll solve this bug also in the wizard using the same function `createAllTemplateObjects`   
In this solution, I use `Promise.all`. This means that if any object creation request fails, it will follow the fail-fast behavior and throw an exception without waiting for the other promise's resolution.
What to do if one object fail?
Maybe some objects have been created and at least one failed. What can we do? We can try to delete the created objects? WDYT?  I can do it in a separate pr

Bug 2060499: Quick create - template with multiple objects

---

src/views/clusteroverview/SettingsTab/LiveMigrationTab/Limits/Limits.tsx

In virtualization -> setting tab -> live migration tab - if a user types a negative value, it will fail the call and set a zero number instead of not changing the value. This fix will now check for positive/zero values before sending.

reinforcing negative values inputs for migration per cluster and node

---

src/utils/components/SysprepModal/SysprepModal.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/templates/details/tabs/scripts/SysPrepItem.tsx
src/views/templates/details/tabs/scripts/sysprep-utils.ts

Currently, the template can only be attached to an existing Sysprep config in the same namespace.
Now we can add it to the template objects array.
Users can choose between creating a new one every time the template is used or attaching the template to an existing Sysprep config.
Same thing can be done for ssh keys and ssh services

Bug 2096780: Add Sysprep in template Objects array

---

src/utils/hooks/useDefaultStorage/constants.ts
src/utils/hooks/useDefaultStorage/useDefaultStorageClass.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/utils/quick-create-vm.ts

Quick create option from the catalog would have not to use the default storage class but will use the storage class from the template.
Wizard is using the default storage class.
The behavior will now be the same as the wizard, and quick create will use of the default storage class.

Bug 2115258: Quick create -default storage class name

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
src/utils/components/UserCredentials/useSSHCommand.ts
src/utils/resources/vmi/utils/cloud-init.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2101423
Display the user name correctly in the _Guest login credentials_ in the VM's _Console_ tab.
KubeVirt supports the cloud-init NoCloud and ConfigDrive data sources. The implementation for ConfigDrive data source was missing. The fix supports also displaying multiple usernames. Note that `users` (list of objects) is optional in the `passwd` object.
_Useful docs:_
https://coreos.github.io/ignition/configuration-v3_3/
https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#cloud-init
Thanks to @DanaOrr for her suggestions on https://github.com/kubevirt-ui/kubevirt-plugin/pull/806.
**Before:**
Displaying "[" as the _User name_ not corresponding to the VM's yaml:
**After:**
Displaying the _User name_ correctly:
If more users …

Bug 2101423: Display user name on using ignition

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/disk/tables/filesystem/FilesystemListTitle.tsx

This is a small nitpick, a forgotten little change, that should have been [here](https://github.com/kubevirt-ui/kubevirt-plugin/pull/823/files#diff-9f0ec7188a61121e7080447079f9c5959569cbe8defb33218027a30125aa465eR12).
**Before:**
**After:**

Bug 2114636: Change "File system" title to plural in VM Disks tab

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx

Fix when we click the "Review and create VirtualMachine" button, the error will not pop up and we can create a new vm with the new option selected.
Before:
After:

Bug 2100290: Fix when creating a new vm the error doesn't dismissed

---

src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/utils/WizardVMContext/utils/vm-produce.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
src/views/catalog/wizard/tabs/scripts/components/sshkey-utils.ts

Have the wizard play nice with multiple object templates.
SSH auth key section in scripts tab now will add and change secret in the `additionalResources` tabsData. 
Why this pr? 
The template can have in the objects array an already configured secret. With this pr will be detected in the wizard.

Bug 2096780: Wizard with ssh key in additionalResources

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

Adding column management to VM list view
NOTES: 
- The kebab actions columns have no title and it appears as empty in the column management component, we should consider giving this column the `Actions` title so it will look better.
- When moving to a specific namespace and using the management column, check and uncheck to the namespace column will not make any effect, we should consider removing that column when user is under any namespace scope and not the `all-projects` scope.
@metalice @vojtechszocs @hstastna @pcbailey @upalatucci please review
https://user-images.githubusercontent.com/67270715/187917424-dcbbcf4a-ff3f-4408-b7f0-c99032ae832e.mp4

CNV19691: Add table column management to VM list

---

src/utils/hooks/useSingleNodeCluster.ts
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRow.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRunningRow.tsx

When we have a single node cluster, we don't need to enable the option of migration as there are no different nodes to move the resource to.

CNV-21029: Disable migration if its a single node cluster

---

src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

Checking the namespace in the column management component when inside any project was not having any effect.
the fix includes hiding the namespace column since it's not manageable, and can't be disabled.
https://user-images.githubusercontent.com/67270715/188448590-ae095ea5-f705-4fd0-b264-fbeb96b6aa0e.mp4

Fix namespace column management

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsRow.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/MigrationsTable.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
src/views/datasources/list/DataSourcesList.tsx
src/views/datasources/list/DataSourcesListRow.tsx
src/views/datasources/list/hooks/useDataSourcesColumns.ts
src/views/migrationpolicies/list/MigrationPoliciesList.tsx
src/views/migrationpolicies/list/components/MigrationPoliciesRow/MigrationPoliciesRow.tsx
src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts

Adding column management to Template, DataSources, MigrationPolicies and VirtualMachineInstanceMigrations lists.

Add column management

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/GuestAgentIsRequiredText/GuestAgentIsRequiredText.tsx
src/views/virtualmachines/actions/components/CloneVMModal/components/ConfigurationSummary.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/utils/gridHelper.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2117813
Unify the text displayed in the VM _Overview_ and _Details_ tabs: Display 'Not available' for a stopped VM in both tabs.
Display 'Guest agent is required' only when the VM is running and guest agent missing.
**Before:**
**After:**
When the VM is running and guest agent missing, display 'Guest agent is required' text, same as before:

Bug 2117813: Display 'Not available' for a stopped VM

---

src/views/datasources/hooks/useDataSourceActions.tsx

When deleting Datasource, dataimportcron is deleted, but after, so it causes the datasource to reappear in the UI.
The change now will delete first the dataimportcron and then the datasource

Bug 2124565: Deleted datasource reappear in the ui

---

src/utils/components/CloudinitModal/utils/useCloudInit.ts

**Cause**
With ssh key the cloud-init volume does not use `cloudInitNoCloud` but `cloudInitConfigDrive`.

Bug 2117549: Cannot edit cloud-init data after add ssh key

---

src/views/virtualmachines/details/tabs/disk/modal/hooks/useVolumeOwnedResource.tsx
src/views/virtualmachines/details/tabs/disk/modal/hooks/utils/utils.ts

delete modal is searching for datavolume to delete, but when datavolume garbage collector is on, there isn't any datavolume to delete and PVC should be instead deleted. 

Bug 2124307: Fix crash/stuck of detaching disk

---

src/views/clusteroverview/MonitoringTab/top-consumers-card/TopConsumersCard.tsx

Change top consumer metrics default time to 30mins, to match observe dashboard.

Bug 2127931: Change top consumer metrics default to 30 minutes

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DeleteResourceMessage/DeleteResourceMessage.tsx
src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2128002
**Before:**
**After:**

Bug 2128002: Display VM Templates list after template deletion

---

src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx

Adding link to 4.11 doc for migration policies (given by doc team)

Bug 2124555: View documentation link on MigrationPolicies page doesn't work

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/SettingsTab/SettingsTab.tsx
src/views/clusteroverview/SettingsTab/settings-tab.scss

The namespace bar has been added to the entire overview page, which could cause users to think that settings are only effective for the selected namespace. This PR adds an alert to the settings tab that informs users that settings are effective cluster-wide.

Add message alerting users to scope of the settings tab

---

console-extensions.json
src/templates/index.ts
src/templates/migrationpolicy-yaml.ts

adding missing property for YAML example to allow creation
https://user-images.githubusercontent.com/67270715/192751898-e89fc296-4e4f-4da5-86cb-8ed8849e668f.mp4
https://user-images.githubusercontent.com/67270715/192751934-2000824f-3af1-46b8-90df-7e40aa54124a.mp4

Bug 2128949: Cannot create MigrationPolicy from example YAML

---

src/views/catalog/utils/quick-create-vm.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/utils/utils.ts

Add VM as ownerReferences to the additional objects in the creation.
Why only in the creation? ownerReferences needs the UUID that only the created VM can have.

Bug 2129234: Add ownerReferences to template additional objects

---

src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/utils/virtualMachineRowFilter.ts

Changing the `Other` opt to `None` for template filter to avoid conflicts on different filters and to have better terminology for not having a template label in the VM.

Bug 2101144: VM filter has two 'Other' checkboxes which are triggered together

---

src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx
src/views/migrationpolicies/list/MigrationPoliciesList.tsx
src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2124558
Allow _MigrationPolicy_ creation only to privileged user by displaying _Create MigrationPolicy_ button only for such users.
**Before**:
The unprivileged user can click on _Create MigrationPolicy_ button:
**After**:
No any  _Create MigrationPolicy_ button present for unprivileged user:

Bug 2124558: Allow MigrationPolicy creation only to privileged user

---

src/views/templates/actions/components/EditBootSourceModal.scss
src/views/templates/actions/components/EditBootSourceModal.tsx
src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
src/views/templates/actions/components/PersistentVolumeClaimSelect/PersistentVolumeSelectName.tsx
src/views/templates/actions/components/PersistentVolumeClaimSelect/utils.tsx
src/views/templates/actions/components/SelectSource.tsx
src/views/templates/actions/components/SelectSourceSkeleton.tsx
src/views/templates/actions/components/utils.ts
src/views/templates/actions/editBootSource.ts

**Cause**
The EditBootSourceModal does not fetch the dataVolume and does not show the dataVolume source.
**Solution**
Fetch DV from DataSource and get from it the specs. Populate the form with specs data and be able to edit them. On submission, edit the DV
Most of the changes were made in the [SelectSource](https://github.com/kubevirt-ui/kubevirt-plugin/pull/913/files#diff-67651d5ff71151c93431684b8f429ba4985aef31fb688bbb6ee994ebb0b09daf).
The previous select source was not accepting a state or an initial state so was impossible to solve the bug without touching it.
Also in the component, there were a giant `useEffect` runner at every update. 
Now the SelectSource accepts a state (data volume spec) and all the component states were transformed into constants dependent on that state. There …

Bug 2132793: Load and show boot source reference

---

src/views/clusteroverview/MonitoringTab/top-consumers-card/utils/utils.ts

The values for storage throughput in the top consumers card were being reported incorrectly when compared with the same metric in the top consumers dashboard in Observe > Dashboards. This PR fixes the issue by using the correct function to convert from the bytes returned from Prometheus to the unit to be displayed.
Before:
After:

Bug 2071491: Fix storage throughput value in Top Consumers card

---

src/utils/components/Charts/MigrationUtil/MigrationThresholdChartDiskRate.tsx
src/utils/components/Charts/utils/queries.ts
src/views/virtualmachines/details/tabs/metrics/MigrationCharts/MigrationCharts.tsx

Adding kv disk data rate chart to metrics tab - most of the time this chart will not have data according to https://bugzilla.redhat.com/show_bug.cgi?id=2117186

Bug 2131157: Adding KV disk data rate to metrics tab

---

cypress/utils/const/testVM.ts
locales/en/plugin__kubevirt-plugin.json
src/views/catalog/customize/CustomizeVirtualMachine.tsx
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx
src/views/catalog/customize/tests/CustomizeSource.test.tsx
src/views/catalog/customize/tests/CustomizeVirtualMachine.test.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx

Removing the "Template default" option when there's no default data source exists for the template
https://user-images.githubusercontent.com/67270715/193026766-855c6a71-3887-4873-b236-bb2ea84b2402.mp4

Bug 2093771: The disk source should be PVC if the template has no auto-update boot source

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/ClusterOverviewPage.tsx

> Removing the monitoring tab and moving the top consumers and migration cards to main navigation

Bug 2132746: Background is broken in Virtualization Monitoring page

---

src/utils/components/CapacityInput/CapacityInput.tsx

Bug 2119615: The unit field doesn't change if the size number is big enough in Disk modal

---

src/utils/components/Consoles/Consoles.tsx
src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentials.tsx
src/utils/components/Consoles/components/CloudInitCredentials/CloudInitCredentialsContent.tsx
src/utils/components/SSHAccess/components/SSHCommand.tsx
src/utils/components/SSHAccess/useSSHCommand.ts
src/utils/resources/vmi/utils/cloud-init.ts
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2117803#c7
Get the correct cloud-init credentials even when the VM is stopped and generate the ssh command properly (_SSH over NodePort_).
Disable the SSH over NodePort related checkbox and show the tooltip on hover to inform the user in case that there is no username set.
**Before:**
The username missing in the command:
**After:**
The username present in the command:
If there is no username set, it doesn't make sense to display the command:

Bug 2117803: Display correct command with username for SSH

---

src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.scss
src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusesCard.tsx
src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts

In dark mode the additional status in the virtual machine statuses card was not visible enough.
And I removed the icons in the additional status because they are the same. 
Before:
After:

Bug 2131165: Fixed in virtual machine statuses card the dark mode and removing icons

---

src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDataVolumeConvertedVolumeNames.ts
src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDeleteVMResources.ts
src/views/virtualmachines/details/tabs/disk/modal/hooks/utils/utils.ts

> DataVolume is now garbage collected after creating the PVC, when trying to delete the DataVolume it no longer exists which causes it to not find the proper resource to delete.

Bug 2137241: Checkbox about delete vm disks is not loaded while deleting VM

---

src/views/datasources/dataimportcron/hooks/useDataImportCronActions.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2137349
Prevent _Manage source_ action from loading infinitely, in the _Actions_ menu on _DataImportCron Details_ page.
**Before:**
**After:**

Bug 2137349: Prevent "Manage source" action from loading infinitely

---

src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts

Bug 2137736: The column name "MigrationPolicy name" can just be "Name"

---

src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx
src/views/clusteroverview/OverviewTab/vm-statuses-card/utils/utils.ts
src/views/virtualmachines/utils/virtualMachineRowFilter.ts
src/views/virtualmachines/utils/virtualMachineStatuses.ts

issues:
- Error status on overview has no link to VM Failed status - link was added and VM Failed status changed to Error for consistency
- VM status link in the overview where broken - namespace prop was having a value of `#ALL-NS#` instead of being empty made a check to verify if namespace value indicates on `all-namespace` or a specific namespace
https://user-images.githubusercontent.com/67270715/197972342-93f0bf22-8787-460d-85b4-a1e20819b50a.mp4
https://user-images.githubusercontent.com/67270715/197972376-da862572-3e59-48f1-865f-a2b814008f62.mp4
NOTE: this PR also solves https://bugzilla.redhat.com/show_bug.cgi?id=2137731 as they are strongly related and to avoid PR conflicts

Bug 2137731: Overview links for VM status not working

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx

> Guest agent is showing wrong pretty name data for win 11 so we change the way we evaluate the OS for the single VM overview details card

Bug 2136425: Windows 11 is detected as Windows 10

---

src/views/clusteroverview/SettingsTab/settings-tab.scss

the card height was 100% and in addition to the alert's component height we got unwanted scrollbar which broke the background from the overview copmonent.

Bug 2132746: Background is broken in Virtualization Settings page

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
src/views/catalog/customize/components/CustomizeSource/SelectSourceOption.tsx
src/views/templates/actions/components/SelectSourceOption.tsx

> Change URL disk source description to show support of HTTPS and not S3 URLs
https://user-images.githubusercontent.com/67270715/198296850-f125fe95-281e-4c98-a4b8-807427d9286a.mp4

Bug 2138112: Unsupported S3 endpoint option in Add disk modal

---

src/utils/hooks/useSingleNodeCluster.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx

> The VM list was stuck as it tried to fetch the Infrastructure resource which a non-priv user is usually not allowed to list this resource at all, also missing the namespace prop for vmim resource list which also is not allowed on cluster scope for non-priv users, both caused the VM list page to stuck as it is still loading

Bug 2139293: Non-admin user cannot load VM list page

---

console-extensions.json

> requiring `CAN_LIST_NS` flag for MigrationPolicies page to show this page only for privileged users

Bug 2139296: Non-admin cannot load MigrationPolicies page

---

console-extensions.json
src/views/clusteroverview/ClusterOverviewPage.tsx

> NamespaceBar component is causing issues for non-priv users, removed NamespaceBar component and injected via console-extensions

Bug 2139479: virtualization overview crashes for non-priv user

---

src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/virtualmachines/list/VirtualMachinesList.tsx

> Non-privileged user could click on create for both VirtualMachine and Templates views under namespace not allowed to `list` or `create` and eventually leads to a crash

Bug 2139651: non-priv user can click create when have no permissions

---

src/utils/components/CapacityInput/CapacityInput.tsx
src/utils/components/DiskModal/DiskFormFields/utils/constants.ts

When trying to edit root disk to use the existing PVC option getting this error message:

Bug 2139257: cant edit root disk to use existing PVC

---

src/utils/hooks/useLastNamespacePath.ts
src/views/templates/actions/hooks/useVirtualMachineTemplatesActions.tsx
src/views/templates/details/TemplatePageTitle.tsx
src/views/virtualmachines/actions/components/DeleteVMModal/DeleteVMModal.tsx
src/views/virtualmachines/list/components/VirtualMachineBreadcrumb/VirtualMachineBreadcrumb.tsx
src/views/virtualmachinesinstance/list/components/VirtualMachineInstanceBreadcrumb/VirtualMachineInstanceBreadcrumb.tsx

> getting error about useLastNamespace hook from SDK when trying to reach VM details page (also affecting VM delete modal, vmi details page, template details page, and templates list page).
to get the actual last namespace property we can access it through the local storage (as done by console)
currently no option to reset it but only view it
https://user-images.githubusercontent.com/67270715/199743562-57d7f3f6-2ca6-4cc8-ab92-c950ea1d45c1.mp4
https://user-images.githubusercontent.com/67270715/199743610-f8256217-ebdb-409a-8d98-515541f7477b.mp4

Bug 2139820: cant reach vm details

---

src/utils/components/DiskModal/DiskFormFields/StorageClassSelect.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2140627
Allow to select StorageClass when adding a new Disk to a VM if there is no default storageclass defined.
Note that if you want to reproduce this bug, you need to:
- set the annotation _storageclass.kubernetes.io/is-default-class_ to `'false'` for all storage classes
(in _Storage_ > _StorageClasses_)
**Before:**
Not being able to select a different StorageClass than already selected (nothing happens when clicking on it):
Error in the browser console:
**After:**
Successfully selected a different StorageClass, incl. displaying the correct info:

Bug 2140627: Allow to select storageClass in Add disk modal

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/customize/components/FormActionGroup.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2138119
Rename "Review and create VirtualMachine" button on the Edit Template Parameters modal to "Next", to make the process of VM creation more clear to the user.
**Before:**
**After:**

Bug 2138119: Rename "Review and create VirtualMachine" to "Next"

---

src/utils/resources/shared.ts
src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2140730
Make links to the lists of VMs, Templates, Networks work correctly - to lead to the correct list of the resources with the correct project/namespace name.
**Before:** 
After clicking on the number of _VirtualMachines_ in the _Virtualization > Overview_ page, VMs for _All Projects_ are displayed, all the VMs incl. those that don't belong to the namespace or project originally set in the _Overview_ page (same for the Templates, Networks):
**After:**

Bug 2140730: Make links to resources on Overview page work correctly

---

src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
src/views/clusteroverview/OverviewTab/resources-inventory-card/hooks/useResourcesQuantities.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2140998
Display the correct number of Nodes and NADs/Networks in the Virtualization Overview page.
_Cause:_
The number of Nodes wasn't fetched correctly (`namespace` was unnecessary). 
Regarding NADs, there was a mismatch between "nads" and "networks" in the code.
_Note:_
When testing/reproducing this bug, make sure the project name/namespace in the _Overview_ page is the same - for "before" and "after" scenarios.
**Before:**
Incorrect numbers in the Nodes and Networks cards (after clicking on the number, the correct list is displayed):
**After**:

Bug 2140998: Display correct number of Nodes and NADs in the Overview

---

src/utils/components/CloneTemplateModal/CloneTemplateModal.tsx
src/views/templates/utils/constants.ts
src/views/templates/utils/selectors.ts

when cloning a template we need to add labels to the template object so we can identify the base template
https://user-images.githubusercontent.com/67270715/200864410-f6a3ab64-c2fc-48c0-823f-b839605af3b8.mp4

Bug 2140982: The base template of cloned template is "Not available"

---

src/utils/resources/shared.ts
src/utils/tests/resource.test.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/wizard/components/WizardFooter.tsx
src/views/clusteroverview/OverviewTab/resources-inventory-card/ResourcesInventoryCard.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/MigrationProgressPopover/MigrationProgressPopover.tsx

Improve `getResourceUrl` function to accept an object instead of separate arguments. 
See: https://github.com/kubevirt-ui/kubevirt-plugin/pull/958#discussion_r1018068575

Improve getResourceUrl to accept an object instead of separate args

---

src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

> hiding the node column in case a user is non-privileged that can't list nodes

Bug 2141711: Node column selector is redundant for non-priv user

---

src/utils/components/DeleteModal/DeleteModal.tsx

> Delete modal was building the return URL in the wrong way which caused to 404 error when deleting a resource with a short name like `a`
basing now the return URL on the deleted resource's model to create the URL
https://user-images.githubusercontent.com/67270715/201921035-2b98ac3d-3cf0-49ed-a201-995e75766750.mp4
https://user-images.githubusercontent.com/67270715/201921026-5ffb0076-3679-4dc8-a900-6e79c2fb66c6.mp4

Bug 2142647: Delete modal lead to wrong URL

---

src/utils/resources/template/hooks/useProcessedTemplate.ts
src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
src/views/catalog/customize/utils.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/utils.ts
src/views/catalog/utils/quick-create-vm.ts

workaround to failing proccessTemplate request as namespace of request call e.g. the active namespace is not the same as the namespace of the proccessed Template (regression from v4.12.0-151)
https://user-images.githubusercontent.com/67270715/202486230-9501c27f-e151-4367-ad3e-b553d3b458c2.mp4
https://user-images.githubusercontent.com/67270715/202485898-0c4ae87b-42e2-44a1-88ff-319cdcd4024b.mp4

' Bug 2143498:  Could not load template while creating VM from catalog'

---

src/views/templates/details/tabs/disks/components/DiskListTitle.tsx
src/views/templates/details/tabs/disks/template-disk-tab.scss

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2144580
Display the Patternfly _HelpIcon_ in size small, according to the design recommendations and for consistency reasons, in the _Disks_ tab's page title.
_Note:_
There is an older BZ for the same problem but for VMs:
https://bugzilla.redhat.com/show_bug.cgi?id=2090057
**Before**:
**After:**

Bug 2144580: Make Help icon small in VM Template's Disks tab

---

src/utils/components/AlertsCard/AlertsCard.tsx
src/utils/hooks/useKubevirtAlerts.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2144839
Display the correct total number of Alerts on Virtualization _Overview_ page - _Alerts_ card, according to the selected scope:
- Virtualization health only or
- All alerts.
**Before:**
Number of all alerts displayed in the brackets, when "Show virtualization health alerts" selected:
**After:**
Only the number of virtualization health alerts displayed:

[release-4.12] Bug 2144839: Display correct number of Alerts on Overview page

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloudinitModal/CloudinitForm.tsx
src/utils/components/HostnameModal/HostnameModal.tsx
src/utils/components/PendingChanges/hooks/usePendingChanges.tsx
src/utils/components/PendingChanges/utils/helpers.ts
src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

Removing the hostname field in the Cloud-init form
Before:
After:
Adding the option to edit the hostname on the details page: 
Adding the hostname field to the Review and create VirtualMachine page:

CNV-22029: Adding the option to edit the Hostname

---

src/views/clusteroverview/OverviewTab/vm-statuses-card/VMStatusItem.tsx

> trying to render an undefined component (the status icon is undefined for about a second), which causes react to crash
> adding safety to render Icon only if defined would cause react to avoid this crash and will still render the icons properly
https://user-images.githubusercontent.com/67270715/206159052-9e8e698d-89d0-49f4-b16c-5722ca204531.mp4
https://user-images.githubusercontent.com/67270715/206159081-82763e91-397b-4e79-a385-fbc4b6745bc0.mp4

Bug 2151427: Virtualization -> Overview is crashed when creating VM in other browser session

---

src/utils/components/Consoles/components/SerialConsole/SerialConsole.scss
src/utils/components/Consoles/components/SerialConsole/SerialConsole.tsx
src/utils/components/Consoles/components/SerialConsole/SerialConsoleActions.tsx

Adding a paste to console button for serial console
[issue](https://issues.redhat.com/browse/CNV-23051)

Bug 2149897: The context menu of the serial console does not contain a paste command

---

src/views/cdi-upload-provider/PVCAlertExtension.tsx

Changing to render null instead of undefined to avoid React minified error 152#

Bug 2155409: PVC details page crashing

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx

This is the 2nd PR for the feature: https://issues.redhat.com/browse/CNV-21086
Add 'Live migratable' field to the _Details_ card in the VM _Overview_ tab.
**Before:**
**After:**

CNV-21086: Add 'Live migratable' field to the VM Overview tab

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

This is the 3rd PR for the feature: https://issues.redhat.com/browse/CNV-21086
**Before:**
**After:**
_Live migratable_ field present under the _Status_ with the appropriate Yes/No value:

CNV-21086: Add Live migratable to VM Details tab

---

src/utils/resources/template/hooks/useProcessedTemplate.ts
src/views/catalog/customize/utils.ts
src/views/catalog/utils/quick-create-vm.ts

manual backport for https://github.com/kubevirt-ui/kubevirt-plugin/pull/974
https://user-images.githubusercontent.com/67270715/209650035-198ce3df-5d86-4453-8b1a-daa2757b61c3.mp4
https://user-images.githubusercontent.com/67270715/209649415-de02dc63-f62d-4084-9904-40c1ea5cba45.mp4

Bug 2154257: 'Quick create VirtualMachine' does no show up when upgrade OCP 4.11 to OCP 4.12

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
src/views/virtualmachines/list/components/VMNotMigratableBadge/VMNotMigratableBadge.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx
src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx

This is another PR for the feature: https://issues.redhat.com/browse/CNV-21086
Add 'Not migratable' badge to _Status_ in the _Details_ card of the VM _Overview_ tab, instead of 'Live migratable' field (removed in this PR), to clearly mark the VM that isn't live migratable (only if it isn't, of course).
This change follows the very recent design changes. With this change, we achieve the UI to be more "airy" and the non live migratable VM is very easily recognized, and we also save some space in the UI.
**Before:**
_Live migratable_ field always present in the VM _Overview_:
**After:**
'Not migratable' badge displayed only if the VM is not live migratable:

CNV-21086: Add 'Not migratable' badge to VM Overview tab

---

src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx

This is another (hopefully the last) PR for the feature: https://issues.redhat.com/browse/CNV-21086
Add 'Not migratable' badge next to the status in the VM title, to clearly mark the VM that isn't live migratable (only if it isn't, of course), according to the very recent design changes. 
**Before:**
Not so clearly and fast recognizable from the VM title, if the VM is/isn't live migratable:
**After:**
'Not migratable' badge present next to the status in the VM title, clearly marking the non live migratable VM:

CNV-21086: Add 'Not migratable' badge to VM title

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/SidebarEditor/SidebarEditorSwitch.tsx
src/utils/components/SidebarEditor/sidebar-editor.scss

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2160298
Simplify the text and use the regular font weight, not the **bold** one, according to the design changes.
**Before:**
When the switcher is off:
When the switcher is on:
**After:**

Bug 2160298: Simplify YAML Switcher text to "YAML"

---

src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/VirtualMachinesOverviewTabDetails.tsx
src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx
src/views/virtualmachines/list/components/VirtualMachineStatus/VirtualMachineStatus.tsx

This is another (hopefully the last) PR for the feature: https://issues.redhat.com/browse/CNV-21086
Replace 'Not migratable' badge, for clearly marking the VM that isn't live migratable, with the label, to be less contrasting to the badge to not to get all the user’s attention to it, according to yesterday's design changes.
**Before:**
VMs list:
VM _Details_ tab (see also the VM title):
VM _Overview_ tab (see also the VM title):
**After:**

CNV-21086: Replace 'Not migratable' badge with label

---

src/utils/resources/vm/utils/disk/rowData.ts
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/details/VirtualMachinePendingChangesAlert.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskRowActions.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/utils/getEditDiskStates.ts

> This PR focuses on making sure the VM details tabs view is still functional and nothing crashes
** Fixing a crash of VM disks tab, and cancelling the pending changes for VMs with instancetype or preference section included in the VM YAML
> https://user-images.githubusercontent.com/67270715/214373191-b4cef08b-e4ac-4f78-98ed-0b9ae9a4a5b9.mp4

CNV-23381: Make necessary changes to VM details tabs

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx

This PR fixes a bug where the All namespaces key is used as the namespace and displayed in the VM details section of the Instancetypes tab when All namespaces is selected. The namespace is changed to default.

Change namespace to default when All namespaces is selected

---

src/views/clusteroverview/OverviewTab/metric-charts-card/utils/metricQueries.ts

This PR corrects the vCPU query in the cluster over metric charts to use `count` instead of `sum` and to use `kubevirt_vmi_vcpu_wait_seconds` instead of `kubevirt_vmi_vcpu_seconds`.

Bug 2150832: Fix vCPU query in cluster overview metrics card

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGridLayout.tsx

This is the last PR for the feature: https://issues.redhat.com/browse/CNV-21086
Remove forgotten unnecessary _Live migratable_ field from VM _Details_ page,
as this field was already replaced by the label, placed next to the _Status_ of the VM,
see: https://github.com/kubevirt-ui/kubevirt-plugin/pull/1008, https://github.com/kubevirt-ui/kubevirt-plugin/pull/1013, https://github.com/kubevirt-ui/kubevirt-plugin/pull/1018.
**Before:**
_Live migratable_ field together with the label containing the same info:
**After:**
Only the label next to the _Status_:

CNV-21086: Remove Live migratable from VM Details

---

locales/en/plugin__kubevirt-plugin.json
src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/views/catalog/templatescatalog/hooks/useAvailableDataSourcesAndPVCs.ts
src/views/templates/list/VirtualMachineTemplatesList.tsx
src/views/templates/list/components/VirtualMachineTemplatesRow.tsx
src/views/templates/list/components/VirtualMachineTemplatesSource.tsx
src/views/templates/list/hooks/useTemplatesWithAvailableSource.ts

Forward also cloning DS and add label to them in the template list
Do you think other states will be added in the future? Maybe better to consider forwarding all the DS and filtering based on states later?  
**Before**
**After**

CNV-21974: clone in progress label

---

src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/utils.ts

https://bugzilla.redhat.com/show_bug.cgi?id=2167251
virtualization overview crash. this fix prevents it.

Adding a check for getDay in metric virtualization

---

src/views/clusteroverview/SettingsTab/LiveMigrationTab/Network/Network.tsx

Bug 2166508: Setting page doesn't crash when the user doesn't have permission

---

src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss
src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx

This is another PR for the feature: https://issues.redhat.com/browse/CNV-21086
Change the label to Compact, Unfilled, Orange, according to the design changes and Patternfly styles.
More on Patternfly `Label` component:
https://www.patternfly.org/v4/components/label
https://www.patternfly.org/v4/components/label/design-guidelines#when-to-use-filled-or-unfilled-labels
**Before:**
VMs list:
VM _Overview_ tab:
VM _Details_ tab:
**After:**

CNV-21086: Change Not migratable label style

---

src/utils/components/SSHAccess/utils.ts

Error during ssh service creation.
VMs without `spec.template.metadata.labels` throw errors on k8sPatch.
Switch to `k8sUpdate` creating first the label object and after adding it

fix: create ssh service with no labels obj

---

src/utils/components/DeveloperPreviewLabel/DeveloperPreviewLabel.scss
src/utils/components/DeveloperPreviewLabel/DeveloperPreviewLabel.tsx

Update colors of the label according to the design changes and Patternfly guidlines, for better visual experience.
The exact colors the label should have (I've got the info from our UX):
- text: #3D2C00, equivalent to PF variable `--pf-global--palette--gold-700`
- fill: #FFF6EC ... `--pf-c-label--m-orange--BackgroundColor`
- border: #F4B678 ... `--pf-global--palette--orange-100`
- icon: #EC7A08 ... `--pf-global--palette--orange-300`
_Some resources:_
https://www.patternfly.org/2022.11/components/label
https://www.patternfly.org/2022.11/guidelines/colors
_Note:_
I had to remove `variant="outline"` from the `Label` component, to be able to overwrite color of the border.
**Before:**
**After:**

Update 'Developer preview' label colors

---

src/utils/components/WindowsDrivers/WindowsDrivers.tsx
src/utils/components/WindowsDrivers/utils.ts
src/utils/resources/template/utils/drivers.ts
src/utils/resources/vm/utils/disk/constants.ts
src/utils/resources/vm/utils/disk/drivers.ts
src/views/catalog/customize/constants.ts
src/views/catalog/customize/utils.ts
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/virtualmachines/details/tabs/disk/tables/disk/DiskList.tsx

Add checkbox to mount or unmount windows drivers
How to know if the VM has windows drivers mounted?
Control over all containerDisk volumes and check if the windows drivers image URL is used by one of them.
**Wizard**
https://user-images.githubusercontent.com/29160323/217866274-68310d5b-b1f3-4bfe-a27c-479d6f2070c7.mp4
**VM details**
https://user-images.githubusercontent.com/29160323/217866280-4b51e7c5-62a4-4ff9-81f6-039ff5620506.mp4

CNV-22306: mount window drivers on wizard and vm disk tab

---

src/utils/components/AuthorizedSSHKeyModal/AuthorizedSSHKeyModal.tsx
src/utils/components/AuthorizedSSHKeyModal/SelectSecret.tsx
src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx
src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx

namespace is undefined here and the `SSHServiceSelect` show all the secrets cluster-wide.
Should filter based on VM namespace as cannot attach secrets with a different namespace
Avoid fetching secrets cluster-wide because of permissions errors

Bug 2168859: useParams under HorizontalNav does not give namespace

---

src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.tsx

This is another PR for the feature: https://issues.redhat.com/browse/CNV-21086
Display "Not migratable" label only for the VMs that are running.
The purpose of this change is to limit the amount of labels and to display the labels only when necessary.
**Before:**
**After:**

CNV-21086: Display "Not migratable" only for running VMs

---

src/views/virtualmachines/list/components/VMNotMigratableLabel/VMNotMigratableLabel.scss

This is another PR for the feature: https://issues.redhat.com/browse/CNV-21086
Change the label to Compact, Unfilled, Blue, according to the design changes and Patternfly styles.
More on Patternfly `Label` component:
https://www.patternfly.org/v4/components/label
https://www.patternfly.org/v4/components/label/design-guidelines#when-to-use-filled-or-unfilled-labels
**Before:**
VMs list:
VM _Overview_ tab:
VM _Details_ tab:
**After:**

CNV-21086: Change Not migratable label to blue

---

src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx

When cloning or using a PVC in a terminate state, VM wont be able to run or schedule.
This will filter the PVC in the wizard and won't present unworking PVC to select.

Bug 2158362: filtering PVCs that are in terminate state

---

src/utils/resources/vm/utils/source.ts

When changing blank disk to existing PVC on wizard - wizard still showing modal of no available boot source.
This fix will not show this modal, as existing PVC is a available boot source.
https://bugzilla.redhat.com/show_bug.cgi?id=2151766
Before:
After:

Bug 2151766: No boot source available for existing pvc

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/utils/components/DiskModal/utils/helpers.ts
src/views/catalog/customize/components/CustomizeSource/utils.ts

Bug 2159975: Remove the "docker://" prefix while editing the rootdisk (registry)

---

src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
src/views/bootablevolumes/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx

Rename the _Upload_ button to _Save_, in _Add volume to boot from_ modal, also update the style of dividers of the sections in _Create new VirtualMachine_ page when creating a VM from volume (_InstanceTypes_ tab).
_More on used Patternfly variables:_
https://www.patternfly.org/2021.16/components/divider/
https://pf4.patternfly.org/developer-resources/global-css-variables
_This PR is related to both features:_
https://issues.redhat.com/browse/CNV-18014
https://issues.redhat.com/browse/CNV-15501
**Before:**
_Upload_ button (as a bit misleading term, especially when using existing PVC - 2nd radio button in the modal):
Dividers not properly aligned, not clearly divided sections:
**After:**
_Save_ button (more general, less misleading):
Clear and nice dividers, more space around (increased …

CNV-18014: Rename Upload to Save in Add volume modal

---

src/utils/components/HelpTextIcon/HelpTextIcon.tsx

**Fixes** https://bugzilla.redhat.com/show_bug.cgi?id=2173593
Display _No data available_ helper text correctly to prevent _Top consumers_ page/tab crash in _Virtualization > Overview_. Display the helper texts in _Add volume to boot from_ and _Edit volume parameters_ modals correctly, too, to prevent crashing the UI when accessing those modals, as all those places have the common root cause.
**Before:**
_Top consumers_ page broken:
Blank page after accessing _Add volume to boot from_ or _Edit volume parameters_ modal + same error in the browser console as in the picture above:
**After:**
_Top consumers_ page rendered correctly, incl. the helper text (+ no errors):
_Add volume to boot from_ (or _Edit volume parameters_) modal rendered as expected:

Bug 2173593: Display 'No data available' helper text correctly

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts

Enable column sorting for bootable volumes list under instance type VM create flow
https://user-images.githubusercontent.com/67270715/221902137-1ff2e458-f5bb-4ca4-bbe0-1ffd6eff449e.mp4

Enable column sorting for bootable volumes list

---

src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts

Fixing OS name in the VM details section in VM create with Instance type flow
Before:
After:

Fix OS display name

---

locales/en/plugin__kubevirt-plugin.json
src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2174324
Rename the button from "Add" to "Add volume", in the _Bootable volumes_ list.
This change makes the list looking more consistent with the bootable volumes list under the _InstanceTypes_ tab when creating a VM, where _Add volume_ button already exists, with the same functionality.
**Before:**
**After:**

Bug 2174324: Rename Add to Add volume button for Bootable volumes

---

src/views/clusteroverview/MigrationsTab/components/BandwidthConsumptionCharts/utils.ts

when gridLineSpacer is 0 the for loop will run endlessly which will crash the script 
After:

Bug 2174636: Visit Virtualization -> Overview -> Migrations crashes the app

---

src/utils/hooks/useInfrastructureAlerts/useInfrastructureAlerts.ts
src/utils/hooks/useInfrastructureAlerts/utils/utils.ts

This PR removes alerts whose value for the label `operator_health_impact` is `none` from the chart shown in the "OpenShift Virtualization" health status popup.

Remove alerts with health impact of none from health status popup chart

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
src/views/templates/details/tabs/details/components/DescriptionItem.tsx
src/views/templates/details/tabs/details/components/TemplateDetailsLeftGrid.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/Details.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2173527
Add help text/popover with more info to _Machine type_ field, present in the following places:
- VM Details tab
- VMI Details tab
- VM Template Details tab
- Customize VM flow (VM creation)
Display the following info in the popover, when clicking on the dashed title of the field:
_"The machine type defines the virtual hardware configuration while the operating system name and version refer to the hypervisor."_
**Before:**
No way to get some info about the _Machine type (VM _Details_ page/tab):
**After:**
Clicking on the title of the _Machine type_ field shows us more (VM _Details_ page/tab):
Note that in other places, the result of adding the popover looks the same.

Bug 2173527: Add help text to Machine type field

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/DedicatedResourcesModal/DedicatedResourcesModal.tsx
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/templates/details/tabs/scheduling/components/DedicatedResourcesModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2175274
Fix the error, prevent blank page to be displayed, after trying to edit CPU/Memory of a VM, created from a template without `spec.template.spec.domain.cpu` defined in its VM object (see the YAML of a VM or a Template).
Fix the error by making sure the path exists (using `ensurePath`), when editing the VM or Template object (the same problem occurs in more places).
**Before:**
**After:**

Bug 2175274: Display Edit CPU | Memory modal in VM Details

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2175256
Fix the error of `bootableVolume.metadata.annotations` that was `undefined`, when accessing the _Catalog_ page.
**Before:**
Right after accessing _Catalog_ (_Virtualization > Catalog_), TypeError occurs:
**After:**
_Catalog_ page displayed correctly:

Bug 2175256: Display Catalog page correctly, fix TypeError when accessing Catalog

---

src/views/catalog/utils/quick-create-vm.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2168486
Make "Restore template settings" enabled, when editing VM's CPU/Memory, by fixing incorrect link to the original Template the VM was created from. Fix the incorrect namespace in the link, which was set to the namespace of the VM when creating a VM, not the original Template's one.
**Before:**
Incorrect link to the base template:
After clicking on the template:
"Restore template settings" disabled, when editing VM's CPU/Memory:
**After:**
Correct link to the base template:
After clicking on the template:
"Restore template settings" enabled as expected:

Bug 2168486: Enable Restore template settings by fixing templates link

---

src/utils/resources/vm/utils/network/utils.ts
src/views/catalog/wizard/tabs/network/components/list/NetworkInterfaceList.tsx
src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
src/views/templates/details/tabs/network/components/list/NetworkInterfaceList.tsx
src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceList.tsx
src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2167226
Make sorting NICs by _Type_ work correctly (alphabetically), in VM _Network Interfaces_ tab,
also for VM _Templates_ and in _Catalog_ accordingly.
**Before:**
**After:**

Bug 2167226: Make sorting NICs by Type work correctly

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2172371
Disable _Restore template settings_ button in _Edit CPU | Memory_ modal in VM _Details_ tab, because it does not make sense if the VM has no base template specified (check _Template_ field in the same page in the UI).
**Before:**
_Restore template settings_ button was loaded and is now clickable even it makes no sense:
**After:**
_Restore template settings_ disabled for the VM without base template:

Bug 2172371: Disable "Restore template settings" for VM without template

---

src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
src/views/bootablevolumes/utils/utils.ts

Add missing ability to sort Bootable volumes in _Bootable volumes_ list by OS name (_Operating system_ column).
**Before:**
Bootable volumes not sorted by OS, no ability to sort them:
**After:**
Bootable volumes can be sorted by OS, ability to change the direction (ascending/descending):

Add sorting Bootable volumes by Operating system

---

src/utils/components/BootOrderModal/BootOrderModalBody.tsx

Guys, is it right that the modal should show all the possible devices? Even if they don't have a bootOrder?
Are all devices in theory bootable?

Bug 2174619: render any device as bootable

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts

Adding Size and StorageClass columns to boot volumes list, also adding column management 
NOTE: No col manage inside the show all modal since we can't show modal in modal as PF won't allow it
https://user-images.githubusercontent.com/67270715/223338508-ca8016ab-ad06-44a9-8abe-792912cdf636.mp4

Add size and StorageClass columns to bootable volumes list

---

src/utils/components/NetworkInterfaceModal/components/hooks/useNadsData.ts
src/utils/constants/constants.ts

When a non-admin user tries to fetch nads, it fails. When failing the loading variable received from hook is false, so added a check that is load error is existing  the loading will be true

Bug 2175601: Nads loading - non admin user

---

src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/SSHKeySection/SSHKeySection.tsx

the ssh section component had an effect that generate a secret name as default, which causes the created VM to get stuck on Provisioning status
After:
https://user-images.githubusercontent.com/67270715/224018604-df8fc733-5e52-4384-8bb8-b4f51f865a8e.mp4

Bug 2176804: VM created with instanceType from UI cannot be started due to secret missing

---

src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/constants.ts

creating a volume from the 'use existing PVC' in Add volume modal dialog is creating a non functional PVC due to missing annotation to bind CDI to the DV

Bug 2175641: Add volume from existing PVC not working

---

src/views/bootablevolumes/utils/utils.ts

Delete bootable volume modal crash the page as obj don't have annotations. This will fix it.

Bug 2175054: Delete bootable volume modal crash the page

---

src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

missing disk on vm creation causes the VM to boot from cloud-init instead of booting from PVC
Before:
https://bugzilla.redhat.com/attachment.cgi?id=1949350
After:
https://user-images.githubusercontent.com/67270715/224098950-f029af42-22b2-4e8a-a703-3ed3779b05a6.mp4

Bug 2176843 - 'No bootable device' shows in VM console if it's created with instanceType

---

src/views/catalog/templatescatalog/TemplatesCatalog.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogItems.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2175571
Sort the VM Templates in _Catalog_ alphabetically (by name), when displayed in the grid view.
**Before:**
Templates not sorted, beginning with "rhel...":
**After:**
Templates sorted by their names (ascending):

Bug 2175571: Sort Catalog templates in grid view

---

src/views/migrationpolicies/details/tabs/details/components/MigrationPolicyDetailsSection/MigrationPolicyDetailsSection.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2176753
Remove the dashed line from the _Configurations_ subtitle in _MigrationPolicies_ _Details_ page, as there is no any helper text for the title, but the modal is opened instead, when clicking on it.
**Before:**
Misleading dashed line under _Configurations_, as there's no any popover/helper text when clicking on it:
**After:**
Proper style for the link to edit Configurations (modal is opened after clicking on it):

Bug 2176753: Remove dashed line from Configurations subtitle

---

src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx

Disable the 'create VM' button if the user hasn't selected a volume OR if he doesn't have create permission to that namespace
Before:
Button enabled at all times
After:
https://user-images.githubusercontent.com/67270715/224116191-879ed654-a1f6-4885-899c-52c1dc47e1b2.mp4

Disable create VM button when cant create VM

---

src/utils/components/PendingChanges/utils/constants.ts
src/utils/components/PendingChanges/utils/helpers.ts
src/views/virtualmachines/details/VirtualMachineNavPage.tsx
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts
src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
src/views/virtualmachines/details/tabs/configuration/disk/modal/MakePersistentModal.tsx
src/views/virtualmachines/details/tabs/configuration/utils/utils.ts
src/views/virtualmachines/details/virtual-machine-page-title.scss
src/views/virtualmachines/details/virtual-machine-page.scss
src/views/virtualmachines/utils/constants.ts

Configuration inner tabs were missing routing, this is a small hack to add routing as we don't have support from SDK tabs, nor can we add Route from react-router-dom as the tabs from patternfly are nested into Tabs which causes the Switch not to work.
After:

Bug 2176706: Fix inner tabs routing

---

src/utils/components/HelpTextIcon/HelpTextIcon.scss
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.scss
src/views/catalog/customize/components/CustomizeSource/ExpandableCustomizeSourceSection.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2158079
Align _Storage_ expandable section with its `HelpIcon` "?", in _Customize Template parameters_ when creating a VM.
**Before:**
Storage and "?" not aligned nicely, "?" too far from Storage:
**After:**
Storage and "?" aligned properly:

Bug 2158079: Align Storage expandable section with HelpIcon

---

src/utils/components/EnvironmentEditor/EnvironmentForm.scss
src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
src/views/virtualmachines/details/tabs/configuration/scheduling/components/SchedulingSection/SchedulingSection.tsx
src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2173563
Add missing titles to VM _Environment_ and _Scripts_ tabs, place the _YAML_ switcher next to them.
Make the existing subtitle for Environment tab smaller, position its text properly:
_Include all values from existing config maps, secrets or service accounts (as disk)_
Make these changes to achieve consistency with the other tabs.
**Before:**
_Environment_ tab without the title, subtitle too big:
_Scripts_ tab without the title:
**After:**
_Environment_ tab with the nice title and subtitle:
_Scripts_ tab with the title:

Bug 2173563: Add titles to VM Environment and Scripts tabs

---

src/utils/components/DiskModal/utils/helpers.ts
src/utils/hooks/useCDIUpload/utils.ts

DataVolumes are now garbage collected, so when trying to update ownerReference for the upload's DV, it will not find it.
updating owner reference on correlated PVC, so the PVC will be GC when deleting VM.
Also fixed an issue where the volume name and the PVC resource name didn't match which caused the VM to fail on start
Before:
https://user-images.githubusercontent.com/67270715/224706010-c431cc4a-5988-464d-b926-110028c347e5.mp4
https://user-images.githubusercontent.com/67270715/224706017-ff8d7f0f-ac84-4402-a473-feee5d709b48.mp4
After:
https://user-images.githubusercontent.com/67270715/224706060-eecad2db-a54b-473c-af4f-471e1ce60b83.mp4
https://user-images.githubusercontent.com/67270715/224706065-a9cb4f2f-ae54-442c-801e-7103d111c87e.mp4

Bug 2174334: VM's disk is not deleted along with the VM if the VM is created from upload image

---

src/views/catalog/customize/utils.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/wizard/components/WizardFooter.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2176725
Carry over "Start this VirtualMachine after creation" checkbox value to the last step of creating VM when customizing VM.
Notes:
For achieving the expected behavior `useWizardVMContext` hook was used.
Also note that changes in _src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx_ look a bit wild, but that's just because indentation was updated a bit, due to importing `memo` from `'react'`, and only [this](https://github.com/kubevirt-ui/kubevirt-plugin/compare/main...hstastna:BZ_Start_this_VirtualMachine_after_creation_not_carried_over?expand=1#diff-fcad411937b404f59f942a70de7a8de426f001e371ff8bdaef5151d8409569baR48) and  [this piece of …

Bug 2176725: Carry over "Start this VirtualMachine after creation" value

---

src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2177589
Sort the preferences names in _Preference_ field/drop down, in _Add volume to boot from_ modal alphabetically, no matter where the modal is accessible from.
Move sorting of InstanceTypes names alphabetically to the modal component, too.
Also remove forgotten `loaded` prop from the component `AddBootableVolumeButton` and from the places where the component is used.
**Before:**
Preferences names not sorted in the modal, in _Bootable volumes_ list:
**After:**
Preferences names sorted alphabetically:

Bug 2177589: Sort Preferences in Add volume modal

---

src/views/virtualmachines/details/tabs/metrics/TimeRange/TimeRange.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2168480
Correct the link for _Virtualization dashboard_ present in VM's _Metrics_ tab, so it redirects to _Observe -> Dashboards_
with "KubeVirt / Infrastructure Resources / Top Consumers" selected in the _Dashboard_ drop down.
When clicking on _Virtualization dashboard_:
**Before:**
Clicking on _Virtualization dashboard_ leads to the following unexpected page:
**After:**
Clicking on _Virtualization dashboard_ leads us to the correct page:

Bug 2168480: Correct the link for Virtualization dashboard

---

src/utils/resources/shared.ts
src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/bootablevolumes/list/components/BootableVolumesRow.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2177973
Display volumes that are boing cloned in _Bootable volumes_ list, also display _Clone in progress_ label in _Name_ column for such bootable volumes in the list, so the user can see a volume immediately in the list, right after they add it (via Add volume to boot from modal), so they know what is going on.
**Before:**
After adding a new bootable volume, nothing has appeared in the list, user has to wait and wondering what's going on:
**After:**
After adding a new bootable volume, the volume did appear in the list immediately, together with the label:

Bug 2177973: Display cloning bootable volumes, add "Clone in progress"

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/TableData.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2177578
Set the minimum width for each of the columns in the volumes list in _Catalog_ > _InstanceTypes_. To be able to do that, update `TableData` component to be able to get `width` as an optional prop, to get styled according to requirements.
**Before:**
Not enough space for the volume name, in case that the description is very long:
If more columns displayed, same problem as for the volume name:
**After:**
Enough space for the volume name, in case that the description is very long:
If more columns displayed, each column has an appropriate width suitable for its content:

Bug 2177578: Set columns' width for volumes in Catalog > InstanceTypes

---

src/utils/components/TabModal/TabModal.tsx
src/utils/components/VMAuthorizedSSHKeyModal/utils.ts

**Cause**
`produce` inside another `produce` cause some issues with `immer` apparently.
**Solution**
Anyways, the function `removeSecretToVM` was a little bit useless as its just one line so i copied it without the additional `produce`
If the VM does not have other accessCredentials, just don't try to remove it another time.
Why that change in TabModal?
This bug would be more easily solved if the TabModal would throw the error in the submit catch.
Even to just log that something bad happened.

Bug 2172375: Error on deleting secret

---

src/utils/components/DiskModal/utils/helpers.ts

Adding the namespace to the DataVolumeTemplate object causes issues and is not really necessary
After:
https://user-images.githubusercontent.com/67270715/226923973-38367565-8f98-4345-85c4-f7230bf5bb1d.mp4

Bug 2180279: VM cannot be started while creating from a template which has 2nd disk added

---

src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2175977
Disable _Create VirtualMachine_ button when creating a VM from InstanceType, if not everything needed is selected, for example when a VM name is missing or InstanceType selection (in case that a chosen volume is missing label with InstanceType name).
**Before**:
Name and InstanceType missing but _Create VirtualMachine_ button still enabled: 
**After:**
Name and InstanceType missing and _Create VirtualMachine_ button disabled, as expected:

Bug 2175977: Disable Create VM button if not everything selected

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/constants.ts

Update the bootable volumes list to show 8 rows at a time.

Bug 2175974: Show 8 rows in bootable volumes list

---

src/utils/components/NetworkInterfaceModal/NetworkInterfaceModal.tsx
src/utils/components/NetworkInterfaceModal/components/NameFormField.tsx
src/views/virtualmachines/details/tabs/configuration/network/copmonents/modal/VirtualMachinesEditNetworkInterfaceModal.tsx

Renaming the networks interfaces is not supported by the backend for already created VM

Bug 2168749: disable network renaming on already created vm

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx

This PR fixes the misalignment of the filter chips on the InstanceTypes page.

Bug 2174744: Fix bootable volumes filter chips alignment

---

src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2180931
Use wrap modifier "truncate" to shorten long description text displayed in _Description_ column in _Bootable volumes_ list and in volumes list in _Catalog > InstanceTypes_ page.
Display the whole text in the popover when the mouse pointer moves over the description text.
More about used modifier of the Patternfly `TableText` component:
https://www.patternfly.org/2022.05/components/table
**Before:**
Description column in _Bootable volumes_ list:
Description in volumes list in _Catalog > InstanceTypes_ page:
**After:**
Description column in _Bootable volumes_ list:
Description in volumes list in _Catalog > InstanceTypes_ page:

Bug 2180931: Truncate long text in Description column for boot volumes

---

src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsRightGrid.tsx
src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
src/views/catalog/templatescatalog/TemplatesCatalog.scss

This PR fixes:
- Selecting the volume from the `Add volume` modal + including a label for cloning in progress
- Getting correct size for volume that is cloned from another PVC instead of `0 B` (saw this regression a few days ago on another cluster)
- Disabling `Add volume` button if user is not allowed to create a DataSource object within the os images name (either kubevirt-os-images for US or openshift-virtualization-os-images for DS)
Before:
https://user-images.githubusercontent.com/67270715/227772536-3609ef18-86cf-43b5-9549-300190ca9836.mp4
After:
https://user-images.githubusercontent.com/67270715/227772389-ac51e3fc-c954-4e67-b36f-db5c3af9bdb8.mp4

Bug 2177977: The volume in instanceTypes page should be selected automatically just after it's been added

---

src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

carrying the firmware from source VM to cloned VM
Before:
https://user-images.githubusercontent.com/67270715/228194307-76a83c26-2afd-4dcc-aa54-9abbd12b8f4e.mp4
After:
https://user-images.githubusercontent.com/67270715/228194360-75b5fff0-58ac-4f4e-a347-6249308bf60d.mp4

Bug 2181515: spec.firmware.bootloader is not copied while cloning a UEFI VM

---

src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
src/utils/components/SSHAccess/utils.ts
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2180719
Provide correct username in the copied command for "Copy SSH command" action in VM _Overview_ tab - _Details_ card, instead of username being `undefined`.
Make `userName` not optional param anymore, in `getConsoleVirtctlCommand` util, as we do need it to properly generate the command.
**Before:**
After VM creation, `undefined` user present in the ssh command, copied by "Copy SSH command" in VM _Overview_:
https://user-images.githubusercontent.com/13417815/228270885-65ba32c3-4171-403a-a0ae-b216c2fae47a.mp4
**After:**
Correct username present in the ssh command:
https://user-images.githubusercontent.com/13417815/228270913-be8f8bc6-8fc2-4711-96e7-0fb4176afa4b.mp4

Bug 2180719: Provide username in "Copy SSH command" of a VM

---

src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx

Move _StorageClass_ field together with _Disk size_ to _Destination details_ section from _Source details_ one, in _Add volume_ modal, according to the design doc.
_Design doc:_
https://docs.google.com/document/d/1HTF6_H2WDXwlVy7RnrHH28dzFlhNIa15Hhpeoyg2R0Q/edit#heading=h.xt31tt3xq1x
**Before:**
Add volume modal and selecting "Upload volume" radio button:
Add volume modal and selecting "Use existing volume" radio button:
**After:**
Add volume modal and selecting "Upload volume" radio button:
Add volume modal and selecting "Use existing volume" radio button:

Move StorageClass field to Destination details

---

src/utils/resources/template/hooks/useProcessedTemplate.ts
src/utils/resources/template/hooks/useVMTemplateGeneratedParams.ts
src/utils/resources/template/utils/constants.ts
src/utils/resources/template/utils/helpers.ts
src/utils/resources/template/utils/selectors.ts

A new request of restoring VM pretty names and ignoring name param of the template if annotation openshift.kubevirt.io/pronounceable-suffix-for-name-expression: true is presented in the template

Bug 2182317: Restore vm's pretty names

---

src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
src/utils/components/SidebarEditor/SidebarEditor.tsx
src/utils/components/SidebarEditor/useEditorHighlighter.ts
src/utils/components/SidebarEditor/utils.ts
src/utils/resources/vm/utils/constants.ts
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
src/views/virtualmachines/details/tabs/configuration/disk/DiskListPage.tsx
src/views/virtualmachines/details/tabs/configuration/network/NetworkInterfaceListPage.tsx
src/views/virtualmachines/details/tabs/configuration/scheduling/VirtualMachineSchedulingPage.tsx
src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx
src/views/virtualmachines/details/tabs/details/VirtualMachineDetailsPage.tsx

Highlight editor parts in the LIVE YAML
https://user-images.githubusercontent.com/29160323/225008478-a1458235-6d86-4a1c-b70d-17644c59fa3f.mp4

Bug 2167608: highlight parts

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/configuration/scheduling/components/VirtualMachineSchedulingRightGrid.tsx

Disabled editing Dedicated resources on vm with instance type. `DedicatedResourcesModal` edit the cpu `dedicatedCpuPlacement` property that goes in conflict with the instance type
Showing tooltip on vm with instancetype 
We cannot

Bug 2182362: no dedicated resources with instancetype

---

src/utils/components/Charts/utils/utils.ts

We can get `-Infinity` value from Prometheus which which causes an infinite loop that causes the UI to get stuck as CPU is getting overload
NOTE: credits to @metalice the genius! :crown: 
Before:
https://user-images.githubusercontent.com/67270715/228532763-15944add-ccb1-4092-9bbf-423ae4b4b287.mp4
After:
https://user-images.githubusercontent.com/67270715/228532978-6d5cd88d-1a60-495d-8612-0c54c0112bda.mp4

Bug 2180664: Console is almost frozen if scroll down and up in VM metrics tab

---

src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2181323
Select the 1st of the options in _Size_ dropdown if already some _Default InstanceType_ was chosen. Prevent missing 'instancetype.kubevirt.io/default-instancetype' label in the created bootable volume's yaml in case of not choosing _Size_ in _Add volume_ modal, because the correctly set instanceType label requires both parts defined. It does not make sense to only choose _Default InstanceType_ without size. 
With this change, also align with the actual behavior in _Edit_ modal accessible in _Bootable_ _volumes_ list. Save one user's click when automatically selecting the 1st option from sizes, if they already choose something from _Default InstanceType_ dropdown. They still can choose some other option if they want. …

Bug 2181323: Select 'Size' automatically if 'Default InstanceType' chosen

---

src/views/catalog/wizard/tabs/scripts/components/sshkey-utils.ts
src/views/templates/details/tabs/scripts/components/SSHKey/sshkey-utils.ts

The secret volume has a maximum of 63 chars. The BE adds more chars to the volume name extending our secret name, and this fix limits the chars to 51 to stay safe with the 63 volume limit.

Bug 2182233: Enforcing ssh secret name to be 51 chars or less

---

src/views/clusteroverview/OverviewTab/metric-charts-card/utils/hooks/useMetricChartData.ts

This PR fixes a bug that caused the trend charts on the overview page to display no data. This bug does not present when the UI is run in the local context. The fix is to remove the `namespace` property in the `usePrometheusPoll` call when the active namespace is the all projects key `#ALL_NS#`. There appears to be a difference in how Prometheus handles the call based on whether the UI is in the local or cluster context.

Bug 2167660: Fix overview trend charts for All Projects namespace

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DiskModal/DiskFormFields/DiskSizeInput/DiskSizeInput.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2180666
Display _Persistent Volume Claim size_ correctly, readable for a user, in _Add disk_ modal accessible from VM _Disks_ page, when choosing _PVC (creates PVC)_ for _Source_ field. Display the value in appropriate size and unit (for example _GiB_ instead of big number + _B_ as bytes unit).
The actual info about the selected PVC as an example of the expected size when selecting that PVC later in Add disk modal:
**Before:**
Not very user friendly PVC size (in bytes):
**After:**
Nice, readable size - smaller number with _GiB_ units instead of bytes:

Bug 2180666: Display PVC size correctly in Add disk modal

---

src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeDestination/VolumeDestination.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx

when getting a size from the pvc we need to remove the `B` suffix more info on: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/
After:
https://user-images.githubusercontent.com/67270715/229574555-2f907a8f-6258-4d92-a182-817d60f306ee.mp4

Bug 2184098: Fix size in add volume modal

---

src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/AutoAttachedNetworkEmptyState.tsx
src/views/virtualmachines/details/tabs/configuration/network/copmonents/list/NetworkInterfaceList.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2184058
Remove _Add network interface_ button from VM's _Network interfaces_ tab in case there are no any NICs present, according to the UX suggestions. Display the button only once - in the left up, next to the YAML switcher.
_Notes:_
Note that the solution is not 100% consistent with "empty state" but it’s more important that all the buttons in the VM details page are aligned (discussed that with the UX).
Also note that within the BZ https://bugzilla.redhat.com/show_bug.cgi?id=2176797, the title of the page _Network interfaces_ will be added and then the button will be positioned under that title.
**Before:**
_Add network interface_ button  displayed twice:
**After:**
_Add network interface_ button  displayed once - position of the …

Bug 2184058: Display 'Add network interface' button only once

---

locales/en/plugin__kubevirt-plugin.json
src/views/bootablevolumes/actions/BootableVolumesActions.tsx
src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
src/views/bootablevolumes/actions/hooks/useBootableVolumesActions.tsx
src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/bootablevolumes/list/components/BootableVolumesRow.tsx
src/views/bootablevolumes/utils/types.ts
src/views/bootablevolumes/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/InstanceTypeSelect/InstanceTypeSelect.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2175990
Improve _Default InstanceType_ field/dropdown in _Edit volume metadata_ modal, accessible in _Bootable volumes_ list, according to the design update: add descriptive text to each one, omit "highperformance" and "server" options from the dropdown.
Improve also related 'Size' dropdown to display items with more info about number of CPUs and Memory size, sorted according to the size and not alpabetically, as expected.
_See more for Default InstanceType and Size drop downs design here:_
https://docs.google.com/document/d/1HTF6_H2WDXwlVy7RnrHH28dzFlhNIa15Hhpeoyg2R0Q/edit
**Before:**
Not much info about options for _Default InstanceType_, also the selected option not marked as selected in the dropdown:
Sizes sorted alphabetically: …

Bug 2175990: Improve Default InstanceType field in Edit modal

---

src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2181920
Disable secure boot when choosing "UEFI" option in the VM _Details_ page for "Boot mode" field. Fix the yaml when choosing this option in the UI.
_How to reproduce the bug:_
1. choose/create some VM with Fedora OS (or any other OS, but easier to reproduce with Fedora, because it has _bootctl_ already installed - to easily get the status for secure boot)
2. go to VM's _Details_ page and check _Boot mode_ field:
- if there is "UEFI" already chosen, continue to the next step
- if there is something else, choose "UEFI" in the modal and restart the VM to apply the change
3. go to VM's console:
click on _Open web console_ in VM _Overview_ tab or also you can go to VM Console tab
5. log in to (running!) VM, open _Guest login …

Bug 2181920: Disable Secure Boot for UEFI Boot mode

---

console-extensions.json

This PR adds the "Virtualization" label to the Virtualization status item in the OCP dashboard.
This bug does not exist in 4.13 onward as the Virtualization status item has been replaced with a more robust solution.

Bug 2176932: Add title to Virtualization status in OCP dashboard

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/Consoles/Consoles.tsx
src/utils/components/Consoles/components/vnc-console/VncConsole.tsx
src/utils/components/Consoles/components/vnc-console/utils/VncConsoleTypes.ts
src/views/virtualmachines/details/tabs/console/VirtualMachineConsolePage.tsx

When VM headless mode is on, the console page is all disabled, but only vnc console page should be disabled as the serial console is available. 
After:
Before:

Bug 2183979: Console page - disable only vnc console in headless mode

---

src/utils/components/PendingChanges/utils/helpers.ts

when vm has no nics, the default one will be mounted anyways.
I've fixed that in the wrong function

Bug 2177888: false pending nic state

---

src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabConditions.tsx
src/views/virtualmachines/details/tabs/diagnostic/tables/VirtualMachineDiagnosticTabVolumeStatus.tsx
src/views/virtualmachines/details/tabs/diagnostic/virtual-machine-diagnostic-tab.scss

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2184063
Display "Status conditions" and "Volume snapshot status" sub-titles in VM _Diagnostic_ tab smaller, more aligned with such titles in other VM tabs.
Use Patternfly `Flex`, `FlexItem` components for that, simplify the related css file.
_Used PF `Flex` component:_
https://pf4.patternfly.org/layouts/flex/
**Before:**
Titles too big, also aligning of pagination not perfect:
**After:**
Titles smaller, aligning of pagination perfect:

Bug 2184063: Display titles in VM Diagnostic tab smaller

---

src/utils/components/NetworkInterfaceModal/components/NetworkInterfaceNetworkSelect.tsx
src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts
src/utils/components/NetworkInterfaceModal/components/hooks/useNADsData.ts
src/utils/components/NetworkInterfaceModal/components/hooks/utils.ts

This PR fixes a bug that prevented non-admin users from being able to create a new network interface.
Cause: The code was attempting to pull network attachment definitions in namespaces inaccessible to non-admin users, which caused an error that prevented the form submit button from being enabled.

Bug 2186462: Fix Add network interface modal for non-admin user

---

src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
src/utils/components/Charts/NetworkUtil/NetworkThresholdChartSingleSource.tsx
src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkCharts.tsx
src/views/virtualmachines/details/tabs/metrics/NetworkCharts/NetworkChartsByNIC.tsx
src/views/virtualmachines/details/tabs/metrics/UtilizationCharts/UtilizationCharts.tsx
src/views/virtualmachines/details/tabs/metrics/VirtualMachineMetricsTab.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2182000
Display Memory, CPU and Network graphs consistently with Storage graphs, in VM _Metrics_ tab:
show missing y-axis for those graphs.
**Before:**
No y-axis for Memory, CPU and Network graphs :
**After:**
Y-axis present in Memory, CPU and Network graphs, same as in Storage graphs:

Bug 2182000: Display VM Metrics graphs with Y-Axis

---

cypress/support/nav.ts
cypress/tests/catalog/filter.spec.ts
cypress/tests/check-tabs.spec.ts
src/views/templates/details/CommonTemplateAlert.tsx

Fixing cypress test:
- Aligning text to fit current text in the app.
- filter.spec.ts:
1. the visit function was flaky changed to the visitCatalog function.
2. changing rhel 6 to 9 and using metadata name instead of name as it didn't match anymore.
3. switch to check for fedora template instead of checking just count of templates (crashes locally when having more than one fedora template).
- check-tabs.spec.ts: 
1. creating vm/template from yaml gets a resource name `example` for both cases.
2. common template alert text didn't matched - getting by id instead of text.

Update cypress tests

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/ShowAllBootableVolumesButton/ShowAllBootableVolumesButton.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts

When Creating a new volume from the "Add volume" modal dialog or selecting a volume from the "Show all" modal dialog, the volume is selected but the pagination is not moving to the proper page to show the created/selected volume.
Before:
select volume:
https://user-images.githubusercontent.com/67270715/232485885-357eae98-4735-4bcc-a864-840bdb2da1da.mp4
create volume:
https://user-images.githubusercontent.com/67270715/232486028-4925c48e-3e30-4e5f-89cf-d6fcdea20357.mp4
After:
select volume:
https://user-images.githubusercontent.com/67270715/232486226-b0a12f47-c0e0-47bb-b3f6-cd5489c8c86d.mp4
create volume:
https://user-images.githubusercontent.com/67270715/232486294-52e82a86-cf6e-4f03-9e96-2ad29ff8a229.mp4

Bug 2177977: Move pagination to created/selected volume from modals

---

src/utils/components/BootOrderModal/BootOrderModalBody.tsx
src/utils/components/BootOrderModal/DeviceTypeIcon.tsx
src/utils/components/BootOrderModal/boot-order.scss

Adding icons for boot order modal
**Before**
**After**

Bug 2173525: Disk and net icons for boot order modal

---

src/views/clusteroverview/MigrationsTab/components/MigrationsTable/MigrationsRow.tsx

The missing namespace prop is causing the VMIM details page to reach 404
Before:
https://user-images.githubusercontent.com/67270715/232819594-15d4d415-e793-4c77-9a67-42962a4e213c.mp4
After:
https://user-images.githubusercontent.com/67270715/232819688-58f75408-c815-44c9-9b8b-5a8f40ec614d.mp4

Bug 2151237: "404: Not Found" appears before the VMIM details is loaded

---

src/utils/components/ExternalLink/ExternalLink.tsx
src/views/bootablevolumes/actions/components/EditBootableVolumesModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/components/VolumeMetadata/components/PreferenceSelect/PreferenceSelect.tsx
src/views/clusteroverview/OverviewTab/getting-started-card/utils/getting-started-content/GettingStartedLinkExtraContent.tsx
src/views/migrationpolicies/list/MigrationPoliciesList.tsx
src/views/migrationpolicies/list/components/MigrationPoliciesCreateButton/MigrationPoliciesCreateButton.tsx
src/views/migrationpolicies/list/components/MigrationPoliciesEmptyState/MigrationPoliciesEmptyState.tsx
src/views/migrationpolicies/list/utils/constants.ts
src/views/virtualmachines/list/VirtualMachinesList.tsx
src/views/virtualmachines/list/components/VirtualMachineEmptyState/VirtualMachineEmptyState.tsx
src/views/virtualmachines/list/components/VirtualMachinesCreateButton/VirtualMachinesCreateButton.tsx

This is a followup PR for the comment:
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1234#issuecomment-1496124398
Don't display the unnecessary buttons to create VirtualMachine or MigrationPolicy in the empty state pages (no resources present), as there is the button to create the appropriate resource present also in the center of the page, which is the default for Patternfly empty state. Make this change according to the UX suggestions.
Create new `MigrationPoliciesCreateButton` component to be used where needed.
Update `MigrationPoliciesEmptyState` component: use preferred `ExternalLink` component instead of `a` in there.
Also remove unnecessary pagination for VM's empty state page, as it doesn't make sense for this case.
**Before:**
MigrationPolicies empty state - 2 buttons to …

Remove extra buttons to create VM or MigrationPolicy

---

cypress/tests/check-tabs.spec.ts
cypress/views/tab.ts
locales/en/plugin__kubevirt-plugin.json
src/utils/constants/tabs-constants.ts
src/views/virtualmachines/details/hooks/useVirtualMachineTabs.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2188010
Display the proper name of the VM tab for diagnostics.
**Before:**
**After:**

Bug 2188010: Rename VM "Diagnostic" tab to "Diagnostics"

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/StorageUtil/StorageUtil.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2187242
Increase pie charts popovers font size in the VM _Overview_ _Utilization_ card to be the same as in the line charts displayed below those pie charts, for better readability, as the original popovers font size was too small.
**Before:**
CPU chart popover font size too small to be easily readable (same for _Memory_ and _Storage_ charts):
**After:**
CPU chart popover font size bigger (same for _Memory_ and _Storage_ charts):

Bug 2187242: Increase Utilization pie charts popovers font size

---

src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx

The namespace was not propagated to the `SelectSecret`. With no namespace, the select was not fetching any namespace. 
This is to prevent the `useK8sWatchResources` to fetch all secrets from all namespaces

Bug 2187664: vm with no namespace means default

---

src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/utils/helpers.ts
src/utils/resources/template/utils/helpers.ts

No UI diff.
Do not use `vm.metadata.name` if contains a parameter to create the DV NAME. Like ${NAME}
Disk name is provided by the user so no need to guard on that.

Bug 2187971: guard for template parameter on disk moda

---

src/utils/components/TabModal/TabModal.tsx
src/views/virtualmachines/details/tabs/configuration/disk/modal/DeleteDiskModal.tsx
src/views/virtualmachines/details/tabs/configuration/disk/modal/hooks/useVolumeOwnedResource.tsx

**Cause**
We transform volume in `persistentVolumeClaim` with `convertDataVolumeToPVC` even when the volume is not a DV.
**Solution** 
Do not transform the volume if it's not a datavolume.
To prevent further issues, let's show the fetch error to the user when something goes wrong.
If we fail to load the resource, we'll not be able to delete it or detach it
I've added a prop to the TabModal as in this component the error alert is already showed for API errors and can be useful for other modals that use tabmodal

Bug 2188886: Pending loading on detach modal

---

src/utils/resources/template/hooks/useVmTemplateSource/utils.ts
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeButton/AddBootableVolumeButton.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/AddBootableVolumeModal/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/BootableVolumeList.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeRow/BootableVolumeRow.tsx
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeFilters.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeSortColumns.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
src/views/catalog/CreateFromInstanceTypes/components/SectionListItem/SectionListItem.tsx
src/views/catalog/CreateFromInstanceTypes/components/SelectInstanceTypeSection/SelectInstanceTypeSection.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/VMDetailsBody.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/VMDetailsBody/components/DetailsLeftGrid.tsx
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts
src/views/catalog/CreateFromInstanceTypes/hooks/useBootableVolumes.ts
src/views/catalog/CreateFromInstanceTypes/utils/constants.ts
src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

Enabling user to select either a DS or a PVC and create a VM from it with IT and prefs.
Will get only PVCs that are not represented by a DataSource and have the default preference label
https://user-images.githubusercontent.com/67270715/234808328-93106942-8a86-4cf6-a3a2-45fea89efb5d.mp4

CNV-27327: Implement the UI to enable users to create a VM from a PVC

---

src/utils/hooks/useUserSettings/useUserSettings.ts

This is the first step of adding the user setting feature.
In this PR I have built the hook that will be in charge of creating/updating the config map of user setting. 
https://issues.redhat.com/browse/CNV-28327

CNV-28327: User settings hook infrastracture

---

src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
src/utils/hooks/useKubevirtUserSettings/utils/userSettingsInitialState.ts
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

Updaing useKubevirtUserSettings (name and a bit refactor)
Adding new hook based on useKubevirtUserSettings to manage user selected columns that will be persistent among sessions and logins.
Connect VirtualMachineList to the new hook
A follow-up PR will connect the rest of the tables in our code base that use column management. 

CNV-28334: Adding ability to user settings column management

---

i18n-scripts/build-i18n.sh
i18next-parser.config.js
package.json

There was something wrong with translations. 
the script for no reason adds inexistence keys like.
```json
{
"showFailed": "showFailed",
"showSuccess": "showSuccess"
}
```
just use i18next which will load automatically our i18next configuration file and restrict the research to the `src` folder and the console-extensions.json file

Fix i18n script

---

src/views/catalog/customize/cd.ts
src/views/catalog/customize/components/CustomizeForms/CustomizeFormWithStorage.tsx
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/customize/components/CustomizeSource/BootCDCheckboxLabel.tsx
src/views/catalog/customize/components/CustomizeSource/CustomizeSource.tsx
src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts

remove docker prefix when using containerDisk.
ContainerDisk already expect a docker image URL so using `docker://` prefix is wrong

Bug 2189744: no docker prefix for container image

---

src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTableColumns.ts
src/views/bootablevolumes/list/hooks/useBootableVolumesColumns.ts
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts
src/views/clusteroverview/MigrationsTab/components/MigrationsTable/hooks/useVirtualMachineInstanceMigrationsColumns.ts
src/views/datasources/list/hooks/useDataSourcesColumns.ts
src/views/instancetypes/list/hooks/useClusterInstancetypeListColumns.ts
src/views/migrationpolicies/list/hooks/useMigrationPoliciesListColumns.ts
src/views/preferences/list/hooks/useClusterPreferenceListColumns.ts
src/views/templates/list/hooks/useVirtualMachineTemplatesColumns.ts
src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticConditionsTableColumns.ts
src/views/virtualmachines/details/tabs/diagnostic/hooks/useDiagnosticVolumeStatusTableColumns.ts
src/views/virtualmachines/list/hooks/useVirtualMachineColumns.ts

Part 2:
Connection all table that used useActiveColumn to our new KubevirtColumns hook, that will keep the user settings about columns management persistent. 

CNV-28334: Adding ability to user settings column managment - part 2

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

Clone `ControllerRevision` for `instancetype` and `preference` in the new namespace as suggested by @lyarwood 
**The flow**
(Only In case of cloning vm created through instance type) 
- if in the destination namespace there is no ControllerRevision with the same name, we'll create it. (for instance type and prefernece)
- clone the vm
- in case the controller revision was not created, the cloned vm will be added as owner. In case the controlelr revision was created, does not have owner and we'll add the cloned vm as only owner

Bug 2182938: clone revisions alongside vm

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/AlertScripts/AlertScripts.tsx
src/utils/components/AlertScripts/index.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx
src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx

- Add lines and units to VM metric charts y-axis
- Bug 2182172: Add alert for clound init and ssh auth keys
Cloud-init runs only the first time and editing this property alongside auth keys is useless for now.
Unfortunately, following the bug conversation, there is no good way to understand if was already executed and applied.
We could use the status.created of the VM to disable cloud init and ssh key editing but it's not accurate as the cloud-init could not be executed yet.
The good news: the backend is implementing a way to fix that and allow the user to change the configuration after the first tun.

Bug 2182172: Add alert for clound init and ssh auth keys

---

src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettingsTopConsumerCards.ts
src/utils/hooks/useKubevirtUserSettings/utils/const.ts
src/utils/hooks/useKubevirtUserSettings/utils/types.ts
src/utils/hooks/useKubevirtUserSettings/utils/utils.ts
src/utils/hooks/useLocalStorage.ts
src/views/clusteroverview/TopConsumersTab/TopConsumersTab.tsx
src/views/clusteroverview/TopConsumersTab/utils/TopConsumerCard.tsx
src/views/clusteroverview/TopConsumersTab/utils/TopConsumersChartList.tsx
src/views/clusteroverview/TopConsumersTab/utils/TopConsumersGridRow.tsx

connection overview -> top consumers
All charts settings are now connecting to kubevirt user settings and will be persistent between logins in different sessions and not only over sessions.

CNV-28335: Connecting top consumer cards to persistent user settings

---

cypress/utils/const/index.ts
locales/en/plugin__kubevirt-plugin.json
src/utils/components/FirmwareBootloaderModal/FirmwareBootloaderModal.tsx
src/utils/components/FirmwareBootloaderModal/utils/constants.ts
src/utils/components/FirmwareBootloaderModal/utils/types.ts
src/utils/components/FirmwareBootloaderModal/utils/utils.ts
src/views/catalog/wizard/tabs/overview/components/WizardOverviewGrid.tsx
src/views/templates/details/tabs/details/components/BootMethod/BootMethod.tsx
src/views/templates/details/tabs/details/components/BootMethod/TemplateBootloaderModal.tsx
src/views/virtualmachines/details/tabs/details/components/grid/leftGrid/VirtualMachineDetailsLeftGrid.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2181920
This is a followup of https://github.com/kubevirt-ui/kubevirt-plugin/pull/1236 introducing the change that `efi: { secureBoot: false }` was written to VM's yaml when changing _Boot mode_ field value to "UEFI", because that was correct representation of "UEFI" boot mode (secure boot disabled).
**In this PR, the following remaining issues are fixed:**
- for existing VM:
- it shows "UEFI" for _Boot mode_ field in _Details_ for `efi: {}` in the yaml's bootloader section
- in Create VM wizard:
- it shows "UEFI" for _Boot mode_ in _Review and create VirtualMachine_ screen for `efi: {}` in the yaml's bootloader section
- for existing template:
- it shows "UEFI" for _Boot mode_ in _Details_ for `efi: {}` in the yaml's bootloader …

Bug 2181920: Display "UEFI" for Boot mode for "efi: {}" in yaml

---

src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/hooks/useCloneVMResources.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2196765
Sort the namespaces/project names for "Namespace" field/drop down in "Clone VirtualMachine" modal alphabetically to make searching easier.
**Before:**
Namespaces not sorted alphabetically, harder to find the specific one:
**After:**
Namespaces sorted as expected:

Bug 2196765: Sort project names in Clone VM modal

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/components/BootableVolumeListModal/BootableVolumeListModal.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2207916
Change submit button text from "Save" to "Select" in "Available volumes" modal accessible when clicking on "Show all" link when creating a VM from InstanceTypes. Make this change according to the UX recommendation.
_Related design doc:_
https://docs.google.com/document/d/1HTF6_H2WDXwlVy7RnrHH28dzFlhNIa15Hhpeoyg2R0Q/edit#heading=h.1f45n413fzcm
**Before:**
**After:**

Bug 2207916: Change button text to 'Select' in 'Available volumes' modal

---

src/utils/components/Charts/utils/queries.ts

Fixing the memory query to show proper values.
gauge queries should have the pattern of: `sum(rate(<metric_query>[duration]))`
[Screencast from 05-29-2023 11:14:51 AM.webm](https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/8cd58b55-9d3a-4e7a-b199-26b95840a8ac)
[Screencast from 05-29-2023 11:15:14 AM.webm](https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/3f10ea5b-9904-4b21-b23d-57af1b9eec29)

Fix memory metric query

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/CloneResourceModal/CloneResourceModal.tsx
src/utils/components/RedHatLabel/RedHatLabel.tsx
src/views/instancetypes/actions/hooks/useClusterInstancetypeActionsProvider.tsx
src/views/instancetypes/list/components/ClusterInstancetypeRow.tsx
src/views/preferences/actions/hooks/useClusterPreferenceActionsProvider.tsx
src/views/preferences/list/components/ClusterPreferenceRow.tsx

Add clone action for VirtualMachineClusterPreference and VirtualMachineClusterInstancetype resource pages.
NOTE: Clone action is removing previous metadata and only assigns a new name.
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/9696456d-6d36-49c9-98ae-d2c6adbd1e00

CNV-27319: Add clone action and provider label for IT and prefs

---

src/views/catalog/CreateFromInstanceTypes/utils/utils.ts

VM created from instanceTypes cannot be scheduled because secret not found

CNV-29220: Remove VM's access credentials if ssh is not configured

---

src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx

Showing the VMI networks and interfaces in case the VM is running.
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/952537e0-79f9-4590-8c34-5d3a8d9e9854
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/8f11db94-480a-4ea3-8e59-4b2afe84c814

Show running networks when VMI exists

---

src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourcePVCSelect.tsx
src/utils/utils/units.ts
src/views/catalog/utils/quantity.ts

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2203187
Make adding disk in _Add disk_ modal when choosing _PVC (creates PVC)_ as a source work. Make it work by setting the PVC size unit correctly for this option.
_Details:_
The problem was that when setting disk size for _PVC (creates PVC)_ source (`setDiskSize`), the disk size unit was set to one of the following: MiB, GiB, TiB. The disk was not able to be created when using these units (that we prefer when displaying size in the UI). The problem was presence of "B" at the end of the unit (a.k.a. IEC units) when using `bytesFromQuantity` to get the correct size and unit.
Originally, `bytesFromQuantity` was used to prevent getting the size in bytes in some situations (for example when deleting the size number in the appropriate …

Bug 2203187: Make adding disk by cloning PVC work

---

locales/en/plugin__kubevirt-plugin.json
src/views/templates/details/tabs/details/TemplateDetailsPage.scss
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.scss
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/template-network-tab.scss
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/parameters/template-parameters-page.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
src/views/templates/details/tabs/scripts/components/SSHKey/SSHKey.tsx
src/views/templates/details/tabs/scripts/components/SysPrepItem/SysPrepItem.tsx
src/views/templates/details/tabs/scripts/template-scripts-tab.scss

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2189312
Add missing titles to the following _Templates_ tabs:
- _Details_
- _Scheduling_
- _Network interfaces_
- _Parameters_
Update _Disks_ tab title to be better aligned with YAML switcher, for better look.
Make titles in _Scripts_ tab bigger, same as in other tabs, for consistency reasons.
_Design doc:_
https://docs.google.com/document/d/1Y8TA1EeAZVCLkqUT-ZHzWKGkSEpVMq6jYdXwG1Uv2Gw/
_Notes:_
Note that in the design doc, YAML switcher is not displayed. This is not because it should be removed, no.
It is just a bug of the doc. And there is a plan to move the YAML switcher to another location, as mentioned in the design doc at it's top. This will be done by another PR once the design doc will be updated.
Note that picture for …

Bug 2189312: Add missing titles to Templates tabs

---

src/views/virtualmachines/details/tabs/configuration/VirtualMachineConfigurationTab.tsx
src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss

Changing tabs layout to be vertical

CNV-29213: Change VM config tab to vertical tabs layout

---

src/views/bootablevolumes/list/components/BootableVolumesRow.tsx

_Related BZ:_
https://bugzilla.redhat.com/show_bug.cgi?id=2196161
_Related PR comment:_
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1323#discussion_r1218273916
This is just a small improvement of the BZ fix. Add missing namespace prop to `ResourceLink` in `BootableVolumesRow` component, to avoid possible 404 error when clicking on the resource in _Bootable volumes_ list.

Add missing namespace to ResourceLink in BootableVolumesRow

---

console-extensions.json
src/utils/hooks/usePreviewFeatures/constants.ts
src/utils/hooks/usePreviewFeatures/usePreviewFeatures.ts

This PR exposes a new hook called `usePreviewFeatures` to enable opt-in and out for tech preview feature (currently only `create VM from InstanceTypes flow`)
No visible changes

CNV-28829: Preview feature mechanism for IT - part 1

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/CPUMemoryModal/constants.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-29237
Enable _Restore template settings_ button displayed in _Edit CPU | Modal_ accessible in _Catalog_ drawer and make it work correctly, by providing a correct template namespace to get the original CPU/Memory data, needed for restoring template CPU/Memory values.
_Notes:_
_src/utils/components/CPUMemoryModal/constants.ts_ file was deleted as it has no use anymore. It contained only one constant used in only [one place](https://github.com/kubevirt-ui/kubevirt-plugin/compare/main...hstastna:kubevirt-plugin:BZ_Restore_template_settings_is_disabled_catalog?expand=1#diff-604e7268a1183adcb2fe6c4ae607baf9b22253a3a0856c27675fd94317aa803fL50). We have some other constant with the same string if needed in future. No need to define more constants …

CNV-29237: Enable Restore template settings" in Catalog CPU modal

---

src/views/templates/details/CommonTemplateAlert.tsx
src/views/templates/details/NoPermissionTemplateAlert.tsx
src/views/templates/details/TemplateNavPage.scss
src/views/templates/details/TemplateNavPage.tsx
src/views/templates/details/TemplatePageTitle.tsx
src/views/templates/details/tabs/details/TemplateDetailsPage.scss
src/views/templates/details/tabs/details/TemplateDetailsPage.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.scss
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/network/TemplateNetworkPage.tsx
src/views/templates/details/tabs/network/template-network-tab.scss
src/views/templates/details/tabs/parameters/TemplateParametersPage.tsx
src/views/templates/details/tabs/parameters/template-parameters-page.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.scss
src/views/templates/details/tabs/scheduling/TemplateSchedulingTab.tsx
src/views/templates/details/tabs/scripts/TemplateScriptsPage.tsx
src/views/templates/details/template-header-alert.scss
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-29485
_Design doc:_
https://docs.google.com/document/d/1Y8TA1EeAZVCLkqUT-ZHzWKGkSEpVMq6jYdXwG1Uv2Gw/
Move the YAML switcher out of the Templates tabs/pages, display it to the left of _Actions_ menu and only for relevant pages, that contained the switcher also before this change. Make this change according to the recent design updates.
Make some css updates for some pages to achieve more consistent look: align sidebar editor properly in _Disks_ and _NICs_ tabs to be the same as in the other pages (`padding-top`).
The following screenshots are displayed as pairs - before and after, for better visual comparison:
_Details_ tab:
_Disks_ tab:
_Network interfaces_ (a.k.a NICs) tab:
_Parameters_ tab:
_Scheduling_ tab:
_Scripts_ tab:

CNV-29485: Move YAML switcher out of Template tabs

---

src/utils/components/EnvironmentEditor/EnvironmentForm.tsx
src/utils/components/EnvironmentEditor/components/EnvironmentFormSkeleton.tsx
src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
src/views/catalog/wizard/Wizard.scss
src/views/catalog/wizard/components/WizardHeader.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/wizard-disk-tab.scss
src/views/catalog/wizard/tabs/environment/WizardEnvironmentTab.tsx
src/views/catalog/wizard/tabs/metadata/WizardMetadataTab.tsx
src/views/catalog/wizard/tabs/metadata/wizard-metadata-tab.scss
src/views/catalog/wizard/tabs/network/WizardNetworkTab.tsx
src/views/catalog/wizard/tabs/network/wizard-network-tab.scss
src/views/catalog/wizard/tabs/overview/WizardOverviewTab.tsx
src/views/catalog/wizard/tabs/scheduling/WizardSchedulingTab.tsx
src/views/catalog/wizard/tabs/scripts/WizardScriptsTab.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-29502
**Design:**
https://docs.google.com/document/d/1j5SeV-4ZxJnOvJAhnVn6pjF7A-5TJgx4UQD-6brTn64/
Move the YAML switcher out of the tabs in _Review and create VirtualMachine_ page to the new place in the right - above the tabs, same as it is for VM or Template tabs, for consistency reasons. Display the switcher only for relevant pages that contained the switcher also before this change (all tabs in the page except _YAML_ one). Make this change according to the recent design updates.
Make also some minor css updates for some pages to achieve more consistent look:
align sidebar editor properly in _Disks_ and _NICs_ tabs to be the same as in the other pages (`padding-top`).
The following screenshots are displayed as pairs - before and after, …

CNV-29502: Move YAML switcher out of tabs in Review and create VM

---

src/views/bootablevolumes/list/BootableVolumesList.tsx
src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
src/views/catalog/CreateVMHorizontalNav/components/CreateVMTabTitle/CreateVMTabTitle.tsx
src/views/instancetypes/list/ClusterInstancetypeList.tsx
src/views/preferences/list/ClusterPreferenceList.tsx
src/views/virtualmachines/list/components/VirtualMachinesCreateButton/VirtualMachinesCreateButton.tsx

After discussion with UX, to move from dev preview to tech preview we need to just remove the dev preview labels.

CNV-28485: Move IT feature from dev preview to tech preview

---

src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/VMDetailsSection.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-29304
Make more space for "VirtualMachine details" - step 3 of VM creation from InstanceTypes (_Catalog > InstanceTypes_ tab), especially for a long VM name and small screens.
**Before:**
**After:**

CNV-29304: Make more space for VirtualMachine details in step 3

---

src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts
src/utils/hooks/useKubevirtUserSettings/utils/const.ts

This PR includes these changes to user settings mechanism:
- We create one CM for all users instead of one per user, named `kubevirt-user-settings` on `default` namespace, and the CMs data is looking like: `username: userSettings`
- We create a Role and RoleBinding CRs to allow all users `get` / `list` / `update` / `patch` actions only on the `kubevirt-user-settings` CM.
Current issues: 
- In some edge cases a user is logging into a cluster before any cluster admin is, this  feature won't work, an initial cluster-admin login is required. (We should push to get this CM on Kubevirt deployment from BE on the next version to avoid this issue).
- It is possible for any user to edit this CM manually (not directly through the UI) which can impact other users settings. 
After:

Fix user setting for non admin users

---

src/utils/components/EnvironmentEditor/components/EnvironmentFormTitle.tsx
src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/wizard-disk-tab.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-29788
Remove titles from _Environment_ and _Disks_ tabs in _Review and create VirtualMachine_ page to make the tabs more consistent with each other. 
Add _The following information is provided by the OpenShift Virtualization operator._ text to _Disks_ tab instead of help text icon displaying the popover containing this text, similarly as it is already done in the _Environment_ tab, to keep the original information available to the user.
**Before**:
**After:**
_Disks_ title removed, text of the original popover added:
_Environment_ title removed:

CNV-29788: Remove titles from Environment, Disks tab for customizing VM

---

src/utils/components/CloudinitDescription/CloudInitDescription.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2211168
_Jira issue:_
https://issues.redhat.com/browse/CNV-29295
Display VM _Scripts_ tab correctly, fix the error in the page, for VMs with specific cloud init data.
**Before:**
Error in the page, unable to display _Scripts_ tab correctly:
**After:**
_Scripts_ tab displayed as expected:

Bug 2211168: Display VM Scripts tab correctly

---

src/utils/hooks/useFeatures/types.ts
src/utils/hooks/useFeatures/useFeatures.ts
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.scss
src/views/catalog/CreateFromInstanceTypes/CreateFromInstanceType.tsx
src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx
src/views/catalog/CreateFromInstanceTypes/hooks/useEnableInstanceTypeModal.ts
src/views/catalog/CreateVMHorizontalNav/CreateVMHorizontalNav.tsx
src/views/catalog/EnableInstanceTypeTechPreviewModal/EnableInstanceTypeTechPreviewModal.tsx

This Pr fixes:
- loading state of InstanceType tab under the catalog - instead of sections load one by one and modal to pop, I add a loading spinner to make the page loading look better
- By getting inside dev tools it was possible to remove the enable IT modal and create a VM, so adding another defense to disable the create button if the feature is disabled.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/397e684a-bc24-422c-aba5-5c5fea09d07d
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/6df48245-d00e-4163-96be-276f1d5d738c

Fix InstanceType tab loading state

---

src/utils/components/Charts/CPUUtil/CPUThresholdChart.tsx
src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
src/utils/components/Charts/NetworkUtil/NetworkThresholdChart.tsx
src/utils/components/Charts/StorageUtil/StorageTotalReadWriteThresholdChart.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/virtual-machines-overview-tab-utilization.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-29306
Simplify VM _Overview_ _Utilization_ charts, especially _CPU, Memory_ and _Storage_ ones, remove unnecessary y axis, make the padding of the charts the same, so the distance between each other is the same, make charts look similar as Network transfer chart.
Additionally, update font size of _In_ and _Out_ to be the same as _Total_.
**Before:**
Showing the data of the last day:
**After:**
Showing the data of the last day:

CNV-29306: Simplify VM Overview Utilization charts

---

locales/en/plugin__kubevirt-plugin.json
src/views/clusteroverview/OverviewTab/getting-started-card/feature-highlights-section/FeatureHighlightsSection.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2214120
_Jira:_
https://issues.redhat.com/browse/CNV-29725
Change text "OpenShift Virtualization 4.10 Highlights" to "OpenShift Virtualization 4.13 Highlights",
update the link to https://docs.openshift.com/container-platform/4.13/virt/virt-4-13-release-notes.html#virt-4-13-new
(as it was suggested by me and approved by our PM).
**Before:**
**After:**

Bug 2214120: Show Feature highlights in CNV 4.13 instead of 4.10

---

src/utils/resources/vm/utils/selectors.ts
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

VM that has only pvc was crashing because of trying to loop on dataVolumeTemplate section of the VM assuming it's populated. Adding a protection to avoid looping on undefined as solved this issue.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/f66790c3-f5eb-46b2-9299-c344d01b662a
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/8e844a81-6ab0-4493-8ab2-d250cb477828

CNV-30370: Clone modal crashes if VM has only pvcs

---

src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/CPUUtil/CPUUtil.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-29473
Change units from 's' to 'm' for CPU Utilization chart in VM's Overview page, including labels for the chart (black in the pictures below).
**Before:**
**After:**

CNV-29473: Change CPU unit from 's' to 'm' in single VM Overview

---

src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx

When getting inside any VM and clicking on actions will crash as the VM is not loaded yet
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/9586fd45-b9ac-41ee-8981-8ec3d2123e0a
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/9040270a-ebb4-4b0b-bb26-e331827922db

Fix VM details action crash when vm not loaded yet

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/SSHAccess/SSHAccess.tsx
src/utils/components/SSHAccess/components/ConsoleOverVirtctl.tsx
src/utils/components/SSHAccess/components/VirtctlSSHCommandClipboardCopy.tsx
src/utils/components/SSHAccess/constants.ts
src/utils/components/SSHAccess/utils.ts
src/views/virtualmachines/actions/VirtualMachineActionFactory.tsx
src/views/virtualmachines/actions/hooks/useVirtualMachineActionsProvider.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsTitle.tsx

This PR fixes:
- Allow editing the SSH command in the details tab to insert the identity file (ssh private key) path.
- Adding an example of how an SSH command should look like with virtctl.
- Disable the option to copy the SSH command if the VM is missing an SSH secret attached to it.
Before: 
actions enabled and VM does not have secret with ssh public key:
showing ssh command:
After:
show ssh command only if ssh secret is available
ssh secret not configured:
action disabled only if vm missing ssh secret configured:

CNV-30327: Add identity flag to ssh command

---

src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.scss
src/views/virtualmachines/actions/components/VirtualMachineActions/VirtualMachineActions.tsx
src/views/virtualmachines/details/VirtualMachineNavPageTitle.tsx
src/views/virtualmachines/list/components/VirtualMachineRow/VirtualMachineRowLayout.tsx

When appending the dropdown to the outer page, every re-render on that page will cause the dropdown to re-render and change location.
When using the Dropdown component from PF we can use the menuAppentTo prop to append the dropdown to the parent, however this presents a scrolling issue on the firefox browser, as the dropdown keeps getting focus and the scorlling would seem stuck. this is a PF issue that needs to be resolved as the focus is coming from the dropdown component.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/483f3437-e26c-4b95-ba1b-5ad3e59fe30c
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/25afa42a-7c70-4758-841c-191d53a770cc

CNV-29392: VM actions menu jumps when vms on list change state

---

src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/BandwidthConsumptionChart.tsx
src/views/clusteroverview/MonitoringTab/migrations-card/components/BandwidthConsumptionChart/utils.ts

https://issues.redhat.com/browse/CNV-25217
Fixing the wrong values in Bandwidth consumption chart on the Migration tab on the Overview page. 
Before:
After:

CNV-25217: Fixing the wrong values in Bandwidth Consumption chart

---

src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypeVMInitialStore.ts
src/views/catalog/CreateFromInstanceTypes/state/utils/state.ts
src/views/catalog/CreateFromInstanceTypes/state/utils/utils.ts

Creating a VM with IT is missing the os prefix as we do in the catalog.
To fix that we must select a volume first, and than we base the VM name on that volume's OS
Before:
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/5be0f2fb-5b78-4a93-90c8-1f06b00cff87

CNV-30667: Align VM name in catalog tabs

---

src/views/virtualmachines/details/tabs/configuration/virtual-machine-configuration-tab.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-30536
Display second-level VM _Configuration_ tabs that have been truncated for small browser window.
**Before:**
Sub-tabs like _Scheduling_, _Environment_ etc are not visible for small browser window:
**After:**

[release-4.13] CNV-30536: Display second-level VM Configuration tabs

---

src/views/clusteroverview/SettingsTab/settings-tab.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-30519
Prevent text to exceed the size of the tab in _Overview > Settings > General_, display size of the tab (represented by the PF `Tab` component, seen as the white background in the screenshots below) according to its content. Make it work in the actual Firefox, Chrome, Chromium browsers.
Note that the problem has occurred mainly for smaller browser windows, when size of the tab was set to 75% of the visible screen by the css `height` prop. This is also core of the problem, so removing unnecessary prop fixes the problem. Now the size of the tab is based on its content, nothing exceeds no matter the size of the browser window, no matter the browser used.
**Before:**
**After:**

[release-4.13] CNV-30519: Prevent text to exceed the size of tab in Overview > Settings

---

src/views/catalog/CreateFromInstanceTypes/components/CreateVMFooter/CreateVMFooter.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2222607
_Jira:_
https://issues.redhat.com/browse/CNV-30901
Make the checkbox responsive/change its value in the catalog drawer when clicking on the label of the checkbox.
In general, it is not a good practice to have same elements with the same id in the same page. Having it so can lead to unexpected behavior. In this PR, one of such checkbox ids is changed to fix the problem.
**Before:**
The checkbox in the catalog drawer does not work as expected, when clicking on its label:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/0a855a5d-960f-4f89-83d3-1a3eb1fc7fb1
**After:**
All the checkboxes to allow starting VM after its creation work as expected:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/91c22a70-5e0 …

CNV-30901: Make "Start this VirtualMachine after creation" checkbox work

---

src/utils/components/CloudinitModal/CloudInitEditor/CloudInitEditor.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-30719
Hide unnecessary _Cancel_ button that is part of the `ResourceYAMLEditor` component, displayed in _Cloud-init_ modal accessible in VM's _Configuration > Scripts_ tab.
**Before:**
Two _Cancel_ buttons present in the modal and clicking on the 1st one redirects to the incorrect page:
**After:**
Only one Cancel button present in the modal (and clicking on it does not redirect us anywhere as expected):

CNV-30719: Hide Cancel button for ResourceYAMLEditor for VM Cloud-init

---

src/views/catalog/CreateFromInstanceTypes/state/hooks/useInstanceTypeVMInitialStore.ts

centos stream preference has more than 1 '.' char in it's name so using replaceAll to fix to issue.
Before:
After:

CNV-30667: Align VM name in catalog tabs - fix centos stream use case

---

src/utils/components/CloudinitModal/utils/cloudinit-utils.ts
src/utils/components/CloudinitModal/utils/consts.ts
src/utils/components/SSHSecretSection/utils/utils.ts
src/utils/hooks/useRHELAutomaticSubscription/useRHELAutomaticSubscription.ts
src/utils/hooks/useRHELAutomaticSubscription/utils/types.ts
src/views/catalog/CreateFromInstanceTypes/utils/utils.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerFooter.tsx
src/views/catalog/templatescatalog/tests/TemplatesCatalogDrawer.test.tsx
src/views/catalog/utils/quick-create-vm.ts
src/views/clusteroverview/SettingsTab/ClusterTab/components/AutomaticSubscriptionRHELGuests/components/AutomaticSubscriptionForm/AutomaticSubscriptionForm.tsx

Apply activation key and organization ID to cloud-init config when creating RHEL VM with Quick Create VM flow.
Also Changing the cloud-init volume to Cloud Drive
upgrade successful:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/37c29be1-1017-4337-9712-0c5e55f5e47c

CNV-20469: Apply activation key and organiztion ID to QuickCreate VM - part2

---

src/views/catalog/CreateFromInstanceTypes/components/BootableVolumeList/hooks/useBootVolumeColumns.ts

**Fixes:**
https://issues.redhat.com/browse/CNV-29219
Hide unnecessary namespace related info text displayed usually in _Manage columns_ modal, part of `ListPageFilter` component, for list of bootable resources when creating VM from InstanceTypes, as namespace is not relevant for this page. Specifically, hide the following in the modal:
_The namespace column is only shown when in "All projects"_
**Before:**
**After:**

CNV-29219: Hide namespace related info in Manage columns modal

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2221939
_Jira:_
https://issues.redhat.com/browse/CNV-30864
Add "?" help icon with the popover containing the following text to help the user find where to add static public SSH key:
_"Static SSH keys can be added on Overview > Settings > User > Manage SSH keys."_
Add it to "Authorized SSH key" field/section in VM _Configuration > Scripts_ tab, according to the suggestions from the doc team and UX.
**Before:**
**After:**

Bug 2221939: Add help icon with text to SSH key field in  M Sctips tab

---

src/views/bootablevolumes/list/hooks/useBootableVolumesFilters.ts

Add resource kind filter to bootable volumes page
Before:
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/326c5470-ba22-48f8-ad90-dda7ec38adff

CNV-31184: Add an option to filter DS and PVC in bootable volumes page

---

src/utils/components/NetworkInterfaceModal/components/hooks/useNADListPermissions.ts

useAccess was missing the group field, because of that we were getting false response about non-admin users that can list nads

CNV-29391: Fix nads list permissions

---

src/views/catalog/CreateFromInstanceTypes/state/useInstanceTypeVMStore.ts

The list was getting PVC and DS from all namespaces instead of just from the OS images namespace.
Before:
After:

CNV-31190: PVCs from default namespace present in catalog instanceType list page

---

src/views/bootablevolumes/list/BootableVolumesList.tsx

Fix bootable volumes list to listen to the namespace bar
Before:
After:

CNV-31249: Bootable volume list does not listen to namespace bar

---

locales/en/plugin__kubevirt-plugin.json
src/views/bootablevolumes/list/BootableVolumesList.tsx

Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2221921
_Jira:_
https://issues.redhat.com/browse/CNV-30859
Change page title from _Bootable resources_ to _Bootable volumes_ to match the menu item in `Virtualization` section. Make this change according to the UX suggestions.
**Before:**
_Bootable resources_ page title vs _Bootable volumes_ in `Virtualization` section:
**After:**

Bug 2221921: Change page title to "Bootable volumes"

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DescriptionItem/DescriptionItemHeader.tsx
src/utils/components/VirtualMachineDescriptionItem/VirtualMachineDescriptionItem.tsx
src/views/virtualmachines/details/tabs/configuration/scripts/ScriptsTab.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2221939
see the comment: https://bugzilla.redhat.com/show_bug.cgi?id=2221939#c14
_Jira:_
https://issues.redhat.com/browse/CNV-30864
_Related PR that added the popover originally:_
https://github.com/kubevirt-ui/kubevirt-plugin/pull/1395
Remove "?" help icon with the popover containing the following text that was originally added to help the user find where to add static public SSH key:
_"Static SSH keys can be added on Overview > Settings > User > Manage SSH keys."_
Remove it from "Authorized SSH key" field/section in VM _Configuration_ > _Scripts_ tab, according to the suggestions from the doc team and UX.
**Before:**
"?" icon with popover present next to the _Authorized SSH key_:
**After:**
No any "?" icon with popover present next …

Bug 2221939: Remove help icon for SSH key field in VM Sctips tab

---

src/views/catalog/wizard/tabs/disks/WizardDisksTab.tsx
src/views/catalog/wizard/tabs/disks/wizard-disk-tab.scss

**Fixes:**
https://issues.redhat.com/browse/CNV-31357
Remove "The following information is provided by the OpenShift Virtualization operator" text from _Customize and create VirtualMachine_ page - _Disks_ tab, as it is not necessary. Make this change according to the latest UX suggestion.
**Before:**
**After:**

CNV-31357: Remove unnecessary text from Disks tab when customizing VM

---

src/utils/hooks/useAlerts/utils/utils.ts

**Fixes:**
https://issues.redhat.com/browse/CNV-29082
Make clicking on _View alert_ link to a specific alert work, accessible on _Virtualization > Overview > Alerts_ card > _Warnings_.
_How to reproduce a bug/test this PR:_
You need to clone the monitoring repo: https://github.com/openshift/monitoring-plugin
Then you just need to add it as the plugin and run that together with this repo, so that _Observe_ appears in the main menu in the UI. If you need help/more details, feel free to ask me. 
**Before:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/71a86c22-caf4-4ce3-bd2d-45709ac97679
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/dfc998a7-36a0-4f95-ac6c-c7286321295e

CNV-29082: Make "View alert" on Overview > Alerts card work

---

src/views/catalog/wizard/tabs/overview/components/VMNameModal/VMNameModal.tsx
src/views/virtualmachines/actions/components/CloneVMModal/utils/helpers.tsx

Change the DVT of cloned volume according to [DOCS](https://docs.openshift.com/container-platform/4.13/virt/virtual_machines/cloning_vms/virt-cloning-vm-using-datavolumetemplate.html#virt-creating-new-vm-from-cloned-pvc-using-datavolumetemplate_virt-cloning-vm-using-datavolumetemplate)
Before:
After:

CNV-31188: Fix VM clone

---

src/views/catalog/templatescatalog/components/TemplatesCatalogFilters/TemplatesCatalogFilters.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogHeader.tsx
src/views/catalog/templatescatalog/hooks/useVmTemplatesFilters.ts
src/views/catalog/templatescatalog/tests/TemplatesCatalog.test.tsx
src/views/catalog/templatescatalog/utils/consts.ts
src/views/catalog/templatescatalog/utils/helpers.ts
src/views/catalog/templatescatalog/utils/types.ts

**Fixes:**
https://issues.redhat.com/browse/CNV-31327
Display "Default templates" in Catalog page by default, when first time in, not "All items" as previously.
TODO:
**Before:**
"All items" displayed when accessing Catalog:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/d29b1e0d-0c90-490d-a298-f17b0401a49e
**After:**
"Default templates" displayed when accessing Catalog:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/2897915d-9aab-4d98-bfb2-5b57e1ee68e1

CNV-31327: Display Default templates in Catalog by default

---

src/utils/components/DiskModal/DiskFormFields/DiskInterfaceSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/DiskSourceFormSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskSourceFormSelect/components/DiskSourceUrlInput.tsx
src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/EditDiskModal.tsx
src/views/templates/details/tabs/disks/TemplateDisksPage.tsx
src/views/templates/details/tabs/disks/components/DiskRowActions.tsx

Since upload is occurring instantly to a PVC, we can't save an upload to a template to be created.
Removing the upload option from the add disk / edit disk flow for Templates view
Before:
After:

CNV-28827: Remove upload option from template add/edit disk modal

---

src/views/virtualmachines/actions/components/DeleteVMModal/components/DeleteOwnedResourcesMessage.tsx
src/views/virtualmachines/actions/components/DeleteVMModal/utils/helpers.ts

When data volume garbage collector is disabled, we count two times the data volume disks. 
One as PVC and one as dv but they are actually the same disk.
Here: https://github.com/kubevirt-ui/kubevirt-plugin/blob/5c9a4131711ee885c01e297fd91bef19caa4b772/src/views/virtualmachines/actions/components/DeleteVMModal/hooks/useDataVolumeConvertedVolumeNames.ts
So, just filter the PVC already represented by the DV in the count. 
**Before**
**After**

Delete modal count

---

src/utils/resources/template/utils/helpers.ts
src/views/catalog/templatescatalog/utils/helpers.ts
src/views/clusteroverview/OverviewTab/inventory-card/utils/constants.ts
src/views/clusteroverview/OverviewTab/inventory-card/utils/flattenTemplates.ts

**Fixes:**
https://issues.redhat.com/browse/CNV-31327
This is hopefully the last PR that belongs to the feature (see the link above).
Display really only user created templates in _Catalog_ page when clicking on _User templates_. Filter out common templates from templates previously displayed in the page as user created templates.
Additionally, remove `isDeprecatedTemplate` from _src/views/clusteroverview/OverviewTab/inventory-card/utils/flattenTemplates.ts_ because the same function is already defined in _src/utils/resources/template/utils/helpers.ts_ (same definition). It's better if you DRY.
**Before:**
Common templates present in the page when clicking on "User templates":
**After:**
Only user created templates displayed:

CNV-31327: Filter User templates in Catalog correctly

---

package.json
start-console.sh

Adding the option to run more plugin along side kubevirt from a single terminal
just neeed to run yarn start-console-with-monitoring

Adding support to run more plugin along side kubevirt

---

src/utils/components/AddBootableVolumeModal/AddBootableVolumeModal.tsx
src/utils/components/AddBootableVolumeModal/components/SchedulingSettings.tsx
src/utils/components/AddBootableVolumeModal/components/VolumeSource/VolumeSource.tsx
src/utils/components/AddBootableVolumeModal/utils/utils.ts

Add bootable volume have a graphical structure different from Upload/PVC to registry.
With this pr I align everything.
- Under *Source details* have only the registry URL and move the Volume name under Destination details (re-suing the same `Volume name` field that Upload/PVC use.
- Remove the Size field and use the storageClassname/size fields.
- Create the DataImportCron with the selected storageClassname
**Upload/Registry**
**Before**
**After**

CNV-31551: Edit add bootable volume

---

cypress/views/vm.ts
locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/list/components/VirtualMachinesCreateButton/VirtualMachinesCreateButton.tsx

**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2222185
_Jira:_
https://issues.redhat.com/browse/CNV-30878
Change "From YAML" to "With YAML" option for creating VMs in VM list page, for consistency reasons and suggestions from the docs team.
**Before:**
**After:**

Bug 2222185: Change "From YAML" to "With YAML"

---

src/utils/components/SSHSecretSection/SSHSecretModal.tsx
src/utils/components/SSHSecretSection/utils/utils.ts
src/utils/hooks/useKubevirtUserSettings/useKubevirtUserSettings.ts

The UI has a few specific input validations, but we should also validate against the BE validation.
Processing the secret with the `dryRun` param will apply an error to the modal dialog if the request is not proper.
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/a091aae2-040c-4734-9c12-3589ebc8eee5
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/c2f831d4-d9ac-4bf3-b4fe-1c0f9ccf8149

CNV-31946: VM cannot be started if the secret name does not match the k8s conventions

---

src/utils/components/CPUMemory/CPUMemory.tsx
src/utils/resources/vm/hooks/useInstanceType.ts
src/utils/resources/vm/hooks/useVMI.ts
src/utils/resources/vm/hooks/useVMIAndPodsForVM.ts

For VMs created from InstanceTypes the CPU and memory on the VM Details page is currently being read from the InstanceType, which leads to a mismatch on the VM Details page if the Instancetype is updated. The value circled on the graph shows the actual value.
The InstanceType used to create the VM starts off having 1 CPU and 4GiB of RAM. Between the "Before InstanceType update" and "After InstanceType update" screenshots, that InstanceType is edited to have 2 CPU and 2GiB of RAM.

CNV-28248: Display CPU and memory from VMI on VM Details page

---

src/views/catalog/CreateFromInstanceTypes/state/utils/utils.ts
src/views/catalog/utils/WizardVMContext/utils/tabs-data.ts
src/views/catalog/utils/useWizardVmCreate.ts
src/views/catalog/wizard/tabs/scripts/components/SSHKey.tsx

The checkbox in the SSH modal dialog was checked when you open it if the key was applied from the user settings.
Changing that behavior to just show the key name (checkbox is not unchecked on initial load if the key is applied from user settings).
Also changing the behavior of changing the key in the create VM flow to change the key in the settings only after VM creation and not everytime we edit the SSH key (on VM submit instead of SSH modal submit)
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/1a4f39cb-a0be-4058-b18a-3bfb4695a1d1
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/0fd9e001-6d57-482b-a1fd-cc65fd3fe3f5

CNV-31902: "Automatically apply" is checked when adding a new ssh key while there is a key configured in settings

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx

when customizing we try to process the template as is, and it should be processed in the scope of the current namespace
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/9c561122-c6e6-4274-9e92-741580fd0ad7
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/240d0ad0-6e46-4e91-8406-db30f48485be

CNV-32040: “vm is undefined“ shows when creating VM from template with regular user

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/PendingBadge/PendingBadge.scss
src/utils/components/PendingBadge/PendingBadge.tsx
src/utils/resources/vm/utils/network/utils.ts
src/utils/resources/vm/utils/selectors.ts
src/utils/resources/vmi/utils/selectors.ts
src/utils/utils/utils.ts
src/views/catalog/wizard/tabs/network/hooks/useNetworkColumns.ts
src/views/templates/details/tabs/network/hooks/useNetworkColumns.ts
src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx
src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx
src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceRow.tsx
src/views/virtualmachines/details/tabs/configuration/network/hooks/useNetworkColumns.ts

Newly added NICs are not present in the NICs list on the VM Details page. This PR adds the NICs to the list and marks them as pending.

CNV-31483: Add pending NICs to list in VM Details page

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DiskModal/DiskFormFields/DiskInterfaceSelect.tsx
src/utils/components/DiskModal/DiskFormFields/DiskTypeSelect.tsx
src/utils/components/DiskModal/DiskFormFields/StorageClassAndPreallocation.tsx
src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/EditDiskModal.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-31550
Add an info alert to "Add disk (hot plugged)" modal to inform the user that _Additional disks types and interfaces are available when the VirtualMachine is stopped._ for a running VM.
Also disable "Type" and "Interface" drop downs for a running VM.
Refactor `DiskModal` and `EditDiskModal` components, create new `StorageClassAndPreallocation` component to be used within `DiskModal` and `EditDiskModal` to prevent unnecessary repeating the same code in those components.
**Before:**
**After:**

CNV-31550: Add an alert to Add disk (hot plugged) modal

---

src/utils/hooks/useSingleNodeCluster.ts

When a non-admin user navigates to the VMs list page only the loading skeleton is displayed.

CNV-32310: Fix VMs list for non-admins

---

src/views/clusteroverview/OverviewTab/vms-per-resource-card/RunningVMsChartLegendLabel.tsx

Links for individual resource types in the VirtualMachines per Resource chart on the Virtualization Overview were all hardcoded to use 'all-namespaces'. This PR makes the links namespaced to the active namespace.
Issue link: https://issues.redhat.com/browse/CNV-32168

CNV-32168: Fix links in VMs per resource chart on the Virtualization Overview page

---

locales/en/plugin__kubevirt-plugin.json
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/components/DetailsRightGrid.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32401
Change _SSH key name_ field name to _Authorized SSH key_ in _InstanceTypes_ tab when creating VM from InstanceTypes, section 3 - _VirtualMachine details_, to align it more with the _Authorized SSH key_ modal and with _VM -> Configuration -> Scripts_ tab.
**Before:**
**After:**

CNV-32401: Change "SSH key name" field to "Authorized SSH key"

---

src/utils/components/DiskModal/utils/helpers.ts

Disk modal crash if open too fast, this cause by missing VM obj so also draftvm is nullush value. 

CNV-32467: Disk modal crash if open too fast

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/PersistentVolumeClaimSelect.tsx
src/views/catalog/customize/components/PersistentVolumeClaimSelect/utils.tsx

When checking Boot from CD on the customize VM parameters view, and choosing a PVC, we missing the storage section for the data volume template to clone the PVC we selected, which caused the VM creation to fail.
Note: For some reason pending changes alert for eviction strategy is shown on VM creation, will address that in a different Jira/PR.
After:
Create a VM with CD as boot (DV upload takes a while this mainly shows that the process of cloning the PVC is really happening)
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/d106e060-bc34-4851-95f4-9a367754ecf1
VM is running successfully:

CNV-32332: Boot from CD with CD source "PVC (clone PVC)" not working

---

console-extensions.json

Non admin users cannot list instancetypes and preferences in main menu
Admin user:
Non admin user:

CNV-32498: Main menu remove instancetype entries for non admin users

---

src/templates/clusterpreference-yaml.ts
src/views/catalog/CreateFromInstanceTypes/components/VMDetailsSection/utils/utils.ts

Adding os display name annotation to the initial example yaml.
Fallback to empty OS instead of preference name.

CNV-31484: The example of preference has 'example' as OS

---

src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx

Change the condition to start watching VMI and pod if VM status is not `Stopped`
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/db668cb9-b24d-4d84-b0ff-f7dd26c1984f

[release-4.12] CNV-27485: Unavailable data and wrong data during VM live migration

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx

This PR fixes a bug where an error alert was displayed in the catalog drawer.
Cause: Using the All Projects namespace session key in a `k8sCreate` call.
Issue: https://issues.redhat.com/browse/CNV-32392

CNV-32392: Fix error in catalog drawer for All Projects namespace

---

locales/en/plugin__kubevirt-plugin.json
src/utils/components/DiskModal/DiskFormFields/StorageClass/AlertedStorageClassSelect.tsx
src/utils/components/DiskModal/DiskFormFields/StorageClass/DefaultStorageClassAlert.tsx
src/utils/components/DiskModal/DiskFormFields/StorageClass/StorageClassSelect.tsx
src/utils/components/DiskModal/DiskFormFields/StorageClassAndPreallocation.tsx
src/utils/components/DiskModal/DiskModal.tsx
src/utils/components/DiskModal/utils/helpers.ts

Currently the alert is shown whenever a SC is selected which is not the same as the cluster's default which is wrong.
Changing the alert to show when VM is created with DS or cloned PVC as boot disk, and the selected SC of newly created disk is not the same.
Note: If VM was booted from URL/upload/registry, the alert should not show at all.
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/f0c695cd-5d79-468d-a043-4c8ecd44d823

CNV-22802: Warning "Selected StorageClass is different from the default StorageClass" should be improved

---

src/utils/components/DiskModal/DiskFormFields/StorageClass/StorageClassSelect.tsx

Improve check to useEffect hook on StorageClassSelect component, to allow selection when no default SC exists

Bug 2236393: Not able to select StorageClass if there is no default StorageClass defined in the cluster

---

src/utils/components/DiskModal/DiskFormFields/utils/helpers.ts
src/views/catalog/wizard/tabs/disks/hooks/useEditDiskState.ts
src/views/virtualmachines/details/tabs/disk/tables/disk/hooks/useEditDiskStates.ts

VM Disk table crashed after doing a memory dump
After:
Before:

[release-4.12] Bug 2236112: Fix disk table crash after memory dump

---

src/utils/components/CPUMemory/CPUMemory.tsx
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerPanel.tsx
src/views/catalog/wizard/components/WizardHeader.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32369
Display the CPU and Memory values for "CPU | Memory" field in the Catalog drawer, instead of showing "Not available". Make them editable again. 
Also display the values correctly, reflect the latest actual values after editing (this was also not correct) in the drawer.
The root cause of the problem was that to the related CPU/Memory code - to `CPUMemory` component was VMI related logic added without any considering that this code is common for existing VMs/VMIs and also for Catalog drawer and VMs that don't exist yet (so those cannot run yet, obviously). This also caused incorrect CPU value in the drawer (once "Not available" issue was solved by adding necessary conditions to `vmi` checks in the same component).
_Note:_
There is …

CNV-32369: Display proper CPU | Memory values in Catalog drawer

---

src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32609
Save correctly the CPU value from _Catalog_ drawer, especially if the user has edited this value in the drawer, so it can be displayed in _Customize and create VirtualMachine_ page correctly, same as it was set when the user has left the drawer.
_Note:_
This PR can be merged now, but it is kinda problematic to reproduce the bug without https://github.com/kubevirt-ui/kubevirt-plugin/pull/1514 being merged. 
**Before:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/310234ff-65d8-4c75-9b71-aabc870826c0
**After:**
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/d72aaff2-e7e7-4696-8e77-76aa6ae94dfb

CNV-32609: Keep the CPU value from Catalog drawer for customizing page

---

src/utils/components/CPUMemory/CPUMemory.tsx
src/utils/components/DiskModal/DiskModal.tsx
src/utils/resources/vm/hooks/disk/useDisksTableData.ts
src/views/virtualmachines/actions/components/CloneVMModal/CloneVMModal.tsx
src/views/virtualmachines/details/tabs/configuration/disk/tables/disk/DiskRowActions.tsx
src/views/virtualmachines/details/tabs/configuration/disk/tables/filesystem/FilesystemList.tsx
src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceActions.tsx
src/views/virtualmachines/details/tabs/details/components/grid/rightGrid/VirtualMachineDetailsRightGrid.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabDetails/components/VirtualMachinesOverviewTabDetailsConsole.tsx
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/VirtualMachinesOverviewTabUtilization.tsx
src/views/virtualmachines/utils/utils.ts

Use recently implemented `isVMRunning` util instead of repeatedly defining the same variable across the codebase, rename it to `isRunning`, which is shorter and still self explaining enough, and it also prevents potential bugs that could be created while unnecessary renaming `isVMRunning` variable already used in many components.
No any visual changes

Use isRunning VM util

---

src/utils/components/CPUMemory/CPUMemory.tsx
src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/CPUMemoryModal/hooks/useTemplateDefaultCpuMemory.ts
src/utils/components/Charts/MemoryUtil/MemoryThresholdChart.tsx
src/utils/components/EnvironmentEditor/tests/mocks.ts
src/utils/components/PendingChanges/utils/helpers.ts
src/utils/resources/template/utils/flavor.ts
src/utils/resources/vm/utils/constants.ts
src/views/catalog/customize/components/CustomizeForms/useCustomizeFormSubmit.ts
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx
src/views/catalog/templatescatalog/utils/helpers.ts
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx
src/views/virtualmachines/actions/tests/mocks.ts
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/MemoryUtil/MemoryUtil.tsx
src/views/virtualmachinesinstance/details/tabs/details/components/Details/CPUMemory/CPUMemory.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32596
The recent backend change in https://github.com/kubevirt/common-templates/pull/543 broke displaying memory value in the whole UI. This PR updates our UI codebase to reflect this new change. From now the memory value is read from:
`vm.spec.template.spec.domain.memory.guest`
**Before:**
Catalog drawer, error right after opening the drawer, no values for CPU and Memory:
Template details page - no value for memory:
**After:**

CNV-32596: Display Memory value correctly in the UI

---

src/views/virtualmachines/details/tabs/configuration/network/components/list/NetworkInterfaceList.tsx

This PR fixes a bug wherein the Pending badge still shows on a hot plug NIC even after the VM has migrated and the NIC has been added to the VMI.
jira issue: https://issues.redhat.com/browse/CNV-32618

CNV-32618: Fix pending badge showing on migrating VMs

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx

Exposing the size input for "Template default" option in customize template's parameters section.
Before:
Missing size input:
After:
Added size input:
Make sure change is accepted:

CNV-32173: Missing size input when creating disk from "Template default" disk source

---

src/templates/vm-template-yaml.ts
src/templates/vm-yaml.ts

**Fixes:**
https://issues.redhat.com/browse/CNV-32823
Update the "example" YAML of both VM and template used in the UI. Replace `vm.spec.template.spec.domain.resources.requests.memory` with `vm.spec.template.spec.domain.memory.guest` in the VM object, so the memory value gets saved correctly, according to the recent backend change introduced in
https://github.com/kubevirt/common-templates/pull/543.
Note that the bug this PR is fixing, fortunately didn't prevent VM to be created successfully and ran. 
Also note that VM creation from "example" template works as expected, too, with this PR, so its YAML is created and updated correctly.
**Before:**
"example" template creation - template created successfully, but incorrect YAML represetation regarding memory: …

CNV-32823: Update the example of VM and template YAML

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplatesCatalogDrawerCreateForm.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32787
Sometimes, the generated VM name is a bit longer, so the VM name field cannot hold it completely. This commit makes it a bit longer to hold the long name, as there's enough space in the line of the _Catalog_ drawer.
Additionally, edit the padding of the related part of the drawer the way that the whole content of the drawer is nicely aligned.
**Before:**
**After:**

CNV-32787: Adjust length of VM name field in Catalog drawer

---

locales/en/plugin__kubevirt-plugin.json
src/views/virtualmachines/details/tabs/overview/components/VirtualMachinesOverviewTabUtilization/components/NetworkUtil/NetworkUtil.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-32925
Display 'Bps' units instead of 'Bs' for _Network transfer_ statistics displayed in the VM _Overview_ tab of a running VM. Also change "Network Transfer" title to "Network transfer" to use sentence case to align with the rest of the UI.
**Before:**
**After:**

CNV-32925: Display correct units for Network transfer statistics

---

console-extensions.json

**Fixes:**
https://issues.redhat.com/browse/CNV-32959
Move _InstanceTypes_ and _Preferences_ menu items under _Templates_ in the _Virtualization_ menu, as those are just other resources related to VM creation.
**Before:**
_InstanceTypes_ and _Preferences_ menu items placed under _MigrationPolicies_:
**After:**
_InstanceTypes_ and _Preferences_ menu items placed under _Templates_:

CNV-32959: Move InstanceTypes and Preferences under Templates in menu

---

src/views/virtualmachines/details/VirtualMachinePendingChangesAlert/VirtualMachinePendingChangesAlert.tsx

**Fixes:**
https://issues.redhat.com/browse/CNV-31856
Prevent displaying "Pending changes" warning in _Configuration > Disks_ page of a stopped VM if non-bootdisk was added to the VM.
_Note:_
The bug this PR is fixing is reproducible only just a very short time after a VM was stopped, later you won't be able to reproduce.
**Before:** Pending changes warning appears for a while:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/a5ac3f04-fde3-4923-8841-93882627f931
**After:** Pending changes warning doesn't appear (as expected for a stopped VM):
https://github.com/kubevirt-ui/kubevirt-plugin/assets/13417815/73d7e8f4-4e6c-46ba-bd40-2999cb22bd92

CNV-31856: Prevent displaying "Pending changes" for stopped VM

---

src/utils/components/CPUMemoryModal/CpuMemoryModal.tsx
src/utils/components/CPUMemoryModal/utils/CpuMemoryUtils.ts
src/utils/components/PendingChanges/utils/helpers.ts
src/utils/resources/vm/utils/selectors.ts
src/utils/resources/vmi/utils/selectors.ts
src/views/templates/details/tabs/details/components/CPUMemoryModal.tsx

Use the existing `getCPUcores` selector in `checkCPUMemoryChanged` where possible, also add other minor improvements to the code like add missing "instance" to the description of some VMI related selectors, also move `getCPUcores` to VM selectors related file.
No any visual changes

Use getCPUcores selector in checkCPUMemoryChanged

---

src/views/catalog/customize/components/CustomizeSource/SelectSource.tsx
src/views/catalog/customize/components/CustomizeSource/utils.ts
src/views/catalog/customize/utils.ts

When adding size input for default source https://github.com/kubevirt-ui/kubevirt-plugin/pull/1529 
We accidentally override the boot source's source
Before:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/39551eff-c387-4ec1-9768-ea96432db446
After:
https://github.com/kubevirt-ui/kubevirt-plugin/assets/67270715/fecd650f-e573-45f0-8400-2a31d29c4a18

CNV-32874: Customize VM is prompting 'No boot source available' dialog

---

src/views/catalog/templatescatalog/components/TemplatesCatalogDrawer/TemplateCatalogDrawer.scss
src/views/virtualmachines/details/tabs/configuration/network/components/modal/VirtualMachinesNetworkInterfaceModal.tsx

This fixes a bug wherein a secondary hot-plugged NIC is added to a VM, but it is not added to the VMI after live migration.
jira issue: https://issues.redhat.com/browse/CNV-32665

CNV-32665: Fix hot plug NIC not added to VMI after live migration
